<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(403);exit("CLI only\n");}
$root=dirname(__DIR__,2);$pass=[];$fail=[];$check=function(string $name,bool $ok,string $detail='')use(&$pass,&$fail){$line=$name.($detail!==''?' - '.$detail:'');if($ok)$pass[]=$line;else $fail[]=$line;};$text=function(string $rel)use($root){return @file_get_contents($root.'/'.$rel)?:'';};$exists=function(string $rel)use($root){return is_file($root.'/'.$rel);};
$required=['public_html/api/src/AgentPolicyEngine.php','public_html/api/src/AgentUsageBudgetService.php','public_html/api/src/AgentAutonomyService.php','public_html/api/src/AgentInitiativeService.php','public_html/api/src/CoreAgentInitiativeService.php','public_html/api/src/CreatorIntelligenceService.php','public_html/api/src/AgentBuilderService.php','public_html/api/src/AgentResourceService.php','public_html/api/src/PhysicalSchemaService.php','public_html/api/src/AgentWorkflowService.php','public_html/api/src/VoiceAgentCenterService.php','public_html/api/src/ProviderCapabilityRouter.php','public_html/api/src/AiCapabilityRouter.php','public_html/api/src/PromptCanonicalizerService.php','public_html/api/src/MigrationPreflightService.php','public_html/api/src/MigrationRunner.php','public_html/api/src/MigrationRunnerService.php','public_html/api/src/SchemaPreflightService.php','public_html/api/src/VaultSnapshotService.php','public_html/api/src/ConfigSnapshotService.php','public_html/api/src/RuntimeValidationService.php','public_html/api/src/SystemDoctor.php','private/bin/migrate-20.php','private/bin/static-call-check.php','database/upgrade_companyos_17_19_to_20_0_final_unified.sql','database/PerseBayt_CompanyOS_20.0_FULL_FRESH_DATABASE_WITH_CURRENT_DATA.sql'];foreach($required as $r)$check('required:'.$r,$exists($r));
$release=$text('public_html/api/src/ReleaseInfo.php');$check('release:20.x',preg_match("/VERSION='20\.[^']*'/",$release)===1);foreach(["SCHEMA='20.0'",'unified_policy_engine','normalized_workflow_runtime','risk_gated_autonomy','image_generation_routing','video_generation_routing','browser_routing','encrypted_vault_snapshot','encrypted_config_snapshot'] as $n)$check('release:'.$n,str_contains($release,$n));
$sql=$text('database/upgrade_companyos_17_19_to_20_0_final_unified.sql');$fresh=$text('database/PerseBayt_CompanyOS_20.0_FULL_FRESH_DATABASE_WITH_CURRENT_DATA.sql');foreach(['17_policy_superset','17_workflow_superset','17_sources_and_vault','19_brain_and_usage','19_provider_routes','19_prompt_canonicalization','20_superset_integrity','20_policy_and_workflow_canonical','20_prompt_canonicalization','20_data_sources_and_routes','20_runtime_validation_and_release'] as $s)$check('migration_step:'.$s,str_contains($sql,'-- @step: '.$s));foreach(['agent_policy_rules','agent_policy_decisions','agent_workflow_steps','agent_workflow_runs','secure_vault_snapshots','secure_config_snapshots','resource_registry','physical_schema_requests','agent_schema_requests','creator_intelligence_snapshots','agent_goal_contributions','auto_execute_max_risk','v20_core_acceptance'] as $n)$check('sql_superset:'.$n,str_contains($sql,$n)&&str_contains($fresh,$n));$san=preg_replace('/--[^\n]*/','',$sql);$check('upgrade_non_destructive',!preg_match('/\b(?:DELETE\s+FROM|TRUNCATE\s+(?:TABLE\s+)?|DROP\s+TABLE)\b/i',(string)$san));
$router=$text('public_html/api/src/ProviderCapabilityRouter.php');foreach(['function embedding','function vision','function webSearch','function image','function video','function browser','function realtimeVoice','function syncFromProviders','function markProviderHealth','function markRouteHealth','recordDirectImage'] as $n)$check('router:'.$n,str_contains($router,$n));$check('router:no_embedLegacy',!str_contains($router,'embedLegacy'));
$policy=$text('public_html/api/src/AgentPolicyEngine.php');foreach(['agent_policy_rules','AgentUsageBudgetService::authorize','AiBudgetService::assertAllowed','verified_backup_required','project_access_required','external_action_gateway_required'] as $n)$check('policy:'.$n,str_contains($policy,$n));
$workflow=$text('public_html/api/src/AgentWorkflowService.php');foreach(['waiting_task_id','on_failure','policy_decision_id','workflow.run','workflow.step'] as $n)$check('workflow:'.$n,str_contains($workflow,$n));
$autonomy=$text('public_html/api/src/AgentAutonomyService.php');foreach(['auto_execute_max_risk','max_initiatives_per_day','AgentInitiativeService'] as $n)$check('autonomy:'.$n,str_contains($autonomy,$n));
$ayman=$text('public_html/api/src/AymanRunner.php');$check('ayman:image_router',str_contains($ayman,'AiCapabilityRouter::image'));$check('ayman:video_router',str_contains($ayman,'AiCapabilityRouter::video'));
$runtime=$text('public_html/api/src/RuntimeValidationService.php');foreach(['v20_core_acceptance','provider_health_sync','encrypted_config_snapshot','migration20','canonicalizer_service'] as $n)$check('runtime:'.$n,str_contains($runtime,$n));
$schema=$text('public_html/api/src/SchemaPreflightService.php');foreach(['companyos_20_0_final_unified','system_schema_not_20','encrypted_vault_snapshot_hash_mismatch','encrypted_config_snapshot_hash_mismatch','canonical_prompt_version_missing','missing_provider_route'] as $n)$check('schema_preflight:'.$n,str_contains($schema,$n));
$php=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f)if($f->isFile()&&strtolower($f->getExtension())==='php')$php[]=$f->getPathname();$bad=[];foreach($php as $file){$o=[];$c=0;exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($file).' 2>&1',$o,$c);if($c!==0)$bad[]=str_replace($root.'/','',$file);}$check('php_lint_all',$bad===[],count($php).' files'.($bad?' bad='.implode(',',$bad):''));$o=[];$c=0;exec(escapeshellarg(PHP_BINARY).' '.escapeshellarg($root.'/private/bin/static-call-check.php').' 2>&1',$o,$c);$check('static_class_calls',$c===0,implode(' | ',$o));
$secretOk=is_file($root.'/private/config.php')&&is_file($root.'/private/runtime/master.key')&&is_file($root.'/private/runtime/secrets.enc');$check('owner_runtime_secrets_present',$secretOk,'checks presence only; values are never printed');
echo "PerseBayt Company OS 20 static acceptance\nPASS=".count($pass)." FAIL=".count($fail)."\n";foreach($fail as $x)echo '[FAIL] '.$x.PHP_EOL;foreach($pass as $x)echo '[PASS] '.$x.PHP_EOL;exit($fail?2:0);
