<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$months=db()->query("SELECT DISTINCT data_month FROM agency_creator_monthly ORDER BY data_month DESC LIMIT 24")->fetchAll(PDO::FETCH_COLUMN);
$month=preg_match('/^20\d{4}$/',(string)($_GET['month']??''))?(string)$_GET['month']:((string)($months[0]??''));
$summary=AgencyService::summary($month?:null);$rows=AgencyService::creatorRows($month?:null,600);usort($rows,static fn($a,$b)=>(int)($b['attention']['score']??0)<=>(int)($a['attention']['score']??0) ?: ((int)$b['diamonds']<=>(int)$a['diamonds']));
$history=AgencyService::importHistory();$contacts=array_values(array_filter(ContactDirectoryService::all(),static fn($x)=>(string)($x['group_key']??'')==='elfares_supervisors'||str_contains((string)($x['role_title']??''),'مشرف')));
$fmtMonth=static function(?string $m):string{if(!$m||strlen($m)!==6)return '—';return substr($m,0,4).'-'.substr($m,4,2);};
AdminUi::header('وكالة الفارس','agency');echo AdminUi::flash();
?>
<section class="tech-hero card agency-hero"><div><span class="eyebrow">BASANT · EL FARES OPERATIONS</span><h2>إدارة المبدعين من البيانات — الماسات أولًا</h2><p>بسنت تربط شيت إدارة المبدعين مع أرباح TikTok عبر Creator ID. الأولوية: الماسات، ثم أيام البث الصالح، ثم ساعات البث. السياسات تمنع اقتراح الجولات/التكبيس لمن لا يناسبه ذلك.</p></div><div class="tech-live"><span class="live-dot"></span><b>بسنت</b><small>مبادرة ومتابعة تلقائية من Runtime</small></div></section>

<div class="card compact-toolbar"><form method="get" class="inline-form"><div class="field"><label>الشهر</label><select name="month" onchange="this.form.submit()"><option value="">الأحدث</option><?php foreach($months as $m):?><option value="<?=e($m)?>" <?=$m===$month?'selected':''?>><?=e($fmtMonth($m))?></option><?php endforeach?></select></div></form><div class="field grow"><label>بحث حي</label><input type="search" data-live-filter placeholder="اسم المبدع، اليوزر، Creator ID، المجموعة"></div></div>
<div class="metric-grid metric-grid-4">
<?=AdminUi::stat('الفترة',$fmtMonth($summary['latest_month']??null),'مصدر موحد بدون تكرار المصدرين')?>
<?=AdminUi::stat('المبدعون',number_format((int)$summary['creators']),'Creator ID فريد')?>
<?=AdminUi::stat('الماسات',number_format((int)$summary['diamonds']),'المؤشر الأساسي')?>
<?=AdminUi::stat('البث',number_format((float)$summary['valid_days'],1).' يوم / '.number_format((float)$summary['live_hours'],1).' س','Valid days ثم hours')?>
</div>

<div class="grid"><section class="card span-5"><div class="card-title"><div><h2>استيراد شيتات TikTok</h2><span class="muted small">يدعم ملفات XLSX الحالية حتى لو Dimension داخل الملف غير صحيح. يمنع تكرار نفس الملف بالـSHA-256.</span></div></div><form method="post" action="action.php" enctype="multipart/form-data"><?=AdminUi::csrf()?><input type="hidden" name="action" value="agency_import"><input type="hidden" name="return" value="/api/admin/agency.php"><div class="field"><label>شيت إدارة المبدعين أو الأرباح الشهرية</label><input type="file" name="agency_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></div><button class="btn full-width">استيراد ومراجعة</button></form><p class="small muted">لا يتم تنفيذ Macros/صيغ من الملف. البيانات الخام تحفظ كسجل تدقيق، ويستخدم النظام الحقول المعروفة فقط.</p></section>
<section class="card span-7"><div class="card-title"><h2>المشرفات</h2><a class="link" href="contacts.php">جهات الاتصال</a></div><div class="two-col"><?php foreach($contacts as $c):?><article class="card subtle" style="margin:0"><div class="card-title"><b><?=e($c['display_name'])?></b><?=AdminUi::badge((int)$c['enabled']?'active':'disabled')?></div><p class="small muted"><?=e($c['role_title']?:'مشرفة')?> · <?=e($c['whatsapp_phone']?:'رقم واتساب لم يضف بعد')?></p></article><?php endforeach?></div><p class="small muted">كنزي مفعلة مبدئيًا، وإيلينا تبقى متوقفة حتى تفعلها من جهات الاتصال وتضيف الرقم الصحيح.</p></section></div>

<section class="card"><div class="card-title"><div><h2>المبدعون — أولوية المتابعة</h2><span class="muted small">الترتيب هنا حسب Attention أولًا ثم الماسات، حتى تظهر الحالات المحتاجة متابعة. افتح الكارت لضبط الاستثناءات والميلاد والمشرفة.</span></div><span class="badge s-active"><?=count($rows)?> سجل</span></div><div class="creator-grid">
<?php foreach($rows as $r):$att=(array)$r['attention'];$search=pb_strtolower(implode(' ',[(string)$r['creator_id'],(string)$r['handle'],(string)$r['nickname'],(string)$r['group_name'],(string)$r['supervisor_name']]));?>
<article class="card subtle creator-card" style="margin:0" data-live-filter-item data-search="<?=e($search)?>"><div class="card-title"><div><b><?=e($r['nickname']?:$r['handle']?:$r['creator_id'])?></b><small class="muted block"><?=e($r['handle']?'@'.ltrim($r['handle'],'@'):'')?> · ID <?=e($r['creator_id'])?></small></div><span class="attention-score <?=((int)$att['score']>=60?'high':((int)$att['score']>=30?'medium':'low'))?>"><?=(int)$att['score']?>%</span></div>
<div class="creator-metrics"><span><small>الماسات</small><b><?=number_format((int)$r['diamonds'])?></b><?php if((int)($r['previous_diamonds']??0)>0):?><em>السابق <?=number_format((int)$r['previous_diamonds'])?></em><?php endif?></span><span><small>أيام البث</small><b><?=number_format((float)$r['valid_days'],1)?></b></span><span><small>ساعات البث</small><b><?=number_format((float)$r['live_hours'],1)?></b></span></div>
<p class="small muted"><?=e($r['group_name']?:'بدون مجموعة')?> · المشرفة: <?=e($r['supervisor_name']?:'غير محددة')?> · آخر بث <?=e(AdminUi::date($r['last_live_at']))?></p>
<?php if($att['reasons']):?><div class="tag-row"><?php foreach($att['reasons'] as $x):?><span><?=e($x)?></span><?php endforeach?></div><?php endif?>
<details><summary>سياسة المبدع والمتابعة</summary><form method="post" action="action.php" class="details-pad"><?=AdminUi::csrf()?><input type="hidden" name="action" value="agency_creator_policy"><input type="hidden" name="return" value="/api/admin/agency.php?month=<?=e($month)?>"><input type="hidden" name="creator_id" value="<?=e($r['creator_id'])?>"><div class="field"><label>المشرفة</label><select name="supervisor_contact_id"><option value="0">غير محددة</option><?php foreach($contacts as $c):?><option value="<?=$c['id']?>" <?=((int)$r['supervisor_contact_id']===(int)$c['id'])?'selected':''?>><?=e($c['display_name'])?><?=!(int)$c['enabled']?' — متوقفة':''?></option><?php endforeach?></select></div><div class="two-col"><div class="field"><label>تاريخ الميلاد</label><input type="date" name="birth_date" value="<?=e($r['birth_date']?:'')?>"></div><div class="field"><label>متابعة كل ساعات</label><input type="number" name="preferred_followup_hours" min="1" max="168" value="<?=e((string)($r['preferred_followup_hours']?:6))?>"></div></div><label class="check"><input type="checkbox" name="no_official_matches" value="1" <?=!empty($r['no_official_matches'])?'checked':''?>> لا يلعب جولات رسمية — لا تقترحها</label><label class="check"><input type="checkbox" name="no_tapping_campaigns" value="1" <?=!empty($r['no_tapping_campaigns'])?'checked':''?>> لا يعمل حملات تكبيس — لا تقترحها</label><div class="field"><label>ملاحظات بسنت</label><textarea name="notes"><?=e($r['policy_notes']?:'')?></textarea></div><button class="btn secondary full-width">حفظ السياسة</button></form></details></article>
<?php endforeach?>
<?php if(!$rows):?><?=AdminUi::empty('استورد شيت إدارة المبدعين وشيت الأرباح ليبدأ تحليل بسنت.')?><?php endif?>
</div></section>

<section class="card"><div class="card-title"><h2>سجل الاستيراد</h2></div><div class="table-wrap"><table><thead><tr><th>الملف</th><th>النوع</th><th>الشهر</th><th>المستورد</th><th>المتروك</th><th>الحالة</th><th>الوقت</th></tr></thead><tbody><?php foreach($history as $h):?><tr><td><?=e($h['source_filename'])?></td><td><?=e($h['import_type'])?></td><td><?=e($fmtMonth($h['data_month']))?></td><td><?=(int)$h['rows_imported']?></td><td><?=(int)$h['rows_skipped']?></td><td><?=AdminUi::badge($h['state'])?></td><td><?=e(AdminUi::date($h['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<?php $agencyEvents=AgencyEventService::openEvents(120); ?>
<section class="card"><div class="card-title"><div><h2>Agency event engine</h2><span class="muted small">Birthdays, inactivity, performance decline and supervisor follow-ups are explicit events. Inbound supervisor replies are linked to the open thread and cancel/reschedule the pending follow-up instead of creating blind reminders.</span></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="agency_events_generate"><input type="hidden" name="return" value="/api/admin/agency.php"><button class="btn">Generate events now</button></form></div><div class="creator-grid"><?php foreach($agencyEvents as $ev):?><article class="card subtle" style="margin:0"><div class="card-title"><div><b><?=e($ev['title'])?></b><small class="block muted"><?=e($ev['nickname']?:$ev['handle']?:$ev['creator_id']?:'General')?> | <?=e($ev['supervisor_name']?:'No supervisor')?></small></div><?=AdminUi::badge($ev['state'])?></div><p class="small"><?=e($ev['details_text']?:'')?></p><p class="small muted">Type: <?=e($ev['event_type'])?> | Due: <?=e(AdminUi::date($ev['due_at']))?> | Thread: <?=e($ev['thread_id']?(string)$ev['thread_id']:'-')?></p><?php if(in_array($ev['state'],['open','scheduled','failed'],true)&&$ev['supervisor_contact_id']):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="agency_event_send"><input type="hidden" name="return" value="/api/admin/agency.php"><input type="hidden" name="event_id" value="<?=$ev['id']?>"><div class="field"><label>Message to supervisor</label><textarea name="message" placeholder="Leave blank to let Basant build the event message"></textarea></div><button class="btn secondary">Send and schedule follow-up</button></form><?php endif?></article><?php endforeach?></div><?php if(!$agencyEvents)echo AdminUi::empty('No open agency events. Generate events after importing current monthly data.');?></section>
<?php AdminUi::footer();
