<?php
declare(strict_types=1);

final class AgencyEventService {
    private const REPLY_STATES=['resolved','waiting_creator','waiting_supervisor','followup_later','needs_question','needs_owner','unknown'];

    public static function generate():array{
        if(setting('agency.events_enabled','1')==='0')return ['enabled'=>false];$basant=AgentService::bySlug('basant');$created=0;$errors=[];$days=max(1,min(30,(int)setting('agency.birthdays_days_ahead','7')));$reminderDays=max(0,min($days,(int)setting('agency.birthday_reminder_days','3')));
        $creators=db()->query("SELECT c.*,d.display_name supervisor_name,d.enabled supervisor_enabled FROM agency_creators c LEFT JOIN contact_directory d ON d.id=c.supervisor_contact_id WHERE c.active=1 AND c.birth_date IS NOT NULL")->fetchAll();
        foreach($creators as $c){$md=substr((string)$c['birth_date'],5,5);if(!preg_match('/^\d{2}-\d{2}$/',$md))continue;for($i=0;$i<=$days;$i++){if(gmdate('m-d',time()+$i*86400)!==$md)continue;$eventAt=gmdate('Y-m-d 18:00:00',time()+$i*86400);$remindTs=max(time(),strtotime($eventAt.' UTC')-$reminderDays*86400);$remindAt=gmdate('Y-m-d 10:00:00',$remindTs);$id=self::ensureEvent((string)$c['creator_id'],$c['supervisor_contact_id']?(int)$c['supervisor_contact_id']:null,(int)$basant['id'],'birthday','عيد ميلاد '.self::creatorName($c),'متابعة عيد الميلاد وتشجيع احتفال Live مناسب لزيادة التفاعل والدعم.',$eventAt,$remindAt,['days_ahead'=>$i,'event_at'=>$eventAt,'reminder_days'=>$reminderDays]);if($id)$created++;break;}}
        try{$rows=AgencyService::creatorRows(null,500);foreach($rows as $r){$att=(array)($r['attention']??[]);if((int)($att['score']??0)<30)continue;$type=(int)$att['score']>=60?'performance_critical':'performance_decline';$due=gmdate('Y-m-d H:i:s',time()+300);$title='متابعة '.self::creatorName($r);$details=implode('، ',(array)($att['reasons']??[]));$id=self::ensureEvent((string)$r['creator_id'],$r['supervisor_contact_id']?(int)$r['supervisor_contact_id']:null,(int)$basant['id'],$type,$title,$details,$due,$due,['attention'=>$att,'month'=>$r['data_month']??null,'diamonds'=>$r['diamonds']??0,'valid_days'=>$r['valid_days']??0,'live_hours'=>$r['live_hours']??0]);if($id)$created++;}}catch(Throwable $e){$errors[]=$e->getMessage();}
        $dispatch=self::dispatchDue(20);put_setting('agency.events_last_generated_at',now_utc());return ['enabled'=>true,'created'=>$created,'dispatch'=>$dispatch,'errors'=>array_map(static fn($e)=>pb_substr(Security::redactSecrets($e),0,180),$errors)];
    }

    public static function dispatchDue(int $limit=20):array{
        $limit=max(1,min(100,$limit));$q=db()->query("SELECT id FROM agency_events WHERE state IN ('open','scheduled','waiting_creator') AND supervisor_contact_id IS NOT NULL AND COALESCE(next_action_at,remind_at,due_at,created_at)<=NOW() ORDER BY COALESCE(next_action_at,remind_at,due_at,created_at),id LIMIT {$limit}");$sent=0;$deferred=0;$blocked=0;$ids=[];
        foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id){$id=(int)$id;try{$ev=self::event($id);$policy=self::communicationAllowed((int)$ev['supervisor_contact_id']);if(!$policy['allowed']){db()->prepare("UPDATE agency_events SET state='scheduled',next_action_at=?,resolution_code='quiet_hours',updated_at=NOW() WHERE id=?")->execute([$policy['next_at'],$id]);$deferred++;continue;}$r=self::sendQuestion($id);if(!empty($r['sent'])){$sent++;$ids[]=$id;}else $blocked++;}catch(Throwable $e){$blocked++;}}
        return ['sent'=>$sent,'deferred'=>$deferred,'blocked'=>$blocked,'event_ids'=>$ids];
    }

    public static function handleInboundWhatsApp(string $from,string $text,string $externalId='',array $raw=[]):array{
        $digits=preg_replace('/\D+/','',$from)?:'';if($digits==='')return ['handled'=>false];$contact=self::supervisorByPhone($digits);if(!$contact)return ['handled'=>false];$basant=AgentService::bySlug('basant');$match=self::resolveThread((int)$contact['id'],$text,$raw);$thread=$match['thread'];$confidence=(int)$match['confidence'];
        if(!$thread){db()->prepare("INSERT INTO agency_threads(contact_id,agent_id,channel,state,last_message_at,context_json) VALUES (?,?,'whatsapp','open',NOW(),?)")->execute([(int)$contact['id'],(int)$basant['id'],j(['created_from'=>'inbound_supervisor','unresolved_creator'=>true])]);$thread=['id'=>(int)db()->lastInsertId(),'creator_id'=>null];$confidence=20;}
        try{db()->prepare("INSERT INTO agency_thread_messages(thread_id,direction,external_id,body_text,metadata_json) VALUES (?,'inbound',?,?,?)")->execute([(int)$thread['id'],$externalId?:null,pb_substr(trim($text),0,12000),$raw?j($raw):null]);}catch(PDOException $e){if((string)$e->getCode()==='23000')return ['handled'=>true,'duplicate'=>true,'thread_id'=>(int)$thread['id']];throw $e;}
        db()->prepare("UPDATE agency_threads SET state='open',last_message_at=NOW(),last_inbound_id=? WHERE id=?")->execute([$externalId?:null,(int)$thread['id']]);
        $events=self::eventsForThread((int)$thread['id']);$classification=self::classifyReply($basant,$contact,$thread,$events,$text,$confidence);$applied=[];foreach($events as $ev)$applied[]=self::applyReplyDecision($ev,$classification,$text,$externalId);
        $creator=(string)($classification['creator_id']??$thread['creator_id']??'');if($creator!==''&&(string)($thread['creator_id']??'')==='')db()->prepare('UPDATE agency_threads SET creator_id=? WHERE id=?')->execute([$creator,(int)$thread['id']]);
        $desc="ردت المشرفة ".(string)$contact['display_name'].($creator!==''?' بخصوص المبدع '.$creator:'').":\n".$text."\nتصنيف النظام: ".(string)$classification['decision']." (ثقة ".(int)$classification['confidence']."%). راجعي البيانات وحددي الخطوة التالية، ولا تغلقي المتابعة إلا عند resolved.";$tid=TaskService::create('basant','رد من مشرفة الوكالة: '.(string)$contact['display_name'],$desc,null,['job_kind'=>'agent_task','agency_thread_id'=>(int)$thread['id'],'creator_id'=>$creator?:null,'contact_id'=>(int)$contact['id'],'supervisor_reply'=>1,'reply_decision'=>$classification],'high',true,null,'system','agency_inbound');
        AgentBrainService::remember((int)$basant['id'],'episodic','رد مشرفة وكالة الفارس',pb_substr($text,0,6000),null,['thread_id'=>(int)$thread['id'],'contact_id'=>(int)$contact['id'],'creator_id'=>$creator?:null,'classification'=>$classification],80,90,$creator!==''?'creator:'.$creator:null,'whatsapp',$externalId?:null);
        if($classification['decision']==='needs_owner')try{CommunicationGateway::ramyDashboardUpdate('بسنت تحتاج قرار المالك في متابعة الوكالة: '.$text,null,$tid);}catch(Throwable){}
        return ['handled'=>true,'thread_id'=>(int)$thread['id'],'task_id'=>$tid,'classification'=>$classification,'event_updates'=>$applied,'contact_id'=>(int)$contact['id']];
    }

    public static function sendQuestion(int $eventId,string $message=''):array{
        $q=db()->prepare("SELECT e.*,c.display_name,c.enabled,c.whatsapp_phone,c.phone,a.slug FROM agency_events e JOIN contact_directory c ON c.id=e.supervisor_contact_id JOIN agents a ON a.id=e.agent_id WHERE e.id=?");$q->execute([$eventId]);$e=$q->fetch();if(!$e)throw new RuntimeException('agency_event_not_found');if(!(int)$e['enabled'])throw new RuntimeException('agency_supervisor_disabled');Permissions::requireAgent((int)$e['agent_id'],'whatsapp.send');$policy=self::communicationAllowed((int)$e['supervisor_contact_id']);if(!$policy['allowed']){db()->prepare("UPDATE agency_events SET state='scheduled',next_action_at=? WHERE id=?")->execute([$policy['next_at'],$eventId]);return ['sent'=>false,'deferred'=>true,'next_at'=>$policy['next_at']];}
        $to=ContactDirectoryService::whatsappNumber((int)$e['supervisor_contact_id']);$message=trim($message);if($message==='')$message=self::messageFor($e);if(!preg_match('/\bEV[-#:]?'.preg_quote((string)$eventId,'/').'\b/i',$message))$message.='\nRef: EV'.$eventId;$threadId=self::ensureThread($e);
        $action=ExternalActionGateway::propose((int)$e['agent_id'],(int)$e['supervisor_contact_id'],'whatsapp','agency.supervisor_message',['text'=>$message,'event_id'=>$eventId,'thread_id'=>$threadId],'جهة اتصال مفعلة كـمشرفة وكالة الفارس ومسموح لبسنت بمتابعتها.',false);
        try{$r=ExternalActionGateway::execute($action);$mid=(string)($r['message_id']??'');db()->prepare("INSERT INTO agency_thread_messages(thread_id,direction,external_id,body_text,metadata_json) VALUES (?,'outbound',?,?,?)")->execute([$threadId,$mid?:null,pb_substr($message,0,12000),j(['gateway'=>$r])]);db()->prepare("UPDATE agency_threads SET state='waiting_reply',last_message_at=NOW() WHERE id=?")->execute([$threadId]);$hours=self::followupHours((string)($e['creator_id']??''));$fid=AgentFollowupService::schedule((int)$e['agent_id'],'متابعة رد '.(string)$e['display_name'].' — '.(string)$e['title'],gmdate('Y-m-d H:i:s',time()+$hours*3600),'إذا لم يصل رد افتحي Thread الوكالة وتابعي بلطف. لا تكرري الإرسال إذا وصل رد.',null,null,(int)$e['supervisor_contact_id'],'whatsapp');db()->prepare("UPDATE agency_events SET state='waiting_supervisor',thread_id=?,followup_id=?,next_action_at=NULL,resolution_code=NULL,updated_at=NOW() WHERE id=?")->execute([$threadId,$fid,$eventId]);return ['sent'=>true,'message_id'=>$mid,'thread_id'=>$threadId,'followup_id'=>$fid];}
        catch(Throwable $ex){$safe=pb_substr(Security::redactSecrets($ex->getMessage()),0,240);db()->prepare("UPDATE agency_events SET state='open',thread_id=?,resolution_code='send_blocked',updated_at=NOW() WHERE id=?")->execute([$threadId,$eventId]);Notifications::add('warning','agency','بسنت لم تستطع إرسال متابعة للمشرفة','الرسالة محفوظة، لكن WhatsApp لم يقبل الإرسال الآن: '.AdminUi::humanError($safe),'agency_event',(string)$eventId);return ['sent'=>false,'blocked'=>true,'error'=>$safe,'thread_id'=>$threadId];}
    }

    public static function openEvents(int $limit=200):array{$limit=max(1,min(500,$limit));return db()->query("SELECT e.*,c.display_name supervisor_name,cr.handle,cr.nickname FROM agency_events e LEFT JOIN contact_directory c ON c.id=e.supervisor_contact_id LEFT JOIN agency_creators cr ON cr.creator_id=e.creator_id ORDER BY FIELD(e.state,'open','waiting_supervisor','waiting_creator','scheduled','failed','completed','cancelled'),COALESCE(e.next_action_at,e.remind_at,e.due_at,'9999-12-31'),e.id DESC LIMIT $limit")->fetchAll();}

    private static function classifyReply(array $basant,array $contact,array $thread,array $events,string $text,int $entityConfidence):array{
        $fallback=self::fallbackClassify($text);$creator=(string)($thread['creator_id']??'');if($creator==='')$creator=self::entityFromText((int)$contact['id'],$text)['creator_id']??'';
        $schema=['type'=>'object','additionalProperties'=>false,'properties'=>['decision'=>['type'=>'string','enum'=>self::REPLY_STATES],'creator_id'=>['type'=>'string'],'confidence'=>['type'=>'integer'],'followup_hours'=>['type'=>'integer'],'reason'=>['type'=>'string']],'required'=>['decision','creator_id','confidence','followup_hours','reason']];
        $prompt='صنّفي رد مشرفة وكالة الفارس باللهجة العربية/المصرية. لا تعتبري مجرد وصول رسالة إغلاقًا للمتابعة. resolved فقط إذا انتهت المسألة فعلًا. waiting_creator مثل: لسه مردش/مستنية المبدع. waiting_supervisor إذا المشرفة نفسها ستراجع وترد. followup_later إذا يوجد وقت لاحق محدد. needs_question إذا الرد غامض ويحتاج سؤال. needs_owner إذا يحتاج قرار المالك. unknown إذا غير واضح. اربطي creator_id فقط عند ثقة عالية.';
        try{$r=AiGateway::json($basant,$prompt,[['role'=>'user','content'=>j(['message'=>$text,'contact'=>$contact['display_name'],'thread_creator'=>$thread['creator_id']??null,'events'=>array_map(static fn($e)=>['id'=>$e['id'],'creator_id'=>$e['creator_id'],'type'=>$e['event_type'],'state'=>$e['state'],'title'=>$e['title']],$events),'entity_confidence'=>$entityConfidence])]],$schema,'agency_reply_classifier',1000);$d=(array)($r['data']??$r['json']??[]);$decision=in_array((string)($d['decision']??''),self::REPLY_STATES,true)?(string)$d['decision']:$fallback['decision'];$conf=max(0,min(100,(int)($d['confidence']??$fallback['confidence'])));$cid=trim((string)($d['creator_id']??$creator));if($cid!==''&&!self::creatorExists($cid))$cid='';return ['decision'=>$decision,'creator_id'=>$cid,'confidence'=>min($conf,max(20,$entityConfidence?:100)),'followup_hours'=>max(1,min(168,(int)($d['followup_hours']??$fallback['followup_hours']))),'reason'=>pb_substr((string)($d['reason']??$fallback['reason']),0,1000)];}catch(Throwable){return $fallback+['creator_id'=>$creator,'confidence'=>min((int)$fallback['confidence'],max(20,$entityConfidence?:100))];}
    }
    private static function fallbackClassify(string $text):array{$t=pb_strtolower(trim($text));if(preg_match('/(خلص|تم|تمام.*(فتح|رد|اتفق)|انته|done|resolved)/u',$t))return ['decision'=>'resolved','confidence'=>72,'followup_hours'=>24,'reason'=>'عبارة تدل على انتهاء المتابعة'];if(preg_match('/(لسه|لِسه|مردش|ما رد|مستني.*(احمد|المبدع|هو|هي)|waiting.*creator)/u',$t))return ['decision'=>'waiting_creator','confidence'=>82,'followup_hours'=>max(3,(int)setting('agency.followup_default_hours','6')),'reason'=>'الرد يفيد انتظار المبدع'];if(preg_match('/(هراجع|هشوف|هسأل|هرجعلك|هرد عليك|بكرة|غدا|بعد .*ساعة|later)/u',$t))return ['decision'=>'followup_later','confidence'=>68,'followup_hours'=>12,'reason'=>'المشرفة ستعود لاحقًا'];if(preg_match('/(مش عارفة|مش فاهمة|تقصد|مين|اي مبدع|أي مبدع)/u',$t))return ['decision'=>'needs_question','confidence'=>75,'followup_hours'=>6,'reason'=>'يحتاج توضيح'];return ['decision'=>'unknown','confidence'=>35,'followup_hours'=>6,'reason'=>'لم تتضح النتيجة من النص وحده'];}
    private static function applyReplyDecision(array $ev,array $d,string $text,string $externalId):array{
        $decision=(string)$d['decision'];$conf=(int)$d['confidence'];$eventId=(int)$ev['id'];$payload=self::mergeJson((string)($ev['payload_json']??''),['supervisor_reply'=>$text,'reply_at'=>now_utc(),'external_id'=>$externalId,'reply_classification'=>$d]);$state='open';$next=null;$resolution=$decision;
        if($decision==='resolved')$state='completed';elseif($decision==='waiting_creator'){$state='waiting_creator';$next=gmdate('Y-m-d H:i:s',time()+self::followupHours((string)($ev['creator_id']??''))*3600);}elseif($decision==='waiting_supervisor'){$state='waiting_supervisor';$next=gmdate('Y-m-d H:i:s',time()+max(1,(int)$d['followup_hours'])*3600);}elseif($decision==='followup_later'){$state='scheduled';$next=gmdate('Y-m-d H:i:s',time()+max(1,(int)$d['followup_hours'])*3600);}elseif($decision==='needs_owner'||$decision==='needs_question'||$decision==='unknown')$state='open';
        db()->prepare('UPDATE agency_events SET state=?,next_action_at=?,resolution_code=?,reply_confidence=?,payload_json=?,updated_at=NOW() WHERE id=?')->execute([$state,$next,$resolution,$conf,$payload,$eventId]);
        if(!empty($ev['followup_id'])){if($state==='completed')AgentFollowupService::cancel((int)$ev['followup_id'],'تم حسم الحدث من رد المشرفة.');elseif($next){try{AgentFollowupService::reschedule((int)$ev['followup_id'],$next,'أعيدت الجدولة بعد فهم رد المشرفة.');}catch(Throwable){}}}
        return ['event_id'=>$eventId,'state'=>$state,'decision'=>$decision,'next_action_at'=>$next];
    }
    private static function resolveThread(int $contactId,string $text,array $raw):array{
        $replyTo=trim((string)($raw['context']['id']??''));if($replyTo!==''){$q=db()->prepare('SELECT t.* FROM agency_thread_messages m JOIN agency_threads t ON t.id=m.thread_id WHERE m.external_id=? AND t.contact_id=? ORDER BY m.id DESC LIMIT 1');$q->execute([$replyTo,$contactId]);if($t=$q->fetch())return ['thread'=>$t,'confidence'=>100,'method'=>'reply_context'];}
        if(preg_match('/\bEV[-#:]?(\d+)\b/i',$text,$m)){$q=db()->prepare('SELECT t.* FROM agency_events e JOIN agency_threads t ON t.id=e.thread_id WHERE e.id=? AND t.contact_id=? LIMIT 1');$q->execute([(int)$m[1],$contactId]);if($t=$q->fetch())return ['thread'=>$t,'confidence'=>100,'method'=>'event_ref'];}
        $entity=self::entityFromText($contactId,$text);if(!empty($entity['creator_id'])){$q=db()->prepare("SELECT * FROM agency_threads WHERE contact_id=? AND creator_id=? AND state IN ('open','waiting_reply') ORDER BY last_message_at DESC,id DESC LIMIT 1");$q->execute([$contactId,$entity['creator_id']]);if($t=$q->fetch())return ['thread'=>$t,'confidence'=>$entity['confidence'],'method'=>'creator_entity'];}
        $q=db()->prepare("SELECT * FROM agency_threads WHERE contact_id=? AND state IN ('open','waiting_reply') ORDER BY last_message_at DESC,id DESC LIMIT 2");$q->execute([$contactId]);$rows=$q->fetchAll();if(count($rows)===1)return ['thread'=>$rows[0],'confidence'=>55,'method'=>'single_open_thread'];return ['thread'=>null,'confidence'=>20,'method'=>'ambiguous'];
    }
    private static function entityFromText(int $contactId,string $text):array{$q=db()->prepare('SELECT creator_id,handle,nickname FROM agency_creators WHERE active=1 AND supervisor_contact_id=?');$q->execute([$contactId]);$t=pb_strtolower($text);$hits=[];foreach($q->fetchAll() as $c){$score=0;foreach([(string)$c['creator_id'],(string)$c['handle'],(string)$c['nickname']] as $v){$v=trim($v);if($v!==''&&pb_strlen($v)>=2&&str_contains($t,pb_strtolower(ltrim($v,'@'))))$score+=40;}if($score)$hits[]=['creator_id'=>(string)$c['creator_id'],'confidence'=>min(100,$score)];}usort($hits,static fn($a,$b)=>$b['confidence']<=>$a['confidence']);if(count($hits)===1||(!empty($hits[0])&&($hits[0]['confidence']??0)>($hits[1]['confidence']??0)+20))return $hits[0];return ['creator_id'=>'','confidence'=>20];}
    private static function eventsForThread(int $threadId):array{$q=db()->prepare("SELECT * FROM agency_events WHERE thread_id=? AND state IN ('waiting_supervisor','waiting_creator','scheduled','open') ORDER BY id DESC LIMIT 8");$q->execute([$threadId]);return $q->fetchAll();}
    private static function followupHours(string $creatorId):int{if($creatorId!==''){$q=db()->prepare('SELECT preferred_followup_hours FROM agency_creator_policies WHERE creator_id=?');$q->execute([$creatorId]);$h=(int)($q->fetchColumn()?:0);if($h>0)return max(1,min(168,$h));}return max(1,min(48,(int)setting('agency.supervisor_reply_timeout_hours',setting('agency.followup_default_hours','6'))));}
    private static function communicationAllowed(int $contactId):array{
        $q=db()->prepare('SELECT * FROM contact_communication_policies WHERE contact_id=? AND enabled=1');$q->execute([$contactId]);$p=$q->fetch();if(!$p)$p=['timezone'=>'Africa/Cairo','quiet_start'=>'23:00:00','quiet_end'=>'09:00:00','weekend_days_json'=>'[5]','max_messages_per_day'=>4,'min_gap_minutes'=>120];$tz=new DateTimeZone((string)$p['timezone']);$now=new DateTimeImmutable('now',$tz);$dow=(int)$now->format('w');$week=json_decode((string)$p['weekend_days_json'],true);if(!is_array($week))$week=[];$start=(string)$p['quiet_start'];$end=(string)$p['quiet_end'];$time=$now->format('H:i:s');$quiet=$start<$end?($time>=$start&&$time<$end):($time>=$start||$time<$end);$weekend=in_array($dow,array_map('intval',$week),true);
        $q=db()->prepare("SELECT COUNT(*) FROM agency_thread_messages m JOIN agency_threads t ON t.id=m.thread_id WHERE t.contact_id=? AND m.direction='outbound' AND m.created_at>=UTC_DATE()");$q->execute([$contactId]);$count=(int)$q->fetchColumn();$q=db()->prepare("SELECT MAX(m.created_at) FROM agency_thread_messages m JOIN agency_threads t ON t.id=m.thread_id WHERE t.contact_id=? AND m.direction='outbound'");$q->execute([$contactId]);$last=$q->fetchColumn();$gap=$last?time()-(utc_ts((string)$last)?:0):999999;$minGap=max(0,(int)$p['min_gap_minutes'])*60;
        if(!$quiet&&!$weekend&&$count<(int)$p['max_messages_per_day']&&$gap>=$minGap)return ['allowed'=>true,'next_at'=>null];$next=$now->modify('+1 hour');for($i=0;$i<72;$i++){$tt=$next->format('H:i:s');$dd=(int)$next->format('w');$qQuiet=$start<$end?($tt>=$start&&$tt<$end):($tt>=$start||$tt<$end);if(!$qQuiet&&!in_array($dd,array_map('intval',$week),true))break;$next=$next->modify('+1 hour');}return ['allowed'=>false,'next_at'=>$next->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s'),'reason'=>$quiet?'quiet_hours':($weekend?'weekend':($count>=(int)$p['max_messages_per_day']?'daily_limit':'min_gap'))];
    }
    private static function ensureEvent(string $creatorId,?int $contactId,int $agentId,string $type,string $title,string $details,string $due,string $remind,array $payload):int{$dedupe=hash('sha256',$creatorId.'|'.$type);$q=db()->prepare("SELECT id FROM agency_events WHERE dedupe_key=? AND state IN ('open','waiting_supervisor','waiting_creator','scheduled') ORDER BY id DESC LIMIT 1");$q->execute([$dedupe]);$existing=(int)($q->fetchColumn()?:0);if($existing){db()->prepare('UPDATE agency_events SET details_text=?,due_at=?,remind_at=LEAST(COALESCE(remind_at,?),?),payload_json=?,updated_at=NOW() WHERE id=?')->execute([pb_substr($details,0,8000),$due,$remind,$remind,j($payload),$existing]);return 0;}db()->prepare("INSERT INTO agency_events(creator_id,supervisor_contact_id,agent_id,event_type,title,details_text,due_at,remind_at,next_action_at,state,dedupe_key,payload_json) VALUES (?,?,?,?,?,?,?,?,?,'scheduled',?,?)")->execute([$creatorId,$contactId,$agentId,$type,pb_substr($title,0,240),pb_substr($details,0,8000),$due,$remind,$remind,$dedupe,j($payload)]);return (int)db()->lastInsertId();}
    private static function ensureThread(array $e):int{$q=db()->prepare("SELECT id FROM agency_threads WHERE contact_id=? AND creator_id<=>? AND state IN ('open','waiting_reply') ORDER BY id DESC LIMIT 1");$q->execute([(int)$e['supervisor_contact_id'],$e['creator_id']?:null]);$id=(int)($q->fetchColumn()?:0);if($id)return $id;db()->prepare("INSERT INTO agency_threads(creator_id,contact_id,agent_id,channel,state,last_message_at,context_json) VALUES (?,?,?,'whatsapp','open',NOW(),?)")->execute([$e['creator_id']?:null,(int)$e['supervisor_contact_id'],(int)$e['agent_id'],j(['event_id'=>(int)$e['id']])]);$id=(int)db()->lastInsertId();db()->prepare('UPDATE agency_events SET thread_id=? WHERE id=?')->execute([$id,(int)$e['id']]);return $id;}
    private static function messageFor(array $e):string{$creator='';if(!empty($e['creator_id'])){$q=db()->prepare('SELECT handle,nickname FROM agency_creators WHERE creator_id=?');$q->execute([$e['creator_id']]);$c=$q->fetch()?:[];$creator=self::creatorName($c).' (ID '.$e['creator_id'].')';}$base='أنا بسنت من متابعة وكالة الفارس.';if($creator!=='')$base.="\nبخصوص ".$creator.': ';if($e['event_type']==='birthday')return $base.'قرب عيد ميلاده/ا. هل نرتب احتفال في اللايف أو نشاط مناسب يساعده/ا على زيادة الدعم؟';return $base.(string)$e['details_text']."\nممكن تقولي آخر وضعه الحالي وهل في سبب أو خطوة عملية نقدر نساعد بها؟";}
    private static function supervisorByPhone(string $digits):?array{$suffix='%'.substr($digits,-10);$q=db()->prepare("SELECT * FROM contact_directory WHERE enabled=1 AND group_key='elfares_supervisors' AND (REPLACE(REPLACE(REPLACE(REPLACE(COALESCE(whatsapp_phone,''),'+',''),' ',''),'-',''),'(', '') LIKE ? OR REPLACE(REPLACE(REPLACE(REPLACE(COALESCE(phone,''),'+',''),' ',''),'-',''),'(', '') LIKE ?) ORDER BY id LIMIT 1");$q->execute([$suffix,$suffix]);return $q->fetch()?:null;}
    private static function event(int $id):array{$q=db()->prepare('SELECT * FROM agency_events WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('agency_event_not_found');return $r;}
    private static function creatorExists(string $id):bool{$q=db()->prepare('SELECT 1 FROM agency_creators WHERE creator_id=? LIMIT 1');$q->execute([$id]);return (bool)$q->fetchColumn();}
    private static function creatorName(array $c):string{return trim((string)($c['nickname']??''))?:trim((string)($c['handle']??''))?:'المبدع';}
    private static function mergeJson(string $raw,array $add):string{$old=json_decode($raw,true);if(!is_array($old))$old=[];return j(array_merge($old,$add));}
}
