<?php
declare(strict_types=1);

final class AgencyService {
    public static function import(string $path,string $filename,string $createdBy='owner:1'):array{
        if(!is_file($path)||filesize($path)>20*1024*1024)throw new RuntimeException('agency_file_invalid');$sha=hash_file('sha256',$path);$q=db()->prepare('SELECT * FROM agency_imports WHERE file_sha256=?');$q->execute([$sha]);if($existing=$q->fetch())return ['duplicate'=>true,'import_id'=>(int)$existing['id'],'state'=>$existing['state'],'data_month'=>$existing['data_month'],'rows_imported'=>(int)$existing['rows_imported']];
        $rows=XlsxLiteReader::rows($path,12000,80);if(!$rows)throw new RuntimeException('agency_sheet_empty');$det=self::detect($rows,$filename);$type=$det['type'];$headerIndex=(int)$det['header_index'];$headers=self::headers($rows[$headerIndex]);$month=$det['data_month'];
        db()->prepare("INSERT INTO agency_imports(import_type,source_filename,file_sha256,data_month,rows_total,state,created_by) VALUES (?,?,?,?,?,'processing',?)")->execute([$type,pb_substr($filename,0,255),$sha,$month,count($rows)-$headerIndex-1,pb_substr($createdBy,0,100)]);$importId=(int)db()->lastInsertId();$imported=0;$skipped=0;$warnings=[];
        try{
            foreach(array_slice($rows,$headerIndex+1) as $row){$mapped=self::mapRow($headers,$row);$creatorId=self::stringId(self::pick($mapped,['creator id','رقم تعريف المبدع:','رقم تعريف المبدع']));if($creatorId===''||!preg_match('/^[0-9]{6,30}$/',$creatorId)){$skipped++;continue;}
                if($type==='monthly_earnings'){$rowMonth=self::month(self::pick($mapped,['data month']))?:$month;$month=$month?:$rowMonth;self::upsertCreator($creatorId,[
                        'handle'=>self::pick($mapped,['handle']),'nickname'=>self::pick($mapped,['creator nickname']),'network_manager'=>self::pick($mapped,['creator network manager']),'group_name'=>self::pick($mapped,['group']),'group_manager'=>self::pick($mapped,['group manager'])]);
                    self::upsertMonthly($creatorId,$rowMonth?:$month,'monthly_earnings',[ 'diamonds'=>self::num(self::pick($mapped,['diamonds'])),'valid_days'=>self::num(self::pick($mapped,['valid days(d)','valid days'])),'live_hours'=>self::num(self::pick($mapped,['live duration(h)','live duration'])),'estimated_bonus'=>self::num(self::pick($mapped,['estimated bonus']))],$mapped,$importId);
                }else{
                    self::upsertCreator($creatorId,[ 'handle'=>self::pick($mapped,['اسم المستخدم للمبدع']),'group_name'=>self::pick($mapped,['المجموعة']),'agency_account'=>self::pick($mapped,['الوكيل']),'relationship_status'=>self::pick($mapped,['حالة العلاقة']),'subscription_status'=>self::pick($mapped,['حالة الاشتراك']),'last_live_at'=>self::dateTime(self::pick($mapped,['آخر بث مباشر'])),'joined_at'=>self::dateTime(self::pick($mapped,['وقت الانضمام'])),'followers'=>(int)self::num(self::pick($mapped,['المتابعون'])),'notes'=>self::pick($mapped,['ملاحظات'])]);
                    self::upsertMonthly($creatorId,$month,'creator_management',[ 'diamonds'=>self::num(self::pick($mapped,['الماسات في الـ 30 يومًا الماضية'])),'valid_days'=>self::num(self::pick($mapped,['أيام البث الصالحة في آخر 30 يومًا'])),'live_hours'=>self::num(self::pick($mapped,['مدة البث في آخر 30 يومًا'])),'followers'=>(int)self::num(self::pick($mapped,['المتابعون'])),'videos'=>(int)self::num(self::pick($mapped,['الفيديوهات'])),'likes'=>(int)self::num(self::pick($mapped,['تسجيلات الإعجاب'])),'fan_diamonds'=>(int)self::num(self::pick($mapped,['الماس من مجتمع المعجبين في آخر 30 يومًا'])),'active_fans'=>(int)self::num(self::pick($mapped,['المعجبون النشطون من مجتمع المعجبين في آخر 30 يومًا']))],$mapped,$importId);
                }$imported++;
            }
            $state=$skipped>0?'completed_warning':'completed';$summary=['type'=>$type,'month'=>$month,'imported'=>$imported,'skipped'=>$skipped,'warnings'=>$warnings];db()->prepare('UPDATE agency_imports SET data_month=?,rows_imported=?,rows_skipped=?,state=?,summary_json=? WHERE id=?')->execute([$month,$imported,$skipped,$state,j($summary),$importId]);Audit::log('owner',(string)(Auth::user()['id']??1),'agency.import','agency_import',(string)$importId,'verified',null,null,$summary);return ['duplicate'=>false,'import_id'=>$importId,'state'=>$state,'data_month'=>$month,'rows_imported'=>$imported,'rows_skipped'=>$skipped,'type'=>$type];
        }catch(Throwable $e){db()->prepare("UPDATE agency_imports SET rows_imported=?,rows_skipped=?,state='failed',summary_json=? WHERE id=?")->execute([$imported,$skipped,j(['error'=>pb_substr(Security::redactSecrets($e->getMessage()),0,500)]),$importId]);throw $e;}
    }

    public static function summary(?string $month=null):array{
        if($month===null||$month==='')$month=(string)(db()->query("SELECT data_month FROM agency_creator_monthly ORDER BY data_month DESC LIMIT 1")->fetchColumn()?:'');if($month==='')return ['latest_month'=>null,'creators'=>0,'diamonds'=>0,'valid_days'=>0,'live_hours'=>0];
        $q=db()->prepare("SELECT COUNT(DISTINCT creator_id) c,COALESCE(SUM(diamonds),0) diamonds,COALESCE(SUM(valid_days),0) valid_days,COALESCE(SUM(live_hours),0) live_hours FROM agency_creator_monthly WHERE data_month=? AND source_type=(CASE WHEN EXISTS(SELECT 1 FROM agency_creator_monthly x WHERE x.data_month=? AND x.source_type='monthly_earnings') THEN 'monthly_earnings' ELSE 'creator_management' END)");$q->execute([$month,$month]);$r=$q->fetch()?:[];return ['latest_month'=>$month,'creators'=>(int)($r['c']??0),'diamonds'=>(int)($r['diamonds']??0),'valid_days'=>(float)($r['valid_days']??0),'live_hours'=>(float)($r['live_hours']??0)];
    }

    public static function creatorRows(?string $month=null,int $limit=500):array{
        $month=$month?:self::summary()['latest_month'];if(!$month)return [];$limit=max(1,min(1000,$limit));
        $sql="SELECT c.*,p.no_official_matches,p.no_tapping_campaigns,p.preferred_followup_hours,p.notes policy_notes,m.data_month,m.source_type,m.diamonds,m.valid_days,m.live_hours,m.estimated_bonus,m.followers monthly_followers,m.videos,m.likes,m.fan_diamonds,m.active_fans,pc.display_name supervisor_name,pc.enabled supervisor_enabled,(SELECT m2.diamonds FROM agency_creator_monthly m2 WHERE m2.creator_id=c.creator_id AND m2.data_month<m.data_month ORDER BY m2.data_month DESC,FIELD(m2.source_type,'monthly_earnings','creator_management') LIMIT 1) previous_diamonds FROM agency_creators c JOIN agency_creator_monthly m ON m.creator_id=c.creator_id AND m.data_month=? LEFT JOIN agency_creator_policies p ON p.creator_id=c.creator_id LEFT JOIN contact_directory pc ON pc.id=c.supervisor_contact_id WHERE m.source_type=(CASE WHEN EXISTS(SELECT 1 FROM agency_creator_monthly z WHERE z.creator_id=c.creator_id AND z.data_month=? AND z.source_type='monthly_earnings') THEN 'monthly_earnings' ELSE 'creator_management' END) ORDER BY m.diamonds DESC,c.id LIMIT ".$limit;
        $q=db()->prepare($sql);$q->execute([$month,$month]);$rows=$q->fetchAll();foreach($rows as &$r){$r['attention']=self::attention($r);}$r=null;return $rows;
    }

    public static function setPolicy(string $creatorId,array $d):void{
        $creatorId=self::stringId($creatorId);if($creatorId==='')throw new RuntimeException('creator_id_required');$hours=max(1,min(168,(int)($d['preferred_followup_hours']??6)));db()->prepare('INSERT INTO agency_creator_policies(creator_id,no_official_matches,no_tapping_campaigns,preferred_followup_hours,notes) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE no_official_matches=VALUES(no_official_matches),no_tapping_campaigns=VALUES(no_tapping_campaigns),preferred_followup_hours=VALUES(preferred_followup_hours),notes=VALUES(notes)')->execute([$creatorId,!empty($d['no_official_matches'])?1:0,!empty($d['no_tapping_campaigns'])?1:0,$hours,pb_substr(trim((string)($d['notes']??'')),0,8000)?:null]);
        $birth=trim((string)($d['birth_date']??''));$sup=(int)($d['supervisor_contact_id']??0)?:null;if($birth!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$birth))throw new RuntimeException('birth_date_invalid');if($sup)ContactDirectoryService::get($sup);db()->prepare('UPDATE agency_creators SET birth_date=COALESCE(?,birth_date),supervisor_contact_id=? WHERE creator_id=?')->execute([$birth?:null,$sup,$creatorId]);
    }

    public static function importHistory(int $limit=40):array{$limit=max(1,min(100,$limit));return db()->query('SELECT * FROM agency_imports ORDER BY id DESC LIMIT '.$limit)->fetchAll();}

    private static function detect(array $rows,string $filename):array{
        $max=min(6,count($rows));for($i=0;$i<$max;$i++){$h=array_map([self::class,'norm'],$rows[$i]);if(in_array('creator id',$h,true)&&in_array('diamonds',$h,true)){$month=self::month((string)($rows[$i+1][0]??''));return ['type'=>'monthly_earnings','header_index'=>$i,'data_month'=>$month];}if(in_array('رقم تعريف المبدع:',$h,true)||in_array('رقم تعريف المبدع',$h,true)){$m='';foreach(array_slice($rows,0,$i) as $r)foreach($r as $v)if(preg_match('/(20\d{2})[-:\/]?(\d{2})/u',(string)$v,$x)){$m=$x[1].$x[2];break 2;}if($m===''){if(preg_match('/(20\d{2})[_-](\d{2})[_-]\d{2}/u',$filename,$x))$m=$x[1].$x[2];}return ['type'=>'creator_management','header_index'=>$i,'data_month'=>$m?:gmdate('Ym')];}}
        throw new RuntimeException('agency_sheet_type_unrecognized');
    }
    private static function headers(array $row):array{$out=[];foreach($row as $i=>$v){$k=self::norm((string)$v);if($k!=='')$out[$i]=$k;}return $out;}
    private static function mapRow(array $headers,array $row):array{$out=[];foreach($headers as $i=>$h)$out[$h]=(string)($row[$i]??'');return $out;}
    private static function norm(string $v):string{$v=trim(preg_replace('/\s+/u',' ',$v)??$v);return pb_strtolower($v);}
    private static function pick(array $m,array $keys):string{foreach($keys as $k){$n=self::norm($k);if(array_key_exists($n,$m))return trim((string)$m[$n]);}return '';}
    private static function stringId(string $v):string{$v=trim($v);if(str_contains(strtolower($v),'e+')){$f=(float)$v;if(is_finite($f))$v=sprintf('%.0f',$f);}return preg_replace('/\.0+$/','',$v)?:'';}
    private static function num(string $v):float{$v=str_replace([',',' '],'',$v);if($v===''||!is_numeric($v))return 0.0;return (float)$v;}
    private static function month(string $v):string{$v=preg_replace('/\D+/','',$v)?:'';return preg_match('/^20\d{4}$/',$v)?$v:'';}
    private static function dateTime(string $v):?string{$v=trim($v);if($v===''||$v==='-')return null;if(preg_match('/^(\d{4})[:\/-](\d{2})[:\/-](\d{2})\s+(\d{2}):(\d{2}):(\d{2})/',$v,$m))return "$m[1]-$m[2]-$m[3] $m[4]:$m[5]:$m[6]";$ts=strtotime(str_replace('(UTC+0)','',$v));return $ts===false?null:gmdate('Y-m-d H:i:s',$ts);}
    private static function upsertCreator(string $id,array $d):void{$q=db()->prepare("INSERT INTO agency_creators(creator_id,handle,nickname,group_name,network_manager,group_manager,agency_account,relationship_status,subscription_status,last_live_at,joined_at,followers,notes,active,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1,'{}') ON DUPLICATE KEY UPDATE handle=COALESCE(NULLIF(VALUES(handle),''),handle),nickname=COALESCE(NULLIF(VALUES(nickname),''),nickname),group_name=COALESCE(NULLIF(VALUES(group_name),''),group_name),network_manager=COALESCE(NULLIF(VALUES(network_manager),''),network_manager),group_manager=COALESCE(NULLIF(VALUES(group_manager),''),group_manager),agency_account=COALESCE(NULLIF(VALUES(agency_account),''),agency_account),relationship_status=COALESCE(NULLIF(VALUES(relationship_status),''),relationship_status),subscription_status=COALESCE(NULLIF(VALUES(subscription_status),''),subscription_status),last_live_at=COALESCE(VALUES(last_live_at),last_live_at),joined_at=COALESCE(VALUES(joined_at),joined_at),followers=COALESCE(VALUES(followers),followers),notes=COALESCE(NULLIF(VALUES(notes),''),notes),active=1");$q->execute([$id,$d['handle']??null,$d['nickname']??null,$d['group_name']??null,$d['network_manager']??null,$d['group_manager']??null,$d['agency_account']??null,$d['relationship_status']??null,$d['subscription_status']??null,$d['last_live_at']??null,$d['joined_at']??null,$d['followers']??null,$d['notes']??null]);}
    private static function upsertMonthly(string $id,string $month,string $source,array $d,array $raw,int $importId):void{if(!preg_match('/^20\d{4}$/',$month))$month=gmdate('Ym');$q=db()->prepare("INSERT INTO agency_creator_monthly(creator_id,data_month,source_type,diamonds,valid_days,live_hours,estimated_bonus,followers,videos,likes,fan_diamonds,active_fans,raw_json,import_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE diamonds=VALUES(diamonds),valid_days=VALUES(valid_days),live_hours=VALUES(live_hours),estimated_bonus=VALUES(estimated_bonus),followers=VALUES(followers),videos=VALUES(videos),likes=VALUES(likes),fan_diamonds=VALUES(fan_diamonds),active_fans=VALUES(active_fans),raw_json=VALUES(raw_json),import_id=VALUES(import_id),updated_at=NOW()");$q->execute([$id,$month,$source,(int)round((float)($d['diamonds']??0)),(float)($d['valid_days']??0),(float)($d['live_hours']??0),(float)($d['estimated_bonus']??0),isset($d['followers'])?(int)$d['followers']:null,isset($d['videos'])?(int)$d['videos']:null,isset($d['likes'])?(int)$d['likes']:null,isset($d['fan_diamonds'])?(int)$d['fan_diamonds']:null,isset($d['active_fans'])?(int)$d['active_fans']:null,j($raw),$importId]);}
    private static function attention(array $r):array{$reasons=[];$score=0;$d=(int)$r['diamonds'];$days=(float)$r['valid_days'];$hours=(float)$r['live_hours'];$prev=(int)($r['previous_diamonds']??0);if($d===0){$score+=50;$reasons[]='لا توجد ماسات في الفترة الحالية';}elseif($prev>0&&$d<$prev*0.7){$score+=35;$reasons[]='الماسات أقل بأكثر من 30% من الفترة السابقة';}if($days<5){$score+=25;$reasons[]='أيام البث الصالحة منخفضة';}if($hours<10){$score+=20;$reasons[]='ساعات البث منخفضة';}if(!empty($r['last_live_at'])&&($ts=utc_ts((string)$r['last_live_at']))!==false&&$ts<time()-7*86400){$score+=30;$reasons[]='آخر بث أقدم من 7 أيام';}return ['score'=>min(100,$score),'reasons'=>$reasons,'can_official_match'=>empty($r['no_official_matches']),'can_tapping_campaign'=>empty($r['no_tapping_campaigns'])];}
}
