<?php
declare(strict_types=1);
final class AgentActionService {
    public static function schema():array{
        return ['type'=>'array','items'=>['type'=>'object','additionalProperties'=>false,'properties'=>['type'=>['type'=>'string'],'payload_json'=>['type'=>'string'],'reason'=>['type'=>'string']],'required'=>['type','payload_json','reason']]];
    }
    private static function payload(array $action):array{$raw=trim((string)($action['payload_json']??''));if($raw==='')return [];try{$p=json_decode($raw,true,64,JSON_THROW_ON_ERROR);return is_array($p)?$p:[];}catch(Throwable){throw new RuntimeException('agent_action_payload_invalid');}}
    private static function approved(array $task,string $type):bool{$ctx=json_decode((string)($task['context_json']??''),true);if(!is_array($ctx))$ctx=[];$approved=array_map('strval',(array)($ctx['approved_actions']??[]));return in_array($type,$approved,true)||in_array('*',$approved,true);}
    public static function execute(array $agent,array $task,array $action):array{
        $type=trim((string)($action['type']??''));$p=self::payload($action);$agentId=(int)$agent['id'];$projectId=$task['project_id']?(int)$task['project_id']:null;$taskId=(int)$task['id'];
        return match($type){
            'learning.propose'=>self::learn($agentId,$projectId,$taskId,$p),
            'learning.change_proposal'=>self::changeProposal($agentId,$projectId,$taskId,$p),
            'followup.schedule'=>self::followup($agentId,$projectId,$taskId,$p),
            'team.message'=>self::teamMessage($agent,$task,$p),
            'owner.message'=>self::ownerMessage($agent,$p),
            'account.create'=>self::accountCreate($agentId,$task,$p),
            'browser.execute'=>self::browser($agentId,$task,$p),
            'data.ensure_schema'=>self::ensureSchema($agentId,$p),
            'data.add_row'=>self::addRow($agentId,$projectId,$p),
            'social.contact_upsert'=>self::contact($agentId,$p),
            'social.content_draft'=>self::draft($agentId,$projectId,$p),
            'video.generate'=>self::video($agentId,$projectId,$taskId,$p),
            'telegram.send'=>self::telegram($agentId,$task,$p),
            'tiktok.publish'=>self::tiktok($agentId,$task,$p),
            'facebook.publish'=>self::socialPublish($agentId,$task,$p,'facebook.publish'),
            'instagram.publish'=>self::socialPublish($agentId,$task,$p,'instagram.publish'),
            'social.publish'=>self::socialPublish($agentId,$task,$p,'social.publish'),
            'youtube.upload'=>self::youtube($agentId,$task,$p),
            'whatsapp.send'=>self::whatsapp($agentId,$task,$p),
            default=>throw new RuntimeException('agent_action_not_supported:'.$type)
        };
    }
    private static function changeProposal(int $agentId,?int $projectId,int $taskId,array $p):array{Permissions::requireAgent($agentId,'learning.propose');$id=AgentChangeProposalService::propose($agentId,(string)($p['proposal_type']??'workflow'),(string)($p['title']??''),(string)($p['summary']??''),(string)($p['reason']??''),(array)($p['payload']??[]),(string)($p['risk_level']??'medium'),$projectId,$taskId);return ['type'=>'learning.change_proposal','id'=>$id,'evidence'=>'change_proposal#'.$id];}
    private static function followup(int $agentId,?int $projectId,int $taskId,array $p):array{$due=trim((string)($p['due_at']??''));if($due===''&&!empty($p['after_hours']))$due=gmdate('Y-m-d H:i:s',time()+max(1,min(720,(int)$p['after_hours']))*3600);$id=AgentFollowupService::schedule($agentId,(string)($p['purpose']??''),$due,(string)($p['message']??''),$projectId,$taskId,(int)($p['contact_id']??0)?:null,(string)($p['channel']??'dashboard'));return ['type'=>'followup.schedule','id'=>$id,'evidence'=>'followup#'.$id];}
    private static function teamMessage(array $agent,array $task,array $p):array{Permissions::requireAgent((int)$agent['id'],'team_chat.write');$to=trim((string)($p['to_slug']??'team'));$body=trim((string)($p['text']??''));if($body==='')throw new RuntimeException('team_message_required');if($to==='team'){TeamChatService::post('agent',(string)$agent['slug'],'team',$body,'note',$task['project_id']?(int)$task['project_id']:null,(int)$task['id']);return ['type'=>'team.message','evidence'=>'team_chat'];}$command=!array_key_exists('dispatch',$p)||!empty($p['dispatch']);if($command){$r=TeamChatService::dispatchAgentCommand((string)$agent['slug'],$to,$body,(int)$task['id'],$task['project_id']?(int)$task['project_id']:null);return ['type'=>'team.message','evidence'=>'team_dispatch#'.(int)($r['primary_task']??0),'result'=>$r];}TeamChatService::agentMessage((string)$agent['slug'],$to,$body,(int)$task['id'],$task['project_id']?(int)$task['project_id']:null);return ['type'=>'team.message','evidence'=>'team_chat'];}
    private static function ownerMessage(array $agent,array $p):array{Permissions::requireAgent((int)$agent['id'],'team_chat.write');$text=trim((string)($p['text']??''));if($text==='')throw new RuntimeException('owner_message_required');$r=CommunicationGateway::agentToOwner((string)$agent['slug'],$text,'dashboard',false,!empty($p['emergency']));return ['type'=>'owner.message','evidence'=>'owner_dashboard_message','result'=>['sent'=>(bool)($r['sent']??false),'session_id'=>$r['session_id']??null]];}
    private static function accountCreate(int $agentId,array $task,array $p):array{Permissions::requireAgent($agentId,'accounts.create');if(!self::approved($task,'account.create'))throw new RuntimeException('owner_approval_required:account.create');$r=SocialAccountWorkflowService::request($agentId,['platform'=>(string)($p['platform']??''),'display_name'=>(string)($p['display_name']??''),'username'=>(string)($p['username']??''),'email'=>(string)($p['email']??''),'login_url'=>(string)($p['login_url']??''),'purpose'=>(string)($p['purpose']??''),'owner_agent_id'=>$agentId],(int)$task['id']);return ['type'=>'account.create','id'=>(int)$r['account_id'],'evidence'=>'service_account#'.(int)$r['account_id'],'result'=>$r];}
    private static function browser(int $agentId,array $task,array $p):array{$op=(string)($p['operation']??'snapshot');if(in_array($op,['send_message','create_account','fill','submit'],true)&&!self::approved($task,'browser.external'))throw new RuntimeException('owner_approval_required:browser.external');$r=BrowserAutomationService::execute($agentId,(int)($p['account_id']??0),$op,(array)($p['params']??[]));return ['type'=>'browser.execute','evidence'=>'browser_operation:'.$op,'result'=>$r];}
    private static function learn(int $agentId,?int $projectId,int $taskId,array $p):array{Permissions::requireAgent($agentId,'learning.propose');$id=AgentLearningService::proposeAuto($agentId,(string)($p['learning_type']??'experience'),(string)($p['text']??''),$projectId,$taskId,(int)($p['confidence']??75));return ['type'=>'learning.propose','id'=>$id,'evidence'=>'learning#'.$id];}
    private static function ensureSchema(int $agentId,array $p):array{Permissions::requireAgent($agentId,'agent_data.schema');$id=AgentDataService::ensureSchema($agentId,(string)($p['schema_key']??''),(string)($p['label']??''),(string)($p['description']??''),(string)($p['scope']??'agent'),(array)($p['fields']??[]));return ['type'=>'data.ensure_schema','id'=>$id,'evidence'=>'schema#'.$id];}
    private static function addRow(int $agentId,?int $projectId,array $p):array{Permissions::requireAgent($agentId,'agent_data.write');$schema=AgentDataService::schemaByKey($agentId,(string)($p['schema_key']??''));$id=AgentDataService::addRow((int)$schema['id'],(array)($p['data']??[]),$projectId,(string)($p['row_label']??''));return ['type'=>'data.add_row','id'=>$id,'evidence'=>'data_row#'.$id];}
    private static function contact(int $agentId,array $p):array{$id=SocialMediaService::upsertContact($agentId,(string)($p['platform']??'other'),(string)($p['external_ref']??''),(string)($p['display_name']??''),(string)($p['phone']??''),(string)($p['email']??''),(string)($p['username']??''),(string)($p['member_role']??''),(array)($p['tags']??[]),(string)($p['notes']??''));return ['type'=>'social.contact_upsert','id'=>$id,'evidence'=>'social_contact#'.$id];}
    private static function draft(int $agentId,?int $projectId,array $p):array{$id=SocialMediaService::draftContent($agentId,$projectId,(string)($p['content_type']??'text'),(string)($p['title']??''),(string)($p['caption']??''),(string)($p['prompt']??''),isset($p['asset_id'])?(int)$p['asset_id']:null,isset($p['scheduled_at'])?(string)$p['scheduled_at']:null);return ['type'=>'social.content_draft','id'=>$id,'evidence'=>'social_content#'.$id];}
    private static function video(int $agentId,?int $projectId,int $taskId,array $p):array{$r=VideoProductionService::create($agentId,$projectId,$taskId,(string)($p['title']??''),(string)($p['concept']??''),(int)($p['duration_seconds']??30),(string)($p['aspect_ratio']??'16:9'),(string)($p['target_platform']??'youtube'));return ['type'=>'video.generate','evidence'=>'video_production#'.($r['production_id']??0),'result'=>$r];}
    private static function telegram(int $agentId,array $task,array $p):array{Permissions::requireAgent($agentId,'telegram.send');if(!self::approved($task,'telegram.send'))throw new RuntimeException('owner_approval_required:telegram.send');$text=(string)($p['text']??'');$r=TelegramClient::sendMessage((string)($p['chat_id']??''),$text);$messageId=(string)($r['result']['message_id']??'');try{SocialMediaService::recordInteraction($agentId,'telegram','outbound','message',$messageId!==''?'tg:'.$messageId:'',$text,null,[]);}catch(Throwable){}return ['type'=>'telegram.send','evidence'=>'telegram_message#'.($messageId?:'accepted')];}
    private static function tiktok(int $agentId,array $task,array $p):array{Permissions::requireAgent($agentId,'tiktok.publish');if(!self::approved($task,'tiktok.publish'))throw new RuntimeException('owner_approval_required:tiktok.publish');$r=TikTokClient::initDirectPostFromUrl((string)($p['video_url']??''),(string)($p['title']??''),(string)($p['privacy_level']??'SELF_ONLY'),!empty($p['disable_comment']),!empty($p['disable_duet']),!empty($p['disable_stitch']),!empty($p['brand_content_toggle']),array_key_exists('brand_organic_toggle',$p)?(bool)$p['brand_organic_toggle']:true,array_key_exists('is_aigc',$p)?(bool)$p['is_aigc']:true);return ['type'=>'tiktok.publish','evidence'=>'tiktok_publish#'.($r['data']['publish_id']??'accepted'),'result'=>$r];}
    private static function socialPublish(int $agentId,array $task,array $p,string $approval):array{Permissions::requireAgent($agentId,'social.publish');if(!self::approved($task,$approval)&&!self::approved($task,'social.publish'))throw new RuntimeException('owner_approval_required:'.$approval);$contentId=(int)($p['content_id']??0);$accountId=(int)($p['account_id']??0);if(!$contentId||!$accountId)throw new RuntimeException('social_publish_content_and_account_required');$account=SocialMediaService::account($accountId);if($approval==='facebook.publish'&&(string)$account['platform']!=='facebook')throw new RuntimeException('social_account_platform_mismatch');if($approval==='instagram.publish'&&(string)$account['platform']!=='instagram')throw new RuntimeException('social_account_platform_mismatch');$r=SocialPublisher::queue($contentId,$accountId,$agentId,true,true);return ['type'=>$approval,'evidence'=>'social_publication#'.($r['publication_id']??0),'result'=>$r];}
    private static function youtube(int $agentId,array $task,array $p):array{if(!self::approved($task,'youtube.upload'))throw new RuntimeException('owner_approval_required:youtube.upload');$r=VideoProductionService::uploadYouTube($agentId,(int)($p['production_id']??0),(string)($p['privacy']??'private'),(string)($p['description']??''));return ['type'=>'youtube.upload','evidence'=>'youtube_video#'.($r['id']??'accepted'),'result'=>$r];}
    private static function whatsapp(int $agentId,array $task,array $p):array{Permissions::requireAgent($agentId,'whatsapp.send');if(!self::approved($task,'whatsapp.send'))throw new RuntimeException('owner_approval_required:whatsapp.send');$text=(string)($p['text']??'');$r=CommunicationGateway::outboundCustomer((int)($p['customer_id']??0),$text);try{SocialMediaService::recordInteraction($agentId,'whatsapp','outbound','message','',$text,null,[]);}catch(Throwable){}return ['type'=>'whatsapp.send','evidence'=>'whatsapp_'.(!empty($r['sent'])?'sent':'queued'),'result'=>$r];}
}
