<?php
declare(strict_types=1);
final class AgentInitiativeService {
    private const SAFE_ACTIONS=['review_pipeline','prepare_owner_brief','engineering_review','qa_security_review','social_operations_review','media_queue_review','creator_review','community_review','free_model_review','role_review'];
    public static function all(int $limit=200):array{$limit=max(1,min(500,$limit));return db()->query("SELECT i.*,a.display_name agent_name,a.slug agent_slug,g.title goal_title FROM agent_initiatives i JOIN agents a ON a.id=i.agent_id LEFT JOIN company_goals g ON g.id=i.goal_id ORDER BY i.id DESC LIMIT ".$limit)->fetchAll();}
    public static function propose(int $agentId,string $title,string $summary,string $action,string $risk='low',int $value=50,?int $goalId=null,?int $projectId=null,array $payload=[],?float $expectedDelta=null,string $reason=''):int{
        $action=trim($action)?:'role_review';$risk=in_array($risk,['none','low','medium','high','destructive'],true)?$risk:'high';$value=max(0,min(100,$value));if($goalId&&!CompanyGoalService::validateAssignment($goalId,$agentId))$goalId=null;$dedupe=hash('sha256',$agentId.'|'.$action.'|'.($projectId?:0).'|'.($goalId?:0).'|'.gmdate('Y-m-d'));
        $q=db()->prepare("SELECT id FROM agent_initiatives WHERE agent_id=? AND dedupe_key=? AND state IN ('proposed','approved','queued','executing','completed') AND created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) LIMIT 1");$q->execute([$agentId,$dedupe]);$existing=(int)($q->fetchColumn()?:0);if($existing)return $existing;$requires=in_array($risk,['high','destructive'],true)?1:0;
        db()->prepare("INSERT INTO agent_initiatives(uid,agent_id,goal_id,project_id,initiative_type,title,summary,proposed_action,value_score,risk_level,requires_owner_approval,dedupe_key,reasoning_summary,payload_json,state,expires_at,expected_delta) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'proposed',DATE_ADD(NOW(),INTERVAL 2 DAY),?)")
            ->execute([uid('IN13'),$agentId,$goalId,$projectId,'typed',pb_substr($title,0,220),pb_substr($summary,0,12000),pb_substr($action,0,120),$value,$risk,$requires,$dedupe,pb_substr($reason,0,8000),$payload?j($payload):null,$expectedDelta]);$id=(int)db()->lastInsertId();if($goalId)db()->prepare('INSERT INTO agent_goal_contributions(goal_id,agent_id,initiative_id,expected_delta,note) VALUES (?,?,?,?,?)')->execute([$goalId,$agentId,$id,$expectedDelta,'Initiative proposed']);return $id;
    }
    public static function approve(int $id,int $ownerId):array{Auth::requireOwner();$i=self::get($id);if(!in_array((string)$i['state'],['proposed','failed'],true))throw new RuntimeException('initiative_not_approvable');db()->prepare("UPDATE agent_initiatives SET state='approved',approved_by_user_id=?,approved_at=NOW() WHERE id=?")->execute([$ownerId,$id]);return self::execute($id,true);}
    public static function reject(int $id,int $ownerId,string $note=''):void{Auth::requireOwner();self::get($id);db()->prepare("UPDATE agent_initiatives SET state='rejected',result_json=? WHERE id=? AND state IN ('proposed','approved')")->execute([j(['owner_id'=>$ownerId,'note'=>pb_substr($note,0,1000)]),$id]);}
    public static function execute(int $id,bool $ownerApproved=false):array{
        $i=self::get($id);$agent=AgentService::assertRunnable((int)$i['agent_id']);$slug=(string)$agent['slug'];$projectId=$i['project_id']?(int)$i['project_id']:null;$risk=(string)$i['risk_level'];
        if((string)$i['state']==='completed')return ['initiative_id'=>$id,'state'=>'completed','result'=>json_decode((string)($i['result_json']??'{}'),true)?:[],'already_completed'=>true];
        if((string)$i['state']==='executing')return ['initiative_id'=>$id,'state'=>'executing','result'=>[],'already_executing'=>true];
        if((int)$i['requires_owner_approval']===1&&!$ownerApproved&&empty($i['approved_at']))throw new RuntimeException('owner_approval_required:initiative');$action=(string)$i['proposed_action'];if(!in_array($action,self::SAFE_ACTIONS,true))throw new RuntimeException('initiative_action_requires_workflow:'.$action);
        db()->prepare("UPDATE agent_initiatives SET state='executing' WHERE id=?")->execute([$id]);
        try{TeamChatService::post('agent',$slug,'team','بدأت مبادرة تلقائية #'.$id.': '.pb_substr((string)$i['title'],0,160),'status',$projectId,null,['initiative_id'=>$id,'action'=>$action]);}catch(Throwable){}
        try{
            $payload=json_decode((string)($i['payload_json']??'{}'),true)?:[];$result=CoreAgentInitiativeService::execute($agent,$action,$payload);$actual=array_key_exists('actual_metric_delta',$result)?(float)$result['actual_metric_delta']:null;
            db()->prepare("UPDATE agent_initiatives SET state='completed',result_json=?,executed_at=NOW(),actual_delta=? WHERE id=?")->execute([j($result),$actual,$id]);if($i['goal_id'])db()->prepare('UPDATE agent_goal_contributions SET actual_delta=?,note=? WHERE initiative_id=?')->execute([$actual,'Initiative completed',$id]);
            $summary=trim((string)($result['message']??$result['summary']??''));if($summary==='')$summary='اكتملت المراجعة الداخلية وسُجلت النتيجة.';
            try{TeamChatService::post('agent',$slug,'team','أنهيت المبادرة #'.$id.': '.pb_substr($summary,0,220),'status',$projectId,null,['initiative_id'=>$id,'state'=>'completed']);}catch(Throwable){}
            return ['initiative_id'=>$id,'state'=>'completed','result'=>$result];
        }catch(Throwable $e){$safe=pb_substr(Security::redactSecrets($e->getMessage()),0,500);db()->prepare("UPDATE agent_initiatives SET state='failed',result_json=?,executed_at=NOW() WHERE id=?")->execute([j(['error'=>$safe]),$id]);try{TeamChatService::post('agent',$slug,'ramy','توقفت المبادرة #'.$id.' وتحتاج تشخيصًا: '.AdminUi::humanError($safe),'status',$projectId,null,['initiative_id'=>$id,'state'=>'failed']);}catch(Throwable){}throw $e;}
    }
    public static function get(int $id):array{$q=db()->prepare('SELECT * FROM agent_initiatives WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('initiative_not_found');return $r;}
    public static function defaultAction(string $slug):string{return match($slug){'ramy'=>'review_pipeline','ayman'=>'engineering_review','emad'=>'qa_security_review','samir-social'=>'social_operations_review','video-director'=>'media_queue_review','basant'=>'creator_review','community-manager'=>'community_review','free-model-scout'=>'free_model_review',default=>'role_review'};}
}
