<?php
declare(strict_types=1);
final class AgentResourceService {
    private const TYPES=['project','subdomain','database','file','folder','custom_table','external_account','workflow','contact','task','test_target'];
    public static function request(int $agentId,string $type,array $payload):int{
        AgentService::assertRunnable($agentId);$type=strtolower(trim($type));if(!in_array($type,self::TYPES,true))throw new RuntimeException('resource_type_unsupported');AgentCapabilityService::require($agentId,'resource_manager','use');
        $risk=in_array($type,['subdomain','database','custom_table','external_account','test_target'],true)?'medium':'low';$projectId=(int)($payload['project_id']??0)?:null;
        $policy=AgentPolicyEngine::check($agentId,'resource_manager','use',['risk'=>$risk,'external'=>in_array($type,['subdomain','database','external_account'],true),'project_id'=>$projectId,'owner_approved'=>false,'gateway_managed'=>true]);
        $approval=empty($policy['allowed'])||$risk!=='low'||!empty($payload['requires_owner_approval']);
        db()->prepare("INSERT INTO resource_requests(agent_id,resource_type,project_id,payload_json,risk_level,requires_owner_approval,state) VALUES (?,?,?,?,?,?,?)")
          ->execute([$agentId,$type,$projectId,j(self::clean($payload)),$risk,$approval?1:0,$approval?'pending_approval':'approved']);$id=(int)db()->lastInsertId();if(!$approval)self::execute($id,true);return $id;
    }
    public static function approve(int $id,int $ownerId=1):array{Auth::requireOwner();$q=db()->prepare('SELECT * FROM resource_requests WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('resource_request_not_found');db()->prepare("UPDATE resource_requests SET state='approved',approved_by_user_id=?,approved_at=NOW() WHERE id=?")->execute([$ownerId,$id]);return self::execute($id,true);}
    public static function execute(int $id,bool $ownerApproved=false):array{
        $q=db()->prepare('SELECT * FROM resource_requests WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('resource_request_not_found');if(in_array((string)$r['state'],['completed'],true))return ['state'=>'completed','resource_id'=>$r['resource_id']];if((int)$r['requires_owner_approval']&&!$ownerApproved)throw new RuntimeException('owner_approval_required:resource');$agentId=(int)$r['agent_id'];$type=(string)$r['resource_type'];$d=json_decode((string)$r['payload_json'],true)?:[];$projectId=(int)($r['project_id']??0)?:null;
        AgentPolicyEngine::authorizeAction($agentId,'resource_manager',$ownerApproved?'use':'manage',['risk'=>(string)$r['risk_level'],'external'=>in_array($type,['subdomain','database','external_account'],true),'project_id'=>$projectId,'owner_approved'=>$ownerApproved,'gateway_managed'=>true]);db()->prepare("UPDATE resource_requests SET state='executing',last_error=NULL WHERE id=?")->execute([$id]);
        try{$out=match($type){'project'=>self::project($agentId,$d),'subdomain'=>self::subdomain($agentId,$d),'database'=>self::database($agentId,$d),'file'=>self::file($agentId,$d,false),'folder'=>self::file($agentId,$d,true),'custom_table'=>self::table($agentId,$d),'external_account'=>self::account($agentId,$d),'workflow'=>self::workflow($agentId,$d),'contact'=>self::contact($agentId,$d),'task'=>self::task($agentId,$d),'test_target'=>self::target($agentId,$d),default=>throw new RuntimeException('resource_type_unsupported')};$rid=(int)($out['resource_id']??0)?:null;db()->prepare("UPDATE resource_requests SET state='completed',resource_id=?,completed_at=NOW(),result_json=? WHERE id=?")->execute([$rid,j(self::clean($out)),$id]);return $out+['request_id'=>$id];}catch(Throwable $e){db()->prepare("UPDATE resource_requests SET state='failed',last_error=? WHERE id=?")->execute([substr(Security::redactSecrets($e->getMessage()),0,500),$id]);throw $e;}
    }
    public static function list(int $limit=200):array{$limit=max(1,min(500,$limit));return db()->query('SELECT r.*,a.display_name agent_name,p.name project_name FROM resource_requests r JOIN agents a ON a.id=r.agent_id LEFT JOIN projects p ON p.id=r.project_id ORDER BY r.id DESC LIMIT '.$limit)->fetchAll();}
    private static function project(int $a,array $d):array{$name=trim((string)($d['name']??''));if($name==='')throw new RuntimeException('project_name_required');$uid=uid('PRJ');db()->prepare("INSERT INTO projects(uid,name,status,workflow_stage,source,hosting_presence,metadata_json) VALUES (?,?, 'development','awaiting_execution','system','unknown',?)")->execute([$uid,substr($name,0,220),j(['created_by_agent_id'=>$a])]);$id=(int)db()->lastInsertId();$rid=ResourceRegistryService::register('project',$uid,$name,$a,$id,(string)($d['primary_domain']??''),[]);return ['resource_id'=>$rid,'project_id'=>$id,'uid'=>$uid];}
    private static function subdomain(int $a,array $d):array{$pid=(int)($d['project_id']??0);$sub=trim((string)($d['subdomain']??''));$dir=trim((string)($d['directory']??''));if(!$pid||$sub===''||$dir==='')throw new RuntimeException('subdomain_request_invalid');$r=HostingerClient::createSubdomain($pid,$sub,$dir,true);$p=ProjectService::get($pid);$base=trim((string)($d['base_domain']??setting('staging.domain','nourmakkah.com')))?:'nourmakkah.com';$fqdn=str_contains($sub,'.')?$sub:$sub.'.'.$base;$rid=ResourceRegistryService::register('subdomain',$fqdn,$fqdn,$a,$pid,$fqdn,['directory'=>$dir]);return ['resource_id'=>$rid,'domain'=>$fqdn,'provider_result'=>$r];}
    private static function database(int $a,array $d):array{$pid=(int)($d['project_id']??0);if(!$pid)throw new RuntimeException('project_required');$db=StagingDatabaseService::ensureForProject($pid,(int)($d['source_db_id']??0));$key='project:'.$pid.':staging_db:'.($db['id']??0);$rid=ResourceRegistryService::register('database',$key,(string)($db['db_name']??'staging database'),$a,$pid,(string)($db['db_name']??''),['project_database_id'=>$db['id']??null]);return ['resource_id'=>$rid,'database_id'=>$db['id']??null,'database_name'=>$db['db_name']??null,'verified'=>true];}
    private static function file(int $a,array $d,bool $folder):array{$pid=(int)($d['project_id']??0);$path=trim((string)($d['path']??''));if(!$pid||$path===''||str_contains($path,'..'))throw new RuntimeException('resource_path_invalid');$write=$folder?rtrim($path,'/').'/.persebayt_keep':$path;$agent=AgentService::byId($a);$task=(int)($d['task_id']??0);if(!$task)$task=TaskService::create((string)$agent['slug'],'Create resource '.$path,'Create managed resource in approved project.',$pid,['resource_create'=>true],'normal',true,null,'agent',(string)$a,false);$r=HostingerClient::writeFile($pid,$task,$write,$folder?'PerseBayt managed folder':(string)($d['content']??''),true);$rid=ResourceRegistryService::register($folder?'folder':'file',$pid.':'.$path,$path,$a,$pid,$path,[]);return ['resource_id'=>$rid,'path'=>$path,'evidence'=>$r];}
    private static function table(int $a,array $d):array{$rid=PhysicalSchemaService::request($a,(string)($d['label']??$d['name']??'agent_data'),(array)($d['fields']??[]),(string)($d['reason']??''));return ['schema_request_id'=>$rid,'state'=>'pending_approval'];}
    private static function account(int $a,array $d):array{$r=SocialAccountWorkflowService::request($a,$d,(int)($d['task_id']??0));$rid=ResourceRegistryService::register('external_account','account:'.(string)($r['account_id']??uid('A')),(string)($d['display_name']??$d['platform']??'account'),$a,null,(string)($r['account_id']??''),['state'=>$r['state']??null]);return ['resource_id'=>$rid]+$r;}
    private static function workflow(int $a,array $d):array{$wid=AgentWorkflowService::saveTemplate($d,(int)(Auth::user()['id']??1));AgentWorkflowService::assign($a,$wid,true);$rid=ResourceRegistryService::register('workflow','workflow:'.$wid,(string)($d['name']??'workflow'),$a,null,(string)$wid,[]);return ['resource_id'=>$rid,'workflow_id'=>$wid];}
    private static function contact(int $a,array $d):array{$id=ContactDirectoryService::save($d);$rid=ResourceRegistryService::register('contact','contact:'.$id,(string)($d['display_name']??'contact'),$a,null,(string)$id,[]);return ['resource_id'=>$rid,'contact_id'=>$id];}
    private static function task(int $a,array $d):array{$agent=AgentService::byId($a);$id=TaskService::create((string)($d['agent_slug']??$agent['slug']),(string)($d['title']??'Agent task'),(string)($d['description']??''),(int)($d['project_id']??0)?:null,['resource_request'=>true],(string)($d['priority']??'normal'),true);$rid=ResourceRegistryService::register('task','task:'.$id,(string)($d['title']??'task'),$a,(int)($d['project_id']??0)?:null,(string)$id,[]);return ['resource_id'=>$rid,'task_id'=>$id];}
    private static function target(int $a,array $d):array{$id=SecurityLabService::createTarget($d,(string)(Auth::user()['id']??1));$rid=ResourceRegistryService::register('test_target','target:'.$id,(string)($d['label']??'test target'),$a,(int)($d['project_id']??0)?:null,(string)$id,[]);return ['resource_id'=>$rid,'target_id'=>$id];}
    private static function clean(array $a):array{foreach($a as $k=>&$v){if(preg_match('/password|secret|token|api[_-]?key/i',(string)$k))$v='[REDACTED]';elseif(is_array($v))$v=self::clean($v);}unset($v);return $a;}
}
