<?php
declare(strict_types=1);
final class AgentCapabilityService {
    private const SOURCE_TYPES=['capability','role_template','owner_manual','system','legacy_manual'];
    private const LEVELS=['none'=>0,'read'=>1,'use'=>2,'manage'=>3,'approve'=>4];
    public static function catalogForAgent(int $agentId):array{
        AgentService::byId($agentId);
        $q=db()->prepare("SELECT c.*,COALESCE(a.enabled,0) assigned,COALESCE(a.access_level,c.default_access_level,'use') access_level,a.config_json assignment_config,a.requires_owner_approval assignment_requires_owner_approval,a.requires_backup assignment_requires_backup FROM agent_capability_catalog c LEFT JOIN agent_capability_assignments a ON a.capability_key=c.capability_key AND a.agent_id=? WHERE c.enabled=1 ORDER BY c.label_ar,c.capability_key");
        $q->execute([$agentId]);return $q->fetchAll();
    }
    public static function set(int $agentId,string $key,bool $enabled,array $config=[]):void{$cap=self::catalogRow($key);self::setWithLevel($agentId,$key,self::normalizeLevel((string)($cap['default_access_level']??'use')),$enabled,null,null,$config);}
    public static function setWithLevel(int $agentId,string $key,string $level='use',bool $enabled=true,?bool $ownerApproval=null,?bool $backup=null,array $config=[]):void{
        AgentService::byId($agentId);$cap=self::catalogRow($key);$level=self::normalizeLevel($level);if($level==='none')$enabled=false;
        $oa=$ownerApproval===null?(int)($cap['requires_owner_approval']??0):($ownerApproval?1:0);$bk=$backup===null?(int)($cap['requires_backup']??0):($backup?1:0);
        db()->prepare("INSERT INTO agent_capability_assignments(agent_id,capability_key,access_level,enabled,requires_owner_approval,requires_backup,config_json) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE access_level=VALUES(access_level),enabled=VALUES(enabled),requires_owner_approval=VALUES(requires_owner_approval),requires_backup=VALUES(requires_backup),config_json=VALUES(config_json),updated_at=NOW()")
          ->execute([$agentId,$key,$level,$enabled?1:0,$oa,$bk,$config?j($config):'{}']);
        $perms=self::jsonList($cap['permission_keys_json']??'[]');$tool=trim((string)($cap['tool_key']??''));
        if($enabled){foreach($perms as $p)self::grantPermission($agentId,$p,'capability',$key);if($tool!=='')self::grantTool($agentId,$tool,'capability',$key);}
        else{foreach($perms as $p)self::removePermissionSource($agentId,$p,'capability',$key);if($tool!=='')self::removeToolSource($agentId,$tool,'capability',$key);}
        try{Audit::log('owner',(string)(Auth::user()['id']??1),'agent.capability','agent',(string)$agentId,'verified',null,null,['capability'=>$key,'enabled'=>$enabled,'access_level'=>$level]);}catch(Throwable){}
    }
    public static function assignment(int $agentId,string $key):?array{$q=db()->prepare("SELECT a.*,c.label_ar,c.description_text,c.tool_key,c.permission_keys_json,c.default_access_level,c.risk_level catalog_risk,c.requires_owner_approval catalog_requires_owner_approval,c.requires_backup catalog_requires_backup,c.external_action,c.production_sensitive FROM agent_capability_assignments a JOIN agent_capability_catalog c ON c.capability_key=a.capability_key WHERE a.agent_id=? AND a.capability_key=? LIMIT 1");$q->execute([$agentId,$key]);return $q->fetch()?:null;}
    public static function require(int $agentId,string $key,string $level='use'):array{$a=self::assignment($agentId,$key);if(!$a||(int)$a['enabled']!==1)throw new RuntimeException('agent_capability_denied:'.$key);$have=self::normalizeLevel((string)($a['access_level']??$a['default_access_level']??'use'));$need=self::normalizeLevel($level);if((self::LEVELS[$have]??0)<(self::LEVELS[$need]??2))throw new RuntimeException('agent_capability_level_denied:'.$key.':'.$need);return $a;}
    public static function has(int $agentId,string $key,string $level='use'):bool{try{self::require($agentId,$key,$level);return true;}catch(Throwable){return false;}}
    public static function normalizeLevel(string $level):string{$level=strtolower(trim($level));return array_key_exists($level,self::LEVELS)?$level:'use';}
    public static function grantPermission(int $agentId,string $permission,string $sourceType='owner_manual',string $sourceKey='direct'):void{AgentService::byId($agentId);$permission=trim($permission);if($permission==='')throw new RuntimeException('permission_required');if(!self::permissionExists($permission))throw new RuntimeException('permission_not_in_catalog:'.$permission);$sourceType=self::sourceType($sourceType);$sourceKey=substr(trim($sourceKey)?:'direct',0,160);db()->prepare('INSERT IGNORE INTO agent_permission_sources(agent_id,permission_key,source_type,source_key) VALUES (?,?,?,?)')->execute([$agentId,$permission,$sourceType,$sourceKey]);db()->prepare('INSERT INTO agent_permissions(agent_id,permission_key,allowed) VALUES (?,?,1) ON DUPLICATE KEY UPDATE allowed=1')->execute([$agentId,$permission]);}
    public static function grantTool(int $agentId,string $tool,string $sourceType='owner_manual',string $sourceKey='direct',array $config=[]):void{AgentService::byId($agentId);$tool=trim($tool);if($tool==='')throw new RuntimeException('tool_required');$sourceType=self::sourceType($sourceType);$sourceKey=substr(trim($sourceKey)?:'direct',0,160);db()->prepare('INSERT IGNORE INTO agent_tool_sources(agent_id,tool_key,source_type,source_key) VALUES (?,?,?,?)')->execute([$agentId,$tool,$sourceType,$sourceKey]);db()->prepare("INSERT INTO agent_tools(agent_id,tool_key,allowed,config_json) VALUES (?,?,1,?) ON DUPLICATE KEY UPDATE allowed=1,config_json=VALUES(config_json)")->execute([$agentId,$tool,$config?j($config):'{}']);self::resumeToolJobs($agentId,$tool);}
    public static function revokeManualPermission(int $agentId,string $p,string $sourceKey='direct'):void{self::removePermissionSource($agentId,$p,'owner_manual',$sourceKey);}
    public static function revokeManualTool(int $agentId,string $t,string $sourceKey='direct'):void{self::removeToolSource($agentId,$t,'owner_manual',$sourceKey);}
    public static function bootstrap(int $agentId,array $selected=[],string $role='restricted'):void{$tpl=self::roleTemplate($role);$caps=$tpl?self::jsonList($tpl['default_capabilities_json']??'[]'):['structured_memory'];$perms=$tpl?self::jsonList($tpl['default_permissions_json']??'[]'):['tasks.create'];$tools=$tpl?self::jsonList($tpl['default_tools_json']??'[]'):['memory','task_context','team_chat'];foreach(array_unique(array_merge($caps,$selected)) as $k){try{self::set($agentId,(string)$k,true);}catch(Throwable){}}foreach($perms as $p){try{self::grantPermission($agentId,$p,'role_template',$role);}catch(Throwable){}}foreach($tools as $t){try{self::grantTool($agentId,$t,'role_template',$role);}catch(Throwable){}}}
    public static function synchronizeSources(int $agentId=0):array{$args=[];$sql='SELECT a.agent_id,a.capability_key,c.tool_key,c.permission_keys_json FROM agent_capability_assignments a JOIN agent_capability_catalog c ON c.capability_key=a.capability_key WHERE a.enabled=1';if($agentId>0){$sql.=' AND a.agent_id=?';$args[]=$agentId;}$q=db()->prepare($sql);$q->execute($args);$count=0;foreach($q->fetchAll() as $r){$aid=(int)$r['agent_id'];foreach(self::jsonList($r['permission_keys_json']??'[]') as $p){if(!self::permissionExists($p))continue;db()->prepare("INSERT IGNORE INTO agent_permission_sources(agent_id,permission_key,source_type,source_key) VALUES (?,?,'capability',?)")->execute([$aid,$p,$r['capability_key']]);$count++;}$t=trim((string)($r['tool_key']??''));if($t!=='')db()->prepare("INSERT IGNORE INTO agent_tool_sources(agent_id,tool_key,source_type,source_key) VALUES (?,?,'capability',?)")->execute([$aid,$t,$r['capability_key']]);}return ['sources_synced'=>$count];}
    public static function permissionExists(string $p):bool{$q=db()->prepare('SELECT COUNT(*) FROM permissions WHERE permission_key=?');$q->execute([$p]);return (int)$q->fetchColumn()>0;}
    public static function roleTemplate(string $key):?array{try{$q=db()->prepare('SELECT * FROM agent_role_templates WHERE template_key=? AND enabled=1');$q->execute([$key]);return $q->fetch()?:null;}catch(Throwable){return null;}}
    private static function catalogRow(string $key):array{$q=db()->prepare('SELECT * FROM agent_capability_catalog WHERE capability_key=? AND enabled=1');$q->execute([$key]);$r=$q->fetch();if(!$r)throw new RuntimeException('agent_capability_not_found:'.$key);return $r;}
    private static function removePermissionSource(int $a,string $p,string $st,string $sk):void{db()->prepare('DELETE FROM agent_permission_sources WHERE agent_id=? AND permission_key=? AND source_type=? AND source_key=?')->execute([$a,$p,$st,$sk]);$q=db()->prepare('SELECT COUNT(*) FROM agent_permission_sources WHERE agent_id=? AND permission_key=?');$q->execute([$a,$p]);if((int)$q->fetchColumn()===0)db()->prepare('UPDATE agent_permissions SET allowed=0 WHERE agent_id=? AND permission_key=?')->execute([$a,$p]);}
    private static function removeToolSource(int $a,string $t,string $st,string $sk):void{db()->prepare('DELETE FROM agent_tool_sources WHERE agent_id=? AND tool_key=? AND source_type=? AND source_key=?')->execute([$a,$t,$st,$sk]);$q=db()->prepare('SELECT COUNT(*) FROM agent_tool_sources WHERE agent_id=? AND tool_key=?');$q->execute([$a,$t]);if((int)$q->fetchColumn()===0)db()->prepare('UPDATE agent_tools SET allowed=0 WHERE agent_id=? AND tool_key=?')->execute([$a,$t]);}
    private static function jsonList(mixed $raw):array{$v=is_array($raw)?$raw:json_decode((string)$raw,true);if(!is_array($v))return [];return array_values(array_unique(array_filter(array_map(fn($x)=>trim((string)$x),$v))));}
    private static function sourceType(string $t):string{return in_array($t,self::SOURCE_TYPES,true)?$t:'owner_manual';}
    private static function resumeToolJobs(int $agentId,string $tool):void{try{$code='agent_tool_disabled:'.$tool;db()->prepare("UPDATE jobs SET state='queued',available_at=NOW(),error_code=NULL WHERE agent_id=? AND state='waiting' AND error_code=?")->execute([$agentId,$code]);WorkerWakeup::schedule();}catch(Throwable){}}
}
