<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){Auth::verifyCsrf();try{$r=AgentBuilderService::create($_POST);$_SESSION['flash']='Agent created with policy-aware capabilities, memory, autonomy and workflows.';$_SESSION['flash_type']='success';header('Location: /api/admin/agent-profile.php?id='.$r['agent_id']);exit;}catch(Throwable $e){$_SESSION['flash']=AdminUi::humanError($e->getMessage());$_SESSION['flash_type']='error';header('Location: /api/admin/agent-builder.php');exit;}}
$agents=AgentService::all();$roles=AgentBuilderService::roleTemplates();$caps=AgentBuilderService::capabilityCatalog();$flows=AgentWorkflowService::templates();$goals=CompanyGoalService::list('active');$providers=db()->query("SELECT provider_key,label,status FROM providers WHERE kind='ai' AND enabled=1 ORDER BY FIELD(status,'verified','configured','untested','failed','disabled'),label")->fetchAll();
AdminUi::header('Company OS 20 Final Agent Builder','agent_builder');echo AdminUi::flash();
?>
<section class="card"><div class="card-title"><div><h2>Company OS 20 Final Agent Builder</h2><span class="muted small">Create a complete employee profile: identity, intelligence, autonomy, layered memory, capability levels, tools, permissions, communication, workflows, KPIs and goals. Role templates are least-privilege defaults; capabilities remain source-tracked and revocable.</span></div></div>
<form method="post"><?=AdminUi::csrf()?><div class="grid"><div class="span-6"><h3>Identity</h3><div class="field"><label>Name</label><input name="display_name" required></div><div class="field"><label>Slug</label><input name="slug" pattern="[a-z0-9_-]+" required></div><div class="field"><label>Role title</label><input name="role_title" required></div><div class="field"><label>Specialty</label><input name="specialty" required></div><div class="field"><label>Description</label><textarea name="description"></textarea></div><div class="field"><label>Manager</label><select name="manager_id"><option value="0">Ramy default</option><option value="-1">Owner directly</option><?php foreach($agents as $a):?><option value="<?=$a['id']?>"><?=e($a['display_name'])?></option><?php endforeach?></select></div><div class="field"><label>Role template</label><select name="role_template"><?php foreach($roles as $r):?><option value="<?=e($r['template_key'])?>"><?=e($r['label_ar'])?> - <?=e($r['template_key'])?></option><?php endforeach?></select></div></div>
<div class="span-6"><h3>Intelligence and autonomy</h3><div class="field"><label>Primary provider</label><select name="provider_key"><?php foreach($providers as $p):?><option value="<?=e($p['provider_key'])?>"><?=e($p['label'])?> - <?=e($p['status'])?></option><?php endforeach?></select></div><div class="field"><label>Preferred model</label><input name="model" placeholder="optional"></div><div class="field"><label>Mission</label><textarea name="mission_text" required></textarea></div><label class="check"><input type="checkbox" name="initiative_enabled" value="1" checked> Proactive initiatives enabled</label><div class="field"><label>Think cadence minutes</label><input type="number" name="cadence_minutes" value="240" min="15"></div><div class="field"><label>Max active tasks</label><input type="number" name="max_active_tasks" value="2" min="1" max="8"></div><div class="field"><label>Max initiatives/day</label><input type="number" name="max_initiatives_per_day" value="6" min="1" max="50"></div><div class="field"><label>Minimum initiative value</label><input type="number" name="initiative_min_value" value="60" min="1" max="100"></div><div class="field"><label>Auto execute max risk</label><select name="auto_execute_max_risk"><option value="none">None</option><option value="low" selected>Low</option><option value="medium">Medium</option></select></div><input type="hidden" name="brain_enabled" value="1"><input type="hidden" name="followup_enabled" value="1"><input type="hidden" name="learning_enabled" value="1"><input type="hidden" name="self_improvement_enabled" value="1"><div class="field"><label>Initiative scope</label><select name="initiative_scope"><option value="internal">Internal only</option><option value="owner_team" selected>Owner + team</option><option value="external_guarded">Guarded external actions</option></select></div></div>
<div class="span-12"><h3>Canonical system prompt</h3><textarea name="system_prompt" rows="12" required placeholder="One clean current prompt. Do not paste historical versions here."></textarea></div>
<div class="span-6"><h3>Memory and budgets</h3><label class="check"><input type="checkbox" name="semantic_memory_enabled" value="1" checked> Semantic retrieval enabled</label><input type="hidden" name="memory_mode" value="layered"><div class="field"><label>Daily AI budget USD (0 = policy default)</label><input type="number" step="0.01" name="daily_ai_usd" value="0"></div><div class="field"><label>Monthly AI budget USD</label><input type="number" step="0.01" name="monthly_ai_usd" value="0"></div><div class="field"><label>Daily search budget USD</label><input type="number" step="0.01" name="daily_search_usd" value="0"></div><div class="field"><label>Monthly media budget USD</label><input type="number" step="0.01" name="monthly_media_usd" value="0"></div><label class="check"><input type="checkbox" name="hard_stop" value="1"> Hard stop on budget</label><h4>Daily operation limits</h4><div class="field"><label>AI calls/day</label><input type="number" name="daily_ai_call_budget" value="60" min="1"></div><div class="field"><label>External actions/day</label><input type="number" name="daily_external_action_budget" value="20" min="1"></div><div class="field"><label>Search requests/day</label><input type="number" name="daily_search_budget" value="40" min="1"></div><div class="field"><label>Media requests/day</label><input type="number" name="daily_media_budget" value="20" min="1"></div><div class="field"><label>Voice actions/day</label><input type="number" name="daily_voice_budget" value="40" min="1"></div><div class="field"><label>Browser actions/day</label><input type="number" name="daily_browser_budget" value="80" min="1"></div></div>
<div class="span-6"><h3>Communication</h3><div class="field"><label>Owner communication mode</label><select name="owner_communication"><option value="through_ramy">Through Ramy</option><option value="dashboard_only">Dashboard only</option><option value="dashboard_whatsapp">Dashboard + WhatsApp</option><option value="whatsapp">WhatsApp</option><option value="emergency_only">Emergency only</option><option value="disabled">Disabled</option></select></div><label class="check"><input type="checkbox" name="channels[dashboard]" value="1" checked> Dashboard</label><label class="check"><input type="checkbox" name="channels[whatsapp]" value="1"> WhatsApp</label><label class="check"><input type="checkbox" name="whatsapp_enabled" value="1"> WhatsApp enabled</label><label class="check"><input type="checkbox" name="channels[voice]" value="1"> Voice</label></div>
<div class="span-12"><h3>Capabilities and access levels</h3><div class="creator-grid"><?php foreach($caps as $c):?><div class="card subtle" style="margin:0"><b><?=e($c['label_ar'])?></b><small class="muted" style="display:block"><?=e($c['capability_key'])?></small><p class="small"><?=e($c['description_text']??'')?></p><select name="capabilities[<?=e($c['capability_key'])?>]"><option value="none">None</option><option value="read">Read</option><option value="use">Use</option><option value="manage">Manage</option><option value="approve">Approve</option></select></div><?php endforeach?></div></div>
<div class="span-6"><h3>Manual additions</h3><div class="field"><label>Extra permission keys</label><textarea name="permission_keys_csv" placeholder="one per line or comma-separated"></textarea></div><div class="field"><label>Extra tool keys</label><textarea name="tool_keys_csv" placeholder="one per line or comma-separated"></textarea></div></div>
<div class="span-6"><h3>Reusable workflows</h3><?php foreach($flows as $w):?><label class="check"><input type="checkbox" name="workflow_ids[]" value="<?=$w['id']?>"> <?=e($w['name'])?> <small class="muted"><?=e($w['workflow_key'])?></small></label><?php endforeach?><?php if(!$flows):?><p class="muted">Create workflows from Workflow Builder after migration.</p><?php endif?><h3>Company goals</h3><?php foreach($goals as $g):?><label class="check"><input type="checkbox" name="goal_ids[]" value="<?=$g['id']?>"> <?=e($g['title'])?></label><?php endforeach?></div>
</div><button class="btn full-width">Create complete agent</button></form></section>
<?php AdminUi::footer();
