<?php
declare(strict_types=1);

final class AiBudgetService {
    private static function executeRetry(string $sql,array $params=[]):void{
        try{db()->prepare($sql)->execute($params);return;}catch(Throwable $e){
            if(!Database::isDisconnect($e))throw $e;
            Database::reconnect();
            db()->prepare($sql)->execute($params);
        }
    }
    private const MEDIA_CAPS=['media','image','video','stt','tts','voice','realtime_voice','audio'];
    public static function policy(int $agentId):array{$q=db()->prepare('SELECT * FROM agent_budget_policies WHERE agent_id=?');$q->execute([$agentId]);$r=$q->fetch();if($r)return $r;db()->prepare('INSERT IGNORE INTO agent_budget_policies(agent_id,warn_percent,hard_stop) VALUES (?,80,0)')->execute([$agentId]);$q->execute([$agentId]);return $q->fetch()?:['agent_id'=>$agentId,'warn_percent'=>80,'hard_stop'=>0];}
    public static function savePolicy(int $agentId,array $d):void{AgentService::byId($agentId);$num=static function($v){$v=trim((string)$v);return $v===''?null:max(0,(float)$v);};db()->prepare("INSERT INTO agent_budget_policies(agent_id,daily_ai_usd,monthly_ai_usd,daily_search_usd,monthly_media_usd,warn_percent,hard_stop) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE daily_ai_usd=VALUES(daily_ai_usd),monthly_ai_usd=VALUES(monthly_ai_usd),daily_search_usd=VALUES(daily_search_usd),monthly_media_usd=VALUES(monthly_media_usd),warn_percent=VALUES(warn_percent),hard_stop=VALUES(hard_stop)")->execute([$agentId,$num($d['daily_ai_usd']??''),$num($d['monthly_ai_usd']??''),$num($d['daily_search_usd']??''),$num($d['monthly_media_usd']??''),max(10,min(100,(int)($d['warn_percent']??80))),!empty($d['hard_stop'])?1:0]);}
    private static function bucket(string $capability):string{$c=pb_strtolower(trim($capability));if($c==='search')return 'search';if(in_array($c,self::MEDIA_CAPS,true))return 'media';return 'ai';}
    private static function spend(int $agentId,string $period,string $bucket='all',bool $withReservations=true):float{$where=$period==='day'?'created_at>=UTC_DATE()':"created_at>=DATE_FORMAT(UTC_DATE(),'%Y-%m-01')";if($bucket==='search')$where.=" AND capability='search'";elseif($bucket==='media')$where.=" AND capability IN ('media','image','video','stt','tts','voice','realtime_voice','audio')";elseif($bucket==='ai')$where.=" AND capability NOT IN ('search','media','image','video','stt','tts','voice','realtime_voice','audio')";$q=db()->prepare('SELECT COALESCE(SUM(estimated_cost_usd),0) FROM agent_usage_ledger WHERE agent_id=? AND '.$where);$q->execute([$agentId]);$spent=(float)($q->fetchColumn()?:0);if($withReservations){$range=$period==='day'?"created_at>=UTC_DATE()":"created_at>=DATE_FORMAT(UTC_DATE(),'%Y-%m-01')";$caps=$bucket==='search'?"capability='search'":($bucket==='media'?"capability IN ('media','image','video','stt','tts','voice','realtime_voice','audio')":"capability NOT IN ('search','media','image','video','stt','tts','voice','realtime_voice','audio')");$q=db()->prepare("SELECT COALESCE(SUM(estimated_cost_usd),0) FROM agent_budget_reservations WHERE agent_id=? AND state='reserved' AND (expires_at IS NULL OR expires_at>NOW()) AND {$range} AND {$caps}");$q->execute([$agentId]);$spent+=(float)($q->fetchColumn()?:0);}return $spent;}
    public static function assertAllowed(int $agentId,string $capability='text',float $estimatedNextCost=0.0):void{if(setting('budgets.enabled','1')==='0')return;$p=self::policy($agentId);$hard=(int)($p['hard_stop']??setting('budgets.default_hard_stop','0'))===1;if(!$hard)return;$bucket=self::bucket($capability);$estimatedNextCost=max(0,$estimatedNextCost);if($bucket==='search'){$spent=self::spend($agentId,'day','search');$limit=(float)($p['daily_search_usd']??0);if($limit>0&&$spent+$estimatedNextCost>$limit+0.000001)throw new RuntimeException('agent_search_budget_limit_reached');return;}if($bucket==='media'){$spent=self::spend($agentId,'month','media');$limit=(float)($p['monthly_media_usd']??0);if($limit>0&&$spent+$estimatedNextCost>$limit+0.000001)throw new RuntimeException('agent_media_budget_limit_reached');return;}$daily=self::spend($agentId,'day','ai');$monthly=self::spend($agentId,'month','ai');$limitD=(float)($p['daily_ai_usd']??0);$limitM=(float)($p['monthly_ai_usd']??0);if(($limitD>0&&$daily+$estimatedNextCost>$limitD+0.000001)||($limitM>0&&$monthly+$estimatedNextCost>$limitM+0.000001))throw new RuntimeException('agent_ai_budget_limit_reached');}
    public static function reserve(int $agentId,string $capability,float $estimatedCost,string $referenceKey='',int $ttlMinutes=30):int{$estimatedCost=max(0,$estimatedCost);self::assertAllowed($agentId,$capability,$estimatedCost);$referenceKey=pb_substr(trim($referenceKey),0,190);if($referenceKey!==''){$q=db()->prepare("SELECT id FROM agent_budget_reservations WHERE reference_key=? AND state='reserved' AND (expires_at IS NULL OR expires_at>NOW()) ORDER BY id DESC LIMIT 1");$q->execute([$referenceKey]);$id=(int)($q->fetchColumn()?:0);if($id)return $id;}db()->prepare("INSERT INTO agent_budget_reservations(agent_id,capability,estimated_cost_usd,state,reference_key,expires_at) VALUES (?,?,?,'reserved',?,DATE_ADD(NOW(),INTERVAL ? MINUTE))")->execute([$agentId,pb_substr($capability,0,60),$estimatedCost,$referenceKey?:null,max(1,min(1440,$ttlMinutes))]);return (int)db()->lastInsertId();}
    public static function consumeReservation(int $id):void{if($id>0)db()->prepare("UPDATE agent_budget_reservations SET state='consumed' WHERE id=? AND state='reserved'")->execute([$id]);}
    public static function releaseReservation(int $id):void{if($id>0)db()->prepare("UPDATE agent_budget_reservations SET state='released' WHERE id=? AND state='reserved'")->execute([$id]);}
    public static function expireReservations():int{db()->exec("UPDATE agent_budget_reservations SET state='expired' WHERE state='reserved' AND expires_at IS NOT NULL AND expires_at<NOW()");return (int)db()->query('SELECT ROW_COUNT()')->fetchColumn();}
    public static function record(int $agentId,string $provider,string $model,string $capability,int $inputTokens=0,int $outputTokens=0,array $meta=[],?int $taskId=null,?int $projectId=null):float{$cost=self::estimate($provider,$model,$capability,$inputTokens,$outputTokens);self::executeRetry('INSERT INTO agent_usage_ledger(agent_id,provider_key,model_key,capability,input_tokens,output_tokens,estimated_cost_usd,task_id,project_id,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?)',[$agentId,pb_substr($provider,0,80),pb_substr($model,0,190)?:null,pb_substr($capability,0,60),max(0,$inputTokens),max(0,$outputTokens),$cost,$taskId,$projectId,$meta?j($meta):null]);if(!empty($meta['reservation_id']))self::consumeReservation((int)$meta['reservation_id']);self::warnIfNeeded($agentId);return $cost;}
    public static function estimate(string $provider,string $model,string $capability,int $in=0,int $out=0):float{$caps=array_values(array_unique([$capability,self::bucket($capability)==='media'?'media':$capability]));$place=implode(',',array_fill(0,count($caps),'?'));try{$q=db()->prepare("SELECT * FROM provider_pricing WHERE provider_key=? AND capability IN ({$place}) AND active=1 AND (model_pattern=? OR model_pattern='*') ORDER BY (model_pattern=? ) DESC,id DESC LIMIT 1");$q->execute([$provider,...$caps,$model,$model]);$p=$q->fetch();}catch(Throwable){$p=false;}if(!$p)return 0.0;return round(((max(0,$in)/1000000)*(float)$p['input_per_million_usd'])+((max(0,$out)/1000000)*(float)$p['output_per_million_usd'])+(float)$p['request_usd'],6);}
    public static function savePricing(string $provider,string $model,string $capability,float $inputPerMillion,float $outputPerMillion,float $requestUsd,string $note='',bool $active=true):void{$provider=pb_strtolower(trim($provider));$model=trim($model)?:'*';$capability=pb_strtolower(trim($capability));$allowed=['text','search','media','image','video','stt','tts','voice','realtime_voice','browser','external_api','audio'];if(!preg_match('/^[a-z0-9_.:-]{2,80}$/',$provider)||pb_strlen($model)>190||!in_array($capability,$allowed,true))throw new RuntimeException('provider_pricing_invalid');db()->prepare('INSERT INTO provider_pricing(provider_key,model_pattern,capability,input_per_million_usd,output_per_million_usd,request_usd,active,source_note) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE input_per_million_usd=VALUES(input_per_million_usd),output_per_million_usd=VALUES(output_per_million_usd),request_usd=VALUES(request_usd),active=VALUES(active),source_note=VALUES(source_note),updated_at=NOW()')->execute([$provider,$model,$capability,max(0,$inputPerMillion),max(0,$outputPerMillion),max(0,$requestUsd),$active?1:0,pb_substr(trim($note),0,500)?:null]);}
    public static function pricing():array{return db()->query("SELECT * FROM provider_pricing ORDER BY FIELD(capability,'text','search','image','video','media','stt','tts','voice','browser','external_api'),provider_key,model_pattern")->fetchAll();}
    public static function usage(int $agentId):array{$dailyAi=self::spend($agentId,'day','ai');$monthlyAi=self::spend($agentId,'month','ai');$dailySearch=self::spend($agentId,'day','search');$monthlyMedia=self::spend($agentId,'month','media');$q=db()->prepare('SELECT provider_key,capability,COUNT(*) requests,SUM(input_tokens) input_tokens,SUM(output_tokens) output_tokens,SUM(estimated_cost_usd) cost FROM agent_usage_ledger WHERE agent_id=? AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY provider_key,capability ORDER BY cost DESC');$q->execute([$agentId]);return ['daily_usd'=>$dailyAi+$dailySearch+self::spend($agentId,'day','media'),'monthly_usd'=>$monthlyAi+self::spend($agentId,'month','search')+$monthlyMedia,'daily_ai_usd'=>$dailyAi,'monthly_ai_usd'=>$monthlyAi,'daily_search_usd'=>$dailySearch,'monthly_media_usd'=>$monthlyMedia,'breakdown'=>$q->fetchAll(),'policy'=>self::policy($agentId)];}
    private static function warnIfNeeded(int $agentId):void{try{$p=self::policy($agentId);$u=self::usage($agentId);$warn=max(10,min(100,(int)($p['warn_percent']??80)))/100;$hit=false;$why=[];foreach([['daily_ai_usd',$u['daily_ai_usd'],'daily AI'],['monthly_ai_usd',$u['monthly_ai_usd'],'monthly AI'],['daily_search_usd',$u['daily_search_usd'],'daily search'],['monthly_media_usd',$u['monthly_media_usd'],'monthly media']] as [$k,$v,$label]){$lim=(float)($p[$k]??0);if($lim>0&&$v>=$lim*$warn){$hit=true;$why[]=$label.' '.round((float)$v,4).'/'.round($lim,4).' USD';}}if($hit){$key='budget.warned.'.$agentId.'.'.gmdate('YmdH');if(setting($key,'0')!=='1'){put_setting($key,'1');Notifications::add('warning','budgets','Agent budget warning',AgentService::byId($agentId)['display_name'].' budget warning: '.implode(', ',$why),'agent',(string)$agentId);}}}catch(Throwable){}}
}
