<?php
declare(strict_types=1);
final class AymanRunner {
    private const MAX_EDIT_BYTES=240000;
    public static function run(int $taskId,bool $recovery=false):array{
        $t=TaskService::start($taskId);$agent=AgentService::byId((int)$t['assigned_agent_id']);AgentService::assertRunnable($agent);
        $ctx=json_decode((string)($t['context_json']??'{}'),true)?:[];$slug=(string)$agent['slug'];
        if($slug!=='ayman'&&!($recovery&&$slug==='emad'&&!empty($ctx['recovery_execution'])))throw new RuntimeException('execution_agent_not_allowed');
        $actorLabel=$slug==='emad'?'عماد (استلام احتياطي)':'أيمن';
        foreach(['hostinger_files','project_files','ai_code','backup','deploy','http_test'] as $tool)AgentService::requireTool((int)$agent['id'],$tool);
        if(!$t['project_id'])throw new RuntimeException('ayman_project_required');$p=self::project((int)$t['project_id']);
        MasterBriefService::requireForExecution((int)$p['id']);Permissions::requireAgent((int)$agent['id'],'files.read');Permissions::requireAgent((int)$agent['id'],'files.write');Permissions::requireAgent((int)$agent['id'],'deploy.execute');Permissions::requireAgent((int)$agent['id'],'backup.create');Permissions::requireProject((int)$agent['id'],(int)$p['id'],'work');if((int)($p['is_system_project']??0)===1&&!(int)($t['owner_authorized']??0))throw new RuntimeException('system_project_owner_authorization_required');
        $target=StagingService::executionTarget($p,true);$site=['domain'=>$target['domain'],'username'=>$target['username']];$listing=HostingerClient::listFiles($site['domain'],$site['username'],'',6,2200);$items=$listing['items']??[];if(!is_array($items))$items=[];$files=[];foreach($items as $it){if(!is_array($it)||($it['type']??'')!=='file')continue;$path=(string)($it['path']??$it['name']??'');if($path===''||preg_match('#(?:^|/)(?:vendor|node_modules|cache|uploads|storage/logs|backup|\.git)(?:/|$)#i',$path))continue;if(!preg_match('/\.(?:php|html?|css|js|json|md|txt|sql|xml|svg)$/i',$path))continue;$files[]=['path'=>$path,'size'=>(int)($it['size_bytes']??$it['size']??0)];if(count($files)>=1000)break;}
        $q=db()->prepare("SELECT id,db_name,db_user,db_host,db_port,status,connection_state FROM project_databases WHERE project_id=? AND status<>'removed' ORDER BY id");$q->execute([(int)$p['id']]);$dbRows=$q->fetchAll();$dbMeta=[];foreach($dbRows as $d)$dbMeta[]=$d+['credentials_configured'=>ProjectDatabaseClient::configured((int)$d['id'])];
        $memory=AgentService::tool((int)$agent['id'],'memory')?['company'=>MemoryService::company(18),'agent'=>MemoryService::agentContext((int)$agent['id'],(int)$p['id'],22),'project'=>MemoryService::project((int)$p['id'],24)]:['company'=>[],'agent'=>[],'project'=>[]];$brief=MasterBriefService::current((int)$p['id']);$teamChat=ProjectChatService::recent((int)$p['id'],30);try{ProjectStageService::set((int)$p['id'],'in_development','agent',$slug,'بدأ '.$actorLabel.' التنفيذ',true);}catch(Throwable){}
        $schema=['type'=>'object','additionalProperties'=>false,'properties'=>['files'=>['type'=>'array','maxItems'=>14,'items'=>['type'=>'object','additionalProperties'=>false,'properties'=>['action'=>['type'=>'string','enum'=>['edit','create']],'path'=>['type'=>'string'],'reason'=>['type'=>'string']],'required'=>['action','path','reason']]],'strategy'=>['type'=>'string'],'needs_database'=>['type'=>'boolean'],'database_id'=>['type'=>'integer'],'database_reason'=>['type'=>'string'],'media_requests'=>['type'=>'array','maxItems'=>4,'items'=>['type'=>'object','additionalProperties'=>false,'properties'=>['type'=>['type'=>'string','enum'=>['image','video','ui_asset']],'label'=>['type'=>'string'],'prompt'=>['type'=>'string']],'required'=>['type','label','prompt']]],'test_paths'=>['type'=>'array','maxItems'=>14,'items'=>['type'=>'string']],'can_execute'=>['type'=>'boolean'],'block_reason'=>['type'=>'string']],'required'=>['files','strategy','needs_database','database_id','database_reason','media_requests','test_paths','can_execute','block_reason']];
        $input=[['role'=>'user','content'=>"TASK:\n".$t['description']."\nPROJECT:\n".j(['name'=>$p['name'],'production_domain'=>$p['primary_domain'],'execution_domain'=>$target['domain'],'using_staging'=>(bool)$target['is_staging'],'technology'=>$p['technology'],'metadata'=>$p['metadata_json']])."\nAVAILABLE_FILES:\n".j($files)."\nPROJECT_DATABASES:\n".j($dbMeta)."\nMASTER_BRIEF:\n".j($brief)."\nPROJECT_TEAM_CHAT:\n".j($teamChat)."\nMEMORY:\n".j($memory)]];
        $plan=AiGateway::json($agent,$agent['system_prompt']."\nخطط للتنفيذ الفعلي. اختر أقل عدد ملفات كافٍ. ما تختاره للتعديل لازم يكون ضروري فعلًا وقابل للقراءة. ممنوع تخطي ملف فشل قراءته ثم ادعاء اكتمال المهمة. ممنوع الأسرار وvendor/node_modules/uploads. لو المهمة تحتاج قاعدة بيانات حددها. أضف وسائط فقط عند الحاجة. لا تسأل المالك عن معلومة موجودة. أنت مبرمج Full-Stack مسؤول عن بناء المهمة كاملة لا مجرد تعديل شكلي. إذا كانت محطة الاختبار مفعلة فاعتبر execution_domain هو الهدف الحقيقي للتنفيذ والاختبار، ولا تلمس دومين العميل النهائي قبل اعتماد عماد. كل الملخصات والخطط الداخلية بالعربية.",$input,$schema,'ayman_execution_plan',7500,'coding');self::runLog($agent,$taskId,$plan,'completed','خطة التنفيذ');$d=$plan['data'];if(!$d['can_execute'])throw new RuntimeException('ayman_blocked:'.pb_substr((string)$d['block_reason'],0,240));
        if(!empty($d['needs_database']))AgentService::requireTool((int)$agent['id'],'database');if(!empty($d['media_requests']))AgentService::requireTool((int)$agent['id'],'media_generation');
        TaskService::assertContinuable($taskId);AgentService::assertRunnable($agent);
        $deploymentId=self::deploymentStart((int)$p['id'],$taskId,(string)$t['uid'],$files,$dbMeta);$changes=[];$summaries=[];$dbEvidence=null;$mediaEvidence=[];
        try{
            $indexed=array_column($files,null,'path');
            foreach(array_slice((array)$d['files'],0,14) as $sel){$action=(string)($sel['action']??'edit');$path=ltrim(trim((string)($sel['path']??'')),'/');if($path==='')throw new RuntimeException('selected_file_path_missing');$path=self::resolveSelectedPath($path,$indexed);$exists=isset($indexed[$path]);if($action==='edit'&&!$exists)throw new RuntimeException('selected_file_not_found:'.$path);if($action==='create'&&$exists)throw new RuntimeException('selected_create_file_exists:'.$path);
                $content='';if($exists){$listedSize=(int)($indexed[$path]['size']??0);if($listedSize>self::MAX_EDIT_BYTES)throw new RuntimeException('selected_file_too_large:'.$path);$read=HostingerClient::readFile($site['domain'],$site['username'],$path);$content=(string)($read['content']??'');if(strlen($content)>self::MAX_EDIT_BYTES)throw new RuntimeException('selected_file_too_large:'.$path);}
                $editSchema=['type'=>'object','additionalProperties'=>false,'properties'=>['change_needed'=>['type'=>'boolean'],'content'=>['type'=>'string'],'summary'=>['type'=>'string'],'risks'=>['type'=>'array','items'=>['type'=>'string']]],'required'=>['change_needed','content','summary','risks']];$verb=$action==='create'?'أنشئ الملف كاملًا من الصفر':'عدّل الملف فقط بما يخدم المهمة';
                $editInput=[['role'=>'user','content'=>"OWNER_AUTHORIZED_TASK:\n".$t['description']."\nPROJECT: ".$target['domain']."\nACTION: ".$action."\nFILE: ".$path."\nWHY_SELECTED: ".($sel['reason']??'')."\nCURRENT_FILE:\n".$content]];
                $ed=AiGateway::json($agent,$agent['system_prompt']."\n".$verb.". حافظ على الوظائف غير المرتبطة. ممنوع كلمات مرور أو مفاتيح أو shell/process أو eval أو تحميل كود خارجي أو تجاوز الصلاحيات. أعد الملف كاملًا. لو edit ومفيش تغيير مطلوب اجعل change_needed=false.",$editInput,$editSchema,'ayman_file_'.$action,16000,'coding');self::runLog($agent,$taskId,$ed,'completed',$action.' '.$path);$o=$ed['data'];if(!$o['change_needed']&&$action==='edit'){$summaries[]=$path.': لا يحتاج تغيير';continue;}$next=(string)$o['content'];if($action==='create'&&trim($next)==='')throw new RuntimeException('generated_file_empty:'.$path);if(self::newDangerousCode($content,$next))throw new RuntimeException('dangerous_code_generated');self::validateGeneratedContent($path,$next);TaskService::assertContinuable($taskId);AgentService::assertRunnable($agent);AgentService::requireTool((int)$agent['id'],'deploy');$wr=HostingerClient::writeFile((int)$p['id'],$taskId,$path,$next,$action==='create',(string)$target['domain'],(string)$target['username']);$changes[]=$wr;$summaries[]=$path.': '.pb_substr((string)$o['summary'],0,300);
            }
            if((bool)$d['needs_database']){TaskService::assertContinuable($taskId);AgentService::assertRunnable($agent);AgentService::requireTool((int)$agent['id'],'database');$dbId=(int)$d['database_id'];$valid=array_map(fn($x)=>(int)$x['id'],$dbRows);if(!empty($target['is_staging'])){$stagingDb=StagingDatabaseService::ensureForProject((int)$p['id'],$dbId);$dbId=(int)$stagingDb['id'];}else{if(!$dbId&&count($valid)===1)$dbId=$valid[0];if(!$dbId||!in_array($dbId,$valid,true))throw new RuntimeException('project_database_context_missing');}if(!ProjectDatabaseClient::configured($dbId)){Notifications::add('warning','database','قاعدة المشروع محتاجة بيانات اتصال','المهمة محتاجة قاعدة البيانات، لكن كلمة المرور مش موجودة في الخزنة المشفرة.','project_database',(string)$dbId);throw new RuntimeException('project_database_credentials_required');}$schemaNow=ProjectDatabaseClient::schemaSummary($dbId);$sqlSchema=['type'=>'object','additionalProperties'=>false,'properties'=>['change_needed'=>['type'=>'boolean'],'summary'=>['type'=>'string'],'statements'=>['type'=>'array','maxItems'=>10,'items'=>['type'=>'object','additionalProperties'=>false,'properties'=>['sql'=>['type'=>'string'],'reason'=>['type'=>'string']],'required'=>['sql','reason']]]],'required'=>['change_needed','summary','statements']];$sqlInput=[['role'=>'user','content'=>"TASK:\n".$t['description']."\nDATABASE_REASON:\n".(string)$d['database_reason']."\nCURRENT_SCHEMA:\n".j($schemaNow)."\nFILE_CHANGE_SUMMARY:\n".j($summaries)]];$sqlPlan=AiGateway::json($agent,$agent['system_prompt']."\nاقترح SQL غير تدميري فقط. UPDATE لازم يحتوي WHERE. ممنوع DROP/TRUNCATE/DELETE/REPLACE/GRANT/users أو multiple statements.",$sqlInput,$sqlSchema,'ayman_database_plan',9000,'coding');self::runLog($agent,$taskId,$sqlPlan,'completed','خطة تعديل قاعدة البيانات');$dbEvidence=$sqlPlan['data']['change_needed']?ProjectDatabaseClient::executePlan($dbId,$taskId,(int)$agent['id'],$sqlPlan['data']['statements']):['changed'=>false,'summary'=>$sqlPlan['data']['summary'],'statements'=>[]];if(!empty($target['is_staging'])&&isset($stagingDb))$dbEvidence['staging_database']=$stagingDb;}
            foreach(array_slice((array)($d['media_requests']??[]),0,4) as $mr){TaskService::assertContinuable($taskId);AgentService::assertRunnable($agent);AgentService::requireTool((int)$agent['id'],'media_generation');if(!is_array($mr))continue;$prompt=trim((string)($mr['prompt']??''));if($prompt==='')continue;$type=(string)($mr['type']??'image');$label=trim((string)($mr['label']??'ملف مرئي'));if($type==='image')$mediaEvidence[]=AiCapabilityRouter::image((int)$agent['id'],(int)$p['id'],$label,$prompt,$taskId);elseif($type==='video')$mediaEvidence[]=AiCapabilityRouter::video((int)$agent['id'],(int)$p['id'],$label,$prompt,$taskId);else $mediaEvidence[]=MediaBridgeClient::request((int)$p['id'],$taskId,(int)$agent['id'],$type,$label,$prompt);}
            TaskService::assertContinuable($taskId);AgentService::requireTool((int)$agent['id'],'http_test');$paths=['/'];foreach((array)$d['test_paths'] as $tp){$tp=trim((string)$tp);if($tp===''||preg_match('#^https?://#i',$tp)||str_contains($tp,'..'))continue;$tp='/'.ltrim($tp,'/');if(!in_array($tp,$paths,true))$paths[]=$tp;if(count($paths)>=15)break;}$probes=[];$failedProbes=[];foreach($paths as $tp){$probe=HttpClient::probe('https://'.$target['domain'].$tp,20,131072);$status=(int)($probe['status']??0);$ok=$status>=200&&$status<400;$row=['path'=>$tp,'status'=>$status,'ok'=>$ok,'final_url'=>$probe['final_url']??'','content_type'=>$probe['content_type']??'','sha256'=>$probe['sha256']??'','error'=>$probe['error']??''];$probes[]=$row;if(!$ok)$failedProbes[]=$row;}if($failedProbes){$first=$failedProbes[0];throw new RuntimeException('post_change_smoke_failed:'.$first['path'].':'.$first['status']);}
            TaskService::assertContinuable($taskId);AgentService::assertRunnable($agent);$evidence=['strategy'=>$d['strategy'],'master_brief_id'=>$brief['id']??null,'execution_target'=>$target,'files_changed'=>$changes,'file_notes'=>$summaries,'database'=>$dbEvidence,'media'=>$mediaEvidence,'test_paths'=>$paths,'test_probes'=>$probes,'execution_verified'=>true];TaskEvidence::add($taskId,'deployment','تنفيذ '.$actorLabel.' واختباراته الأولية',$evidence,'verified',(int)$agent['id']);StagingService::markBuilt((int)$p['id'],$taskId,$target);ProjectChatService::post((int)$p['id'],'agent',$slug,'اكتمل تنفيذ المهمة #'.$taskId.'. الملفات المتأثرة: '.count($changes).'. الاختبارات الأولية: '.count($probes).'.','handoff','task',(string)$taskId,false,['deployment_id'=>$deploymentId,'recovery'=>$recovery]);self::deploymentFinish($deploymentId,'verified',$evidence,$changes,$dbEvidence);$where=!empty($target['is_staging'])?' على محطة الاختبار '.$target['domain']:(!empty($target['domain'])?' على '.$target['domain']:'');if($recovery){$summary=($changes||($dbEvidence['changed']??false)||$mediaEvidence)?'استلم عماد التنفيذ بعد تعثر أيمن، ونفذ التغييرات المطلوبة'.$where.' وتحقق منها باختبارات فعلية.':'استلم عماد التنفيذ الاحتياطي وفحص المشروع'.$where.' ولم يحتج كتابة تغيير، وأجرى اختبارات فعلية.';}else{$summary=($changes||($dbEvidence['changed']??false)||$mediaEvidence)?'نفّذ أيمن التغييرات المطلوبة'.$where.' وتحقق منها باختبارات فعلية. المهمة جاهزة لمراجعة عماد.':'فحص أيمن المشروع'.$where.' ولم يحتج كتابة تغيير، وأجرى اختبارات أولية. المهمة جاهزة لمراجعة عماد.';}TaskService::complete($taskId,$evidence,$summary);return $evidence;
        }catch(Throwable $e){$error=$e->getMessage();$rollback=self::rollbackEditedFiles((int)$p['id'],$taskId,$changes,$target);$dbRisk=!empty($dbEvidence['changed'])||str_starts_with($error,'database_plan_partial_failure:');$fileSideEffects=!empty($changes);$rollbackComplete=$fileSideEffects&&empty($rollback['created_files'])&&$rollback['attempted']>0&&$rollback['failed']===0&&$rollback['restored']===$rollback['attempted'];$fileRisk=$fileSideEffects&&!$rollbackComplete;$recoveryRequired=$dbRisk||$fileRisk;$state=$rollbackComplete&&!$dbRisk?'rolled_back':'failed';$paused=$error==='agent_disabled'||str_starts_with($error,'agent_tool_disabled:');$cancelled=in_array($error,['task_cancelled','task_not_active'],true);$failureEvidence=['error'=>$error,'execution_target'=>$target,'rollback'=>$rollback,'test_probes'=>$probes??[],'database_restore_required'=>$dbRisk,'file_recovery_required'=>$fileRisk,'recovery_required'=>$recoveryRequired,'paused'=>$paused,'cancelled'=>$cancelled];self::deploymentFinish($deploymentId,$state,$failureEvidence,$changes,$dbEvidence);$msg='تم إيقاف تنفيذ '.$actorLabel.'. '.($rollback['attempted']?'اتعملت محاولة رجوع للملفات المعدلة. ':'').(!empty($rollback['created_files'])?'في ملفات جديدة اتعملت ومحتاجة مراجعة قبل إعادة التشغيل. ':'').($dbRisk?'تغيير قاعدة البيانات محتاج مراجعة/استرجاع من النسخة الاحتياطية. ':'').AdminUi::humanError($error);$level=($paused||$cancelled)&&!$recoveryRequired?'warning':'critical';$title=$recoveryRequired?'التنفيذ محتاج استرجاع قبل الاستكمال':($cancelled?'تم إيقاف مهمة '.$actorLabel:($paused?'تنفيذ '.$actorLabel.' متوقف مؤقتًا':'فشل تنفيذ '.$actorLabel));Notifications::add($level,'deployments',$title,$msg,'task',(string)$taskId);if($recoveryRequired)throw new RuntimeException('agent_recovery_required:'.$error,0,$e);throw $e;}
    }
    private static function resolveSelectedPath(string $path,array $indexed):string{
        $path=ltrim(str_replace('\\','/',$path),'/');$path=preg_replace('#^(?:public_html/)+#i','',$path)??$path;if(isset($indexed[$path]))return $path;
        $lower=pb_strtolower($path);$suffix=[];$base=pb_strtolower(basename($path));$baseHits=[];
        foreach(array_keys($indexed) as $candidate){$c=(string)$candidate;$cl=pb_strtolower(ltrim($c,'/'));if($cl===$lower)return $c;if(str_ends_with($cl,'/'.$lower)||str_ends_with($lower,'/'.$cl))$suffix[]=$c;if(pb_strtolower(basename($c))===$base)$baseHits[]=$c;}
        if(count($suffix)===1)return $suffix[0];if(count($baseHits)===1)return $baseHits[0];return $path;
    }
    private static function validateGeneratedContent(string $path,string $content):void{$ext=strtolower(pathinfo($path,PATHINFO_EXTENSION));if($ext==='php'){try{token_get_all($content,TOKEN_PARSE);}catch(Throwable){throw new RuntimeException('php_syntax_invalid:'.$path);}}elseif($ext==='json'){json_decode($content,true);if(json_last_error()!==JSON_ERROR_NONE)throw new RuntimeException('json_syntax_invalid:'.$path);}}
    private static function newDangerousCode(string $before,string $after):bool{$rx='/\b(?:eval|shell_exec|system|passthru|exec|popen|proc_open|pcntl_exec|assert)\s*\(/i';return (bool)(preg_match($rx,$after)&&!preg_match($rx,$before));}
    private static function deploymentStart(int $projectId,int $taskId,string $uid,array $files,array $dbMeta):int{$before=hash('sha256',j([$files,$dbMeta]));db()->prepare("INSERT INTO deployments(project_id,task_id,state,version_ref,before_hash,evidence_json) VALUES (?,?,'attempted',?,?,?)")->execute([$projectId,$taskId,'task:'.$uid,$before,j(['started_at'=>now_utc()])]);return (int)db()->lastInsertId();}
    private static function deploymentFinish(int $id,string $state,array $evidence,array $changes,?array $dbEvidence):void{$after=hash('sha256',j([$changes,$dbEvidence]));db()->prepare('UPDATE deployments SET state=?,after_hash=?,evidence_json=?,verified_at=IF(? IN (\'verified\',\'rolled_back\'),NOW(),verified_at) WHERE id=?')->execute([$state,$after,j($evidence),$state,$id]);}
    private static function rollbackEditedFiles(int $projectId,int $taskId,array $changes,array $target):array{$out=['attempted'=>0,'restored'=>0,'failed'=>0,'created_files'=>[]];foreach(array_reverse($changes) as $c){if(!is_array($c)||empty($c['changed']))continue;if(!empty($c['created'])){$out['created_files'][]=$c['path']??'';continue;}if(empty($c['backup'])||empty($c['path']))continue;$out['attempted']++;try{HostingerClient::restoreFileBackup($projectId,$taskId,(string)$c['path'],(string)$c['backup'],(string)($target['domain']??''),(string)($target['username']??''));$out['restored']++;}catch(Throwable){$out['failed']++;}}return $out;}
    private static function project(int $id):array{$q=db()->prepare('SELECT * FROM projects WHERE id=?');$q->execute([$id]);$p=$q->fetch();if(!$p)throw new RuntimeException('project_not_found');return $p;}
    private static function runLog(array $agent,int $taskId,array $r,string $state,string $summary):void{db()->prepare('INSERT INTO agent_runs(agent_id,task_id,state,provider_key,model,input_tokens,output_tokens,summary,completed_at) VALUES (?,?,?,?,?,?,?,?,NOW())')->execute([$agent['id'],$taskId,$state,$agent['provider_key'],$r['model']??$agent['model'],$r['input_tokens']??0,$r['output_tokens']??0,$summary]);}
}
