<?php
declare(strict_types=1);

final class CompanyGoalService {
    public static function create(string $title,string $description='',?string $metricKey=null,?float $target=null,string $unit='',string $priority='normal',?string $dueAt=null,?int $ownerAgentId=null):int{
        $title=trim($title);if($title==='')throw new RuntimeException('goal_title_required');if(!in_array($priority,['low','normal','high','critical'],true))$priority='normal';if($ownerAgentId)AgentService::byId($ownerAgentId);
        $due=null;if($dueAt){$ts=utc_ts($dueAt);if($ts===false)throw new RuntimeException('goal_due_invalid');$due=gmdate('Y-m-d H:i:s',$ts);}if($metricKey!==null&&trim($metricKey)!==''){self::validateMetricKey($metricKey);}
        $q=db()->prepare("INSERT INTO company_goals(title,description_text,metric_key,target_value,current_value,unit_label,start_at,due_at,priority,state,owner_agent_id,health_state) VALUES (?,?,?,?,?,?,NOW(),?,?,'active',?,'unknown')");$q->execute([pb_substr($title,0,240),pb_substr(trim($description),0,8000)?:null,$metricKey?pb_substr($metricKey,0,120):null,$target,0,$unit?pb_substr($unit,0,60):null,$due,$priority,$ownerAgentId]);$id=(int)db()->lastInsertId();Audit::log('owner',(string)(Auth::user()['id']??1),'goal.create','company_goal',(string)$id,'verified');return $id;
    }
    public static function list(string $state=''):array{$where=$state!==''?' WHERE g.state='.db()->quote($state):'';return db()->query("SELECT g.*,a.display_name owner_agent_name,(SELECT COUNT(*) FROM company_goal_agents ga WHERE ga.goal_id=g.id AND ga.state='active') agent_count FROM company_goals g LEFT JOIN agents a ON a.id=g.owner_agent_id{$where} ORDER BY FIELD(g.state,'active','draft','paused','completed','cancelled'),FIELD(g.priority,'critical','high','normal','low'),g.id DESC")->fetchAll();}
    public static function get(int $id):array{$q=db()->prepare('SELECT * FROM company_goals WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('goal_not_found');return $r;}
    public static function assign(int $goalId,int $agentId,string $responsibility='',float $weight=1.0):void{self::get($goalId);AgentService::byId($agentId);$weight=max(0.05,min(100,$weight));db()->prepare("INSERT INTO company_goal_agents(goal_id,agent_id,responsibility,weight,state) VALUES (?,?,?,?,'active') ON DUPLICATE KEY UPDATE responsibility=VALUES(responsibility),weight=VALUES(weight),state='active'")->execute([$goalId,$agentId,pb_substr(trim($responsibility),0,500)?:null,$weight]);}
    public static function validateAssignment(int $goalId,int $agentId):bool{$q=db()->prepare("SELECT COUNT(*) FROM company_goal_agents ga JOIN company_goals g ON g.id=ga.goal_id WHERE ga.goal_id=? AND ga.agent_id=? AND ga.state='active' AND g.state='active'");$q->execute([$goalId,$agentId]);return (int)$q->fetchColumn()>0;}
    public static function progress(int $goalId,?int $agentId,?float $delta,string $note='',?int $initiativeId=null,?int $taskId=null,array $evidence=[]):int{
        self::get($goalId);if($agentId)AgentService::byId($agentId);$q=db()->prepare('INSERT INTO company_goal_events(goal_id,agent_id,initiative_id,task_id,progress_delta,note_text,evidence_json) VALUES (?,?,?,?,?,?,?)');$q->execute([$goalId,$agentId,$initiativeId,$taskId,$delta,pb_substr(trim($note),0,8000)?:null,$evidence?j($evidence):null]);$id=(int)db()->lastInsertId();if($delta!==null)db()->prepare('UPDATE company_goals SET current_value=COALESCE(current_value,0)+?,updated_at=NOW() WHERE id=?')->execute([$delta,$goalId]);if($agentId)db()->prepare('UPDATE company_goal_agents SET last_progress_at=NOW() WHERE goal_id=? AND agent_id=?')->execute([$goalId,$agentId]);try{$g=self::get($goalId);if(trim((string)($g['metric_key']??''))!=='')GoalMetricEngine::syncGoal($goalId);}catch(Throwable){}return $id;
    }
    public static function agentGoals(int $agentId):array{$q=db()->prepare("SELECT g.*,ga.responsibility,ga.weight,ga.last_progress_at FROM company_goal_agents ga JOIN company_goals g ON g.id=ga.goal_id WHERE ga.agent_id=? AND ga.state='active' AND g.state='active' ORDER BY FIELD(g.priority,'critical','high','normal','low'),COALESCE(g.due_at,'9999-12-31')");$q->execute([$agentId]);return $q->fetchAll();}
    public static function context(int $agentId):array{return array_map(static fn($g)=>['id'=>(int)$g['id'],'title'=>$g['title'],'description'=>$g['description_text'],'metric'=>$g['metric_key'],'current'=>$g['current_value'],'target'=>$g['target_value'],'progress_percent'=>$g['progress_percent']??null,'forecast'=>$g['forecast_value']??null,'health'=>$g['health_state']??'unknown','unit'=>$g['unit_label'],'priority'=>$g['priority'],'due_at'=>$g['due_at'],'responsibility'=>$g['responsibility']],self::agentGoals($agentId));}
    public static function setState(int $id,string $state):void{if(!in_array($state,['draft','active','paused','completed','cancelled'],true))throw new RuntimeException('goal_state_invalid');self::get($id);db()->prepare('UPDATE company_goals SET state=?,completed_at=IF(?=\'completed\',COALESCE(completed_at,NOW()),completed_at),updated_at=NOW() WHERE id=?')->execute([$state,$state,$id]);}
    private static function validateMetricKey(string $metric):void{$q=db()->prepare('SELECT COUNT(*) FROM goal_metric_definitions WHERE metric_key=? AND enabled=1');$q->execute([trim($metric)]);if((int)$q->fetchColumn()===0)throw new RuntimeException('goal_metric_not_in_catalog:'.$metric);}
}
