<?php
declare(strict_types=1);
/** Owner-only encrypted configuration snapshots. The master key is never stored in the database. */
final class ConfigSnapshotService {
    private const AAD_V20='persebayt-config-v20';
    private const AAD_V17='persebayt-config-v17';
    private static function key():string{
        $path=PB_ROOT.'/private/runtime/master.key';if(!is_file($path))throw new RuntimeException('vault_key_unavailable');$key=base64_decode(trim((string)file_get_contents($path)),true);if($key===false||strlen($key)!==32)throw new RuntimeException('vault_key_unavailable');return $key;
    }
    public static function capture(string $label='current_owner_config'):int{
        Auth::requireOwner();$target=PB_ROOT.'/private/config.php';if(!is_file($target))throw new RuntimeException('config_file_missing');$plain=(string)file_get_contents($target);if($plain==='')throw new RuntimeException('config_file_empty');$key=self::key();$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($plain,'aes-256-gcm',$key,OPENSSL_RAW_DATA,$iv,$tag,self::AAD_V20);if($cipher===false||strlen($tag)!==16)throw new RuntimeException('config_snapshot_encrypt_failed');$envelope=j(['v'=>2,'alg'=>'aes-256-gcm','aad'=>self::AAD_V20,'iv'=>base64_encode($iv),'tag'=>base64_encode($tag),'data'=>base64_encode($cipher)]);$envelopeSha=hash('sha256',$envelope);$configSha=hash('sha256',$plain);db()->prepare("INSERT INTO secure_config_snapshots(label,envelope_b64,envelope_sha256,config_sha256,source_ref,state,created_by_user_id) VALUES (?,?,?,?,?,'verified',?) ON DUPLICATE KEY UPDATE config_sha256=VALUES(config_sha256),source_ref=VALUES(source_ref),state='verified',created_by_user_id=VALUES(created_by_user_id),created_at=NOW()")->execute([pb_substr($label,0,160),base64_encode($envelope),$envelopeSha,$configSha,'private/config.php',(int)(Auth::user()['id']??1)]);$q=db()->prepare('SELECT id FROM secure_config_snapshots WHERE label=? AND envelope_sha256=? ORDER BY id DESC LIMIT 1');$q->execute([pb_substr($label,0,160),$envelopeSha]);$id=(int)$q->fetchColumn();Audit::log('owner',(string)(Auth::user()['id']??1),'config_snapshot.capture','secure_config_snapshot',(string)$id,'verified',null,null,['envelope_sha256'=>$envelopeSha,'config_sha256'=>$configSha]);return $id;
    }
    public static function latest():?array{$q=db()->query("SELECT * FROM secure_config_snapshots WHERE state='verified' ORDER BY id DESC LIMIT 1");$r=$q->fetch();return $r?:null;}
    public static function restoreLatest():array{
        Auth::requireOwner();$r=self::latest();if(!$r)throw new RuntimeException('config_snapshot_missing');$key=self::key();$raw=base64_decode((string)$r['envelope_b64'],true);if($raw===false||!hash_equals((string)$r['envelope_sha256'],hash('sha256',$raw)))throw new RuntimeException('config_snapshot_integrity_failed');$e=json_decode($raw,true,512,JSON_THROW_ON_ERROR);$iv=base64_decode((string)($e['iv']??''),true);$tag=base64_decode((string)($e['tag']??''),true);$data=base64_decode((string)($e['data']??''),true);if($iv===false||$tag===false||$data===false)throw new RuntimeException('config_snapshot_format_invalid');$aad=(string)($e['aad']??self::AAD_V17);if(!in_array($aad,[self::AAD_V17,self::AAD_V20],true))throw new RuntimeException('config_snapshot_aad_invalid');$plain=openssl_decrypt($data,'aes-256-gcm',$key,OPENSSL_RAW_DATA,$iv,$tag,$aad);if($plain===false)throw new RuntimeException('config_snapshot_decrypt_failed');if(!empty($r['config_sha256'])&&!hash_equals((string)$r['config_sha256'],hash('sha256',$plain)))throw new RuntimeException('config_snapshot_plaintext_integrity_failed');$target=PB_ROOT.'/private/config.php';$backup=PB_ROOT.'/private/runtime/file-backups/config-'.gmdate('Ymd_His').'.php';if(is_file($target)){if(!is_dir(dirname($backup))&&!mkdir(dirname($backup),0700,true)&&!is_dir(dirname($backup)))throw new RuntimeException('config_backup_directory_failed');if(!copy($target,$backup))throw new RuntimeException('config_backup_failed');@chmod($backup,0600);}if(file_put_contents($target,$plain,LOCK_EX)===false)throw new RuntimeException('config_restore_write_failed');@chmod($target,0600);Audit::log('owner',(string)(Auth::user()['id']??1),'config_snapshot.restore','system_config','current','verified',null,null,['snapshot_id'=>(int)$r['id'],'backup_ref'=>basename($backup),'config_sha256'=>hash('sha256',$plain)]);return ['ok'=>true,'snapshot_id'=>(int)$r['id'],'config_sha256'=>hash('sha256',$plain),'backup_ref'=>basename($backup)];
    }
    public static function list():array{return db()->query("SELECT id,label,envelope_sha256,config_sha256,source_ref,state,created_at FROM secure_config_snapshots ORDER BY id DESC LIMIT 50")->fetchAll();}
}
