<?php
declare(strict_types=1);
final class CreatorIntelligenceService {
    public static function analyze(string|int $creatorId,int $months=4,bool $persist=true):array{
        $creatorId=trim((string)$creatorId);if($creatorId==='')throw new RuntimeException('creator_required');$months=max(3,min(12,$months));
        $q=db()->prepare("SELECT data_month,MAX(diamonds) diamonds,MAX(valid_days) valid_days,MAX(live_hours) live_hours,MAX(estimated_bonus) estimated_bonus,MAX(followers) followers FROM agency_creator_monthly WHERE creator_id=? GROUP BY data_month ORDER BY data_month DESC LIMIT ".$months);$q->execute([$creatorId]);$rows=$q->fetchAll();if(!$rows)return ['state'=>'no_data','creator_id'=>$creatorId,'rows'=>[]];
        $latest=$rows[0];$prev=$rows[1]??null;$diamonds=(float)$latest['diamonds'];$previous=(float)($prev['diamonds']??0);$mom=$previous>0?(($diamonds-$previous)/$previous)*100:null;$chron=array_reverse($rows);$three=array_slice($rows,0,3);$avg3=count($three)?array_sum(array_map(static fn($r)=>(float)$r['diamonds'],$three))/count($three):$diamonds;$baseline=count($rows)>1?array_sum(array_map(static fn($r)=>(float)$r['diamonds'],array_slice($rows,1)))/count(array_slice($rows,1)):$diamonds;$gap=$diamonds-$baseline;
        $trend='flat';if(count($chron)===1)$trend='new';elseif($mom!==null&&$mom>=10)$trend='up';elseif($mom!==null&&$mom<=-10)$trend='down';
        $days=(float)$latest['valid_days'];$hours=(float)$latest['live_hours'];$daysRisk=$days>=12?0:($days>=7?25:($days>=3?55:85));$hoursRisk=$hours>=40?0:($hours>=20?25:($hours>=8?55:85));$attention=0;if($trend==='down')$attention+=35;if($mom!==null&&$mom<=-30)$attention+=20;if($diamonds<=0)$attention+=30;$attention+=intdiv($daysRisk+$hoursRisk,4);$attention=max(0,min(100,$attention));
        $target=(float)setting('agency.default_creator_target_diamonds','0');$targetGap=$target>0?$target-$diamonds:null;$projection=['next_month_diamonds'=>max(0,round($diamonds+($prev?($diamonds-$previous):0),0)),'trend'=>$trend,'rolling_3m_avg'=>round($avg3,2)];
        $out=['state'=>'ok','creator_id'=>$creatorId,'data_month'=>(string)$latest['data_month'],'diamonds'=>(int)$diamonds,'previous_diamonds'=>(int)$previous,'mom_percent'=>$mom===null?null:round($mom,2),'rolling_3m_avg'=>round($avg3,2),'baseline_diamonds'=>round($baseline,2),'gap_from_baseline'=>round($gap,2),'trend_direction'=>$trend,'attention_score'=>$attention,'days_risk'=>$daysRisk,'hours_risk'=>$hoursRisk,'target_gap'=>$targetGap,'projection'=>$projection,'rows'=>$rows];
        if($persist)db()->prepare("INSERT INTO creator_intelligence_snapshots(creator_id,data_month,diamonds,previous_diamonds,mom_percent,rolling_3m_avg,baseline_diamonds,gap_from_baseline,trend_direction,attention_score,days_risk,hours_risk,target_gap,projection_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE diamonds=VALUES(diamonds),previous_diamonds=VALUES(previous_diamonds),mom_percent=VALUES(mom_percent),rolling_3m_avg=VALUES(rolling_3m_avg),baseline_diamonds=VALUES(baseline_diamonds),gap_from_baseline=VALUES(gap_from_baseline),trend_direction=VALUES(trend_direction),attention_score=VALUES(attention_score),days_risk=VALUES(days_risk),hours_risk=VALUES(hours_risk),target_gap=VALUES(target_gap),projection_json=VALUES(projection_json),updated_at=NOW()")
            ->execute([$creatorId,$out['data_month'],$out['diamonds'],$out['previous_diamonds'],$out['mom_percent'],$out['rolling_3m_avg'],$out['baseline_diamonds'],$out['gap_from_baseline'],$trend,$attention,$daysRisk,$hoursRisk,$targetGap,j($projection)]);
        return $out;
    }
    public static function refreshAll(int $limit=1000):array{$limit=max(1,min(5000,$limit));$ids=db()->query("SELECT creator_id FROM agency_creators WHERE active=1 ORDER BY id LIMIT ".$limit)->fetchAll(PDO::FETCH_COLUMN);$done=0;$failed=0;foreach($ids as $id){try{self::analyze((string)$id,4,true);$done++;}catch(Throwable){$failed++;}}return ['processed'=>$done,'failed'=>$failed];}
    public static function attention(int $limit=50):array{$limit=max(1,min(200,$limit));try{$month=(string)(db()->query('SELECT MAX(data_month) FROM creator_intelligence_snapshots')->fetchColumn()?:'');if($month===''){self::refreshAll();$month=(string)(db()->query('SELECT MAX(data_month) FROM creator_intelligence_snapshots')->fetchColumn()?:'');}if($month==='')return []; $q=db()->prepare("SELECT s.*,c.nickname,c.username,c.handle FROM creator_intelligence_snapshots s LEFT JOIN agency_creators c ON c.creator_id=s.creator_id WHERE s.data_month=? ORDER BY s.attention_score DESC,s.diamonds DESC LIMIT ".$limit);$q->execute([$month]);return $q->fetchAll();}catch(Throwable){return [];}}
}
