<?php
declare(strict_types=1);
final class DirectAgentChat {
    public static function handle(string $slug,int $sessionId,string $text):array{
        $agent=AgentService::assertRunnable(AgentService::bySlug($slug));if($slug==='ramy')return RamiOrchestrator::owner($sessionId,$text);$ctx=ConversationService::activeContext($sessionId);$memory=AgentService::tool((int)$agent['id'],'memory')?['company'=>MemoryService::company(12),'agent'=>MemoryService::agentContext((int)$agent['id'],$ctx['project']['id']??null,18),'project'=>!empty($ctx['project']['id'])?MemoryService::project((int)$ctx['project']['id'],16):[]]:['company'=>[],'agent'=>[],'project'=>[]];
        $history=[];foreach(array_slice($ctx['history'],-14) as $m)$history[]=['role'=>$m['sender_type']==='owner'?'user':'assistant','content'=>(string)$m['body_text']];
        $teamRecent=[];try{foreach(TeamChatService::recent(12) as $tm)$teamRecent[]=['sender'=>(string)($tm['sender_ref']??$tm['sender_type']??''),'to'=>(string)($tm['receiver_ref']??'team'),'kind'=>(string)($tm['message_kind']??'note'),'text'=>pb_substr((string)($tm['body_text']??''),0,1000)];}catch(Throwable){}
        $schema=['type'=>'object','additionalProperties'=>false,'properties'=>['reply'=>['type'=>'string'],'execute'=>['type'=>'boolean'],'task_description'=>['type'=>'string'],'close'=>['type'=>'boolean']],'required'=>['reply','execute','task_description','close']];
        $prompt=(string)$agent['system_prompt']."\nأنت تتحدث مباشرة مع المالك أبانوب بإذن منه داخل شات الفريق المشترك. اقرأ Context Snapshot وآخر 50 رسالة مهمة وTEAM_RECENT قبل الرد، وافهم تكليفات رامي ورسائل باقي الوكلاء باعتبارها سياق تشغيل مشترك. عرّف نفسك مرة واحدة فقط لكل Session؛ النظام سيضيف الاسم آليًا. لا تتجاوز تخصصك أو صلاحياتك. إذا أعطاك المالك أمرًا واضحًا يدخل في تخصصك اجعل execute=true واكتب task_description دقيقة. لا تطلب تكرار معلومات موجودة في السياق أو في شات الفريق. إذا انتهت المحادثة اجعل close=true؛ النظام سيضيف عبارة ختام واسمك.";
        $r=AiGateway::json($agent,$prompt,array_merge($history,[['role'=>'user','content'=>"ACTIVE_CONTEXT:\n".j(['project'=>$ctx['project'],'task'=>$ctx['task']])."\nTEAM_RECENT:\n".j($teamRecent)."\nMEMORY:\n".j($memory)."\nOWNER_MESSAGE:\n".$text]]),$schema,'direct_agent_chat',2200);$o=$r['data'];$execution=null;
        if(!empty($o['execute'])){$desc=trim((string)$o['task_description'])?:trim($text);$pid=!empty($ctx['project']['id'])?(int)$ctx['project']['id']:null;if($slug==='walid')$execution=Workflow::huntOpportunities('أمر مباشر من المالك إلى وليد: '.$desc);elseif($slug==='ayman'){if(!$pid)$o['reply'].="\nأحتاج تحديد المشروع لأن الجلسة المباشرة الحالية لا تحمل مشروعًا نشطًا.";else $execution=Workflow::assignAyman($pid,$desc,'high');}elseif($slug==='emad'){if(!empty($ctx['task']['id'])&&($ctx['task']['agent_slug']??'')==='ayman'&&in_array((string)$ctx['task']['status'],['needs_review','completed'],true)){$parent=(int)$ctx['task']['id'];$q=db()->prepare("SELECT id FROM tasks WHERE parent_task_id=? AND assigned_agent_id=? AND status NOT IN ('cancelled','failed','completed') ORDER BY id DESC LIMIT 1");$q->execute([$parent,(int)$agent['id']]);$existing=(int)($q->fetchColumn()?:0);if($existing)$execution=['primary_task'=>$existing,'summary'=>'عماد عنده مراجعة شغالة بالفعل لنفس المهمة.'];else{$rid=TaskService::create('emad','مراجعة مباشرة بطلب المالك',$desc,$pid,['review_of'=>$parent],'high',true,$parent);$execution=['primary_task'=>$rid,'summary'=>'بدأ عماد مراجعة المهمة النشطة.'];}}else $o['reply'].="\nلا توجد مهمة أيمن جاهزة للمراجعة في الجلسة الحالية.";}else{$tid=TaskService::create($slug,'مهمة مباشرة من المالك',$desc,$pid,['direct_owner'=>1],'high',true);$execution=['primary_task'=>$tid,'summary'=>'تم إنشاء المهمة للوكيل.'];}}
        return ['reply'=>trim((string)$o['reply']),'close'=>(bool)$o['close'],'execution'=>$execution];
    }
}
