<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$r=SystemDoctor::report();$recentErrors=SystemDoctor::recentErrors(20);
AdminUi::header('فحص النظام','doctor');echo AdminUi::flash();
$labels=['php_version'=>'إصدار PHP','curl'=>'cURL','openssl'=>'OpenSSL','pdo_mysql'=>'PDO MySQL','json'=>'JSON','mbstring'=>'mbstring','database'=>'قاعدة البيانات','database_reconnect_guard'=>'حماية اتصال MySQL بعد AI','schema'=>'هيكل Company OS','version'=>'إصدار النظام','agent_ramy'=>'رامي','agent_walid'=>'وليد','agent_ayman'=>'أيمن','agent_emad'=>'عماد','agents'=>'الوكلاء','web_search'=>'بحث وليد','openai'=>'OpenAI','hostinger'=>'Hostinger','whatsapp'=>'WhatsApp','whatsapp_webhook_security'=>'أمان WhatsApp Webhook','runtime'=>'Runtime','vault'=>'Secret Vault','worker'=>'Worker/Cron','jobs'=>'طابور المهام','ramy_context'=>'سياق رامي','staging'=>'محطة الاختبار','cloud'=>'Cloud Backup','browser_qa'=>'Cloud Browser QA'];
?>
<div class="dashboard-welcome"><div><span class="eyebrow">SYSTEM DOCTOR · <?=e(ReleaseInfo::VERSION)?></span><h2><?=$r['ok']?'النظام جاهز':'يوجد عناصر تحتاج مراجعة'?></h2></div><div class="quick-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="run_worker"><input type="hidden" name="return" value="/api/admin/doctor.php"><button class="btn">تشغيل Worker الآن</button></form><a class="btn secondary" href="health.php">فحص الربط الخارجي</a><a class="btn secondary" href="integrations.php">المفاتيح والـCloud</a></div></div>
<div class="grid">
<section class="card span-12"><div class="card-title"><div><h2>الفحوصات</h2><span class="muted small">Company OS <?=e(ReleaseInfo::VERSION)?> يستخدم Schema Preflight وفحص اتصال MySQL المتجدد بعد عمليات AI الطويلة. ظهور الإصدار 20.1.4 هنا يؤكد أن ملفات Hotfix وصلت إلى المسار الحي /public_html/api وليست داخل مجلد public_html متداخل.</span></div></div><div class="table-wrap"><table><thead><tr><th>العنصر</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody><?php foreach($r['checks'] as $key=>$c):?><tr><td><b><?=e($labels[$key]??$key)?></b></td><td><?=AdminUi::badge($c['ok']?'verified':'failed')?></td><td><?=e($c['note'])?></td></tr><?php endforeach?></tbody></table></div></section>
<?php if($r['schema_issues']):?><section class="card span-12"><div class="card-title"><div><h2>عدم تطابق قاعدة البيانات</h2><span class="muted small">لا تضف أعمدة يدويًا قبل التحقق من إصدار الملفات. في Company OS 20.1.4 العمود الصحيح لذاكرة الوكلاء هو <code>agent_memory_bank.salience</code>. إذا ظهر <code>agent_memory_bank.importance</code> بعد هذا Hotfix فافحص وجود مجلد متداخل <code>/public_html/public_html/</code> واحذفه بعد التأكد؛ الملف الحي المطلوب هو <code>/public_html/api/src/SystemDoctor.php</code>.</span></div></div><div class="code-block"><?=nl2br(e(implode("\n",$r['schema_issues'])))?></div></section><?php endif?>
<?php if($recentErrors):?><section class="card span-12"><div class="card-title"><div><h2>أخطاء آخر 48 ساعة</h2></div></div><div class="table-wrap"><table><thead><tr><th>المرجع</th><th>الصفحة</th><th>السبب</th><th>الوقت</th></tr></thead><tbody><?php foreach($recentErrors as $er):?><tr><td><code><?=e($er['error_ref'])?></code></td><td><?=e(pb_substr((string)$er['request_uri'],0,120))?></td><td><?=e(pb_substr((string)$er['error_message'],0,180))?></td><td><?=e(AdminUi::date($er['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<section class="card span-6"><div class="card-title"><h2>اختبار وليد</h2></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_hunt"><input type="hidden" name="return" value="/api/admin/doctor.php"><input type="hidden" name="lookback_days" value="15"><input type="hidden" name="raw_target" value="10"><button class="btn full-width">تشغيل وليد — اختبار حقيقي</button></form></section>
<section class="card span-6"><div class="card-title"><h2>اختبارات Cloud</h2></div><p class="muted">يمكن اختبار التخزين السحابي وCloud Browser من صفحة المفاتيح والربط بدون التأثير على واتساب أو Hostinger.</p><a class="btn full-width" href="integrations.php">فتح مركز الربط</a></section>
</div>
<?php AdminUi::footer();
