<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();$domain=strtolower(trim((string)($_GET['domain']??'')));AdminUi::header($domain?'الدومين '.$domain:'الدومينات','domains');echo AdminUi::flash();
if($domain!==''){$q=db()->prepare("SELECT d.*,p.name project_name,p.status project_status FROM project_domains d LEFT JOIN projects p ON p.id=d.project_id WHERE d.domain_name=?");$q->execute([$domain]);$d=$q->fetch();if(!$d)throw new RuntimeException('domain_not_found');$dns=[];$snap=[];$dnsError='';try{$dns=HostingerClient::dnsZone($domain);$snap=HostingerClient::dnsSnapshots($domain);}catch(Throwable $e){$dnsError=$e->getMessage();}$tls=TlsInspector::inspect($domain);?>
<div class="actions" style="margin-bottom:15px"><a class="btn secondary" href="domains.php">← كل الدومينات</a><?php if($d['project_id']):?><a class="btn secondary" href="projects.php?id=<?=(int)$d['project_id']?>">فتح المشروع</a><?php endif?></div>
<div class="grid"><section class="card span-6"><div class="card-title"><h2>حالة الدومين</h2><?=AdminUi::badge($d['status'])?></div><dl class="kvs"><dt>الدومين</dt><dd class="mono"><?=e($domain)?></dd><dt>المشروع</dt><dd><?=e($d['project_name']?:'بدون مشروع')?></dd><dt>حالة المشروع</dt><dd><?=$d['project_status']?AdminUi::badge($d['project_status']):'—'?></dd><dt>مرجع Hostinger</dt><dd class="mono"><?=e($d['provider_id']?:'—')?></dd><dt>آخر ظهور</dt><dd><?=e(AdminUi::date($d['last_seen_at']))?></dd></dl></section>
<section class="card span-6"><div class="card-title"><h2>شهادة أمان الموقع</h2><?=AdminUi::badge(!empty($tls['ok'])?'verified':'failed')?></div><?php if(empty($tls['ok'])):?><?=AdminUi::alert('تعذر التحقق: '.AdminUi::humanError((string)($tls['error']??'تعذر التحقق')),'error')?><?php else:?><dl class="kvs"><dt>بيانات الشهادة</dt><dd><?=e($tls['subject']??'—')?></dd><dt>جهة إصدار الشهادة</dt><dd><?=e($tls['issuer']??'—')?></dd><dt>صالحة لحد</dt><dd><?=e($tls['valid_to']??'—')?></dd><dt>الأيام المتبقية</dt><dd><?=e($tls['days_left']??'—')?></dd></dl><?php endif?></section>
<section class="card span-8"><div class="card-title"><div><h2>سجلات الدومين</h2><span class="muted small">قراءة مباشرة من Hostinger عند توفر الاتصال.</span></div><?=AdminUi::badge($dnsError===''?'verified':'warning')?></div><?php if($dnsError!==''):?><?=AdminUi::alert('تعذر القراءة: '.$dnsError,'error')?><?php elseif(!$dns):?><?=AdminUi::empty('لا توجد سجلات دومين أو لم ترجع الاستضافة بيانات.')?><?php else:?><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>النوع</th><th>مدة حفظ السجل</th><th>السجلات</th></tr></thead><tbody><?php foreach($dns as $rr):?><tr><td class="mono"><?=e($rr['name']??'')?></td><td><?=e($rr['type']??'')?></td><td><?=e($rr['ttl']??'')?></td><td class="mono"><?php $vals=[];foreach((array)($rr['records']??[]) as $rec)$vals[]=(string)($rec['content']??'');echo e(implode(' | ',$vals));?></td></tr><?php endforeach?></tbody></table></div><?php endif?></section>
<section class="card span-4"><div class="card-title"><h2>نسخ سجلات الدومين السابقة</h2></div><?php if(!$snap):?><?=AdminUi::empty('لا توجد نسخ سابقة ظاهرة.')?><?php else:foreach(array_slice($snap,0,12) as $x):?><div class="mini-item"><div class="grow"><b>#<?=e($x['id']??'')?></b><small><?=e(AdminUi::label((string)($x['reason']??'نسخة سابقة')))?> · <?=e(AdminUi::date($x['created_at']??null))?></small></div></div><?php endforeach;endif?></section>
<section class="card span-12 danger-zone"><div class="card-title"><h2>تحديث سجلات الدومين</h2></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="dns_update"><input type="hidden" name="domain" value="<?=e($domain)?>"><div class="field"><label>بيانات سجلات الدومين بصيغة تقنية</label><textarea name="zone_json" style="min-height:260px" required><?=e(j($dns))?></textarea></div><label class="check-row"><input type="checkbox" name="overwrite" value="1"> استبدال الموجود السجلات المطابقة الاسم والنوع</label><button class="btn danger" data-confirm="سيتم التحقق ثم تحديث سجلات الدومين على Hostinger. هل تريد المتابعة؟" style="margin-top:12px">راجع وحدّث السجلات</button></form></section></div>
<?php }else{$rows=db()->query("SELECT d.*,p.name project_name,p.status project_status FROM project_domains d LEFT JOIN projects p ON p.id=d.project_id ORDER BY FIELD(d.status,'active','available','missing','removed'),d.domain_name")->fetchAll();$active=0;$available=0;$removed=0;foreach($rows as $r){if($r['status']==='active')$active++;elseif($r['status']==='available')$available++;elseif(in_array($r['status'],['removed','missing'],true))$removed++;}?>
<div class="metric-grid"><?=AdminUi::stat('مرتبطة بمشاريع',$active)?><?=AdminUi::stat('متاحة لمشروع جديد',$available)?><?=AdminUi::stat('مفقودة/محذوفة',$removed)?><?=AdminUi::stat('إجمالي السجل',count($rows))?></div>
<section class="card"><div class="card-title"><div><h2>سجل الدومينات</h2><span class="muted small">الدومين يبقى متاحًا إذا حذف الموقع، ويُخفى من الاستخدام الفعلي إذا اختفى من الاستضافة.</span></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="scan_projects"><button class="btn">فحص Hostinger الآن</button></form></div><div class="table-wrap"><table><thead><tr><th>الدومين</th><th>الحالة</th><th>المشروع</th><th>حالة المشروع</th><th>مرجع Hostinger</th><th>آخر ظهور</th><th>الدومين وشهادة الأمان</th></tr></thead><tbody><?php foreach($rows as $d):?><tr><td class="mono"><?=e($d['domain_name'])?></td><td><?=AdminUi::badge($d['status'])?></td><td><?=$d['project_id']?'<a href="project.php?id='.(int)$d['project_id'].'">'.e($d['project_name']).'</a>':'—'?></td><td><?=$d['project_status']?AdminUi::badge($d['project_status']):'—'?></td><td class="mono"><?=e($d['provider_id']?:'—')?></td><td><?=e(AdminUi::date($d['last_seen_at']))?></td><td><a class="link" href="domains.php?domain=<?=e(rawurlencode($d['domain_name']))?>">إدارة</a></td></tr><?php endforeach?></tbody></table></div></section><?php }AdminUi::footer();
