<?php
declare(strict_types=1);

/** Single audited gate for agent actions that leave PerseBayt. */
final class ExternalActionGateway {
    public static function propose(int $agentId,?int $contactId,string $channel,string $action,array $payload,string $reason='',bool $requiresOwnerApproval=true,?int $taskId=null,?int $initiativeId=null):int{
        AgentService::byId($agentId);$channel=pb_strtolower(trim($channel));$action=trim($action);if(!preg_match('/^[a-z0-9_.:-]{2,80}$/',$channel)||!preg_match('/^[a-z0-9_.:-]{2,100}$/i',$action))throw new RuntimeException('external_action_invalid');Permissions::requireAgent($agentId,'external.propose');
        if($contactId)ContactDirectoryService::get($contactId);$state=$requiresOwnerApproval?'proposed':'authorized';$approved=$requiresOwnerApproval?null:now_utc();db()->prepare('INSERT INTO agent_external_actions(agent_id,initiative_id,task_id,contact_id,channel_key,action_key,state,reason_text,payload_json,requires_owner_approval,approved_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)')->execute([$agentId,$initiativeId,$taskId,$contactId,$channel,$action,$state,pb_substr(trim($reason),0,8000)?:null,j(self::sanitizePayloadForStorage($payload)),$requiresOwnerApproval?1:0,$approved]);$id=(int)db()->lastInsertId();Audit::log('agent',(string)$agentId,'external.propose','agent_external_action',(string)$id,$state,null,$taskId,['channel'=>$channel,'action'=>$action,'requires_owner_approval'=>$requiresOwnerApproval]);return $id;
    }
    public static function approve(int $id):void{Auth::requireOwner();$a=self::get($id);if(!in_array((string)$a['state'],['proposed','blocked'],true))throw new RuntimeException('external_action_not_approvable');db()->prepare("UPDATE agent_external_actions SET state='authorized',approved_at=NOW() WHERE id=?")->execute([$id]);Audit::log('owner',(string)(Auth::user()['id']??1),'external.approve','agent_external_action',(string)$id,'verified');}
    public static function execute(int $id):array{
        $a=self::get($id);if((int)$a['requires_owner_approval']===1&&(string)$a['state']!=='authorized')throw new RuntimeException('external_action_owner_approval_required');if(!in_array((string)$a['state'],['authorized','queued'],true))throw new RuntimeException('external_action_not_executable');$agentId=(int)$a['agent_id'];$payload=json_decode((string)($a['payload_json']??'{}'),true);if(!is_array($payload))$payload=[];$channel=(string)$a['channel_key'];$risk=$channel==='browser'?'high':($channel==='whatsapp'?'medium':'low');$ownerApproved=(int)$a['requires_owner_approval']===0||!empty($a['approved_at']);AgentPolicyEngine::authorizeAction($agentId,'external_guarded','use',['risk'=>$risk,'external'=>true,'owner_approved'=>$ownerApproved,'gateway_managed'=>true,'task_id'=>$a['task_id']?(int)$a['task_id']:null,'publish'=>str_contains((string)$a['action_key'],'publish')]);$result=[];
        try{
            if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'external_action');
            if($channel==='whatsapp'){$contactId=(int)($a['contact_id']??0);if(!$contactId)throw new RuntimeException('external_contact_required');Permissions::requireAgent($agentId,'whatsapp.send');$to=ContactDirectoryService::whatsappNumber($contactId);$text=trim((string)($payload['text']??''));if($text==='')throw new RuntimeException('external_message_required');$r=MetaClient::sendText($to,$text);$result=['message_id'=>(string)($r['messages'][0]['id']??''),'channel'=>'whatsapp','provider'=>'meta'];}
            elseif($channel==='dashboard'){$slug=(string)AgentService::byId($agentId)['slug'];$r=CommunicationGateway::agentToOwner($slug,(string)($payload['text']??''),'dashboard');$result=['channel'=>'dashboard','session_id'=>$r['session_id']??null];}
            elseif($channel==='browser'){$accountId=(int)($payload['service_account_id']??0);$action=(string)($payload['browser_action']??'navigate');$params=(array)($payload['params']??[]);$result=BrowserAutomationService::execute($agentId,$accountId,$action,$params);}
            else throw new RuntimeException('external_channel_not_implemented:'.$channel);
            db()->prepare("UPDATE agent_external_actions SET state='executed',executed_at=NOW(),evidence_json=? WHERE id=?")->execute([j(self::sanitizePayloadForStorage($result)),$id]);Audit::log('agent',(string)$agentId,'external.execute','agent_external_action',(string)$id,'verified',null,$a['task_id']?(int)$a['task_id']:null,['channel'=>$channel,'action'=>$a['action_key']]);if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'external_action',1,0,['channel'=>$channel,'action'=>$a['action_key']]);return $result+['action_id'=>$id];
        }catch(Throwable $e){$safe=pb_substr(Security::redactSecrets($e->getMessage()),0,400);db()->prepare("UPDATE agent_external_actions SET state='blocked',evidence_json=? WHERE id=?")->execute([j(['error'=>$safe]),$id]);throw $e;}
    }
    public static function get(int $id):array{$q=db()->prepare('SELECT * FROM agent_external_actions WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('external_action_not_found');return $r;}
    private static function sanitizePayloadForStorage(array $p):array{$secretKeys=['password','token','secret','api_key','authorization','cookie','otp'];$walk=function(&$v,$k)use(&$walk,$secretKeys){if(is_array($v)){foreach($v as $kk=>&$vv){if(in_array(pb_strtolower((string)$kk),$secretKeys,true))$vv='[REDACTED]';else $walk($vv,$kk);}unset($vv);}elseif(is_string($v))$v=Security::redactSecrets($v);};$walk($p,'');return $p;}
}
