<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    Auth::verifyCsrf();
    try{
        $op=(string)($_POST['op']??'');
        if($op==='run'){$r=FreeModelScoutService::run('owner_manual');$_SESSION['flash']='خلصت دورة نور: '.(int)($r['models_found']??0).' موديل مرصود، '.(int)($r['providers_working']??0).' مزود شغال.';$_SESSION['flash_type']=($r['state']??'')==='completed'?'success':'warning';}
        elseif($op==='toggle'){put_setting('free_model_scout.enabled',!empty($_POST['enabled'])?'1':'0');$_SESSION['flash']='تم تحديث تشغيل نور اليومي.';$_SESSION['flash_type']='success';}
        elseif($op==='route_toggle'){$pk=trim((string)($_POST['provider_key']??''));db()->prepare('UPDATE free_provider_candidates SET auto_route=? WHERE provider_key=?')->execute([!empty($_POST['auto_route'])?1:0,$pk]);$_SESSION['flash']='تم تحديث استخدام المزود في الـFallback.';$_SESSION['flash_type']='success';}
        else throw new RuntimeException('free_model_scout_action_invalid');
    }catch(Throwable $e){$_SESSION['flash']=AdminUi::humanError(Security::redactSecrets($e->getMessage(),240));$_SESSION['flash_type']='error';}
    header('Location: /api/admin/free-model-scout.php');exit;
}
$d=FreeModelScoutService::dashboard();$s=(array)$d['summary'];AdminUi::header('نور — صياد الموديلات المجانية','free_model_scout');echo AdminUi::flash();
?>
<section class="dashboard-welcome"><div><span class="eyebrow">FREE MODEL SCOUT · <?=e(ReleaseInfo::VERSION)?></span><h2>وكيل يومي لاكتشاف الموديلات المجانية والمحافظة على Fallbacks شغالة</h2><p>نور يفحص المصادر الرسمية والمزودات المرتبطة، يحدّث قائمة الموديلات، ويرتب مزودات مجانية/Free-tier قبل الـFallback المدفوع عند توافر مفتاح صالح. لا ينشئ حسابات مكررة لتجاوز الحصص ولا يتجاوز CAPTCHA/2FA؛ التسجيل الذي يحتاج تدخل بشري يظهر بوضوح هنا.</p></div><div class="quick-actions"><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="run"><button class="btn">تشغيل دورة الآن</button></form></div></section>
<div class="metric-grid metric-grid-4"><?=AdminUi::stat('الموديلات المرصودة',(int)$s['models'],'نشطة في الكتالوج')?><?=AdminUi::stat('موديلات شغالة',(int)$s['working_models'],'حسب آخر صحة للمزود')?><?=AdminUi::stat('مزودات شغالة',(int)$s['working_providers'],'Fallback متاح')?><?=AdminUi::stat('تحتاج تدخل',(int)$s['human_required'],'تسجيل/مفتاح يدوي')?></div>
<section class="card"><div class="card-title"><div><h2>التشغيل اليومي</h2><span class="muted small">آخر دورة: <?=e(AdminUi::date($d['last_run_at']))?> · <?=AdminUi::badge((string)$d['last_state'])?></span></div><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="toggle"><label class="check"><input type="checkbox" name="enabled" value="1" <?=setting('free_model_scout.enabled','1')==='1'?'checked':''?>> تشغيل تلقائي كل <?=e(setting('free_model_scout.interval_hours','24'))?> ساعة</label><button class="btn secondary small">حفظ</button></form></div></section>
<section class="card"><div class="card-title"><h2>المزودات</h2></div><div class="table-wrap"><table><thead><tr><th>المزود</th><th>الحالة</th><th>نوع المجاني</th><th>Fallback تلقائي</th><th>آخر ملاحظة</th><th>التسجيل/التوثيق</th></tr></thead><tbody><?php foreach((array)$d['providers'] as $p):?><tr><td><b><?=e($p['label'])?></b><small class="mono"><?=e($p['provider_key'])?></small></td><td><?=AdminUi::badge($p['state'])?></td><td><?=e($p['free_kind'])?></td><td><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="route_toggle"><input type="hidden" name="provider_key" value="<?=e($p['provider_key'])?>"><label class="check"><input type="checkbox" name="auto_route" value="1" <?=!empty($p['auto_route'])?'checked':''?>> استخدام</label><button class="btn secondary small">حفظ</button></form></td><td><?=e($p['last_note']?:'—')?></td><td><?php if($p['signup_url']):?><a class="btn ghost small" target="_blank" rel="noopener" href="<?=e($p['signup_url'])?>">تسجيل/مفتاح</a><?php endif?> <?php if($p['docs_url']):?><a class="btn ghost small" target="_blank" rel="noopener" href="<?=e($p['docs_url'])?>">Docs</a><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="card-title"><h2>كتالوج الموديلات المجانية</h2><span class="muted small">OpenRouter/free نفسه يدوّر بين موديلات OpenRouter المجانية، لكن انتهاء حصة الحساب ينتقل للمزود المجاني التالي بدل تجربة عشرات موديلات من نفس الحساب.</span></div><div class="table-wrap"><table><thead><tr><th>المزود</th><th>الموديل</th><th>الحالة</th><th>Context</th><th>Score</th><th>آخر ظهور</th></tr></thead><tbody><?php foreach((array)$d['models'] as $m):?><tr><td><?=e($m['provider_key'])?></td><td class="mono"><?=e($m['model_key'])?></td><td><?=AdminUi::badge($m['health_state'])?></td><td><?=number_format((int)$m['context_length'])?></td><td><?=(int)$m['score']?></td><td><?=e(AdminUi::date($m['last_seen_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="card-title"><h2>آخر الدورات</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Trigger</th><th>الحالة</th><th>بدأت</th><th>انتهت</th><th>ملخص</th></tr></thead><tbody><?php foreach((array)$d['runs'] as $r):?><tr><td><?=(int)$r['id']?></td><td><?=e($r['trigger_key'])?></td><td><?=AdminUi::badge($r['state'])?></td><td><?=e(AdminUi::date($r['started_at']))?></td><td><?=e(AdminUi::date($r['completed_at']))?></td><td class="small mono"><?=e(pb_substr((string)$r['summary_json'],0,240))?></td></tr><?php endforeach?></tbody></table></div></section>
<?php AdminUi::footer();
