<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$php=['version'=>PHP_VERSION,'php_8_1_plus'=>version_compare(PHP_VERSION,'8.1.0','>='),'curl'=>extension_loaded('curl'),'openssl'=>extension_loaded('openssl'),'pdo_mysql'=>extension_loaded('pdo_mysql'),'json'=>extension_loaded('json'),'mbstring'=>extension_loaded('mbstring')];
$audit=RuntimeAuditService::snapshot();
$issues=(array)$audit['issues'];$worker=(array)$audit['worker'];$walid=(array)$audit['walid'];$ramy=(array)$audit['ramy'];$openrouter=(array)$audit['openrouter'];$hostinger=(array)$audit['hostinger'];$dash=(array)$audit['dashboard'];$oq=(array)($audit['opportunity_quality']??[]);
$critical=count(array_filter($issues,static fn($x)=>(string)($x['severity']??'')==='critical'));
$high=count(array_filter($issues,static fn($x)=>(string)($x['severity']??'')==='high'));
AdminUi::header('صحة النظام والسجل الحي','health');echo AdminUi::flash();
?>
<section class="dashboard-welcome"><div><span class="eyebrow">RUNTIME AUDIT · <?=e(ReleaseInfo::VERSION)?></span><h2><?=$critical||$high?'توجد نقاط تحتاج تدخل':'الفحوص التشغيلية الأساسية مستقرة'?></h2><p>هذه الصفحة تقرأ قاعدة البيانات وسجل التشغيل الحاليين. وجود مفتاح يعني Configured فقط؛ الاختبارات الفعلية وحالة Worker هي الدليل التشغيلي.</p></div><div class="quick-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="run_worker"><input type="hidden" name="limit" value="2"><input type="hidden" name="return" value="/api/admin/health.php"><button class="btn">تشغيل Worker الآن</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="ramy_sync_authority"><input type="hidden" name="return" value="/api/admin/health.php"><button class="btn secondary">مزامنة صلاحيات رامي</button></form><a class="btn secondary" href="integrations.php">اختبارات الربط</a><a class="btn secondary" href="integration-health.php">مركز صحة التكاملات</a><a class="btn secondary" href="post-install-acceptance.php">Post-install Acceptance</a></div></section>

<div class="metric-grid metric-grid-4">
<?=AdminUi::stat('مشاكل حرجة',$critical,'من التحليل الحي')?>
<?=AdminUi::stat('مشاكل مرتفعة',$high,'تحتاج متابعة')?>
<?=AdminUi::stat('Jobs معلقة',(int)($worker['stuck_queued']??0),'أكثر من 10 دقائق')?>
<?=AdminUi::stat('Failed Jobs 24h',(int)($dash['jobs_failed_24h']??0),'من قاعدة البيانات')?>
<?=AdminUi::stat('Worker',!empty($worker['healthy'])?'Healthy':'Stale / Unknown',!empty($worker['heartbeat_at'])?AdminUi::date((string)$worker['heartbeat_at']):'لا يوجد heartbeat')?>
<?=AdminUi::stat('OpenRouter Primary',(int)($openrouter['primary_agents']??0).' / '.(int)($openrouter['active_agents']??0),'الوكلاء النشطون')?>
<?=AdminUi::stat('صلاحيات رامي',(int)($ramy['permissions_granted']??0).' / '.(int)($ramy['permissions_expected']??0),!empty($ramy['raw_secret_view'])?'تحذير: عرض الأسرار الخام مفعّل':'secrets.view محجوبة')?>
<?=AdminUi::stat('بحث وليد',!empty($walid['search_configured'])?'Configured':'Unavailable','المزود: '.((string)($walid['search_provider']??'')?:'—'))?>
<?=AdminUi::stat('فرص مفتوحة عربية',max(0,(int)($oq['open_total']??0)-(int)($oq['missing_title_ar']??0)),'من '.(int)($oq['open_total']??0).' · تفاصيل ناقصة '.(int)($oq['missing_details_ar']??0))?>
</div>

<?php if($issues):?><section class="card"><div class="card-title"><div><h2>الأخطاء والتشخيص المقترح</h2><span class="muted small">مرتبة حسب الشدة. الدليل مأخوذ من Runtime/DB وليس من حالة شكلية للوكيل.</span></div></div><div class="table-wrap"><table><thead><tr><th>الشدة</th><th>الكود</th><th>المشكلة</th><th>الدليل</th><th>الإصلاح</th></tr></thead><tbody><?php foreach($issues as $x):?><tr><td><?=AdminUi::badge((string)$x['severity'])?></td><td class="mono"><?=e($x['code'])?></td><td><b><?=e($x['title'])?></b></td><td><?=e($x['evidence'])?></td><td><?=e($x['fix'])?></td></tr><?php endforeach?></tbody></table></div></section><?php endif?>

<div class="grid">
<section class="card span-6"><div class="card-title"><h2>متطلبات البيئة</h2></div><dl class="kvs"><?php foreach($php as $k=>$v):?><dt><?=e(['version'=>'إصدار PHP','php_8_1_plus'=>'PHP 8.1+','curl'=>'cURL','openssl'=>'OpenSSL','pdo_mysql'=>'PDO MySQL','json'=>'JSON','mbstring'=>'دعم العربية'][$k]??$k)?></dt><dd><?=$k==='version'?e($v):AdminUi::badge($v?'verified':'failed')?></dd><?php endforeach?></dl></section>
<section class="card span-6"><div class="card-title"><h2>الخدمات — آخر اختبار فعلي</h2><a href="integrations.php">اختبار جديد</a></div><?php foreach((array)$audit['connection_tests'] as $t):if(isset($t['__query_error']))continue;?><div class="mini-item"><div class="grow"><b><?=e(AdminUi::provider((string)$t['provider_key']))?></b><small><?=e(AdminUi::date($t['created_at']??null))?><?=!empty($t['result_code'])?' · '.e(AdminUi::humanError((string)$t['result_code'])):''?></small></div><?=AdminUi::badge((string)$t['state'])?></div><?php endforeach?></section>
<section class="card span-6"><div class="card-title"><div><h2>وليد — المسار الفعلي</h2><span class="muted small">Agent → Job → Worker → Search → Buyer Intent → AI → Save</span></div><a href="opportunity-hunt.php">فتح صيد المشاريع</a></div><?php $wj=(array)($walid['last_job']??[]);$wr=(array)($walid['last_run']??[]);?><dl class="kvs"><dt>حالة الوكيل</dt><dd><?=AdminUi::badge((string)(($walid['agent']['status']??'unknown')))?></dd><dt>آخر Job</dt><dd><?=$wj?'#'.e((string)$wj['id']).' · '.AdminUi::badge((string)$wj['state']):'—'?></dd><dt>آخر خطأ Job</dt><dd><?=e(!empty($wj['error_code'])?AdminUi::humanError((string)$wj['error_code']):'—')?></dd><dt>آخر Search Run</dt><dd><?=$wr?'#'.e((string)$wr['id']).' · '.AdminUi::badge((string)$wr['state']):'—'?></dd><dt>Raw / Qualified / Review</dt><dd><?=e((string)((int)($wr['raw_found']??0)))?> / <?=e((string)((int)($wr['qualified_found']??0)))?> / <?=e((string)((int)($wr['review_found']??0)))?></dd><dt>Search Provider</dt><dd><?=e((string)($walid['search_provider']??'—'))?></dd></dl><?php $sum=(array)($walid['summary']??[]);if(!empty($sum['search_diagnostics'])||!empty($sum['warnings'])):?><details class="subtle top-gap"><summary>تشخيص آخر بحث</summary><pre class="json-box"><?=e(j(['search_diagnostics'=>array_slice((array)($sum['search_diagnostics']??[]),0,30),'warnings'=>array_slice((array)($sum['warnings']??[]),0,20)]))?></pre></details><?php endif?></section>
<section class="card span-6"><div class="card-title"><h2>المؤشرات التي تغذي الصفحة الرئيسية</h2><a href="index.php">الصفحة الرئيسية</a></div><dl class="kvs"><dt>نتائج وليد اليوم</dt><dd><?=e((string)($dash['raw_today']??0))?></dd><dt>فرص مؤهلة مفتوحة</dt><dd><?=e((string)($dash['qualified_open']??0))?></dd><dt>عروض نشطة</dt><dd><?=e((string)($dash['active_offers']??0))?></dd><dt>مشاريع أعمال مفتوحة</dt><dd><?=e((string)($dash['projects_open']??0))?></dd><dt>مهام نشطة</dt><dd><?=e((string)($dash['tasks_active']??0))?></dd><dt>وكلاء يعملون فعليًا</dt><dd><?=e((string)($dash['agents_working']??0))?></dd><dt>Queue / Running</dt><dd><?=e((string)($dash['jobs_queued']??0))?> / <?=e((string)($dash['jobs_running']??0))?></dd></dl></section>
</div>

<section class="card"><div class="card-title"><div><h2>System Errors</h2><span class="muted small">Exceptions المسجلة بواسطة المعالج المركزي. لا تعرض أسرارًا خامًا.</span></div></div><div class="table-wrap"><table class="compact"><thead><tr><th>المرجع</th><th>الصفحة</th><th>Class</th><th>الرسالة</th><th>الوقت</th></tr></thead><tbody><?php foreach((array)$audit['system_errors'] as $x):if(isset($x['__query_error']))continue;?><tr><td class="mono"><?=e($x['error_ref'])?></td><td class="mono"><?=e($x['request_uri']?:'—')?></td><td><?=e($x['error_class']?:'—')?></td><td><?=e(Security::redactSecrets((string)($x['error_message']??''),400))?></td><td><?=e(AdminUi::date($x['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section>

<div class="grid"><section class="card span-6"><div class="card-title"><h2>Failed / Waiting Jobs</h2></div><div class="table-wrap"><table class="compact"><thead><tr><th>#</th><th>النوع</th><th>الوكيل</th><th>الحالة</th><th>الخطأ</th><th>الوقت</th></tr></thead><tbody><?php foreach((array)$audit['failed_jobs'] as $x):if(isset($x['__query_error']))continue;?><tr><td>#<?=e((string)$x['id'])?></td><td><?=e(AdminUi::label((string)$x['kind']))?></td><td><?=e($x['agent_name']?:$x['agent_slug']?:'—')?></td><td><?=AdminUi::badge((string)$x['state'])?></td><td><?=e($x['error_code']?AdminUi::humanError((string)$x['error_code']):'—')?></td><td><?=e(AdminUi::date($x['updated_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card span-6"><div class="card-title"><h2>Audit — Failed / Blocked</h2></div><div class="table-wrap"><table class="compact"><thead><tr><th>#</th><th>العملية</th><th>النتيجة</th><th>الكيان</th><th>الوقت</th></tr></thead><tbody><?php foreach((array)$audit['audit_failures'] as $x):if(isset($x['__query_error']))continue;?><tr><td>#<?=e((string)$x['id'])?></td><td><?=e($x['action'])?></td><td><?=AdminUi::badge((string)$x['result'])?></td><td><?=e(($x['entity_type']?:'—').($x['entity_id']?' #'.$x['entity_id']:''))?></td><td><?=e(AdminUi::date($x['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section></div>

<section class="card"><div class="card-title"><h2>Webhook Failures</h2></div><div class="table-wrap"><table class="compact"><thead><tr><th>#</th><th>المزود</th><th>النوع</th><th>التوقيع</th><th>الخطأ</th><th>الوقت</th></tr></thead><tbody><?php foreach((array)$audit['webhook_failures'] as $x):if(isset($x['__query_error']))continue;?><tr><td>#<?=e((string)$x['id'])?></td><td><?=e(AdminUi::provider((string)$x['provider']))?></td><td><?=e(AdminUi::label((string)($x['event_type']?:'')))?></td><td><?=AdminUi::badge(!empty($x['signature_valid'])?'verified':'failed')?></td><td><?=e($x['error_code']?AdminUi::humanError((string)$x['error_code']):'—')?></td><td><?=e(AdminUi::date($x['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<?php AdminUi::footer();
