<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$provider=db()->query("SELECT * FROM providers WHERE provider_key='hostinger' LIMIT 1")->fetch()?:[];
$last=db()->query("SELECT * FROM project_scans ORDER BY id DESC LIMIT 1")->fetch()?:null;
$projects=db()->query("SELECT p.*,COUNT(DISTINCT pd.id) db_count FROM projects p LEFT JOIN project_databases pd ON pd.project_id=p.id AND pd.status='active' GROUP BY p.id ORDER BY FIELD(p.hosting_presence,'unavailable','removed','unknown','present'),p.name")->fetchAll();
$domains=db()->query("SELECT d.*,p.name project_name FROM project_domains d LEFT JOIN projects p ON p.id=d.project_id ORDER BY d.last_seen_at DESC,d.domain_name")->fetchAll();
$dbs=db()->query("SELECT d.*,p.name project_name,p.primary_domain FROM project_databases d JOIN projects p ON p.id=d.project_id WHERE d.status='active' ORDER BY p.name,d.db_name")->fetchAll();
$present=0;$unavailable=0;foreach($projects as $p){if(($p['hosting_presence']??'unknown')==='present')$present++;if(in_array(($p['hosting_presence']??''),['unavailable','removed'],true))$unavailable++;}
AdminUi::header('الاستضافة — Hostinger','hosting');echo AdminUi::flash();
?>
<div class="hero-strip"><div><span class="eyebrow">Technical Inventory</span><h2>فهرسة الاستضافة تحت إدارة رامي — وليد لا يستخدمها للبحث عن العملاء</h2><p>تربط الموقع بالدومين ومجلد الملفات وقاعدة البيانات وتحتفظ بالسجل التاريخي بدون حذف المشروع تلقائيًا إذا اختفى مؤقتًا.</p></div><div class="hero-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="hosting_inventory"><input type="hidden" name="return" value="/api/admin/hosting.php"><button class="btn btn-xl">فحص Hostinger الآن</button></form><a class="btn secondary" href="integrations.php">إدارة المفتاح</a></div></div>
<div class="metric-grid metric-grid-4"><?=AdminUi::stat('اتصال Hostinger',AdminUi::label($provider['status']??'untested'),($provider['enabled']??0)?'المزود مفعّل':'المزود موقوف')?><?=AdminUi::stat('مواقع موجودة',$present,'آخر Inventory')?><?=AdminUi::stat('دومينات',count($domains),'مرتبطة أو متاحة')?><?=AdminUi::stat('قواعد مكتشفة',count($dbs),'مرتبطة بالمشاريع')?></div>
<div class="grid"><section class="card span-4"><div class="card-title"><h2>آخر فحص</h2></div><?php if(!$last):?><?=AdminUi::empty('لا يوجد فحص مسجل.')?><?php else:$summary=json_decode((string)($last['summary_json']??'{}'),true)?:[];?><dl class="kvs"><dt>الحالة</dt><dd><?=AdminUi::badge($last['state'])?></dd><dt>مواقع</dt><dd><?=(int)$last['websites_found']?></dd><dt>مشاريع محدثة</dt><dd><?=(int)$last['projects_updated']?></dd><dt>دومينات</dt><dd><?=(int)$last['domains_updated']?></dd><dt>قواعد بيانات</dt><dd><?=(int)$last['databases_found']?></dd><dt>انتهى</dt><dd><?=e(AdminUi::date($last['completed_at']))?></dd></dl><?php if(!empty($summary['warnings'])):?><details class="subtle"><summary>تحذيرات الفحص (<?=count($summary['warnings'])?>)</summary><pre class="json-box"><?=e(j($summary['warnings']))?></pre></details><?php endif;endif?></section>
<section class="card span-8"><div class="card-title"><div><h2>المواقع والمشاريع</h2><span class="muted small">الحالة التقنية منفصلة عن مرحلة المشروع التجارية.</span></div></div><div class="table-wrap"><table><thead><tr><th>المشروع</th><th>الدومين</th><th>المجلد</th><th>التقنية</th><th>وجوده</th><th>قواعد</th><th>آخر مشاهدة</th><th></th></tr></thead><tbody><?php foreach($projects as $p):?><tr><td><?=e($p['name'])?></td><td><?=e($p['primary_domain']?:'—')?></td><td class="mono small"><?=e($p['document_root']?:'—')?></td><td><?=e($p['technology']?:'—')?></td><td><?=AdminUi::badge((string)($p['hosting_presence']??'unknown'))?></td><td><?=(int)$p['db_count']?></td><td><?=e(AdminUi::date($p['last_seen_hosting_at']??$p['last_scan_at']))?></td><td><a class="link" href="project.php?id=<?=$p['id']?>">مساحة المشروع</a></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card span-7"><div class="card-title"><h2>قواعد البيانات المكتشفة</h2></div><div class="table-wrap"><table><thead><tr><th>المشروع</th><th>الدومين</th><th>قاعدة البيانات</th><th>المضيف</th><th>الحالة</th></tr></thead><tbody><?php foreach($dbs as $d):?><tr><td><?=e($d['project_name'])?></td><td><?=e($d['primary_domain']?:'—')?></td><td class="mono"><?=e($d['db_name'])?></td><td><?=e($d['db_host']?:'localhost')?></td><td><?=AdminUi::badge((string)$d['status'])?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card span-5"><div class="card-title"><h2>الدومينات</h2></div><div class="table-wrap"><table><thead><tr><th>الدومين</th><th>المشروع</th><th>الحالة</th><th>آخر مشاهدة</th></tr></thead><tbody><?php foreach($domains as $d):?><tr><td><?=e($d['domain_name'])?></td><td><?=e($d['project_name']?:'متاح لمشروع جديد')?></td><td><?=AdminUi::badge($d['status'])?></td><td><?=e(AdminUi::date($d['last_seen_at']))?></td></tr><?php endforeach?></tbody></table></div></section></div>
<?php AdminUi::footer();
