<?php
declare(strict_types=1);
final class HttpClient {
    public static function json(string $method,string $url,array $headers=[],?array $body=null,int $timeout=35): array {
        $url=Security::publicUrl($url);$ch=function_exists('curl_init')?curl_init($url):false;if(!$ch)throw new RuntimeException(function_exists('curl_init')?'curl_init_failed':'curl_extension_missing');
        $h=['Accept: application/json'];foreach($headers as $k=>$v)$h[]=is_int($k)?$v:$k.': '.$v;
        $opts=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$h,CURLOPT_CONNECTTIMEOUT=>12,CURLOPT_TIMEOUT=>$timeout,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_REDIR_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS];
        if($body!==null){$payload=j($body);$h[]='Content-Type: application/json';$opts[CURLOPT_HTTPHEADER]=$h;$opts[CURLOPT_POSTFIELDS]=$payload;}
        curl_setopt_array($ch,$opts);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);
        if($raw===false)throw new RuntimeException('network_error:'.$err);$data=$raw===''?[]:json_decode((string)$raw,true);if(!is_array($data))$data=['raw'=>(string)$raw];
        if($status<200||$status>=300)throw new RuntimeException('http_'.$status.':'.pb_substr((string)($data['error']['message']??$data['message']??''),0,300));return $data;
    }
    public static function jsonLoopback(string $method,string $url,array $headers=[],?array $body=null,int $timeout=35): array {
        $p=parse_url(trim($url));$host=strtolower((string)($p['host']??''));$scheme=strtolower((string)($p['scheme']??''));
        if(!in_array($scheme,['http','https'],true)||!in_array($host,['127.0.0.1','localhost','::1'],true))throw new RuntimeException('loopback_url_not_allowed');
        $ch=function_exists('curl_init')?curl_init($url):false;if(!$ch)throw new RuntimeException(function_exists('curl_init')?'curl_init_failed':'curl_extension_missing');
        $h=['Accept: application/json'];foreach($headers as $k=>$v)$h[]=is_int($k)?$v:$k.': '.$v;
        $opts=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$h,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>$timeout,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS];
        if($body!==null){$payload=j($body);$h[]='Content-Type: application/json';$opts[CURLOPT_HTTPHEADER]=$h;$opts[CURLOPT_POSTFIELDS]=$payload;}
        curl_setopt_array($ch,$opts);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);
        if($raw===false)throw new RuntimeException('network_error:'.$err);$data=$raw===''?[]:json_decode((string)$raw,true);if(!is_array($data))$data=['raw'=>(string)$raw];
        if($status<200||$status>=300)throw new RuntimeException('http_'.$status.':'.pb_substr((string)($data['error']['message']??$data['message']??''),0,300));return $data;
    }
    public static function form(string $method,string $url,array $headers,array $form,int $timeout=35): array {
        $url=Security::publicUrl($url);$ch=function_exists('curl_init')?curl_init($url):false;if(!$ch)throw new RuntimeException(function_exists('curl_init')?'curl_init_failed':'curl_extension_missing');$h=['Accept: application/json','Content-Type: application/x-www-form-urlencoded'];foreach($headers as $x)$h[]=$x;
        curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$h,CURLOPT_POSTFIELDS=>http_build_query($form,'','&',PHP_QUERY_RFC3986),CURLOPT_CONNECTTIMEOUT=>12,CURLOPT_TIMEOUT=>$timeout,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS]);
        $raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('network_error:'.$err);$data=json_decode((string)$raw,true);if(!is_array($data))$data=['raw'=>(string)$raw];if($status<200||$status>=300)throw new RuntimeException('http_'.$status.':'.pb_substr((string)($data['error']['message']??$data['message']??''),0,250));return $data;
    }
    public static function raw(string $method,string $url,array $headers=[],?string $body=null,int $timeout=60):array{
        $url=Security::publicUrl($url);$ch=function_exists('curl_init')?curl_init($url):false;if(!$ch)throw new RuntimeException(function_exists('curl_init')?'curl_init_failed':'curl_extension_missing');$h=[];foreach($headers as $k=>$v)$h[]=is_int($k)?$v:$k.': '.$v;$opts=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$h,CURLOPT_CONNECTTIMEOUT=>12,CURLOPT_TIMEOUT=>$timeout,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS];if($body!==null)$opts[CURLOPT_POSTFIELDS]=$body;curl_setopt_array($ch,$opts);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$type=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('network_error:'.$err);if($status<200||$status>=300)throw new RuntimeException('http_'.$status.':'.pb_substr((string)$raw,0,300));return ['body'=>(string)$raw,'status'=>$status,'content_type'=>$type];
    }
    public static function multipart(string $method,string $url,array $headers,array $fields,int $timeout=90):array{
        $url=Security::publicUrl($url);$ch=function_exists('curl_init')?curl_init($url):false;if(!$ch)throw new RuntimeException(function_exists('curl_init')?'curl_init_failed':'curl_extension_missing');$h=['Accept: application/json'];foreach($headers as $k=>$v)$h[]=is_int($k)?$v:$k.': '.$v;curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$h,CURLOPT_POSTFIELDS=>$fields,CURLOPT_CONNECTTIMEOUT=>12,CURLOPT_TIMEOUT=>$timeout,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('network_error:'.$err);$data=$raw===''?[]:json_decode((string)$raw,true);if(!is_array($data))$data=['raw'=>(string)$raw];if($status<200||$status>=300)throw new RuntimeException('http_'.$status.':'.pb_substr((string)($data['error']['message']??$data['message']??$raw),0,300));return $data;
    }

    private static function resolveRedirect(string $base,string $location):string{
        if(preg_match('#^https?://#i',$location))return $location;$p=parse_url($base);if(!is_array($p)||empty($p['host']))throw new RuntimeException('invalid_redirect');$scheme=$p['scheme']??'https';$port=isset($p['port'])?':'.$p['port']:'';if(str_starts_with($location,'//'))return $scheme.':'.$location;if(str_starts_with($location,'/'))return $scheme.'://'.$p['host'].$port.$location;$dir=preg_replace('#/[^/]*$#','/',$p['path']??'/');return $scheme.'://'.$p['host'].$port.$dir.$location;
    }
    private static function oneProbe(string $url,int $timeout,int $maxBytes,bool $head=false):array{
        Security::publicUrl($url);$body='';$headers=[];$location='';$ch=function_exists('curl_init')?curl_init($url):false;if(!$ch)throw new RuntimeException(function_exists('curl_init')?'curl_init_failed':'curl_extension_missing');
        curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>false,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>$timeout,CURLOPT_USERAGENT=>'Mozilla/5.0 (compatible; PerseBayt/7.0; +https://persebayt.com/)',CURLOPT_HTTPHEADER=>['Accept: text/html,application/xhtml+xml,application/json,application/xml;q=0.9,*/*;q=0.8','Accept-Language: ar,en-US;q=0.8,en;q=0.7'],CURLOPT_ENCODING=>'',CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_NOBODY=>$head,CURLOPT_HEADERFUNCTION=>static function($ch,$line)use(&$headers,&$location){$len=strlen($line);$p=strpos($line,':');if($p!==false){$k=strtolower(trim(substr($line,0,$p)));$v=trim(substr($line,$p+1));if($k!==''){$headers[$k]=$v;if($k==='location')$location=$v;}}return $len;},CURLOPT_WRITEFUNCTION=>static function($ch,$chunk)use(&$body,$maxBytes){$remain=$maxBytes-strlen($body);if($remain>0)$body.=substr($chunk,0,$remain);return strlen($chunk);}]);
        $ok=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$type=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);$err=curl_error($ch);curl_close($ch);return ['ok'=>$ok!==false,'status'=>$status,'content_type'=>$type,'body'=>$body,'error'=>$err,'headers'=>$headers,'location'=>$location,'sha256'=>hash('sha256',$body)];
    }
    public static function probeMethod(string $method,string $url,int $timeout=15,int $maxBytes=65536,array $headers=[]):array{
        $method=strtoupper(trim($method));if(!in_array($method,['GET','HEAD','OPTIONS'],true))throw new RuntimeException('probe_method_not_allowed');$url=Security::publicUrl($url);$body='';$respHeaders=[];$ch=function_exists('curl_init')?curl_init($url):false;if(!$ch)throw new RuntimeException(function_exists('curl_init')?'curl_init_failed':'curl_extension_missing');$h=['Accept: */*'];foreach($headers as $k=>$v)$h[]=is_int($k)?$v:$k.': '.$v;curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>false,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$h,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>$timeout,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_HEADERFUNCTION=>static function($ch,$line)use(&$respHeaders){$len=strlen($line);$p=strpos($line,':');if($p!==false){$k=strtolower(trim(substr($line,0,$p)));$v=trim(substr($line,$p+1));if($k!=='')$respHeaders[$k]=$v;}return $len;},CURLOPT_WRITEFUNCTION=>static function($ch,$chunk)use(&$body,$maxBytes){$remain=$maxBytes-strlen($body);if($remain>0)$body.=substr($chunk,0,$remain);return strlen($chunk);}]);$ok=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);return ['ok'=>$ok!==false,'status'=>$status,'headers'=>$respHeaders,'body'=>$body,'sha256'=>hash('sha256',$body),'error'=>$err,'final_url'=>$url];
    }
    public static function probe(string $url,int $timeout=20,int $maxBytes=131072): array {
        $current=Security::publicUrl($url);$last=[];$deadline=microtime(true)+max(1,$timeout);for($i=0;$i<=4;$i++){$remaining=(int)ceil($deadline-microtime(true));if($remaining<=0){$last=['ok'=>false,'status'=>0,'content_type'=>'','body'=>'','error'=>'probe_time_budget_exceeded','headers'=>[],'location'=>''];break;}$last=self::oneProbe($current,max(1,min($timeout,$remaining)),$maxBytes,false);if(!in_array((int)$last['status'],[301,302,303,307,308],true)||$last['location']==='')break;$next=self::resolveRedirect($current,(string)$last['location']);Security::publicUrl($next);$current=$next;}
        unset($last['location']);$last['final_url']=$current;return $last;
    }
    public static function head(string $url,int $timeout=15): array {$current=Security::publicUrl($url);$last=[];$deadline=microtime(true)+max(1,$timeout);for($i=0;$i<=4;$i++){$remaining=(int)ceil($deadline-microtime(true));if($remaining<=0){$last=['status'=>0,'error'=>'head_time_budget_exceeded','headers'=>[],'location'=>''];break;}$last=self::oneProbe($current,max(1,min($timeout,$remaining)),0,true);if(!in_array((int)$last['status'],[301,302,303,307,308],true)||$last['location']==='')break;$current=Security::publicUrl(self::resolveRedirect($current,(string)$last['location']));}return ['status'=>$last['status']??0,'final_url'=>$current,'error'=>$last['error']??'','headers'=>$last['headers']??[]];}
}
