<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$providers=db()->query('SELECT * FROM providers ORDER BY kind,provider_key')->fetchAll();
$by=[];foreach($providers as $p)$by[$p['provider_key']]=$p;
$channels=db()->query('SELECT * FROM communication_channels ORDER BY id')->fetchAll();
$tests=db()->query('SELECT * FROM connection_tests ORDER BY id DESC LIMIT 80')->fetchAll();
$latestTests=[];foreach($tests as $t){$k=(string)$t['provider_key'];if(!isset($latestTests[$k]))$latestTests[$k]=$t;}
$presence=SecretVault::presence();
$has=static fn(string $k):string=>!empty($presence[$k])?'محفوظ ومشفر':'مش متظبط';
$state=static function(string $key)use($by):string{$p=$by[$key]??null;return $p?($p['enabled']?$p['status']:'disabled'):'untested';};
$connectionInfo=static function(string $key)use($latestTests,$state):string{
    $t=$latestTests[$key]??null;$s=(string)($t['state']??$state($key));
    $when=$t?AdminUi::date($t['created_at']??null):'لم يتم الاختبار بعد';
    $raw=$t?trim((string)($t['result_code']??'')):'';$code=$t?AdminUi::humanError($raw):'اضغط اختبار الاتصال للتأكد فعليًا';
    $tech='';if($raw!==''&&$code==='حصل خطأ فني غير متوقع. راجع سجل النظام أو حالة الربط.')$tech=' · الكود: '.pb_substr(Security::redactSecrets($raw),0,135);
    return '<div class="settings-note" style="margin:10px 0"><b>حالة الاتصال:</b> '.AdminUi::badge($s).' <span class="muted small">آخر اختبار: '.e($when).' · '.e($code.$tech).'</span></div>';
};
$waDiag=['pending'=>0,'waiting'=>0,'failed'=>0,'latest_failure'=>'','latest_failure_at'=>''];
try{$waDiag['pending']=(int)db()->query("SELECT COUNT(*) FROM whatsapp_pending_messages WHERE state='pending' AND sent_at IS NULL")->fetchColumn();$waDiag['waiting']=(int)db()->query("SELECT COUNT(*) FROM whatsapp_pending_messages WHERE state='waiting_reply' AND sent_at IS NULL")->fetchColumn();$waDiag['failed']=(int)db()->query("SELECT COUNT(*) FROM whatsapp_pending_messages WHERE state='failed' AND sent_at IS NULL")->fetchColumn();$q=db()->query("SELECT details_json,created_at FROM communication_events WHERE event_type='delivery_status' AND state='failed' ORDER BY id DESC LIMIT 1");$lf=$q->fetch();if($lf){$raw=json_decode((string)$lf['details_json'],true)?:[];$waDiag['latest_failure']=WhatsAppPolicy::humanFailure(['raw'=>$raw]);$waDiag['latest_failure_at']=(string)$lf['created_at'];}}catch(Throwable){}
$searchProvider=(string)setting('opportunities.search_provider','auto');
$openRouterMeta=OpenRouterService::activeKeyMeta();
$customProviders=ProviderCenterService::customProviders();
$editCustom=null;$editKey=trim((string)($_GET['edit_provider']??''));if($editKey!==''){try{$x=ProviderCenterService::get($editKey);if((($x['config']['managed_by']??'')==='provider_center'))$editCustom=$x;}catch(Throwable){$editCustom=null;}}
AdminUi::header('المفاتيح والربط','integrations');echo AdminUi::flash();
?>


<section class="card" style="margin-bottom:16px"><div class="card-title"><div><h2>مركز مزودي الذكاء والبحث</h2><span class="muted small">كل وكيل يختار Primary + Fallback من صفحته. المفاتيح تُحفظ مشفرة ولا تدخل الذاكرة.</span></div><a class="link" href="team.php">صفحات الوكلاء</a></div><div class="provider-grid ai-provider-grid">
<div class="subtle"><div class="card-title"><div><b>OpenRouter — Free Models Router</b><small class="muted block">بوابة OpenAI-Compatible موحدة للوكلاء. الافتراضي openrouter/free ويختار نموذجًا مجانيًا مناسبًا لخصائص الطلب.</small></div><?=AdminUi::badge($state('openrouter'))?></div><div class="settings-note"><b>المفتاح النشط:</b> <?=!empty($openRouterMeta['present'])?'Fingerprint '.e((string)$openRouterMeta['fingerprint']).' · طول '.(int)$openRouterMeta['length'].' حرف':'لا يوجد مفتاح نشط'?><?php if(!empty($openRouterMeta['vault_mtime'])):?><span class="muted small"> · آخر تعديل Vault: <?=e(date('Y-m-d H:i:s',(int)$openRouterMeta['vault_mtime']))?></span><?php endif?><br><span class="muted small">أي نسخة كاملة قديمة من نوع WITH_CURRENT_CONFIG تحتوي Vault قديمًا وقد تعيد المفتاح القديم إذا رفعتها فوق الموقع. استخدم Patch بدون أسرار عند تحديث الكود بعد تدوير المفاتيح.</span></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><input type="hidden" name="openrouter_form" value="1"><div class="field"><label>OpenRouter API Key <span class="secret-state"><?=e($has('providers.openrouter.api_key'))?></span></label><input type="password" name="providers__openrouter__api_key" autocomplete="new-password" placeholder="سيبه فاضي للحفاظ على المفتاح الحالي"></div><div class="field"><label>Model</label><input name="providers__openrouter__model" value="<?=e((string)SecretVault::get('providers.openrouter.model',OpenRouterService::DEFAULT_MODEL))?>" placeholder="openrouter/free"></div><label class="check-row"><input type="checkbox" name="openrouter_strict_privacy" value="1" <?=OpenRouterService::dataCollectionPolicy()==='deny'?'checked':''?>> Strict privacy: data_collection=deny (may reduce free endpoints)</label><label class="check-row"><input type="checkbox" name="openrouter_make_primary" value="1" checked> اجعل OpenRouter Primary لكل الوكلاء الحاليين والجدد، واحتفظ بالمزودات الأخرى كـFallback</label><button class="btn full-width">حفظ وربط OpenRouter</button></form><?=$connectionInfo('openrouter')?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="openrouter"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار OpenRouter</button></form><form method="post" action="action.php" onsubmit="return confirm('حذف مفتاح OpenRouter النشط من الخزنة؟ لن يتم حذف Snapshots القديمة لكنها لا تعمل تلقائيًا.');"><?=AdminUi::csrf()?><input type="hidden" name="action" value="openrouter_clear"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary" type="submit">حذف المفتاح النشط</button></form></div></div>
<?php foreach([
 ['gemini','Google Gemini','providers.gemini.api_key','providers.gemini.model','gemini-2.5-flash'],
 ['anthropic','Anthropic Claude','providers.anthropic.api_key','providers.anthropic.model','claude-sonnet-4-5'],
 ['groq','Groq','providers.groq.api_key','providers.groq.model','llama-3.3-70b-versatile']
] as $ai):?>
<div class="subtle"><div class="card-title"><b><?=e($ai[1])?></b><?=AdminUi::badge($state($ai[0]))?></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>API Key <span class="secret-state"><?=e($has($ai[2]))?></span></label><input type="password" name="<?=e(str_replace('.','__',$ai[2]))?>" autocomplete="new-password"></div><div class="field"><label>Model</label><input name="<?=e(str_replace('.','__',$ai[3]))?>" placeholder="<?=e($ai[4])?>"></div><button class="btn secondary full-width">حفظ وربط</button></form><?=$connectionInfo($ai[0])?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="<?=e($ai[0])?>"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار الاتصال</button></form></div></div>
<?php endforeach?>
<div class="settings-note" style="grid-column:1/-1"><b>Gemini:</b> لو موديل محفوظ قديم رجع 404/غير مدعوم، النظام يجرب موديلات Flash الحديثة تلقائيًا ويحفظ أول موديل ينجح بدل تعطيل رامي.</div>
<div class="subtle"><div class="card-title"><b>Ollama / OpenAI Compatible</b><?=AdminUi::badge($state('ollama'))?></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Base URL</label><input name="providers__ollama__base_url" placeholder="http://127.0.0.1:11434/v1"></div><div class="field"><label>Model</label><input name="providers__ollama__model" placeholder="اسم الموديل المحلي"></div><button class="btn secondary full-width">حفظ الربط</button></form><?=$connectionInfo('ollama')?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="ollama"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار الاتصال</button></form></div></div>
<div class="subtle"><div class="card-title"><div><b>مزود البحث العام لوليد</b><small class="muted block">Auto يستخدم Serper/Brave/Tavily ثم OpenAI Web Search عند توفره. DuckDuckGo/Bing غير موثوقين وموقوفان كـfallback تلقائي في هذه القاعدة. يمكن اختيار OpenRouter Web Search يدويًا، لكنه قد يستهلك رصيد بحث حتى لو الموديل مجاني.</small></div><?=AdminUi::badge(($latestTests['web_search']['state']??'untested'))?></div>
<form method="post" action="action.php" style="margin-bottom:10px"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_search_provider"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>طريقة البحث</label><select name="opportunities__search_provider"><?php foreach(['auto'=>'Auto — أفضل مزود متاح','openai_web'=>'OpenAI Web Search — مفتاح OpenAI الحالي','openrouter_web'=>'OpenRouter Web Search — اختياري وقد يستهلك رصيد بحث','duckduckgo'=>'DuckDuckGo — يدوي فقط','bing_rss'=>'Bing RSS — يدوي فقط','serper'=>'Serper / Google','brave'=>'Brave Search','tavily'=>'Tavily',''=>'المصادر المضافة فقط'] as $v=>$l):?><option value="<?=e($v)?>" <?=$searchProvider===$v?'selected':''?>><?=e($l)?></option><?php endforeach?></select></div><button class="btn secondary full-width">حفظ طريقة البحث</button></form>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Serper Key <span class="secret-state"><?=e($has('sources.serper.api_key'))?></span></label><input type="password" name="sources__serper__api_key"></div><div class="field"><label>Brave Key <span class="secret-state"><?=e($has('sources.brave.api_key'))?></span></label><input type="password" name="sources__brave__api_key"></div><div class="field"><label>Tavily Key <span class="secret-state"><?=e($has('sources.tavily.api_key'))?></span></label><input type="password" name="sources__tavily__api_key"></div><button class="btn secondary full-width">حفظ مفاتيح البحث</button></form><?=$connectionInfo('web_search')?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="web_search"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار البحث الآن</button></form></div></div>
</div></section>

<section class="card" style="margin:16px 0"><div class="card-title"><div><h2>إضافة مزود جديد بدون برمجة</h2><span class="muted small">أضف مزود AI متوافق مع OpenAI API أو سجّل Connector لموقع/Meta/متصفح/وسائط/تخزين. مفاتيح API تحفظ في SecretVault، ومزود AI يظهر تلقائيًا داخل Primary/Fallback للوكلاء.</span></div><a class="btn secondary small-btn" href="provider-chat.php">تجربة دردشة</a></div>
<form method="post" action="action.php" class="subtle"><?=AdminUi::csrf()?><input type="hidden" name="action" value="provider_custom_save"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="form-row"><div class="field"><label>Provider Key</label><input name="provider_key" required value="<?=e((string)($editCustom['provider_key']??''))?>" placeholder="مثال: my_ai" <?=$editCustom?'readonly':''?>></div><div class="field"><label>الاسم الظاهر</label><input name="label" required value="<?=e((string)($editCustom['label']??''))?>" placeholder="My AI Provider"></div><div class="field"><label>النوع</label><select name="kind"><?php foreach(['ai'=>'AI','browser'=>'متصفح','media'=>'صور / فيديو','social'=>'Social / Meta','messaging'=>'رسائل','voice'=>'مكالمات / صوت','storage'=>'تخزين','hosting'=>'استضافة','generic'=>'موقع / Connector عام'] as $kv=>$kl):?><option value="<?=e($kv)?>" <?=($editCustom['kind']??'ai')===$kv?'selected':''?>><?=e($kl)?></option><?php endforeach?></select></div></div><div class="form-row"><div class="field"><label>Base URL</label><input type="url" name="base_url" value="<?=e((string)($editCustom['config']['base_url']??''))?>" placeholder="https://api.example.com/v1"></div><div class="field"><label>API Key</label><input type="password" name="api_key" autocomplete="new-password" placeholder="يحفظ مشفرًا"></div><div class="field"><label>Model الافتراضي — لمزود AI</label><input name="model" value="<?=e((string)($editCustom?SecretVault::get('providers.'.$editCustom['provider_key'].'.model',''):''))?>" placeholder="model-name"></div></div><div class="field"><label>نماذج إضافية</label><textarea name="models" rows="2" placeholder="model-a, model-b"><?=e(implode("\n",(array)($editCustom['config']['models']??[])))?></textarea></div><div class="field"><label>ملاحظات واستخدام المزود</label><textarea name="notes" rows="2"><?=e((string)($editCustom['config']['notes']??''))?></textarea></div><label class="check-row"><input type="checkbox" name="enabled" value="1" <?=!$editCustom||!empty($editCustom['enabled'])?'checked':''?>> تشغيل المزود فورًا</label><button class="btn">إضافة / تحديث المزود</button></form>
<?php if($customProviders):?><div class="provider-grid ai-provider-grid" style="margin-top:14px"><?php foreach($customProviders as $cp):$cc=(array)($cp['config']??[]);?><div class="subtle"><div class="card-title"><div><b><?=e($cp['label'])?></b><small class="muted block"><?=e((string)$cp['kind'])?> · <span class="mono"><?=e($cp['provider_key'])?></span></small></div><?=AdminUi::badge($cp['enabled']?$cp['status']:'disabled')?></div><div class="small muted">Base: <?=e((string)($cc['base_url']??'—'))?> · Models: <?=count((array)($cc['models']??[]))?></div><div class="provider-actions" style="margin-top:10px"><a class="btn secondary small-btn" href="integrations.php?edit_provider=<?=rawurlencode((string)$cp['provider_key'])?>">تعديل</a><?php if($cp['kind']==='ai'):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="<?=e($cp['provider_key'])?>"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary small-btn">اختبار</button></form><a class="btn secondary small-btn" href="provider-chat.php?provider=<?=rawurlencode((string)$cp['provider_key'])?>">دردشة</a><?php endif?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="provider_custom_toggle"><input type="hidden" name="provider_key" value="<?=e($cp['provider_key'])?>"><input type="hidden" name="enabled" value="<?=$cp['enabled']?0:1?>"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary small-btn"><?=$cp['enabled']?'إيقاف':'تشغيل'?></button></form></div></div><?php endforeach?></div><?php endif?>
</section>

<div class="provider-grid">
<section class="card provider-card"><div class="card-title"><div class="provider-meta"><div class="provider-logo">ذ</div><div><h2>OpenAI — ذكاء رامي والفريق</h2><span class="muted small">الموديل الأساسي للوكلاء والتحليل</span></div></div><?=AdminUi::badge($state('openai'))?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php">
<div class="field"><label>مفتاح OpenAI <span class="secret-state"><?=e($has('ai.api_key'))?></span></label><input type="password" name="ai__api_key" autocomplete="new-password" placeholder="سيبه فاضي للحفاظ على المفتاح الحالي"></div>
<div class="field"><label>اسم الموديل</label><input name="ai__model" placeholder="مثال: gpt-5.6"></div><button class="btn full-width">حفظ إعدادات OpenAI</button></form>
<?=$connectionInfo('openai')?>
<div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="openai"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار الاتصال</button></form></div></section>

<section class="card provider-card"><div class="card-title"><div class="provider-meta"><div class="provider-logo">☁</div><div><h2>Hostinger — الاستضافة والمشاريع</h2><span class="muted small">المواقع والملفات وقواعد البيانات والدومينات</span></div></div><?=AdminUi::badge($state('hostinger'))?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>مفتاح Hostinger <span class="secret-state"><?=e($has('hostinger.api_token'))?></span></label><input type="password" name="hostinger__api_token" autocomplete="new-password" placeholder="سيبه فاضي للحفاظ على المفتاح الحالي"></div><button class="btn full-width">حفظ مفتاح Hostinger</button></form>
<?=$connectionInfo('hostinger')?>
<div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="hostinger"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار الاستضافة</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="hosting_inventory"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">فهرسة Hostinger</button></form></div></section>

<section class="card provider-card"><div class="card-title"><div class="provider-meta"><div class="provider-logo">و</div><div><h2>Meta / WhatsApp</h2><span class="muted small">إرسال واستقبال أوامر المالك ورسائل العملاء</span></div></div><?=AdminUi::badge($state('meta_whatsapp'))?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php">
<div class="form-row"><div class="field"><label>مفتاح الوصول <span class="secret-state"><?=e($has('meta.access_token'))?></span></label><input type="password" name="meta__access_token" autocomplete="new-password"></div><div class="field"><label>رقم تعريف واتساب</label><input name="meta__phone_number_id" placeholder="رقم هاتف واتساب داخل Meta"></div></div>
<div class="form-row"><div class="field"><label>سر التطبيق <span class="secret-state"><?=e($has('meta.app_secret'))?></span></label><input type="password" name="meta__app_secret" autocomplete="new-password"></div><div class="field"><label>رمز التحقق <span class="secret-state"><?=e($has('meta.verify_token'))?></span></label><input type="password" name="meta__verify_token" autocomplete="new-password"></div></div>
<div class="field"><label>إصدار واجهة Meta</label><input name="meta__graph_version" placeholder="مثال: v23.0"></div>
<div class="form-row"><div class="field"><label>قالب افتتاح العملاء المعتمد</label><input name="whatsapp__customer_template_name" value="<?=e((string)setting('whatsapp.customer_template_name',''))?>" placeholder="مثال: elmetr_first_contact"><small class="muted">اسم قالب Approved مخصص من حساب الشركة بدون متغيرات. hello_world وsample/demo محظورة على رقم الإنتاج.</small></div><div class="field"><label>لغة القالب</label><input name="whatsapp__customer_template_language" value="<?=e((string)setting('whatsapp.customer_template_language','ar'))?>" placeholder="ar"><small class="muted">استخدم كود اللغة المطابق للقالب في Meta مثل ar أو en_US.</small></div></div>
<button class="btn full-width">حفظ إعدادات واتساب</button></form>
<div class="settings-note" style="margin:10px 0"><b>WhatsApp للعملاء — Company OS 7.0:</b> رامي وهو بيرد عليك لا يثبت إن بدء محادثة عميل جديد شغال؛ دول مساران مختلفان. داخل نافذة 24 ساعة يمكن إرسال نص عادي، وخارجها يلزم قالب Approved. اختبار واتساب أدناه يفحص الآن <b>جاهزية بدء محادثة العملاء</b> وليس رقم الهاتف فقط، ويكشف صلاحية إدارة القوالب أو القالب غير المعتمد. <span class="muted small">WABA: <?=e((string)(setting('meta.waba_id','')?:'غير معروف بعد'))?> · القالب: <?=e((string)(setting('whatsapp.customer_template_name','')?:setting('whatsapp.template_submission_name','غير محدد')))?> · حالة القالب: <?=e((string)(setting('whatsapp.template_submission_state','غير مُرسل')))?> · آخر تحقق تسليم للقالب: <?=e(AdminUi::date(setting('whatsapp.template_verified_delivery_at','')))?> · آخر فحص تلقائي: <?=e(AdminUi::date(setting('whatsapp.last_auto_recovery_at','')))?> · الطابور: <?=e((string)$waDiag['pending'])?> منتظر / <?=e((string)$waDiag['waiting'])?> في انتظار رد / <?=e((string)$waDiag['failed'])?> فشل قابل للمراجعة.</span><?php if($waDiag['latest_failure']!==''):?><div class="small" style="margin-top:8px"><b>آخر فشل تسليم:</b> <?=e($waDiag['latest_failure'])?><?= $waDiag['latest_failure_at']!==''?' · '.e(AdminUi::date($waDiag['latest_failure_at'])):'' ?></div><?php endif?></div>
<p class="secret-hint">رابط الاستقبال: <span class="mono"><?=e((string)config('app.base_url').'/meta/webhook')?></span> · Webhook هو مصدر حقيقة sent / delivered / read / failed؛ قبول Meta الأولي لا يُحسب وصولًا.</p>
<?=$connectionInfo('meta_whatsapp')?>
<div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="meta_whatsapp"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار بدء محادثة العملاء</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="whatsapp_repair"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn">تشخيص وإصلاح WhatsApp</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="whatsapp_template_test"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار قالب الافتتاح على رقمي</button></form></div></section>

<section class="card provider-card"><div class="card-title"><div class="provider-meta"><div class="provider-logo">☎</div><div><h2>Twilio — رسائل ومكالمات</h2><span class="muted small">رسائل نصية ومكالمات صوتية وربط واتساب عند تفعيله</span></div></div><?=AdminUi::badge($state('twilio'))?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><input type="hidden" name="enable_twilio" value="1">
<div class="form-row"><div class="field"><label>رقم الحساب <span class="secret-state"><?=e($has('twilio.account_sid'))?></span></label><input name="twilio__account_sid"></div><div class="field"><label>مفتاح المصادقة <span class="secret-state"><?=e($has('twilio.auth_token'))?></span></label><input type="password" name="twilio__auth_token" autocomplete="new-password"></div></div>
<div class="field"><label>رقم الرسائل</label><input name="twilio__sms_from"></div><div class="field"><label>رقم المكالمات</label><input name="twilio__voice_from"></div><div class="field"><label>رقم واتساب</label><input name="twilio__whatsapp_from"></div><button class="btn full-width">حفظ وتشغيل Twilio</button></form>
<?=$connectionInfo('twilio')?>
<div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="twilio"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار Twilio</button></form></div></section>

<section class="card provider-card"><div class="card-title"><div class="provider-meta"><div class="provider-logo">↗</div><div><h2>ربط رسائل خارجي</h2><span class="muted small">لأي خدمة رسائل عندها مفتاح ربط ورابط استقبال</span></div></div><?=AdminUi::badge($state('generic_bridge'))?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><input type="hidden" name="enable_generic_message" value="1"><div class="field"><label>رابط الإرسال</label><input type="url" name="connections__generic_message__url"></div><div class="field"><label>مفتاح الإرسال <span class="secret-state"><?=e($has('connections.generic_message.token'))?></span></label><input type="password" name="connections__generic_message__token" autocomplete="new-password"></div><div class="field"><label>سر الاستقبال <span class="secret-state"><?=e($has('connections.generic_message.inbound_secret'))?></span></label><input type="password" name="connections__generic_message__inbound_secret" autocomplete="new-password"></div><div class="field"><label>اسم أو رقم المرسل</label><input name="connections__generic_message__from_ref"></div><button class="btn full-width">حفظ وتشغيل ربط الرسائل</button></form>
<p class="secret-hint">رابط الاستقبال: <span class="mono"><?=e((string)config('app.base_url').'/webhooks/generic-message.php')?></span></p><?=$connectionInfo('generic_bridge')?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="generic_bridge"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار الربط</button></form></div></section>

<section class="card provider-card"><div class="card-title"><div class="provider-meta"><div class="provider-logo">☎</div><div><h2>ربط مكالمات خارجي</h2><span class="muted small">لأي مزود مكالمات أو سنترال خارجي عنده واجهة ربط</span></div></div><?=AdminUi::badge($state('generic_call_bridge'))?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><input type="hidden" name="enable_call_bridge" value="1"><div class="field"><label>رابط خدمة المكالمات</label><input type="url" name="calls__bridge_url"></div><div class="field"><label>سر الربط <span class="secret-state"><?=e($has('calls.bridge_secret'))?></span></label><input type="password" name="calls__bridge_secret" autocomplete="new-password"></div><button class="btn full-width">حفظ وتشغيل ربط المكالمات</button></form><p class="secret-hint">رابط الرجوع: <span class="mono"><?=e((string)config('app.base_url').'/webhooks/generic-call.php')?></span></p><?=$connectionInfo('generic_call_bridge')?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="generic_call_bridge"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار الربط</button></form></div></section>

<section class="card provider-card"><div class="card-title"><div class="provider-meta"><div class="provider-logo">▣</div><div><h2>ربط الصور والفيديو</h2><span class="muted small">اختياري لأي خدمة توليد صور أو فيديو</span></div></div><?=AdminUi::badge($state('media_bridge'))?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><input type="hidden" name="enable_media_bridge" value="1"><div class="field"><label>رابط الخدمة</label><input type="url" name="connections__media__url"></div><div class="field"><label>مفتاح الخدمة <span class="secret-state"><?=e($has('connections.media.token'))?></span></label><input type="password" name="connections__media__token" autocomplete="new-password"></div><div class="field"><label>سر الاستقبال <span class="secret-state"><?=e($has('connections.media.inbound_secret'))?></span></label><input type="password" name="connections__media__inbound_secret" autocomplete="new-password"></div><button class="btn full-width">حفظ وتشغيل خدمة الوسائط</button></form><p class="secret-hint">رابط الاستقبال: <span class="mono"><?=e((string)config('app.base_url').'/webhooks/media.php')?></span></p><?=$connectionInfo('media_bridge')?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="media_bridge"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار الربط</button></form></div></section>
</div>


<section class="card" style="margin-top:16px"><div class="card-title"><div><h2>Cloud & Connectors Center</h2><span class="muted small">نسخ احتياطية خارجية + Google Drive / Dropbox / S3 + متصفح QA سحابي. الأسرار تُحفظ داخل الخزنة المشفرة فقط.</span></div></div>
<form method="post" action="action.php" class="subtle" style="margin-bottom:14px"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_cloud_settings"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="form-row"><div class="field"><label>موفر التخزين الافتراضي</label><select name="cloud__storage_provider"><?php $cs=(string)setting('cloud.storage_provider','none');foreach(['none'=>'بدون تخزين خارجي','cloud_s3'=>'S3 Compatible','google_drive'=>'Google Drive','dropbox'=>'Dropbox'] as $v=>$l):?><option value="<?=e($v)?>" <?=$cs===$v?'selected':''?>><?=e($l)?></option><?php endforeach?></select></div><label class="check"><input type="checkbox" name="cloud__auto_backup" value="1" <?=setting('cloud.auto_backup','0')==='1'?'checked':''?>> نسخ الـBackups تلقائيًا إلى السحابة</label><label class="check"><input type="checkbox" name="qa__browser_required" value="1" <?=setting('qa.browser_required','0')==='1'?'checked':''?>> Browser QA إلزامي قبل الاعتماد</label></div><button class="btn">حفظ سياسة السحابة</button></form>
<div class="provider-grid">
<section class="subtle"><div class="card-title"><b>S3 Compatible</b><?=AdminUi::badge($state('cloud_s3'))?></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Endpoint</label><input name="connections__cloud_s3__endpoint" placeholder="https://s3.example.com"></div><div class="field"><label>Bucket</label><input name="connections__cloud_s3__bucket"></div><div class="field"><label>Region</label><input name="connections__cloud_s3__region" placeholder="auto / us-east-1"></div><div class="field"><label>Access Key <span class="secret-state"><?=e($has('connections.cloud_s3.access_key'))?></span></label><input type="password" name="connections__cloud_s3__access_key"></div><div class="field"><label>Secret Key <span class="secret-state"><?=e($has('connections.cloud_s3.secret_key'))?></span></label><input type="password" name="connections__cloud_s3__secret_key"></div><button class="btn secondary full-width">حفظ</button></form><?=$connectionInfo('cloud_s3')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="cloud_s3"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار S3</button></form></section>
<section class="subtle"><div class="card-title"><b>Google Drive</b><?=AdminUi::badge($state('google_drive'))?></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Client ID <span class="secret-state"><?=e($has('connections.google_drive.client_id'))?></span></label><input type="password" name="connections__google_drive__client_id"></div><div class="field"><label>Client Secret <span class="secret-state"><?=e($has('connections.google_drive.client_secret'))?></span></label><input type="password" name="connections__google_drive__client_secret"></div><div class="field"><label>Refresh Token <span class="secret-state"><?=e($has('connections.google_drive.refresh_token'))?></span></label><input type="password" name="connections__google_drive__refresh_token"></div><div class="field"><label>Access Token (اختياري) <span class="secret-state"><?=e($has('connections.google_drive.access_token'))?></span></label><input type="password" name="connections__google_drive__access_token"></div><button class="btn secondary full-width">حفظ</button></form><?=$connectionInfo('google_drive')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="google_drive"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار Drive</button></form></section>
<section class="subtle"><div class="card-title"><b>Dropbox</b><?=AdminUi::badge($state('dropbox'))?></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Access Token <span class="secret-state"><?=e($has('connections.dropbox.token'))?></span></label><input type="password" name="connections__dropbox__token"></div><button class="btn secondary full-width">حفظ</button></form><?=$connectionInfo('dropbox')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="dropbox"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار Dropbox</button></form></section>
<section class="subtle"><div class="card-title"><b>Email Connector</b><?=AdminUi::badge($state('email'))?></div><p class="muted small">إرسال البريد مباشرة للعميل. يدعم API خارجي أو PHP mail؛ القبول لا يُسجل كتسليم نهائي.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Transport</label><select name="connections__email__transport"><option value="api">API</option><option value="php_mail">PHP mail</option></select></div><div class="field"><label>API URL</label><input type="url" name="connections__email__api_url" placeholder="https://provider.example/v1/send"></div><div class="field"><label>API Token <span class="secret-state"><?=e($has('connections.email.token'))?></span></label><input type="password" name="connections__email__token"></div><div class="field"><label>From Email <span class="secret-state"><?=e($has('connections.email.from_email'))?></span></label><input type="email" name="connections__email__from_email"></div><div class="field"><label>From Name</label><input name="connections__email__from_name" placeholder="شركة المتر"></div><div class="field"><label>Reply-To</label><input type="email" name="connections__email__reply_to"></div><button class="btn secondary full-width">حفظ Email Connector</button></form><?=$connectionInfo('email')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="email"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">فحص إعداد البريد</button></form></section>
<section class="subtle"><div class="card-title"><b>Staging Database</b><span class="badge untested">معزولة</span></div><p class="muted small">حساب MySQL مخصص لإنشاء قواعد اختبار منفصلة. إذا لم تُدخل القيم سيحاول النظام استخدام صلاحية قاعدة المشروع، ولن يلمس Production إذا فشل.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Host</label><input name="connections__staging_db__host"></div><div class="field"><label>Port</label><input name="connections__staging_db__port" placeholder="3306"></div><div class="field"><label>User <span class="secret-state"><?=e($has('connections.staging_db.user'))?></span></label><input type="password" name="connections__staging_db__user"></div><div class="field"><label>Password <span class="secret-state"><?=e($has('connections.staging_db.password'))?></span></label><input type="password" name="connections__staging_db__password"></div><div class="field"><label>DB Prefix</label><input name="connections__staging_db__prefix" placeholder="pb_stg"></div><button class="btn secondary full-width">حفظ حساب Staging DB</button></form></section>
<section class="subtle"><div class="card-title"><b>Cloud Browser QA</b><?=AdminUi::badge($state('browser_qa'))?></div><p class="muted small">Runner خارجي آمن لتشغيل JavaScript وMobile/Tablet/Desktop وScreenshots وForms/Links قبل QA Passed.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Runner URL</label><input type="url" name="connections__browser_qa__url"></div><div class="field"><label>Token <span class="secret-state"><?=e($has('connections.browser_qa.token'))?></span></label><input type="password" name="connections__browser_qa__token"></div><button class="btn secondary full-width">حفظ</button></form><?=$connectionInfo('browser_qa')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="browser_qa"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار Browser QA</button></form></section>
<section class="subtle"><div class="card-title"><div><b>Browser Automation Bridge</b><small class="muted block">المتصفح التنفيذي الذي يستخدم الحسابات من الخزنة بدون إظهار كلمة المرور للوكيل. مناسب لـCodespaces/VPS المشغل لـPlaywright.</small></div><?=AdminUi::badge($state('browser_automation'))?></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Bridge URL</label><input type="url" name="connections__browser_automation__url" placeholder="https://your-browser-runner.example"></div><div class="field"><label>Bridge Token <span class="secret-state"><?=e($has('connections.browser_automation.token'))?></span></label><input type="password" name="connections__browser_automation__token" autocomplete="new-password" placeholder="اتركه فارغًا للحفاظ على الحالي"></div><input type="hidden" name="enable_browser_automation" value="1"><button class="btn secondary full-width">حفظ وربط المتصفح التنفيذي</button></form><?=$connectionInfo('browser_automation')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="browser_automation"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار Browser Automation</button></form></section>
</div></section>

<section class="card" style="margin-top:16px"><div class="card-title"><div><h2>قنوات السوشيال والنشر</h2><span class="muted small">المفاتيح تحفظ داخل SecretVault. النشر الفعلي محكوم بموافقة المالك/رامي ولا يتم لمجرد حفظ التوكن.</span></div><a class="link" href="social.php">مركز السوشيال</a></div><div class="provider-grid">
<section class="subtle"><div class="card-title"><b>Meta Social — Facebook + Instagram</b><?=AdminUi::badge($state('meta_social'))?></div><p class="muted small">ربط رسمي عبر Meta Graph API. التوكنات تحفظ داخل SecretVault فقط ولا تُنسخ إلى ذاكرة الوكلاء. استخدم User Access Token طويل المدى أو Page Token مناسب بصلاحيات إدارة/نشر الصفحة وInstagram Professional Account.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>User Access Token <span class="secret-state"><?=e($has('connections.meta_social.access_token'))?></span></label><input type="password" name="connections__meta_social__access_token" autocomplete="new-password" placeholder="اتركه فارغًا للحفاظ على الحالي"></div><div class="field"><label>Facebook Page ID اختياري</label><input name="connections__meta_social__page_id" placeholder="Page ID"></div><div class="field"><label>Page Access Token اختياري <span class="secret-state"><?=e($has('connections.meta_social.page_access_token'))?></span></label><input type="password" name="connections__meta_social__page_access_token" autocomplete="new-password"></div><div class="field"><label>Instagram Professional ID اختياري</label><input name="connections__meta_social__instagram_id" placeholder="IG User ID"></div><div class="field"><label>Graph API Version</label><input name="connections__meta_social__graph_version" value="<?=e((string)SecretVault::get('connections.meta_social.graph_version',(string)config('meta.graph_version','v23.0')))?>" placeholder="v23.0"></div><button class="btn secondary full-width">حفظ Meta Social</button></form><?=$connectionInfo('meta_social')?><div class="provider-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="meta_social"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار Facebook / Instagram</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_sync_accounts"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">مزامنة الحسابات</button></form></div></section>
<section class="subtle"><div class="card-title"><b>YouTube Data API</b><?=AdminUi::badge($state('youtube'))?></div><p class="muted small">استخدم OAuth 2.0 بصلاحيتي youtube.upload وyoutube.readonly حتى يقدر النظام يتحقق من القناة ويرفع الفيديو. يفضل Refresh Token بدل Access Token المؤقت.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Client ID <span class="secret-state"><?=e($has('connections.youtube.client_id'))?></span></label><input type="password" name="connections__youtube__client_id"></div><div class="field"><label>Client Secret <span class="secret-state"><?=e($has('connections.youtube.client_secret'))?></span></label><input type="password" name="connections__youtube__client_secret"></div><div class="field"><label>Refresh Token <span class="secret-state"><?=e($has('connections.youtube.refresh_token'))?></span></label><input type="password" name="connections__youtube__refresh_token"></div><div class="field"><label>Access Token اختياري <span class="secret-state"><?=e($has('connections.youtube.access_token'))?></span></label><input type="password" name="connections__youtube__access_token"></div><button class="btn secondary full-width">حفظ YouTube</button></form><?=$connectionInfo('youtube')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="youtube"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار القناة</button></form></section>
<section class="subtle"><div class="card-title"><b>TikTok Content Posting API</b><?=AdminUi::badge($state('tiktok'))?></div><p class="muted small">التوكن يحتاج صلاحيات النشر المناسبة. الحساب/التطبيق غير المدقق قد يكون مقيدًا بخصوصية محدودة حسب TikTok.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Access Token <span class="secret-state"><?=e($has('connections.tiktok.access_token'))?></span></label><input type="password" name="connections__tiktok__access_token"></div><div class="field"><label>Client Key <span class="secret-state"><?=e($has('connections.tiktok.client_key'))?></span></label><input type="password" name="connections__tiktok__client_key"></div><div class="field"><label>Client Secret <span class="secret-state"><?=e($has('connections.tiktok.client_secret'))?></span></label><input type="password" name="connections__tiktok__client_secret"></div><button class="btn secondary full-width">حفظ TikTok</button></form><?=$connectionInfo('tiktok')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="tiktok"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار TikTok</button></form></section>
<section class="subtle"><div class="card-title"><b>Telegram Bot API</b><?=AdminUi::badge($state('telegram'))?></div><p class="muted small">Bot Token + Chat ID افتراضي. الإرسال الخارجي من الوكيل يحتاج approved_actions صريحة.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_secrets"><input type="hidden" name="return" value="/api/admin/integrations.php"><div class="field"><label>Bot Token <span class="secret-state"><?=e($has('connections.telegram.bot_token'))?></span></label><input type="password" name="connections__telegram__bot_token"></div><div class="field"><label>Default Chat ID <span class="secret-state"><?=e($has('connections.telegram.default_chat_id'))?></span></label><input type="password" name="connections__telegram__default_chat_id"></div><div class="field"><label>Webhook Secret اختياري <span class="secret-state"><?=e($has('connections.telegram.webhook_secret'))?></span></label><input type="password" name="connections__telegram__webhook_secret" placeholder="اتركه فارغًا وسيُنشأ تلقائيًا عند التسجيل"></div><button class="btn secondary full-width">حفظ Telegram</button></form><?=$connectionInfo('telegram')?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="connection_test"><input type="hidden" name="provider" value="telegram"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">اختبار البوت</button></form><form method="post" action="action.php" style="margin-top:8px"><?=AdminUi::csrf()?><input type="hidden" name="action" value="telegram_webhook_register"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary">تسجيل Webhook واستقبال الأعضاء</button></form></section>
</div></section>

<section class="card" style="margin-top:16px"><div class="card-title"><div><h2>قنوات التواصل</h2><span class="muted small">تشغيل أو إيقاف القناة من غير حذف مفاتيحها.</span></div></div><div class="table-wrap"><table><thead><tr><th>القناة</th><th>المزود</th><th>إرسال</th><th>استقبال</th><th>الحالة</th><th>تحكم</th></tr></thead><tbody><?php foreach($channels as $c):?><tr><td><?=e($c['label'])?></td><td><?=e(AdminUi::provider($c['provider']))?></td><td><?=$c['send_enabled']?'مسموح':'موقوف'?></td><td><?=$c['receive_enabled']?'مسموح':'موقوف'?></td><td><?=AdminUi::badge($c['enabled']?'active':'disabled')?></td><td><form method="post" action="action.php" class="inline-form"><?=AdminUi::csrf()?><input type="hidden" name="action" value="channel_toggle"><input type="hidden" name="id" value="<?=$c['id']?>"><input type="hidden" name="enabled" value="<?=$c['enabled']?0:1?>"><input type="hidden" name="return" value="/api/admin/integrations.php"><button class="btn secondary small-btn"><?=$c['enabled']?'إيقاف':'تشغيل'?></button></form></td></tr><?php endforeach?></tbody></table></div></section>

<section class="card" style="margin-top:16px"><div class="card-title"><h2>آخر اختبارات الاتصال</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>الخدمة</th><th>النتيجة</th><th>التفاصيل المختصرة</th><th>الوقت</th></tr></thead><tbody><?php foreach($tests as $t):?><tr><td>#<?=$t['id']?></td><td><?=e(AdminUi::provider($t['provider_key']))?></td><td><?=AdminUi::badge($t['state'])?></td><td><?=e(AdminUi::humanError((string)($t['result_code']?:'—')))?></td><td><?=e(AdminUi::date($t['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<?php AdminUi::footer();
