<?php
declare(strict_types=1);

final class LabEnvironmentService {
    public static function prepare(int $projectId):array{
        $project=ProjectService::get($projectId);$staging=StagingService::ensure($projectId);$root=StagingService::rootDomain();$domain=(string)$staging['domain'];$sub=(string)($staging['subdomain']??explode('.',$domain)[0]);$dir=(string)($staging['directory']??'');
        $fileSync=['state'=>'not_required'];try{$fileSync=StagingService::syncFromProduction($projectId,true);}catch(Throwable $e){$fileSync=['state'=>'failed','error'=>pb_substr(Security::redactSecrets($e->getMessage()),0,180)];}
        $dbId=null;$dbState='not_required';try{$db=StagingDatabaseService::ensureForProject($projectId);$dbId=(int)($db['id']??0)?:null;$dbState='ready';}catch(Throwable $e){$dbState='needs_connector:'.pb_substr(Security::redactSecrets($e->getMessage()),0,140);}
        $health=['ok'=>false,'status'=>0,'error'=>'not_checked'];try{$probe=HttpClient::probe('https://'.$domain.'/',20,131072);$status=(int)($probe['status']??0);$health=['ok'=>$status>=200&&$status<400,'status'=>$status,'final_url'=>$probe['final_url']??'','content_type'=>$probe['content_type']??'','sha256'=>$probe['sha256']??'','error'=>$probe['error']??''];}catch(Throwable $e){$health=['ok'=>false,'status'=>0,'error'=>pb_substr(Security::redactSecrets($e->getMessage()),0,180)];}
        $state='ready';if(($fileSync['state']??'')==='failed')$state='file_sync_failed';elseif(!$health['ok'])$state='needs_runtime_config_or_dns';elseif(str_starts_with($dbState,'needs_connector:'))$state='ready_without_staging_db';elseif(($fileSync['state']??'')==='completed_with_warnings')$state='ready_with_warnings';
        $meta=['staging'=>$staging,'file_sync'=>$fileSync,'database_state'=>$dbState,'health'=>$health,'prepared_at'=>now_utc()];db()->prepare("INSERT INTO lab_environments(project_id,root_domain,subdomain,full_domain,directory_path,database_id,state,last_health_at,metadata_json) VALUES (?,?,?,?,?,?,?,NOW(),?) ON DUPLICATE KEY UPDATE root_domain=VALUES(root_domain),subdomain=VALUES(subdomain),full_domain=VALUES(full_domain),directory_path=VALUES(directory_path),database_id=VALUES(database_id),state=VALUES(state),last_health_at=NOW(),metadata_json=VALUES(metadata_json)")->execute([$projectId,$root,$sub,$domain,$dir,$dbId,$state,j($meta)]);
        if(!$health['ok'])Notifications::add('warning','projects','محطة الاختبار تحتاج مراجعة تشغيل','تمت المزامنة الآمنة، لكن Health Check على '.$domain.' لم ينجح بعد. الملفات الحساسة لا تُنسخ تلقائيًا من Production؛ راجع إعداد Runtime/DNS/SSL وقاعدة Staging قبل الاختبار.','project',(string)$projectId);
        $targetQ=db()->prepare("SELECT id FROM security_targets WHERE project_id=? AND environment IN ('testing','staging') AND active=1 ORDER BY id DESC LIMIT 1");$targetQ->execute([$projectId]);$targetId=(int)($targetQ->fetchColumn()?:0);if(!$targetId)$targetId=SecurityLabService::createTarget(['project_id'=>$projectId,'label'=>'محطة اختبار — '.(string)$project['name'],'base_url'=>'https://'.$domain.'/','environment'=>'staging','paths'=>['/'],'authorization_scope'=>'اختبار مشروع #'.$projectId.' داخل محطة nourmakkah.com قبل التسليم.','allow_authenticated_tests'=>1,'allow_intrusive_tests'=>0,'allow_production_changes'=>0,'allow_data_proof'=>1],(string)(Auth::user()['id']??1));
        return ['project_id'=>$projectId,'environment'=>$staging,'file_sync'=>$fileSync,'database_state'=>$dbState,'database_id'=>$dbId,'health'=>$health,'state'=>$state,'security_target_id'=>$targetId];
    }
    public static function all():array{return db()->query('SELECT l.*,p.name project_name FROM lab_environments l JOIN projects p ON p.id=l.project_id ORDER BY l.id DESC')->fetchAll();}
}
