<?php
declare(strict_types=1);
final class MasterBriefService {
    public static function current(int $projectId):?array{$q=db()->prepare('SELECT b.* FROM project_briefs b WHERE b.project_id=? AND b.is_current=1 ORDER BY b.version_no DESC LIMIT 1');$q->execute([$projectId]);return $q->fetch()?:null;}
    public static function create(int $projectId,array $override=[],bool $approvedByOwner=false):array{
        $p=ProjectService::get($projectId);$ramy=AgentService::bySlug('ramy');$op=null;$customer=null;$quote=null;
        if(!empty($p['opportunity_id'])){$q=db()->prepare('SELECT * FROM opportunities WHERE id=?');$q->execute([(int)$p['opportunity_id']]);$op=$q->fetch()?:null;}
        $q=db()->prepare("SELECT c.* FROM customer_projects cp JOIN customers c ON c.id=cp.customer_id WHERE cp.project_id=? ORDER BY FIELD(cp.relationship,'owner','contact','billing') LIMIT 1");$q->execute([$projectId]);$customer=$q->fetch()?:null;
        $q=db()->prepare('SELECT * FROM quotes WHERE project_id=? ORDER BY id DESC LIMIT 1');$q->execute([$projectId]);$quote=$q->fetch()?:null;
        $brief=[
            'project_name'=>$p['name'],'domain'=>$p['primary_domain']?:null,
            'customer'=>$customer?['name'=>$customer['display_name'],'phone'=>$customer['phone'],'email'=>$customer['email']]:null,
            'source'=>$op?['name'=>$op['source'],'url'=>$op['source_url'],'opportunity_id'=>$op['id']]:null,
            'project_type'=>$op['opportunity_type']??($op['category']??''),'purpose'=>'','audience'=>'',
            'requirements'=>$op['requirements_text']??($quote['scope_text']??''),'scope'=>$quote['scope_text']??($op['requirements_text']??''),'out_of_scope'=>'','final_scope'=>'',
            'price'=>$quote?['amount'=>(float)$quote['amount'],'currency'=>$quote['currency'],'status'=>$quote['status'],'deposit_percent'=>(float)($quote['deposit_percent']??PricingPolicy::values()['deposit_start_percent'])]:null,
            'pages'=>'','features'=>'','design_direction'=>'','colors'=>'','content_source'=>'','languages'=>'','language'=>'',
            'apis'=>'','integrations'=>'','hosting'=>'','database'=>'','authentication'=>'','payments'=>'','notifications'=>'','admin_panel'=>'',
            'deadline'=>'','files'=>[],'customer_notes'=>'','owner_notes'=>'','technical_notes'=>'','client_decisions'=>[],'owner_decisions'=>[],'acceptance_criteria'=>[]
        ];
        $current=self::current($projectId);$previous=[];
        if($current){$old=json_decode((string)($current['brief_json']??'{}'),true);if(is_array($old)){$previous=$old;foreach($old as $k=>$v)if(array_key_exists($k,$brief))$brief[$k]=$v;}$brief['project_name']=$p['name'];$brief['domain']=$p['primary_domain']?:($brief['domain']??null);if($customer)$brief['customer']=['name'=>$customer['display_name'],'phone'=>$customer['phone'],'email'=>$customer['email']];if($op)$brief['source']=['name'=>$op['source'],'url'=>$op['source_url'],'opportunity_id'=>$op['id']];if($quote)$brief['price']=['amount'=>(float)$quote['amount'],'currency'=>$quote['currency'],'status'=>$quote['status'],'deposit_percent'=>(float)($quote['deposit_percent']??PricingPolicy::values()['deposit_start_percent'])];}
        foreach($override as $k=>$v)if(array_key_exists($k,$brief))$brief[$k]=$v;
        if(trim((string)$brief['final_scope'])==='')$brief['final_scope']=$brief['scope'];
        $q=db()->prepare('SELECT COALESCE(MAX(version_no),0)+1 FROM project_briefs WHERE project_id=?');$q->execute([$projectId]);$version=(int)$q->fetchColumn();$diff=self::diff($previous,$brief);
        $text=self::render($brief,$version,$diff);db()->prepare('UPDATE project_briefs SET is_current=0 WHERE project_id=?')->execute([$projectId]);
        $snapshot=['opportunity_id'=>$op['id']??null,'quote_id'=>$quote['id']??null,'customer_id'=>$customer['id']??null,'previous_brief_id'=>$current['id']??null,'diff'=>$diff,'created_at'=>now_utc()];
        $q=db()->prepare('INSERT INTO project_briefs(project_id,version_no,summary_text,brief_json,source_snapshot_json,created_by_agent_id,approved_by_owner,is_current) VALUES (?,?,?,?,?,?,?,1)');$q->execute([$projectId,$version,$text,j($brief),j($snapshot),(int)$ramy['id'],$approvedByOwner?1:0]);$id=(int)db()->lastInsertId();db()->prepare('UPDATE projects SET current_brief_id=? WHERE id=?')->execute([$id,$projectId]);
        ProjectChatService::pinMasterBrief($projectId,$text,$id);try{TeamChatService::post('agent','ramy','team','Master Brief v'.$version.' — المرجع الحالي للتنفيذ والمراجعة'."\n".pb_substr($text,0,3500),'status',$projectId,null,['brief_id'=>$id,'brief_version'=>$version,'diff'=>$diff,'pinned'=>1]);}catch(Throwable){}
        MemoryService::rememberProject($projectId,'master_brief','الإصدار الحالي من Master Brief هو v'.$version.'.','project_brief',(string)$id);Audit::log('agent',(string)$ramy['id'],'project.brief_created','project_brief',(string)$id,'verified',$projectId,null,['version'=>$version,'diff_count'=>count($diff)]);return ['id'=>$id,'version'=>$version,'text'=>$text,'brief'=>$brief,'diff'=>$diff];
    }
    public static function appendClientUpdate(int $projectId,string $summary,bool $ownerApproved=false):?array{$summary=trim($summary);if($summary==='')return null;$current=self::current($projectId);$notes='';if($current){$b=json_decode((string)($current['brief_json']??'{}'),true);if(is_array($b))$notes=trim((string)($b['customer_notes']??''));}$notes=trim($notes.($notes!==''?"\n":'').'• '.$summary);return self::create($projectId,['customer_notes'=>$notes],$ownerApproved);}
    public static function requireForExecution(int $projectId):void{$p=ProjectService::get($projectId);if(setting('workflow.require_master_brief_before_execution','1')!=='1')return;if((string)$p['source']!=='client_project')return;$stage=ProjectStageService::normalize((string)($p['workflow_stage']??''));if(!in_array($stage,['agreed','deposit_pending','awaiting_execution','in_development','awaiting_qa','qa','needs_fix','ready_delivery'],true))return;if(!self::current($projectId))throw new RuntimeException('master_brief_required');}
    private static function diff(array $old,array $new):array{$out=[];if(!$old)return [['field'=>'initial','before'=>null,'after'=>'v1']];foreach($new as $k=>$v){$before=$old[$k]??null;if(j($before)!==j($v))$out[]=['field'=>$k,'before'=>$before,'after'=>$v];}return $out;}
    private static function val(mixed $v):string{if(is_array($v))return implode('، ',array_map(fn($x)=>is_scalar($x)?(string)$x:j($x),$v));return trim((string)$v);}
    private static function render(array $b,int $v,array $diff=[]):string{
        $lines=['PROJECT MASTER BRIEF — v'.$v,'','اسم المشروع: '.($b['project_name']?:'—'),'العميل: '.(($b['customer']['name']??'')?:'—'),'المصدر: '.(($b['source']['name']??'')?:'—'),'نوع المشروع: '.(self::val($b['project_type'])?:'—'),'الغرض: '.(self::val($b['purpose'])?:'—'),'الجمهور: '.(self::val($b['audience'])?:'—'),'المطلوب: '.(self::val($b['requirements'])?:'—'),'نطاق التنفيذ النهائي: '.(self::val($b['final_scope']?:$b['scope'])?:'—'),'خارج النطاق: '.(self::val($b['out_of_scope'])?:'—'),'السعر/المقدم: '.(!empty($b['price'])?(number_format((float)$b['price']['amount'],2).' '.($b['price']['currency']??'').' — مقدم '.(float)($b['price']['deposit_percent']??0).'%'):'—'),'الصفحات: '.(self::val($b['pages'])?:'غير محدد'),'الوظائف: '.(self::val($b['features'])?:'غير محدد'),'اتجاه التصميم: '.(self::val($b['design_direction'])?:'غير محدد'),'الألوان: '.(self::val($b['colors'])?:'غير محدد'),'المحتوى: '.(self::val($b['content_source'])?:'غير محدد'),'اللغات: '.(self::val($b['languages']?:$b['language'])?:'غير محدد'),'APIs: '.(self::val($b['apis'])?:'—'),'Integrations: '.(self::val($b['integrations'])?:'—'),'Hosting: '.(self::val($b['hosting'])?:'—'),'Database: '.(self::val($b['database'])?:'—'),'Authentication: '.(self::val($b['authentication'])?:'—'),'Payments: '.(self::val($b['payments'])?:'—'),'Notifications: '.(self::val($b['notifications'])?:'—'),'Admin Panel: '.(self::val($b['admin_panel'])?:'—'),'الموعد: '.(self::val($b['deadline'])?:'غير محدد'),'Acceptance Criteria: '.(self::val($b['acceptance_criteria'])?:'—'),'ملاحظات العميل: '.(self::val($b['customer_notes'])?:'—'),'ملاحظات المالك: '.(self::val($b['owner_notes'])?:'—'),'ملاحظات فنية: '.(self::val($b['technical_notes'])?:'—')];
        if($v>1){$lines[]='';$lines[]='التغييرات عن الإصدار السابق: '.(count($diff)?:0);foreach(array_slice($diff,0,20) as $d)$lines[]='• '.$d['field'].': '.pb_substr(self::val($d['before']),0,120).' → '.pb_substr(self::val($d['after']),0,120);}
        return implode("\n",$lines);
    }
}
