<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
if($_SERVER['REQUEST_METHOD']==='GET'){$mode=(string)($_GET['hub_mode']??$_GET['hub.mode']??'');$token=(string)($_GET['hub_verify_token']??$_GET['hub.verify_token']??'');$challenge=(string)($_GET['hub_challenge']??$_GET['hub.challenge']??'');$verify=(string)config('meta.verify_token','');if(strlen($verify)>=8&&$mode==='subscribe'&&$token!==''&&hash_equals($verify,$token)){http_response_code(200);echo $challenge;exit;}http_response_code(403);echo 'forbidden';exit;}
$raw=file_get_contents('php://input')?:'';$sig=(string)($_SERVER['HTTP_X_HUB_SIGNATURE_256']??'');$valid=MetaClient::verifySignature($raw,$sig);$payload=json_decode($raw,true);if(!is_array($payload))$payload=[];$eventId=hash('sha256',$raw);
try{db()->prepare("INSERT IGNORE INTO webhook_events(provider,external_event_id,signature_valid,event_type,payload_json) VALUES ('meta',?,?,?,?)")->execute([$eventId,$valid?1:0,'whatsapp',j($payload)]);}catch(Throwable){}
if(!$valid){http_response_code(401);echo 'invalid signature';exit;}
try{MetaClient::rememberWabaId($payload);}catch(Throwable){}
// Return Meta's HTTP acknowledgement before the potentially slow AI/orchestration work.
// On PHP-FPM/Hostinger fastcgi_finish_request() closes the client response while PHP continues safely.
$responseClosed=false;
if(function_exists('fastcgi_finish_request')){http_response_code(200);header('Content-Type: text/plain; charset=UTF-8');echo 'ok';fastcgi_finish_request();$responseClosed=true;ignore_user_abort(true);}
try{foreach(MetaClient::extractMessages($payload) as $m){if($m['id']===''||trim($m['text'])==='')continue;$handled=false;try{$agencyResult=AgencyEventService::handleInboundWhatsApp((string)$m['from'],(string)$m['text'],(string)$m['id'],(array)$m['raw']);$handled=!empty($agencyResult['handled']);}catch(Throwable $agencyError){error_log('ELMETR agency whatsapp inbound: '.Security::redactSecrets($agencyError->getMessage(),180));}if(!$handled){try{$messageRaw=(array)$m['raw'];if(!empty($m['contact_name']))$messageRaw['_contact_name']=$m['contact_name'];CommunicationGateway::inbound('whatsapp','meta',$m['from'],$m['text'],$m['id'],$messageRaw);}catch(PDOException $e){if((string)$e->getCode()!=='23000')throw $e;}}try{$community=AgentService::bySlug('community-manager');$socialContactId=SocialMediaService::upsertContact((int)$community['id'],'whatsapp',(string)$m['from'],(string)($m['contact_name']??''),(string)$m['from'],'','','member',[],'Synced automatically from WhatsApp inbound.');SocialMediaService::recordInteraction((int)$community['id'],'whatsapp','inbound','message',(string)$m['id'],(string)$m['text'],$socialContactId,[]);}catch(Throwable $syncError){error_log('ELMETR whatsapp social contact sync: '.Security::redactSecrets($syncError->getMessage(),180));}}foreach(MetaClient::extractStatuses($payload) as $st){if($st['id']==='')continue;CommunicationGateway::handleMetaDeliveryStatus($st);}foreach(MetaClient::extractCalls($payload) as $call){try{WhatsAppCallingService::handleMetaEvent((array)$call);}catch(Throwable $callError){error_log('ELMETR whatsapp call event: '.Security::redactSecrets($callError->getMessage(),180));}}db()->prepare("UPDATE webhook_events SET processing_state='processed' WHERE provider='meta' AND external_event_id=?")->execute([$eventId]);}catch(Throwable $e){db()->prepare("UPDATE webhook_events SET processing_state='failed',error_code=? WHERE provider='meta' AND external_event_id=?")->execute([pb_substr($e->getMessage(),0,120),$eventId]);Notifications::add('critical','webhooks','WhatsApp processing failed',AdminUi::humanError($e->getMessage()),'webhook',$eventId);}
if(!$responseClosed){http_response_code(200);echo 'ok';}
