<?php
declare(strict_types=1);
final class OpenAIMediaClient {
    private static function key():string{$k=trim((string)config('ai.api_key',''));if($k==='')$k=trim((string)SecretVault::get('providers.openai.api_key',''));if(strlen($k)<20)throw new RuntimeException('openai_not_configured');return $k;}
    private static function mediaDir():string{$d=PB_ROOT.'/private/runtime/generated-media';if(!is_dir($d)&&!mkdir($d,0700,true)&&!is_dir($d))throw new RuntimeException('media_storage_unavailable');return $d;}
    private static function save(string $bytes,string $ext,string $prefix):string{$ext=preg_replace('/[^a-z0-9]+/i','',$ext)?:'bin';$path=self::mediaDir().'/'.$prefix.'-'.gmdate('Ymd-His').'-'.bin2hex(random_bytes(5)).'.'.$ext;if(file_put_contents($path,$bytes,LOCK_EX)===false)throw new RuntimeException('media_file_write_failed');@chmod($path,0600);return $path;}
    public static function transcribe(string $path,?string $model=null):array{if(!is_file($path)||filesize($path)===0)throw new RuntimeException('audio_file_missing');if(filesize($path)>25*1024*1024)throw new RuntimeException('audio_file_too_large');$model=trim((string)$model)?:'gpt-4o-mini-transcribe';$ch=curl_init('https://api.openai.com/v1/audio/transcriptions');if(!$ch)throw new RuntimeException('curl_init_failed');$file=new CURLFile($path,mime_content_type($path)?:'audio/mpeg',basename($path));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.self::key(),'Accept: application/json'],CURLOPT_POSTFIELDS=>['file'=>$file,'model'=>$model,'response_format'=>'json'],CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>120]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('network_error:'.$err);$d=json_decode((string)$raw,true);if(!is_array($d))$d=[];if($status<200||$status>=300)throw new RuntimeException('http_'.$status.':'.substr((string)($d['error']['message']??''),0,300));$text=trim((string)($d['text']??''));if($text==='')throw new RuntimeException('stt_empty_transcript');return ['provider'=>'openai','text'=>$text,'model'=>$model];}
    public static function tts(string $text,?string $model=null,?string $voice=null):array{$text=trim($text);if($text==='')throw new RuntimeException('tts_text_required');$model=trim((string)$model)?:'gpt-4o-mini-tts';$voice=trim((string)$voice)?:'alloy';$ch=curl_init('https://api.openai.com/v1/audio/speech');if(!$ch)throw new RuntimeException('curl_init_failed');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.self::key(),'Content-Type: application/json'],CURLOPT_POSTFIELDS=>j(['model'=>$model,'voice'=>$voice,'input'=>pb_substr($text,0,10000),'response_format'=>'mp3']),CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>120]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$type=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('network_error:'.$err);if($status<200||$status>=300){$d=json_decode((string)$raw,true);throw new RuntimeException('http_'.$status.':'.substr((string)($d['error']['message']??''),0,300));}if(strlen((string)$raw)<100)throw new RuntimeException('tts_empty_audio');$dir=PB_ROOT.'/private/runtime/voice';if(!is_dir($dir)&&!mkdir($dir,0700,true)&&!is_dir($dir))throw new RuntimeException('voice_runtime_not_writable');$name='tts-'.gmdate('Ymd-His').'-'.substr(hash('sha256',$text.microtime(true)),0,12).'.mp3';$path=$dir.'/'.$name;if(file_put_contents($path,$raw)===false)throw new RuntimeException('tts_write_failed');@chmod($path,0600);return ['provider'=>'openai','path'=>$path,'basename'=>$name,'mime'=>$type?:'audio/mpeg','bytes'=>strlen((string)$raw),'model'=>$model,'voice'=>$voice];}
    public static function embedding(string $text,?string $model=null):array{$model=trim((string)$model)?:'text-embedding-3-small';$r=HttpClient::json('POST','https://api.openai.com/v1/embeddings',['Authorization'=>'Bearer '.self::key()],['model'=>$model,'input'=>pb_substr(trim($text),0,12000)],60);$v=$r['data'][0]['embedding']??null;if(!is_array($v)||count($v)<8)throw new RuntimeException('embedding_vector_missing');return ['provider'=>'openai','vector'=>array_map('floatval',$v),'model'=>(string)($r['model']??$model)];}
    public static function vision(string $prompt,string $imageUrl,?string $model=null,int $max=1500):array{$model=trim((string)$model)?:trim((string)setting('ai.vision_model','gpt-5.6'));$imageUrl=Security::publicUrl($imageUrl);$payload=['model'=>$model,'input'=>[['role'=>'user','content'=>[['type'=>'input_text','text'=>$prompt],['type'=>'input_image','image_url'=>$imageUrl]]]],'max_output_tokens'=>$max,'store'=>false];$r=HttpClient::json('POST','https://api.openai.com/v1/responses',['Authorization'=>'Bearer '.self::key()],$payload,90);$text='';foreach((array)($r['output']??[]) as $o)foreach((array)($o['content']??[]) as $c)if(($c['type']??'')==='output_text')$text.=(string)($c['text']??'');if(trim($text)==='')throw new RuntimeException('vision_empty_output');return ['provider'=>'openai','text'=>trim($text),'model'=>(string)($r['model']??$model)];}
    public static function image(string $prompt,?string $model=null,string $size='1024x1024',string $quality='medium'):array{$model=trim((string)$model)?:trim((string)setting('ai.image_model','gpt-image-2'));$prompt=trim($prompt);if($prompt==='')throw new RuntimeException('image_prompt_required');if(!in_array($size,['1024x1024','1024x1536','1536x1024','auto'],true))$size='1024x1024';$r=HttpClient::json('POST','https://api.openai.com/v1/images/generations',['Authorization'=>'Bearer '.self::key()],['model'=>$model,'prompt'=>pb_substr($prompt,0,12000),'size'=>$size,'quality'=>$quality,'n'=>1],120);$item=(array)($r['data'][0]??[]);$b64=(string)($item['b64_json']??'');$url=(string)($item['url']??'');$path='';if($b64!==''){$bytes=base64_decode($b64,true);if($bytes===false)throw new RuntimeException('image_decode_failed');$path=self::save($bytes,'png','img');}if($path===''&&$url==='')throw new RuntimeException('image_result_missing');return ['provider'=>'openai','model'=>$model,'path'=>$path?:null,'url'=>$url?:null,'revised_prompt'=>$item['revised_prompt']??null];}
}
