<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
try{OpportunitySearchService::reconcileRuns(20);}catch(Throwable){}
AgentService::reconcileRuntimeStates();$walid=AgentService::bySlug('walid');
$runs=db()->query("SELECT r.*,t.status task_status,t.uid task_uid FROM opportunity_search_runs r LEFT JOIN tasks t ON t.id=r.task_id ORDER BY r.id DESC LIMIT 80")->fetchAll();
$sources=db()->query("SELECT * FROM opportunity_sources ORDER BY enabled DESC,priority DESC,id ASC")->fetchAll();
$latest=$runs[0]??null;
$active=(int)db()->query("SELECT COUNT(*) FROM jobs WHERE kind='walid_opportunity_search' AND state IN ('queued','running','waiting')")->fetchColumn();
$qualified=(int)db()->query("SELECT COUNT(*) FROM opportunities WHERE fit_status='qualified' AND status IN ('new','needs_review')")->fetchColumn();
$review=(int)db()->query("SELECT COUNT(*) FROM opportunities WHERE fit_status='review' AND status IN ('new','needs_review')")->fetchColumn();
$rejected=(int)db()->query("SELECT COUNT(*) FROM opportunities WHERE status='rejected'")->fetchColumn();
$provider=(string)setting('opportunities.search_provider','auto');
$searchReady=WebSearchClient::configured();$workerHeartbeat=(string)setting('runtime.worker_heartbeat_at','');$workerTs=utc_ts($workerHeartbeat);$workerHealthy=$workerTs!==false&&(time()-$workerTs)<600;$walidJob=db()->query("SELECT j.id,j.state,j.attempts,j.max_attempts,j.error_code,j.updated_at,t.id task_id,t.status task_status FROM jobs j LEFT JOIN tasks t ON t.id=j.task_id WHERE j.kind='walid_opportunity_search' ORDER BY j.id DESC LIMIT 1")->fetch()?:null;
$autoKick=null;if($active>0&&!$workerHealthy){try{$autoKick=WorkerWakeup::kickNow(1);$workerHeartbeat=(string)setting('runtime.worker_heartbeat_at',$workerHeartbeat);$workerTs=utc_ts($workerHeartbeat);$workerHealthy=$workerTs!==false&&(time()-$workerTs)<600;}catch(Throwable $e){$autoKick=['state'=>'failed','code'=>pb_substr($e->getMessage(),0,120)];}}
$searchApiReady=['serper'=>WebSearchClient::hasKey('serper'),'brave'=>WebSearchClient::hasKey('brave'),'tavily'=>WebSearchClient::hasKey('tavily'),'openai_web'=>OpenAIClient::configured(),'openrouter'=>OpenRouterService::configured(),'openrouter_web_paid'=>setting('opportunities.openrouter_web_paid_search','0')==='1','marketplace_seeds'=>setting('opportunities.marketplace_seed_discovery','1')==='1'];
$lastKickState=(string)setting('runtime.worker_last_kick_state','');$lastKickAt=(string)setting('runtime.worker_last_kick_at','');$lastKickMode=(string)setting('runtime.worker_last_kick_mode','');
AdminUi::header('صيد المشاريع — وليد','opportunity_hunt');echo AdminUi::flash();
?>
<div class="hero-strip">
 <div><span class="eyebrow">وكيل البحث والتنقيب</span><h2>وليد يبحث عن فرص المواقع والأتمتة والذكاء الاصطناعي والخدمات الرقمية القابلة للتنفيذ ويحوّلها إلى كروت قابلة للقرار</h2><p>النطاق الافتراضي آخر <?=e(setting('opportunities.lookback_days','15'))?> يومًا. البحث التجاري منفصل تمامًا عن فهرسة Hostinger.</p></div>
 <div class="hero-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_hunt"><input type="hidden" name="return" value="/api/admin/opportunity-hunt.php"><button class="btn btn-xl" <?=$active?'disabled':''?>><?=$active?'وليد يعمل الآن':'ابدأ بحث وليد'?></button></form><a class="btn secondary" href="orders.php">راجع الفرص</a></div>
</div>
<section class="card intelligence-panel"><div class="card-title"><div><span class="eyebrow">VERIFIED DISCOVERY 7.0</span><h2>بحث وليد: إعلانات شراء حقيقية فقط</h2><span class="muted small">يفصل صفحات القوائم عن المشاريع الفردية، ويتحقق من رابط المشروع نفسه ويستبعد المغلق/القديم والمقالات والبروفايلات وصفحات الخدمات. يبحث في مواقع الويب وAPI وAI automation وChatbots وRAG وWhatsApp/CRM وn8n/Zapier/Make واستخراج البيانات من المصادر العامة. التاريخ والعملة ووسائل التواصل تُستخرج من دليل المصدر، والعرض الداخلي دائمًا بالعربية.</span></div><span class="badge s-active"><?=e(AdminUi::provider(WebSearchClient::provider()))?></span></div><div class="intelligence-grid"><div><b>مصادر API عند توفر المفاتيح</b><span>مصادر مباشرة مجانية: نفذلي · مستقل · Freelancer، ومعها Bing RSS/HTML كبحث عام مفلتر. Serper · Brave · Tavily تُستخدم عند وجود مفتاح. OpenRouter Web Search منفصل عن OpenRouter AI ولا يعمل تلقائيًا إلا إذا فعّله المالك. لا تُحفظ أي صفحة قائمة كفرصة؛ يجب استخراج رابط مشروع فردي أولًا</span></div><div><b>لغات التنقيب</b><span>العربية · الإنجليزية · الفرنسية</span></div><div><b>معيار الاختيار</b><span>Buyer intent + تحقق المصدر + صحة العملة + سهولة + هامش ربح + ثقة</span></div><div><b>النطاق</b><span>آخر <?=e(setting('opportunities.lookback_days','15'))?> يومًا · <?=e(setting('opportunities.default_raw_target','40'))?> نتيجة خام</span></div></div></section>
<div class="metric-grid metric-grid-4"><?=AdminUi::stat('حالة وليد',AdminUi::label((string)$walid['status']),'آخر نشاط فعلي: '.AdminUi::date($walid['last_seen_at']??null))?><?=AdminUi::stat('فرص مؤهلة',$qualified,'جاهزة للمراجعة')?><?=AdminUi::stat('تحتاج مراجعة',$review,'نقص بيانات لا يعني رفض')?><?=AdminUi::stat('مرفوض/مكرر',$rejected,'تظل البصمة محفوظة')?></div>
<div class="quick-status" style="margin:0 0 16px"><span class="pill">Worker: <?=e($workerHealthy?'Healthy':'Stale / Unknown')?><?= $workerHeartbeat!==''?' · '.e(AdminUi::date($workerHeartbeat)):'' ?></span><span class="pill">Jobs وليد: <?=e((string)$active)?></span><?php if($walidJob):?><span class="pill">آخر Job #<?=e((string)$walidJob['id'])?>: <?=e(AdminUi::label((string)$walidJob['state']))?><?=!empty($walidJob['error_code'])?' · '.e(AdminUi::humanError((string)$walidJob['error_code'])):''?></span><?php endif?><?php if($lastKickState!==''):?><span class="pill">آخر Wakeup: <?=e($lastKickState)?><?= $lastKickMode!==''?' · '.e($lastKickMode):'' ?><?= $lastKickAt!==''?' · '.e(AdminUi::date($lastKickAt)):'' ?></span><?php endif?></div>
<?php if(!$workerHealthy):?><div class="flash warning"><span>Worker غير مؤكد حاليًا؛ أي Job بحث قد يظل في Queue. الإصدار الحالي يملك HTTPS self-kick كبديل عن FastCGI.</span><div style="margin-inline-start:auto;display:flex;gap:8px;flex-wrap:wrap"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="worker_kick"><input type="hidden" name="return" value="/api/admin/opportunity-hunt.php"><button class="btn secondary small-btn">إيقاظ Worker الآن</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="run_worker"><input type="hidden" name="limit" value="1"><input type="hidden" name="return" value="/api/admin/opportunity-hunt.php"><button class="btn secondary small-btn">تشغيل مباشر للتشخيص</button></form></div></div><?php endif?>
<?php if(!$searchReady):?><div class="flash error"><span>لا يوجد مسار اكتشاف جاهز لوليد. افتح تشخيص البحث وتحقق من المصادر العامة المباشرة وBing أو اربط Serper/Brave/Tavily.</span><a class="btn secondary small-btn" href="integrations.php">فتح الربط</a></div><?php endif?>
<div class="quick-status" style="margin:0 0 16px"><span class="pill">Serper: <?=e($searchApiReady['serper']?'Key':'—')?></span><span class="pill">Brave: <?=e($searchApiReady['brave']?'Key':'—')?></span><span class="pill">Tavily: <?=e($searchApiReady['tavily']?'Key':'—')?></span><span class="pill">OpenAI Web: <?=e($searchApiReady['openai_web']?'Ready':'—')?></span><span class="pill">OpenRouter AI: <?=e($searchApiReady['openrouter']?'Ready':'—')?></span><span class="pill">OpenRouter Web: <?=e($searchApiReady['openrouter_web_paid']?'On':'Off')?></span><span class="pill">Direct markets: <?=e($searchApiReady['marketplace_seeds']?'On':'Off')?></span><span class="pill">Public fallback: <?=e(setting('opportunities.trusted_public_fallback','1')==='1'?'Trusted-only':'Off')?></span><a class="btn secondary small-btn" href="search-diagnostics.php">تشخيص البحث الحي</a><form method="post" action="action.php" style="display:inline-flex"><?=AdminUi::csrf()?><input type="hidden" name="action" value="search_diagnostics_run"><input type="hidden" name="return" value="/api/admin/opportunity-hunt.php"><button class="btn secondary small-btn">اختبار الاكتشاف الآن</button></form></div>
<div class="grid">
<section class="card span-7"><div class="card-title"><div><h2>تشغيل بحث جديد</h2><span class="muted small">يمكن ترك الاستعلامات فارغة ليستخدم وليد قائمة البحث الافتراضية.</span></div><?=AdminUi::badge($searchReady?'verified':'warning')?></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_hunt"><input type="hidden" name="return" value="/api/admin/opportunity-hunt.php">
<div class="form-row"><div class="field"><label>آخر كام يوم؟</label><input type="number" min="1" max="60" name="lookback_days" value="<?=e(setting('opportunities.lookback_days','15'))?>"></div><div class="field"><label>عدد النتائج الخام المستهدف</label><input type="number" min="5" max="100" name="raw_target" value="<?=e(setting('opportunities.default_raw_target','30'))?>"></div></div>
<div class="field"><label>استعلامات إضافية — كل سطر بحث</label><textarea name="queries" placeholder="مطلوب أتمتة واتساب وCRM&#10;AI chatbot RAG freelance project&#10;مطلوب موقع وAPI integration"></textarea></div>
<button class="btn full-width">أنشئ Job بحث لوليد</button></form>
</section>
<section class="card span-5"><div class="card-title"><h2>آخر Run</h2><a class="link" href="tasks.php">المهام</a></div><?php if(!$latest):?><?=AdminUi::empty('لم يتم تشغيل بحث جديد بعد الترقية.')?><?php else:$sum=json_decode((string)($latest['summary_json']??'{}'),true)?:[];?><dl class="kvs"><dt>الحالة</dt><dd><?=AdminUi::badge($latest['state'])?></dd><dt>النتائج الخام</dt><dd><?=(int)$latest['raw_found']?></dd><dt>المؤهل</dt><dd><?=(int)$latest['qualified_found']?></dd><dt>يحتاج مراجعة</dt><dd><?=(int)$latest['review_found']?></dd><dt>المكرر</dt><dd><?=(int)$latest['duplicates_found']?></dd><dt>التحذيرات</dt><dd><?=(int)$latest['warning_count']?></dd><dt>بدأ</dt><dd><?=e(AdminUi::date($latest['started_at']))?></dd><dt>انتهى</dt><dd><?=e(AdminUi::date($latest['completed_at']))?></dd></dl><?php if(!empty($sum['warnings'])):?><details class="subtle"><summary>عرض التحذيرات</summary><pre class="json-box"><?=e(j($sum['warnings']))?></pre></details><?php endif?><?php if(!empty($sum['search_diagnostics'])):?><details class="subtle"><summary>تشخيص مزودات البحث</summary><pre class="json-box"><?=e(j($sum['search_diagnostics']))?></pre></details><?php endif;endif?></section>
<section class="card span-12"><div class="card-title"><div><h2>مصادر وليد</h2><span class="muted small">المصادر المضافة مفضلة وليست حدود البحث. البحث العام يعمل عبر المزود المرتبط.</span></div></div>
<div class="source-grid"><?php foreach($sources as $s):?><article class="source-card"><div class="card-title"><div><b><?=e($s['name'])?></b><small><?=e($s['source_key'])?> · <?=e($s['source_type'])?></small></div><?=AdminUi::badge($s['enabled']?'active':'disabled')?></div><p class="small muted"><?=e($s['base_url']?:'لا يوجد رابط ثابت — يعتمد على بحث عام')?></p><p class="small">الوصول: <?=e(AdminUi::label($s['auth_requirement']))?> · الأولوية: <?=(int)$s['priority']?></p><div class="actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_source_toggle"><input type="hidden" name="id" value="<?=$s['id']?>"><input type="hidden" name="return" value="/api/admin/opportunity-hunt.php"><button class="btn secondary small-btn"><?=$s['enabled']?'إيقاف':'تشغيل'?></button></form></div></article><?php endforeach?></div>
<details class="subtle top-gap"><summary><b>إضافة مصدر مفضل</b></summary><form method="post" action="action.php" class="top-gap"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_source_save"><input type="hidden" name="return" value="/api/admin/opportunity-hunt.php"><div class="form-row"><div class="field"><label>الاسم</label><input name="name" required></div><div class="field"><label>مفتاح داخلي إنجليزي</label><input name="source_key" required placeholder="my-source"></div></div><div class="form-row"><div class="field"><label>النوع</label><select name="source_type"><option value="web">صفحة ويب عامة</option><option value="rss">RSS</option><option value="json">JSON عام</option><option value="manual">مرجع يدوي</option></select></div><div class="field"><label>الوصول</label><select name="auth_requirement"><option value="public">عام بدون Login</option><option value="login_required">يتطلب Login</option><option value="api_required">يتطلب API</option></select></div></div><div class="field"><label>الرابط</label><input type="url" name="base_url"></div><div class="form-row"><div class="field"><label>الأولوية</label><input type="number" min="0" max="100" name="priority" value="70"></div><label class="check-row"><input type="checkbox" name="enabled" value="1" checked> مفعّل</label></div><button class="btn">حفظ المصدر</button></form></details></section>
<section class="card span-12"><div class="card-title"><h2>سجل البحث</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>الحالة</th><th>الفترة</th><th>خام</th><th>مؤهل</th><th>مراجعة</th><th>مرفوض</th><th>مكرر</th><th>تحذيرات</th><th>المهمة</th><th>الوقت</th></tr></thead><tbody><?php foreach($runs as $r):?><tr><td>#<?=$r['id']?></td><td><?=AdminUi::badge($r['state'])?></td><td><?=e(AdminUi::date($r['date_from']))?> ← <?=e(AdminUi::date($r['date_to']))?></td><td><?=(int)$r['raw_found']?></td><td><?=(int)$r['qualified_found']?></td><td><?=(int)$r['review_found']?></td><td><?=(int)$r['rejected_found']?></td><td><?=(int)$r['duplicates_found']?></td><td><?=(int)$r['warning_count']?></td><td><?=$r['task_id']?'<a class="link" href="tasks.php?id='.(int)$r['task_id'].'">#'.(int)$r['task_id'].'</a>':'—'?></td><td><?=e(AdminUi::date($r['completed_at']?:$r['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
</div>
<?php AdminUi::footer();
