<?php
declare(strict_types=1);
final class OpportunityService {
    public static function get(int $id):array{$q=db()->prepare('SELECT o.*,a.display_name discovered_by FROM opportunities o LEFT JOIN agents a ON a.id=o.discovered_by_agent_id WHERE o.id=?');$q->execute([$id]);$o=$q->fetch();if(!$o)throw new RuntimeException('opportunity_not_found');return $o;}
    public static function approve(int $id,string $actor='owner'):array{
        $pdo=db();$o=self::get($id);$ramy=AgentService::bySlug('ramy');$walid=AgentService::bySlug('walid');
        $pricing=PricingPolicy::recommend($o['budget_min']!==null?(float)$o['budget_min']:null,$o['budget_max']!==null?(float)$o['budget_max']:null,(float)$o['estimated_cost'],(string)$o['risk_level']);
        $customerId=(int)($o['customer_id']??0);$projectId=(int)($o['project_id']??0);$quoteId=(int)($o['quote_id']??0);$ramyTask=0;$created=[];
        $pdo->beginTransaction();
        try{
            $pdo->prepare("UPDATE opportunities SET status='approved',fit_status=IF(fit_status='rejected','review',fit_status),owner_decided_at=NOW(),rejection_reason=NULL WHERE id=?")->execute([$id]);
            if(!empty($o['fingerprint']))$pdo->prepare("UPDATE opportunity_fingerprints SET decision='active',reason=NULL,last_seen_at=NOW() WHERE fingerprint=?")->execute([$o['fingerprint']]);
            if(!$customerId){
                $methods=json_decode((string)($o['contact_methods_json']??'[]'),true);$methods=is_array($methods)?$methods:[];$phone=null;$email=null;
                foreach($methods as $m){if(!is_array($m))continue;$type=(string)($m['type']??'');$value=trim((string)($m['value']??''));if(!$phone&&in_array($type,['whatsapp','phone'],true))$phone=preg_replace('/\D+/','',$value);if(!$email&&$type==='email'&&filter_var($value,FILTER_VALIDATE_EMAIL))$email=$value;}
                $contact=trim((string)($o['client_contact']??''));if(!$phone&&preg_match('/\+?[0-9][0-9\s-]{7,}/',$contact,$m))$phone=preg_replace('/\D+/','',$m[0]);if(!$email&&filter_var($contact,FILTER_VALIDATE_EMAIL))$email=$contact;
                $q=$pdo->prepare("INSERT INTO customers(display_name,phone,email,external_ref,primary_channel,status,notes) VALUES (?,?,?,?,?,'lead',?)");$q->execute([trim((string)$o['client_name'])?:('عميل فرصة #'.$id),$phone?:null,$email?:null,'opportunity:'.$id,$phone?'whatsapp':($email?'email':'platform'),'فرصة #'.$id.' من '.$o['source']]);$customerId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE opportunities SET customer_id=? WHERE id=?')->execute([$customerId,$id]);$created[]='customer';
            }
            if(!$projectId){
                $uid=substr(hash('sha256','opportunity:'.$id.'|'.$o['title']),0,16);$name=trim((string)($o['title_ar']??''))?:trim((string)$o['title']);
                $q=$pdo->prepare("INSERT INTO projects(uid,opportunity_id,name,status,workflow_stage,hosting_presence,source,metadata_json) VALUES (?, ?, ?, 'development','approved','unknown','client_project',?)");$q->execute([$uid,$id,pb_substr($name,0,190),j(['opportunity_source'=>$o['source'],'opportunity_url'=>$o['source_url'],'approved_at'=>now_utc()])]);$projectId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE opportunities SET project_id=? WHERE id=?')->execute([$projectId,$id]);$pdo->prepare("INSERT INTO customer_projects(customer_id,project_id,relationship) VALUES (?,?,'owner') ON DUPLICATE KEY UPDATE relationship='owner'")->execute([$customerId,$projectId]);
                foreach(['ramy'=>'manage','walid'=>'read','ayman'=>'read','emad'=>'read'] as $slug=>$scope){$aid=(int)AgentService::bySlug($slug)['id'];$pdo->prepare("INSERT INTO agent_project_access(agent_id,project_id,access_scope) VALUES (?,?,?) ON DUPLICATE KEY UPDATE access_scope=IF(FIELD(VALUES(access_scope),'read','work','manage')>FIELD(access_scope,'read','work','manage'),VALUES(access_scope),access_scope)")->execute([$aid,$projectId,$scope]);}$created[]='project';
            }
            if(!$quoteId && $pricing['price']!==null && OpportunityMoney::normalizeCurrency((string)($o['currency']??''))!=='UNK'){
                $q=$pdo->prepare("SELECT id FROM quotes WHERE project_id=? AND customer_id=? AND status IN ('draft','owner_review') ORDER BY id DESC LIMIT 1");$q->execute([$projectId,$customerId]);$quoteId=(int)($q->fetchColumn()?:0);
                if(!$quoteId){$scope=trim((string)($o['requirements_text']??''))?:trim((string)($o['summary_ar']??''))?:'يُستكمل نطاق العمل بعد جمع متطلبات العميل.';$pdo->prepare("INSERT INTO quotes(customer_id,project_id,title,scope_text,amount,currency,deposit_percent,owner_exception_required,status,owner_approved) VALUES (?,?,?,?,?,?,?,0,'draft',0)")->execute([$customerId,$projectId,'عرض مبدئي: '.(trim((string)($o['title_ar']??''))?:$o['title']),$scope,(float)$pricing['price'],$o['currency'],(float)$pricing['deposit_percent']]);$quoteId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE opportunities SET quote_id=? WHERE id=?')->execute([$quoteId,$id]);$created[]='quote';}
            }
            $q=$pdo->prepare("SELECT id FROM tasks WHERE project_id=? AND assigned_agent_id=? AND title=? AND status NOT IN ('completed','cancelled','failed') ORDER BY id DESC LIMIT 1");$taskTitle='متابعة فرصة #'.$id;$q->execute([$projectId,(int)$ramy['id'],$taskTitle]);$ramyTask=(int)($q->fetchColumn()?:0);
            if(!$ramyTask){$ramyTask=TaskService::create('ramy',$taskTitle,"استلم فرصة وليد #$id. راجع العميل ووسائل التواصل، اجمع المتطلبات، تفاوض داخل سياسة السعر، وجهز العرض والـMaster Brief عند الاتفاق. لا تبدأ التنفيذ قبل تأكيد العربون.",$projectId,['opportunity_id'=>$id,'customer_id'=>$customerId,'quote_id'=>$quoteId?:null,'job_kind'=>'ramy_followup'],'high',true,null,$actor==='owner'?'owner':'agent',$actor==='owner'?'1':$actor,false);$created[]='ramy_task';}
            $pdo->commit();
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
        $o=self::get($id);$walidNote='تسليم وليد للفرصة #'.$id."\nالعنوان: ".(trim((string)($o['title_ar']??''))?:$o['title'])."\nالمصدر: ".$o['source'].($o['source_url']?"\nالرابط: ".$o['source_url']:'').($o['selection_reason']?"\nسبب الاختيار: ".$o['selection_reason']:'');
        try{ProjectChatService::post($projectId,'agent','walid',$walidNote,'handoff','opportunity',(string)$id,true);ProjectChatService::post($projectId,'system','opportunity','تم قبول فرصة وليد #'.$id.' وإنشاء حزمة التفاوض لرامي.','handoff','opportunity',(string)$id,true);TeamChatService::post('agent','walid','ramy',$walidNote,'status',$projectId,null,['opportunity_id'=>$id,'handoff'=>1]);}catch(Throwable){}
        try{TaskService::queueIfReady($ramyTask);}catch(Throwable $e){Notifications::add('warning','tasks','تم قبول الفرصة وتعذر تشغيل متابعة رامي',AdminUi::humanError($e->getMessage()),'task',(string)$ramyTask);}
        Notifications::add('success','opportunities','تم قبول فرصة وليد','تم تجهيز العميل والمشروع'.($quoteId?' والعرض المبدئي':'').' ومهمة رامي #'.$ramyTask.'.','opportunity',(string)$id);
        Audit::log($actor==='owner'?'owner':'agent',$actor==='owner'?'1':$actor,'opportunity.approve','opportunity',(string)$id,'verified',$projectId,$ramyTask,['pricing'=>$pricing,'quote_id'=>$quoteId?:null,'created'=>$created]);
        return ['opportunity_id'=>$id,'project_id'=>$projectId,'customer_id'=>$customerId,'quote_id'=>$quoteId?:null,'ramy_task_id'=>$ramyTask,'pricing'=>$pricing,'created'=>$created];
    }
    public static function reject(int $id,string $reason):void{$o=self::get($id);$reason=trim($reason)?:'رفض المالك';db()->prepare("UPDATE opportunities SET status='rejected',fit_status='rejected',owner_decided_at=NOW(),rejection_reason=? WHERE id=?")->execute([$reason,$id]);if(!empty($o['fingerprint']))db()->prepare("INSERT INTO opportunity_fingerprints(fingerprint,opportunity_id,decision,title_normalized,client_normalized,source_normalized,reason) VALUES (?,?,'rejected',LOWER(?),LOWER(?),LOWER(?),?) ON DUPLICATE KEY UPDATE opportunity_id=VALUES(opportunity_id),decision='rejected',reason=VALUES(reason),last_seen_at=NOW()")->execute([$o['fingerprint'],$id,$o['title'],$o['client_name']??'',$o['source'],$reason]);$walid=(int)AgentService::bySlug('walid')['id'];AgentLearningService::propose($walid,'search_preference','رفض المالك فرصة "'.$o['title'].'". السبب: '.$reason,null,null,80);Audit::log('owner','1','opportunity.reject','opportunity',(string)$id,'verified',null,null,['reason'=>$reason]);}
    public static function markContacted(int $id):void{db()->prepare("UPDATE opportunities SET status='contacted',ramy_contacted_at=COALESCE(ramy_contacted_at,NOW()) WHERE id=?")->execute([$id]);$o=self::get($id);if($o['project_id'])ProjectStageService::set((int)$o['project_id'],'negotiating','agent',(string)AgentService::bySlug('ramy')['id'],'بدأ رامي التواصل مع العميل',true);}
    public static function createDraftQuote(int $id):array{$o=self::get($id);if(!$o['project_id']||!$o['customer_id'])self::approve($id);$o=self::get($id);if(OpportunityMoney::normalizeCurrency((string)($o['currency']??''))==='UNK')throw new RuntimeException('opportunity_currency_unverified');$p=PricingPolicy::recommend($o['budget_min']!==null?(float)$o['budget_min']:null,$o['budget_max']!==null?(float)$o['budget_max']:null,(float)$o['estimated_cost'],(string)$o['risk_level']);if($p['price']===null)throw new RuntimeException('opportunity_budget_missing');$q=db()->prepare("SELECT id FROM quotes WHERE project_id=? AND customer_id=? AND status IN ('draft','owner_review') ORDER BY id DESC LIMIT 1");$q->execute([(int)$o['project_id'],(int)$o['customer_id']]);$qid=(int)($q->fetchColumn()?:0);if(!$qid){db()->prepare("INSERT INTO quotes(customer_id,project_id,title,scope_text,amount,currency,deposit_percent,owner_exception_required,status,owner_approved) VALUES (?,?,?,?,?,?,?,0,'draft',0)")->execute([(int)$o['customer_id'],(int)$o['project_id'],'عرض: '.$o['title'],$o['requirements_text'],(float)$p['price'],$o['currency'],(float)$p['deposit_percent']]);$qid=(int)db()->lastInsertId();db()->prepare('UPDATE opportunities SET quote_id=? WHERE id=?')->execute([$qid,$id]);}return ['quote_id'=>$qid,'pricing'=>$p];}
}
