<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();

$id=(int)($_GET['id']??0);$status=(string)($_GET['status']??'');
$valid=['new','needs_review','approved','rejected','contacted','negotiating','won','lost'];
$money=static function($value,string $currency='UNK'):string{if($value===null||$value===''||(float)$value<=0)return 'غير معلنة';$c=OpportunityMoney::normalizeCurrency($currency);return number_format((float)$value,0).' '.($c==='UNK'?'(عملة غير مؤكدة)':$c);};
$jsonList=static function($raw):array{$x=json_decode((string)($raw??''),true);return is_array($x)?$x:[];};
$clientType=static fn(string $v)=>match($v){'business'=>'شركة','individual'=>'فرد','agency'=>'وكالة',default=>'غير محدد'};

AdminUi::header($id?'تفاصيل الفرصة':'الفرص والمشاريع','orders');echo AdminUi::flash();

if($id){
    $q=db()->prepare("SELECT o.*,a.display_name agent_name,c.display_name customer_name,q.id quote_id,q.status quote_status,q.amount quote_amount FROM opportunities o LEFT JOIN agents a ON a.id=o.discovered_by_agent_id LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN quotes q ON q.id=o.quote_id WHERE o.id=? LIMIT 1");$q->execute([$id]);$o=$q->fetch();if(!$o)throw new RuntimeException('opportunity_not_found');
    $tags=$jsonList($o['tags_json']??null);$missing=$jsonList($o['missing_fields_json']??null);$breakdown=$jsonList($o['score_breakdown_json']??null);$summary=trim((string)($o['summary_ar']??''))?:trim((string)$o['requirements_text']);$offer=(float)($o['suggested_offer']??0);$deposit=(float)($o['suggested_deposit']??0);$cost=(float)($o['estimated_cost']??0);$profit=(float)($o['projected_profit']??0);$score=(int)$o['score'];
    ?>
    <div class="toolbar"><a class="btn secondary" href="orders.php">← رجوع للفرص</a><?php if($o['source_url']):?><a class="btn secondary" target="_blank" rel="noopener" href="<?=e($o['source_url'])?>">فتح المصدر ↗</a><?php endif?></div>
    <section class="opportunity-hero">
      <div class="opportunity-score score-<?=$score>=80?'great':($score>=65?'good':'review')?>"><strong><?=$score?></strong><span>/100</span></div>
      <div class="opportunity-main">
        <div class="opportunity-meta"><span class="source-chip"><?=e($o['source'])?></span><?php if(!empty($o['shortlist_rank'])):?><span class="rank-chip">#<?=(int)$o['shortlist_rank']?> مختارة</span><?php endif?><span><?=e($o['country']?:'دولة غير محددة')?> · <?=e(AdminUi::relative($o['last_verified_at']??$o['published_at']??$o['created_at']))?></span></div>
        <h2><?=e(trim((string)($o['title_ar']??''))?:$o['title'])?></h2>
        <?php if(trim((string)($o['title_ar']??''))!==''&&trim((string)$o['title'])!==trim((string)$o['title_ar'])):?><small class="muted block">العنوان الأصلي: <?=e($o['title'])?></small><?php endif?>
        <p><?=e($summary)?></p>
        <div class="tag-row"><?php foreach(array_slice($tags,0,8) as $tag):?><span><?=e((string)$tag)?></span><?php endforeach?><?php if($o['opportunity_type']??''):?><span><?=e($o['opportunity_type'])?></span><?php endif?><?=AdminUi::badge((string)$o['status'])?></div>
      </div>
    </section>

    <div class="commercial-grid">
      <section class="premium-card"><small>ميزانية العميل</small><strong><?=e($money($o['budget_max']?:$o['budget_min'],$o['currency']))?></strong><span><?=trim((string)($o['advertised_budget_text']??''))!==''?'المعلن: '.e($o['advertised_budget_text']):(($o['budget_min']&&$o['budget_max']&&$o['budget_min']!=$o['budget_max'])?e($money($o['budget_min'],$o['currency']).' — '.$money($o['budget_max'],$o['currency'])):'لم يظهر سعر معلن موثوق')?></span></section>
      <section class="premium-card"><small>عرضنا المقترح</small><strong class="accent-value"><?=e($offer>0?$money($offer,$o['currency']):'يحتاج تسعير')?></strong><span><?=e(setting('business.offer_percent','85'))?>% سياسة عرض افتراضية</span></section>
      <section class="premium-card"><small>التكلفة المتوقعة</small><strong><?=e($cost>0?$money($cost,$o['currency']):'تحتاج تقدير')?></strong><span>تقدير تنفيذ داخلي</span></section>
      <section class="premium-card"><small>صافي الربح المتوقع</small><strong class="accent-value"><?=e($profit>0?$money($profit,$o['currency']):'—')?></strong><span>قبل أي مصاريف خارجية غير مسجلة</span></section>
      <section class="premium-card"><small>العربون المقترح</small><strong><?=e($deposit>0?$money($deposit,$o['currency']):'—')?></strong><span><?=e(setting('business.deposit_percent','40'))?>% قبل بدء التنفيذ</span></section>
      <section class="premium-card"><small>مدة التنفيذ</small><strong><?=!empty($o['estimated_days'])?(int)$o['estimated_days'].' يوم':'غير محسومة'?></strong><span>تقدير أولي قابل للتعديل</span></section>
    </div>

    <div class="grid top-gap">
      <section class="card span-7"><div class="card-title"><div><h2>معلومات الفرصة</h2><span class="muted small">كل ما عرفه وليد من المصدر والتحليل.</span></div><?=AdminUi::badge((string)($o['fit_status']??$o['status']))?></div>
        <dl class="kvs opportunity-kvs"><dt>نوع المشروع</dt><dd><?=e($o['opportunity_type']?:($o['category']?:'غير محدد'))?></dd><dt>الفئة</dt><dd><?=e($o['category']?:'—')?></dd><dt>نوع العميل</dt><dd><?=e($clientType((string)($o['client_type']??'')))?></dd><dt>اسم العميل</dt><dd><?=e($o['client_name']?:'غير معروف')?></dd><dt>التواصل</dt><dd><?=e($o['client_contact']?:'غير متوفر')?></dd><dt>اللغة</dt><dd><?=e(strtoupper((string)($o['language']??''))?:'غير محددة')?></dd><dt>العملة</dt><dd><?=e(OpportunityMoney::normalizeCurrency((string)$o['currency'])==='UNK'?'غير مؤكدة من المصدر':AdminUi::currency((string)$o['currency']))?></dd><dt>المخاطر</dt><dd><?=e($o['risk_level']?:'غير مقيمة')?></dd><dt>الصعوبة</dt><dd><?=e(AdminUi::label((string)($o['difficulty']??'unknown')))?></dd><dt>الوصول</dt><dd><?=e(AdminUi::label((string)($o['login_requirement']??'unknown')))?></dd><dt>جودة المصدر</dt><dd><?=(int)($o['source_quality']??0)?>/100</dd><dt>ثقة أنه طلب مشروع</dt><dd><?=(int)($o['intent_confidence']??0)?>/100</dd><dt>آخر تحقق</dt><dd><?=e(AdminUi::date($o['last_verified_at']??null))?></dd></dl>
      </section>
      <section class="card span-5"><div class="card-title"><h2>لماذا رشحه وليد؟</h2></div><p class="opportunity-reason"><?=e($o['selection_reason']?:($o['rejection_reason']?:'لم يسجل سبب تفصيلي بعد.'))?></p><?php if($missing):?><h3 class="section-subtitle">معلومات ناقصة</h3><div class="tag-row warning-tags"><?php foreach($missing as $m):?><span><?=e((string)$m)?></span><?php endforeach?></div><?php endif?></section>
      <section class="card span-12"><div class="card-title"><div><h2>وصف وليد بالعربية</h2><span class="muted small">تلخيص تفصيلي من نص المصدر بدون اختراع بيانات.</span></div></div><p class="opportunity-reason"><?=e(trim((string)($o['details_ar']??''))?:$summary?:'لا يوجد وصف عربي تفصيلي محفوظ لهذه الفرصة التاريخية.')?></p></section>
      <section class="card span-12"><div class="card-title"><div><h2>تفصيل التقييم</h2><span class="muted small">لماذا حصلت الفرصة على <?=$score?>/100.</span></div></div><div class="score-breakdown"><?php $labels=['execution_fit'=>'ملاءمة أيمن','profitability'=>'الربحية','cost_efficiency'=>'كفاءة التكلفة','difficulty_fit'=>'سهولة التنفيذ','requirements_clarity'=>'وضوح المطلوب','intent_confidence'=>'ثقة أنه طلب شراء','freshness'=>'الحداثة','client_trust'=>'ثقة العميل','contactability'=>'سهولة التواصل','source_quality'=>'جودة المصدر','risk_safety'=>'أمان المخاطر','budget_quality'=>'جودة الميزانية','competition'=>'المنافسة','source_verification'=>'تحقق المصدر','currency_evidence'=>'دليل العملة'];foreach($labels as $k=>$label):$v=(int)($breakdown[$k]??0);?><div><div><span><?=e($label)?></span><b><?=$v?>/100</b></div><div class="progress"><span style="width:<?=$v?>%"></span></div></div><?php endforeach?></div></section>
      <section class="card span-12"><div class="card-title"><h2>الإجراء التالي</h2></div><div class="actions"><?php if(in_array($o['status'],['new','needs_review'],true)):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_decide"><input type="hidden" name="id" value="<?=$o['id']?>"><input type="hidden" name="decision" value="approved"><input type="hidden" name="return" value="/api/admin/orders.php?id=<?=$o['id']?>"><button class="btn">✓ موافقة وتجهيز العرض</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_decide"><input type="hidden" name="id" value="<?=$o['id']?>"><input type="hidden" name="decision" value="rejected"><input type="hidden" name="return" value="/api/admin/orders.php"><button class="btn danger">✕ استبعاد</button></form><?php endif?><?php if(in_array($o['status'],['approved','contacted','negotiating'],true)):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_contact"><input type="hidden" name="id" value="<?=$o['id']?>"><input type="hidden" name="return" value="/api/admin/orders.php?id=<?=$o['id']?>"><button class="btn">بدء/تسجيل تواصل رامي</button></form><?php endif?><?php if($o['customer_id']):?><a class="btn secondary" href="customers.php?id=<?=$o['customer_id']?>">ملف العميل</a><?php endif?><?php if($o['project_id']):?><a class="btn secondary" href="project.php?id=<?=$o['project_id']?>">فتح المشروع</a><?php endif?></div></section>
    </div>
    <?php AdminUi::footer();exit;
}

$where=$status&&in_array($status,$valid,true)?' WHERE o.status='.db()->quote($status):" WHERE o.status NOT IN ('rejected','lost')";
$rows=db()->query("SELECT o.*,a.display_name agent_name,c.display_name customer_name,q.id quote_id,q.status quote_status FROM opportunities o LEFT JOIN agents a ON a.id=o.discovered_by_agent_id LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN quotes q ON q.id=o.quote_id".$where." ORDER BY COALESCE(o.last_verified_at,o.discovered_at,o.created_at) DESC,o.id DESC LIMIT 300")->fetchAll();
$stats=db()->query("SELECT COUNT(*) total,SUM(status IN ('new','needs_review')) new_count,SUM(status IN ('approved','contacted','negotiating')) active_count FROM opportunities")->fetch();$profitRows=db()->query("SELECT UPPER(currency) currency,COALESCE(SUM(projected_profit),0) amount FROM opportunities WHERE status IN ('new','needs_review','approved','contacted','negotiating') AND currency<>'UNK' GROUP BY UPPER(currency) ORDER BY amount DESC")->fetchAll();$profitLabel=$profitRows?implode(' + ',array_map(static fn($r)=>number_format((float)$r['amount'],0).' '.AdminUi::currency((string)$r['currency']),$profitRows)):'0';
$methods=db()->query("SELECT * FROM payment_methods WHERE enabled=1 AND show_on_quotes=1 ORDER BY id")->fetchAll();
?>
<div class="toolbar premium-toolbar"><a class="btn secondary" href="orders.php">كل الفرص</a><?php foreach(['new'=>'جديدة','needs_review'=>'تحتاج مراجعة','approved'=>'مقبولة','contacted'=>'تواصل رامي','negotiating'=>'تفاوض','won'=>'مغلقة بنجاح','rejected'=>'مستبعدة'] as $k=>$l):?><a class="btn secondary" href="orders.php?status=<?=$k?>"><?=$l?></a><?php endforeach?><a class="btn" href="agent-profile.php?slug=walid">تشغيل ومتابعة وليد</a></div>
<div class="metric-grid"><?=AdminUi::stat('فرص جديدة',(int)$stats['new_count'])?><?=AdminUi::stat('قيد التفاوض',(int)$stats['active_count'])?><?=AdminUi::stat('إجمالي الفرص',(int)$stats['total'])?><?=AdminUi::stat('ربح متوقع حسب العملة',$profitLabel)?></div>

<?php if($methods):?><section class="card payment-methods-card"><div class="card-title"><div><h2>وسائل تحصيل العربون</h2><span class="muted small">تظهر لرامي عند تجهيز العرض للعميل المباشر.</span></div><span class="badge s-active">مفعلة</span></div><div class="payment-method-grid"><?php foreach($methods as $m):?><div><b><?=e($m['label'])?></b><span><?=e($m['holder_name']?:'')?></span><strong dir="ltr"><?=e($m['account_reference']?:'—')?></strong></div><?php endforeach?></div></section><?php endif?>

<div class="section-head"><div><h2>أحدث الفرص <span class="count-pill"><?=count($rows)?></span></h2><p class="muted small">المشروعات التي بحث عنها وليد أو أعاد التحقق منها مؤخرًا تظهر أولًا، مع الحفاظ على العملة الأصلية.</p></div></div>
<?php if(!$rows):?><?=AdminUi::empty('لا توجد فرص مطابقة. شغّل وليد أو وسّع فترة البحث من صفحة الوكيل.')?><?php endif?>
<div class="opportunity-list-v48">
<?php $displayRank=0;foreach($rows as $o):$displayRank++;echo AdminUi::opportunityCard($o,$displayRank,'/api/admin/orders.php',false);endforeach?>
</div>

<section class="card top-gap"><details><summary class="details-summary">إضافة فرصة يدويًا</summary><form class="top-gap" method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_create"><input type="hidden" name="return" value="/api/admin/orders.php"><div class="form-row"><div class="field"><label>عنوان الطلب</label><input name="title" required></div><div class="field"><label>المصدر</label><input name="source" required placeholder="مستقل / إحالة / موقع عام"></div></div><div class="field"><label>رابط المصدر</label><input name="source_url" type="url"></div><div class="form-row"><div class="field"><label>اسم العميل</label><input name="client_name"></div><div class="field"><label>هاتف/وسيلة تواصل</label><input name="client_contact"></div></div><div class="field"><label>متطلبات المشروع</label><textarea name="requirements_text" required></textarea></div><div class="form-row"><div class="field"><label>ميزانية من</label><input type="number" min="0" step="0.01" name="budget_min"></div><div class="field"><label>ميزانية إلى</label><input type="number" min="0" step="0.01" name="budget_max"></div><div class="field"><label>العملة</label><select name="currency" required><option value="UNK" selected>اختر العملة / غير مؤكدة</option><option value="EGP">EGP — جنيه مصري</option><option value="USD">USD — دولار</option><option value="EUR">EUR — يورو</option><option value="GBP">GBP — جنيه إسترليني</option><option value="SAR">SAR — ريال سعودي</option><option value="AED">AED — درهم إماراتي</option><option value="KWD">KWD — دينار كويتي</option><option value="QAR">QAR — ريال قطري</option></select></div></div><div class="form-row"><div class="field"><label>تكلفة متوقعة</label><input type="number" min="0" name="estimated_cost"></div><div class="field"><label>التقييم /100</label><input type="number" min="0" max="100" name="score" value="50"></div></div><div class="field"><label>ملاحظات</label><textarea name="raw_details"></textarea></div><button class="btn">إضافة كفرصة جديدة</button></form></details></section>
<?php AdminUi::footer();
