<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);
$explicit=null;$runtimeRequested=false;
foreach(($argv??[]) as $arg){
    if($arg==='--runtime')$runtimeRequested=true;
    if(in_array($arg,['--owner','--full','--allow-config'],true))$explicit='owner';
    if(in_array($arg,['--no-secrets','--public'],true))$explicit='no_secrets';
}
$secretFiles=['private/config.php','private/runtime/master.key','private/runtime/secrets.enc','private/runtime/vault.lock'];
$ownerSignals=0;foreach(array_slice($secretFiles,0,3) as $secret)if(is_file($root.'/'.$secret)&&filesize($root.'/'.$secret)>0)$ownerSignals++;
$runtime=$runtimeRequested||!is_dir($root.'/database');$mode=($runtime?'runtime_':'').($explicit??($ownerSignals>=3?'owner':'no_secrets'));
$fail=[];$ok=[];$warn=[];$required=[
'public_html/api/src/bootstrap.php','public_html/api/src/ReleaseInfo.php','public_html/api/src/AgentBrainService.php','public_html/api/src/AgentCapabilityService.php','public_html/api/src/AgentPolicyEngine.php','public_html/api/src/AgentUsageBudgetService.php','public_html/api/src/AgentInitiativeService.php','public_html/api/src/CoreAgentInitiativeService.php','public_html/api/src/CreatorIntelligenceService.php','public_html/api/src/AgentAutonomyService.php','public_html/api/src/AgentChangeProposalService.php','public_html/api/src/AgentResourceService.php','public_html/api/src/ResourceRegistryService.php','public_html/api/src/PhysicalSchemaService.php','public_html/api/src/AgentWorkflowService.php','public_html/api/src/VoiceAgentCenterService.php','public_html/api/src/ProviderCapabilityRouter.php','public_html/api/src/AiCapabilityRouter.php','public_html/api/src/AgentBuilderService.php','public_html/api/src/MigrationPreflightService.php','public_html/api/src/MigrationRunner.php','public_html/api/src/MigrationRunnerService.php','public_html/api/src/SchemaPreflightService.php','public_html/api/src/PromptCanonicalizerService.php','public_html/api/src/VaultSnapshotService.php','public_html/api/src/ConfigSnapshotService.php','public_html/api/src/ProspectPrototypeService.php','public_html/api/src/AgencyEventService.php','public_html/api/src/VideoStudioService.php','public_html/api/src/SocialPlaybookService.php','public_html/api/src/RuntimeValidationService.php','public_html/api/src/SystemDoctor.php',
'public_html/api/admin/agent-builder.php','public_html/api/admin/initiatives.php','public_html/api/admin/creator-intelligence.php','public_html/api/admin/resources.php','public_html/api/admin/workflow-builder.php','public_html/api/admin/voice.php','public_html/api/admin/provider-center.php','public_html/api/admin/data-sources.php','public_html/api/admin/migration.php','public_html/api/admin/doctor.php',
'public_html/api/src/PostInstallAcceptanceService.php','public_html/api/src/IntegrationHealthService.php','public_html/api/src/DeploymentFingerprintService.php','public_html/api/admin/post-install-acceptance.php','public_html/api/admin/integration-health.php','public_html/api/admin/deployment-status.php','private/bin/migrate-20.php','private/bin/static-call-check.php','private/bin/acceptance-20.php','private/bin/post-install-verify-20.php','private/bin/post-install-verify-201.php','private/bin/acceptance-201.php'];
foreach($required as $rel){if(is_file($root.'/'.$rel))$ok[]='required '.$rel;else $fail[]='missing '.$rel;}
if(str_ends_with($mode,'no_secrets')){foreach($secretFiles as $secret){if(is_file($root.'/'.$secret))$fail[]=$secret.' must not be shipped in NO_SECRETS';else $ok[]='no '.$secret;}}else{foreach(array_slice($secretFiles,0,3) as $secret){if(is_file($root.'/'.$secret)&&filesize($root.'/'.$secret)>0)$ok[]='owner package includes '.$secret;else $fail[]='owner package missing/empty '.$secret;}if(is_file($root.'/private/runtime/vault.lock'))$ok[]='owner package includes vault.lock';$ok[]='owner package mode auto-detected or explicitly selected';}
if(!$runtime){
$baseSqlPath=$root.'/database/upgrade_companyos_17_19_to_20_0_final_unified.sql';$sqlPath=$root.'/database/upgrade_companyos_20_0_to_20_1_maintenance.sql';$freshPath=$root.'/database/PerseBayt_CompanyOS_20.1_FULL_FRESH_DATABASE_WITH_CURRENT_DATA.sql';
foreach([$baseSqlPath,$sqlPath,$freshPath] as $path)if(!is_file($path))$fail[]='delivery SQL missing '.basename($path);
$baseSql=@file_get_contents($baseSqlPath)?:'';$sql=@file_get_contents($sqlPath)?:'';$fresh=@file_get_contents($freshPath)?:'';
$steps=['17_migration_ledger','17_policy_superset','17_capabilities_and_budgets','17_initiatives_and_goals','17_creator_intelligence','17_resources_and_physical_schema','17_workflow_superset','17_voice_superset','17_provider_routes_and_builder','17_workflow_seed','17_prompt_canonicalization','17_sources_and_vault','17_permissions_and_assignments','17_runtime_validation_and_release','19_brain_and_usage','19_creator_intelligence','19_workflow_runtime','19_provider_routes','19_prompt_canonicalization','19_data_sources','19_runtime_policy_seed','20_superset_integrity','20_policy_and_workflow_canonical','20_prompt_canonicalization','20_data_sources_and_routes','20_runtime_validation_and_release'];
foreach($steps as $step){if(str_contains($baseSql,'-- @step: '.$step))$ok[]='base migration step '.$step;else $fail[]='base migration missing step '.$step;}if(str_contains($sql,'companyos_20_1_maintenance'))$ok[]='maintenance migration marker';else $fail[]='maintenance migration marker missing';
$needles=['agent_policy_rules','agent_policy_decisions','agent_usage_daily','agent_usage_events','agent_goal_contributions','creator_intelligence_snapshots','resource_registry','resource_requests','physical_schema_requests','agent_schema_requests','agent_workflow_steps','agent_workflow_runs','secure_vault_snapshots','secure_config_snapshots','provider_capability_routes','auto_execute_max_risk','v20_core_acceptance','companyos_20_0_final_unified','CompanyOS 20 canonical active prompt'];foreach($needles as $needle){if(str_contains($baseSql,$needle)&&str_contains($fresh,$needle))$ok[]='SQL contains '.$needle;else $fail[]='SQL missing '.$needle.' in base upgrade or full fresh';}
foreach(['image','video','browser','embeddings'] as $cap){if(str_contains($baseSql,"('".$cap."',"))$ok[]='provider route '.$cap;else $fail[]='provider route missing '.$cap;}
$san=preg_replace('/--[^\n]*/','',$sql);if(preg_match('/\b(?:DELETE\s+FROM|TRUNCATE\s+(?:TABLE\s+)?|DROP\s+TABLE)\b/i',(string)$san,$m))$fail[]='destructive upgrade SQL detected: '.$m[0];else $ok[]='upgrade has no DELETE/TRUNCATE/DROP TABLE';
if(str_contains($baseSql,'INSERT INTO `secure_vault_snapshots`')&&str_contains($baseSql,'INSERT INTO `secure_config_snapshots`'))$ok[]='encrypted current vault/config snapshot seed present';else $fail[]='encrypted vault/config snapshot seed missing';
}else{$ok[]='runtime deployment mode: delivery SQL artifacts intentionally not required';}
$release=@file_get_contents($root.'/public_html/api/src/ReleaseInfo.php')?:'';$releaseVersionOk=preg_match("/VERSION='20\.1\.[^']*'/",$release)===1;if($releaseVersionOk)$ok[]='release VERSION=20.1.x';else $fail[]='release missing VERSION=20.1.x';foreach(["SCHEMA='20.0'","function label","PromptCanonicalizerService::applyAll","ProviderCapabilityRouter::syncFromProviders"] as $n){if(str_contains($release,$n))$ok[]='release '.$n;else $fail[]='release missing '.$n;}
$router=@file_get_contents($root.'/public_html/api/src/ProviderCapabilityRouter.php')?:'';foreach(['function embedding','function vision','function webSearch','function realtimeVoice','function syncFromProviders','function markRouteHealth','function markProviderHealth','function image','function video','function browser','recordDirectImage'] as $n){if(str_contains($router,$n))$ok[]='router '.$n;else $fail[]='router missing '.$n;}
if(str_contains($router,'embedLegacy'))$fail[]='router contains obsolete embedLegacy';else $ok[]='no obsolete embedLegacy';
$workflow=@file_get_contents($root.'/public_html/api/src/AgentWorkflowService.php')?:'';foreach(['waiting_task_id','on_failure','policy_decision_id','workflow.run','workflow.step'] as $n){if(str_contains($workflow,$n))$ok[]='workflow '.$n;else $fail[]='workflow missing '.$n;}
$policy=@file_get_contents($root.'/public_html/api/src/AgentPolicyEngine.php')?:'';foreach(['agent_policy_rules','AgentUsageBudgetService::authorize','AiBudgetService::assertAllowed','verified_backup_required','project_access_required','external_action_gateway_required'] as $n){if(str_contains($policy,$n))$ok[]='policy '.$n;else $fail[]='policy missing '.$n;}
$ayman=@file_get_contents($root.'/public_html/api/src/AymanRunner.php')?:'';foreach(['AiCapabilityRouter::image','AiCapabilityRouter::video'] as $n){if(str_contains($ayman,$n))$ok[]='ayman media '.$n;else $fail[]='ayman media missing '.$n;}
$php=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if($f->isFile()&&strtolower($f->getExtension())==='php')$php[]=$f->getPathname();}
$canExec=function_exists('exec')&&!in_array('exec',array_map('trim',explode(',',(string)ini_get('disable_functions'))),true);if($canExec){foreach($php as $file){$out=[];$code=0;exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($file).' 2>&1',$out,$code);if($code!==0)$fail[]='php lint '.str_replace($root.'/','',$file).' '.implode(' ',$out);}if(!array_filter($fail,fn($x)=>str_starts_with($x,'php lint ')))$ok[]='php lint '.count($php).' files';$o=[];$c=0;exec(escapeshellarg(PHP_BINARY).' '.escapeshellarg($root.'/private/bin/static-call-check.php').' 2>&1',$o,$c);if($c===0)$ok[]='static class-call check PASS';else $fail[]='static class-call check failed: '.implode(' | ',$o);}else $warn[]='exec disabled; php lint/static-call subprocess checks skipped';
$markers=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile()||$f->getPathname()===__FILE__)continue;$ext=strtolower($f->getExtension());if(!in_array($ext,['php','js','css','sql','md','txt'],true))continue;$txt=@file_get_contents($f->getPathname());if($txt!==false&&(str_contains($txt,'<<<<<<<')||str_contains($txt,'>>>>>>>'))) $markers[]=str_replace($root.'/','',$f->getPathname());}if($markers)$fail[]='merge conflict markers: '.implode(', ',$markers);else $ok[]='no merge conflict markers';
$legacyConfusion=[];foreach(['database/upgrade_companyos_11_1_13_14_to_17_0_final_unified.sql','database/PerseBayt_CompanyOS_17.0_FULL_FRESH_DATABASE_WITH_OLD_DATA.sql'] as $f)if(is_file($root.'/'.$f))$legacyConfusion[]=$f;if($legacyConfusion)$warn[]='legacy database files still present: '.implode(', ',$legacyConfusion);
echo "PerseBayt Company OS 20.1.4 RUNTIME CLOSURE package self-check (mode={$mode})\n";foreach($ok as $line)echo "[OK]   $line\n";foreach($warn as $line)echo "[WARN] $line\n";foreach($fail as $line)echo "[FAIL] $line\n";echo 'Result: '.($fail?'FAIL':'PASS')."\n";exit($fail?2:0);
