<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$rows=db()->query("SELECT p.*,c.display_name customer_name,q.title quote_title,pr.name project_name FROM payments p JOIN customers c ON c.id=p.customer_id LEFT JOIN quotes q ON q.id=p.quote_id LEFT JOIN projects pr ON pr.id=p.project_id ORDER BY p.id DESC LIMIT 500")->fetchAll();
$totals=db()->query("SELECT currency,SUM(CASE WHEN status='confirmed' THEN amount ELSE 0 END) confirmed,SUM(CASE WHEN status='pending' THEN amount ELSE 0 END) pending FROM payments GROUP BY currency")->fetchAll();
$methods=db()->query('SELECT * FROM payment_methods WHERE enabled=1 ORDER BY id')->fetchAll();
$quotes=db()->query("SELECT q.id,q.title,q.amount,q.currency,q.status,c.display_name,c.phone,(SELECT COALESCE(SUM(amount),0) FROM payments p WHERE p.quote_id=q.id AND p.status='confirmed') paid FROM quotes q JOIN customers c ON c.id=q.customer_id WHERE q.status IN ('sent','accepted') ORDER BY q.id DESC LIMIT 300")->fetchAll();
$costProjects=db()->query("SELECT p.id,p.name,p.workflow_stage FROM projects p WHERE p.is_system_project=0 ORDER BY p.id DESC LIMIT 300")->fetchAll();
$costRows=db()->query("SELECT ce.*,p.name project_name,u.full_name created_by_name FROM project_cost_entries ce JOIN projects p ON p.id=ce.project_id LEFT JOIN users u ON u.id=ce.created_by WHERE ce.status='active' ORDER BY ce.id DESC LIMIT 300")->fetchAll();
$finance=[];foreach($costProjects as $cp){try{$finance[(int)$cp['id']]=ProjectCostService::projectSummary((int)$cp['id']);}catch(Throwable){}}
AdminUi::header('الدفعات','payments');echo AdminUi::flash();
?>
<div class="grid"><section class="card span-8"><div class="card-title"><h2>سجل الدفعات</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>العميل</th><th>المشروع</th><th>العرض</th><th>النوع</th><th>المبلغ</th><th>الطريقة</th><th>المرجع</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody><?php foreach($rows as $p):?><tr><td>#<?=$p['id']?></td><td><?=e($p['customer_name']?:'—')?></td><td><?=e($p['project_name']?:'—')?></td><td><?=e($p['quote_title']?:'—')?></td><td><?=e(AdminUi::label((string)$p['payment_kind']))?></td><td><?=e(number_format((float)$p['amount'],2).' '.AdminUi::currency((string)$p['currency']))?></td><td><?=e($p['method']?:'—')?></td><td><?=e($p['reference_text']?:'—')?></td><td><?=AdminUi::badge($p['status'])?></td><td><?=e(AdminUi::date($p['confirmed_at']?:$p['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section><section class="card span-4"><div class="card-title"><h2>تسجيل دفعة مؤكدة</h2></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="payment_confirm"><div class="field"><label>العرض</label><select name="quote_id" required><option value="">اختر العرض</option><?php foreach($quotes as $q):?><option value="<?=$q['id']?>">#<?=$q['id']?> <?=e($q['display_name']?:$q['phone'])?> — <?=e($q['title'])?> — متبقي <?=e(number_format(max(0,(float)$q['amount']-(float)$q['paid']),2).' '.$q['currency'])?></option><?php endforeach?></select></div><div class="form-row"><div class="field"><label>النوع</label><select name="payment_kind"><option value="deposit">عربون</option><option value="preview">معاينة</option><option value="final">نهائي</option><option value="other">أخرى</option></select></div><div class="field"><label>المبلغ</label><input type="number" step="0.01" min="0.01" name="amount" required></div></div><div class="field"><label>الطريقة</label><select name="method"><option value="">غير محدد</option><?php foreach($methods as $m):?><option value="<?=e($m['label'])?>"><?=e($m['label'])?></option><?php endforeach?></select></div><div class="field"><label>مرجع التحويل/ملاحظة</label><input name="reference_text" placeholder="رقم العملية أو وصف التحقق"></div><button class="btn full-width" data-confirm="تأكيد أن هذه الدفعة تم استلامها والتحقق منها؟">تسجيل كدفعة مؤكدة</button></form><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><h3 style="font-size:14px">ملخص التحصيل</h3><?php foreach($totals as $t):?><div class="subtle" style="margin-bottom:10px"><b><?=e(AdminUi::currency((string)$t['currency']))?></b><p class="small">مؤكد: <?=e(number_format((float)$t['confirmed'],2))?> · معلق: <?=e(number_format((float)$t['pending'],2))?></p></div><?php endforeach?></section>
<section class="card span-12"><div class="card-title"><h2>تكلفة وربح المشاريع الفعلي</h2></div><div class="grid"><div class="span-4 subtle"><h3>تسجيل تكلفة فعلية</h3><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="project_cost_add"><input type="hidden" name="return" value="/api/admin/payments.php"><div class="field"><label>المشروع</label><select name="project_id" required><option value="">اختر المشروع</option><?php foreach($costProjects as $p):?><option value="<?=$p['id']?>">#<?=$p['id']?> <?=e($p['name'])?></option><?php endforeach?></select></div><div class="form-row"><div class="field"><label>نوع التكلفة</label><select name="cost_kind"><?php foreach(['ai'=>'AI','api'=>'API','hosting'=>'استضافة','domain'=>'دومين','theme_plugin'=>'قالب/إضافة','assets'=>'أصول','contractor'=>'متعاون','developer'=>'تطوير','other'=>'أخرى'] as $k=>$v):?><option value="<?=e($k)?>"><?=e($v)?></option><?php endforeach?></select></div><div class="field"><label>المبلغ</label><input type="number" name="amount" min="0.01" step="0.01" required></div></div><div class="form-row"><div class="field"><label>العملة</label><input name="currency" value="<?=e((string)setting('business.currency','EGP'))?>" maxlength="3"></div><div class="field"><label>ملاحظة</label><input name="note" placeholder="سبب التكلفة"></div></div><button class="btn full-width">تسجيل التكلفة</button></form></div><div class="span-8"><div class="table-wrap"><table><thead><tr><th>المشروع</th><th>القيمة</th><th>المحصل</th><th>المتبقي</th><th>التكلفة الفعلية</th><th>الربح الفعلي</th><th>الربح المتوقع</th></tr></thead><tbody><?php foreach($costProjects as $p):$f=$finance[(int)$p['id']]??null;if(!$f)continue;?><tr><td><a class="link" href="project.php?id=<?=$p['id']?>"><?=e($p['name'])?></a></td><td><?=e(number_format((float)$f['project_value'],2).' '.$f['currency'])?></td><td><?=e(number_format((float)$f['collected'],2).' '.$f['currency'])?></td><td><?=e(number_format((float)$f['remaining'],2).' '.$f['currency'])?></td><td><?=e(number_format((float)$f['actual_cost'],2).' '.$f['currency'])?></td><td><?=e(number_format((float)$f['actual_profit'],2).' '.$f['currency'])?></td><td><?=e(number_format((float)$f['projected_profit'],2).' '.$f['currency'])?></td></tr><?php endforeach?></tbody></table></div></div></div><?php if($costRows):?><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>#</th><th>المشروع</th><th>النوع</th><th>المبلغ</th><th>الملاحظة</th><th>التاريخ</th></tr></thead><tbody><?php foreach($costRows as $c):?><tr><td>#<?=$c['id']?></td><td><?=e($c['project_name'])?></td><td><?=e(AdminUi::label((string)$c['cost_kind']))?></td><td><?=e(number_format((float)$c['amount'],2).' '.$c['currency'])?></td><td><?=e($c['note']?:'—')?></td><td><?=e(AdminUi::date($c['created_at']))?></td></tr><?php endforeach?></tbody></table></div><?php endif?></section>
<section class="card span-12"><div class="card-title"><h2>طرق الدفع المفعلة</h2></div><div class="grid"><?php foreach($methods as $m):?><div class="subtle span-3"><b><?=e($m['label'])?></b><p class="small muted"><?=e($m['holder_name']?:'')?><?= $m['account_reference']?' · '.e($m['account_reference']):''?></p></div><?php endforeach?></div></section></div><?php AdminUi::footer();
