<?php
declare(strict_types=1);
final class PhysicalSchemaService {
    private const TYPES=['text'=>'TEXT','string'=>'VARCHAR(255)','int'=>'BIGINT','decimal'=>'DECIMAL(20,4)','date'=>'DATE','datetime'=>'DATETIME','bool'=>'TINYINT(1)','json'=>'LONGTEXT','url'=>'VARCHAR(1000)','email'=>'VARCHAR(320)'];
    public static function request(int $agentId,string $label,array $fields,string $reason=''):int{
        AgentCapabilityService::require($agentId,'physical_schema','use');$safe=preg_replace('/[^a-z0-9_]+/','_',strtolower(trim($label)));$safe=trim((string)$safe,'_');if($safe==='')throw new RuntimeException('table_name_invalid');$table='agentx_'.$agentId.'_'.substr($safe,0,32);$f=self::fields($fields);if(!$f)throw new RuntimeException('schema_fields_required');
        db()->prepare("INSERT INTO physical_schema_requests(agent_id,table_name,label,reason_text,fields_json,state) VALUES (?,?,?,?,?,'pending')")->execute([$agentId,$table,substr($label,0,190),substr($reason,0,4000),j($f)]);return (int)db()->lastInsertId();
    }
    public static function approveAndApply(int $id,int $ownerId=1):array{
        Auth::requireOwner();$q=db()->prepare('SELECT * FROM physical_schema_requests WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('schema_request_not_found');if(!in_array((string)$r['state'],['pending','approved','failed'],true))throw new RuntimeException('schema_request_not_pending');$agentId=(int)$r['agent_id'];$table=(string)$r['table_name'];$fields=self::fields(json_decode((string)$r['fields_json'],true)?:[]);if(!$fields)throw new RuntimeException('schema_fields_required');
        AgentPolicyEngine::authorizeAction($agentId,'physical_schema','manage',['risk'=>'high','owner_approved'=>true,'gateway_managed'=>true]);$before=self::snapshot($table);db()->prepare('UPDATE physical_schema_requests SET before_snapshot_json=? WHERE id=?')->execute([j($before),$id]);
        if(!empty($before['exists'])&&!self::compatible($before,$fields))throw new RuntimeException('physical_table_exists_with_different_schema');
        $cols=['`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT'];foreach($fields as $f)$cols[]='`'.$f['name'].'` '.self::TYPES[$f['type']].($f['required']?' NOT NULL':' DEFAULT NULL');$cols[]='`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP';$cols[]='`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP';$cols[]='PRIMARY KEY (`id`)';
        try{db()->prepare("UPDATE physical_schema_requests SET state='approved',approved_by_user_id=?,approved_at=NOW() WHERE id=?")->execute([$ownerId,$id]);db()->exec('CREATE TABLE IF NOT EXISTS `'.$table.'` ('.implode(',',$cols).') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');$after=self::snapshot($table);if(empty($after['exists'])||!self::compatible($after,$fields))throw new RuntimeException('physical_table_verify_failed');$rid=ResourceRegistryService::register('database_table',$table,(string)$r['label'],$agentId,null,$table,['schema_request_id'=>$id,'fields'=>$fields,'verified'=>true]);db()->prepare("UPDATE physical_schema_requests SET state='applied',resource_id=?,applied_at=NOW(),last_error=NULL WHERE id=?")->execute([$rid,$id]);Audit::log('owner',(string)$ownerId,'physical_schema.apply','database_table',$table,'verified',null,null,['request_id'=>$id,'resource_id'=>$rid]);return ['table'=>$table,'resource_id'=>$rid,'already_existed'=>!empty($before['exists']),'verified'=>true];}
        catch(Throwable $e){db()->prepare("UPDATE physical_schema_requests SET state='failed',last_error=? WHERE id=?")->execute([substr(Security::redactSecrets($e->getMessage()),0,500),$id]);throw $e;}
    }
    public static function pending():array{return db()->query("SELECT r.*,a.display_name agent_name FROM physical_schema_requests r JOIN agents a ON a.id=r.agent_id ORDER BY r.id DESC LIMIT 200")->fetchAll();}
    private static function snapshot(string $t):array{$q=db()->prepare('SELECT COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT,EXTRA FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? ORDER BY ORDINAL_POSITION');$q->execute([$t]);$cols=$q->fetchAll();return ['exists'=>(bool)$cols,'table'=>$t,'columns'=>$cols,'captured_at'=>now_utc()];}
    private static function compatible(array $snapshot,array $fields):bool{$have=[];foreach((array)($snapshot['columns']??[]) as $c)$have[(string)$c['COLUMN_NAME']]=strtoupper((string)$c['COLUMN_TYPE']);foreach($fields as $f){if(!isset($have[$f['name']]))return false;$want=self::TYPES[$f['type']];$base=strtoupper(strtok($want,'('));if(!str_starts_with($have[$f['name']],$base))return false;}return true;}
    private static function fields(array $fields):array{$out=[];$seen=[];foreach(array_slice($fields,0,40) as $f){if(!is_array($f))continue;$n=preg_replace('/[^a-z0-9_]+/','_',strtolower(trim((string)($f['name']??''))));$n=trim((string)$n,'_');if($n===''||isset($seen[$n])||in_array($n,['id','created_at','updated_at'],true))continue;$t=(string)($f['type']??'string');if(!isset(self::TYPES[$t]))$t='string';$seen[$n]=1;$out[]=['name'=>substr($n,0,50),'type'=>$t,'required'=>!empty($f['required'])];}return $out;}
}
