<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$id=(int)($_GET['id']??0);if($id<1)throw new RuntimeException('project_required');
$p=ProjectService::get($id);
$opp=null;if(!empty($p['opportunity_id'])){try{$opp=OpportunityService::get((int)$p['opportunity_id']);}catch(Throwable){}}
$q=db()->prepare("SELECT c.*,cp.relationship FROM customer_projects cp JOIN customers c ON c.id=cp.customer_id WHERE cp.project_id=? ORDER BY FIELD(cp.relationship,'owner','contact','billing'),c.id LIMIT 1");$q->execute([$id]);$customer=$q->fetch()?:null;
$q=db()->prepare("SELECT q.*,(SELECT COALESCE(SUM(amount),0) FROM payments x WHERE x.quote_id=q.id AND x.status='confirmed') paid FROM quotes q WHERE q.project_id=? ORDER BY q.id DESC LIMIT 1");$q->execute([$id]);$quote=$q->fetch()?:null;
$brief=MasterBriefService::current($id);
$chat=ProjectChatService::recent($id,120);
$q=db()->prepare("SELECT t.*,a.display_name agent_name FROM tasks t LEFT JOIN agents a ON a.id=t.assigned_agent_id WHERE t.project_id=? ORDER BY t.id DESC LIMIT 100");$q->execute([$id]);$tasks=$q->fetchAll();
$q=db()->prepare("SELECT e.*,a.display_name agent_name FROM task_evidence e LEFT JOIN agents a ON a.id=e.agent_id WHERE e.project_id=? ORDER BY e.id DESC LIMIT 120");$q->execute([$id]);$evidence=$q->fetchAll();
$q=db()->prepare("SELECT r.*,a.display_name reviewer FROM reviews r LEFT JOIN agents a ON a.id=r.reviewer_agent_id WHERE r.project_id=? ORDER BY r.id DESC LIMIT 50");$q->execute([$id]);$reviews=$q->fetchAll();
$q=db()->prepare("SELECT * FROM project_issues WHERE project_id=? ORDER BY FIELD(status,'open','working','resolved','ignored'),FIELD(severity,'critical','high','medium','low','info'),id DESC LIMIT 150");$q->execute([$id]);$issues=$q->fetchAll();
$q=db()->prepare("SELECT * FROM project_stage_events WHERE project_id=? ORDER BY id DESC LIMIT 100");$q->execute([$id]);$stages=$q->fetchAll();
$q=db()->prepare("SELECT * FROM backups WHERE project_id=? ORDER BY id DESC LIMIT 50");$q->execute([$id]);$backups=$q->fetchAll();
$q=db()->prepare("SELECT * FROM deployments WHERE project_id=? ORDER BY id DESC LIMIT 50");$q->execute([$id]);$deploys=$q->fetchAll();
$q=db()->prepare("SELECT * FROM project_memory WHERE project_id=? AND active=1 ORDER BY id DESC LIMIT 60");$q->execute([$id]);$memory=$q->fetchAll();
AdminUi::header('مساحة المشروع — '.$p['name'],'projects');echo AdminUi::flash();
$stage=(string)($p['workflow_stage']??'discovered');$stagingEligible=StagingService::eligible($p);$staging=$stagingEligible?StagingService::existing($p):null;$stagingState=(string)($staging['state']??'not_prepared');
?>
<div class="hero-strip project-hero"><div><span class="eyebrow">PROJECT WORKSPACE</span><h2><?=e($p['name'])?></h2><p><?=e($p['primary_domain']?:'بدون دومين حتى الآن')?> · <?=e(AdminUi::label($p['source']))?> · المرحلة: <b><?=e(AdminUi::label($stage))?></b></p></div><div class="hero-actions"><?=AdminUi::badge($stage)?><a class="btn secondary" href="projects.php">كل المشاريع</a><?php if($p['primary_domain']):?><a class="btn secondary" href="https://<?=e($p['primary_domain'])?>" target="_blank" rel="noopener">فتح الموقع</a><?php endif?></div></div>
<div class="stage-track"><?php $allStages=['discovered','owner_review','approved','negotiating','agreed','deposit_pending','awaiting_execution','in_development','awaiting_qa','qa','needs_fix','ready_delivery','delivered','closed'];$cur=array_search($stage,$allStages,true);foreach($allStages as $i=>$x):?><span class="stage-chip <?=$cur!==false&&$i<=$cur?'done':''?> <?=$x===$stage?'current':''?>"><?=e(AdminUi::label($x))?></span><?php endforeach?></div>
<?php if($stagingEligible):?><section class="staging-command-card"><div><span class="eyebrow">محطة الاختبار الرسمية</span><h2><?=e($staging['domain']??setting('staging.domain','nourmakkah.com'))?></h2><p>أيمن يبرمج هنا أولًا، عماد يراجع نفس النسخة، ولا يتم لمس دومين العميل النهائي قبل اعتماد QA.</p><div class="tag-row"><span>الحالة: <?=e(AdminUi::label($stagingState))?></span><span>الدومين النهائي: <?=e($p['primary_domain']?:'لم يُحدد بعد')?></span><?php if(!empty($staging['qa_approved_at'])):?><span>اعتماد عماد: <?=e(AdminUi::date($staging['qa_approved_at']))?></span><?php endif?></div></div><div class="actions"><?php if(!$staging):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="staging_prepare"><input type="hidden" name="project_id" value="<?=$id?>"><input type="hidden" name="return" value="/api/admin/project.php?id=<?=$id?>"><button class="btn">جهز Staging</button></form><?php else:?><a class="btn secondary" target="_blank" rel="noopener" href="https://<?=e($staging['domain'])?>/">فتح نسخة الاختبار</a><?php endif?><?php if($staging&&in_array($stagingState,['qa_approved','ready_delivery'],true)&&$p['primary_domain']):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="staging_promote"><input type="hidden" name="project_id" value="<?=$id?>"><input type="hidden" name="return" value="/api/admin/project.php?id=<?=$id?>"><button class="btn" data-confirm="نقل النسخة التي اعتمدها عماد إلى دومين العميل النهائي مع Backup؟">نقل للدومين النهائي</button></form><?php endif?></div></section><?php endif?>

<div class="grid">
<section class="card span-4"><div class="card-title"><h2>الفرصة والعميل</h2><?php if($opp):?><a class="link" href="orders.php?id=<?=$opp['id']?>">الفرصة #<?=$opp['id']?></a><?php endif?></div><dl class="kvs"><dt>العميل</dt><dd><?=e($customer['display_name']??'غير محدد')?></dd><dt>الهاتف</dt><dd><?=e($customer['phone']??'—')?></dd><dt>البريد</dt><dd><?=e($customer['email']??'—')?></dd><dt>المصدر</dt><dd><?=e($opp['source']??'—')?></dd><dt>الميزانية</dt><dd><?php if($opp):?><?=e(($opp['budget_min']!==null?number_format((float)$opp['budget_min'],0):'؟').' – '.($opp['budget_max']!==null?number_format((float)$opp['budget_max'],0):'؟').' '.AdminUi::currency((string)$opp['currency']))?><?php else:?>—<?php endif?></dd></dl></section>
<section class="card span-4"><div class="card-title"><h2>العرض والتحصيل</h2><a class="link" href="sales.php">العروض</a></div><?php if(!$quote):?><?=AdminUi::empty('لا يوجد عرض سعر بعد.')?><?php else:?><dl class="kvs"><dt>العرض</dt><dd>#<?=$quote['id']?> — <?=e($quote['title'])?></dd><dt>السعر</dt><dd><?=e(number_format((float)$quote['amount'],2).' '.AdminUi::currency($quote['currency']))?></dd><dt>المقدم</dt><dd><?=e(number_format((float)($quote['deposit_percent']??setting('business.deposit_start_percent','40')),0).'%')?><?=$quote['owner_exception_required']?' '.AdminUi::badge('warning'):''?></dd><dt>المدفوع</dt><dd><?=e(number_format((float)$quote['paid'],2))?></dd><dt>الحالة</dt><dd><?=AdminUi::badge($quote['status'])?></dd></dl><?php endif?></section>
<section class="card span-4"><div class="card-title"><h2>الحالة التقنية</h2><a class="link" href="hosting.php">Hostinger</a></div><dl class="kvs"><dt>الحالة</dt><dd><?=AdminUi::badge($p['status'])?></dd><dt>الاستضافة</dt><dd><?=AdminUi::badge((string)($p['hosting_presence']??'unknown'))?></dd><dt>المجلد</dt><dd class="mono small"><?=e($p['document_root']?:'—')?></dd><dt>التقنية</dt><dd><?=e($p['technology']?:'—')?></dd><dt>آخر Backup</dt><dd><?=e(AdminUi::date($p['last_backup_at']))?></dd></dl></section>

<section class="card span-7"><div class="card-title"><div><h2>PROJECT MASTER BRIEF</h2><span class="muted small">المرجع الحالي لأيمن وعماد — كل تعديل ينشئ Version جديدًا.</span></div><?php if($brief):?><?=AdminUi::badge('verified')?><?php else:?><?=AdminUi::badge('warning')?><?php endif?></div>
<?php if($brief):?><div class="master-brief"><div class="brief-head"><b>v<?=(int)$brief['version_no']?></b><span><?=e(AdminUi::date($brief['created_at']))?></span></div><pre><?=e($brief['summary_text'])?></pre></div><?php else:?><?=AdminUi::empty('لا يوجد Master Brief بعد. أنشئه قبل بدء تنفيذ مشروع العميل.')?><?php endif?>
<details class="subtle top-gap"><summary><b><?= $brief?'إنشاء إصدار جديد من الـBrief':'إنشاء Master Brief الأول'?></b></summary><form method="post" action="action.php" class="top-gap"><?=AdminUi::csrf()?><input type="hidden" name="action" value="master_brief_create"><input type="hidden" name="project_id" value="<?=$id?>"><input type="hidden" name="return" value="/api/admin/project.php?id=<?=$id?>"><div class="field"><label>المطلوب</label><textarea name="requirements"><?=e($opp['requirements_text']??'')?></textarea></div><div class="field"><label>نطاق التنفيذ النهائي</label><textarea name="scope"><?=e($quote['scope_text']??($opp['requirements_text']??''))?></textarea></div><div class="form-row"><div class="field"><label>عدد الصفحات</label><input name="pages"></div><div class="field"><label>اللغة</label><input name="language"></div></div><div class="form-row"><div class="field"><label>الألوان</label><input name="colors"></div><div class="field"><label>الموعد</label><input name="deadline"></div></div><div class="field"><label>المميزات</label><textarea name="features"></textarea></div><div class="field"><label>ملاحظات العميل</label><textarea name="customer_notes"></textarea></div><div class="field"><label>ملاحظات المالك</label><textarea name="owner_notes"></textarea></div><div class="field"><label>ملاحظات فنية</label><textarea name="technical_notes"></textarea></div><button class="btn">حفظ Version جديد وتثبيته في الشات</button></form></details></section>
<section class="card span-5"><div class="card-title"><div><h2>شات فريق المشروع</h2><span class="muted small">أنت + رامي + وليد + أيمن + عماد</span></div></div><div class="project-chat"><?php if(!$chat):?><?=AdminUi::empty('لا توجد رسائل تشغيلية بعد.')?><?php else:foreach($chat as $m):?><div class="team-msg <?=$m['pinned']?'pinned':''?>"><div><b><?=e($m['sender_type']==='owner'?'المالك':($m['sender_type']==='agent'?($m['agent_name']?:AdminUi::label($m['sender_ref'])):'النظام'))?></b><span><?=e(AdminUi::label($m['message_kind']))?> · <?=e(AdminUi::date($m['created_at']))?></span></div><p><?=nl2br(e($m['body_text']))?></p></div><?php endforeach;endif?></div><form method="post" action="action.php" class="chat-compose"><?=AdminUi::csrf()?><input type="hidden" name="action" value="project_chat_post"><input type="hidden" name="project_id" value="<?=$id?>"><input type="hidden" name="return" value="/api/admin/project.php?id=<?=$id?>"><textarea name="body_text" placeholder="أضف قرارًا أو ملاحظة تشغيلية للفريق" required></textarea><button class="btn">إرسال للفريق</button></form></section>

<section class="card span-7"><div class="card-title"><h2>المهام والتنفيذ</h2><div class="actions"><?php if($brief):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="ayman_task"><input type="hidden" name="project_id" value="<?=$id?>"><input type="hidden" name="request" value="ابدأ تنفيذ أحدث Master Brief للمشروع، وسجل Evidence حقيقي ثم سلّم لعماد."><input type="hidden" name="return" value="/api/admin/project.php?id=<?=$id?>"><button class="btn small-btn">شغّل أيمن</button></form><?php endif?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="full_review"><input type="hidden" name="project_id" value="<?=$id?>"><input type="hidden" name="return" value="/api/admin/project.php?id=<?=$id?>"><button class="btn secondary small-btn">دورة تنفيذ + مراجعة</button></form></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>الوكيل</th><th>المهمة</th><th>الحالة</th><th>المراجعة</th><th>التحديث</th></tr></thead><tbody><?php foreach($tasks as $t):?><tr><td><a href="tasks.php?id=<?=$t['id']?>">#<?=$t['id']?></a></td><td><?=e($t['agent_name']?:'—')?></td><td><?=e($t['title'])?></td><td><?=AdminUi::badge($t['status'])?></td><td><?=AdminUi::badge($t['review_status'])?></td><td><?=e(AdminUi::date($t['updated_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card span-5"><div class="card-title"><h2>Evidence — الكلام وحده ليس تنفيذًا</h2></div><?php if(!$evidence):?><?=AdminUi::empty('لا يوجد Evidence مسجل بعد.')?><?php else:foreach($evidence as $ev):?><div class="mini-item"><div class="grow"><b><?=e($ev['label'])?></b><small><?=e($ev['agent_name']?:'النظام')?> · <?=e($ev['evidence_type'])?> · <?=e(AdminUi::date($ev['created_at']))?></small></div><?=AdminUi::badge($ev['state'])?></div><?php endforeach;endif?></section>

<section class="card span-6"><div class="card-title"><h2>تقارير عماد</h2><a class="link" href="qa.php">كل المراجعات</a></div><?php if(!$reviews):?><?=AdminUi::empty('لم يبدأ عماد مراجعة هذا المشروع.')?><?php else:foreach($reviews as $r):?><div class="qa-report"><div class="card-title"><div><b>Review #<?=$r['id']?> — <?=e($r['reviewer']?:'عماد')?></b><small><?=e(AdminUi::date($r['created_at']))?></small></div><?=AdminUi::badge($r['status'])?></div><p><?=nl2br(e($r['summary']))?></p><small class="muted">نجح: <?=(int)$r['tests_passed']?> · فشل: <?=(int)$r['tests_failed']?> · تحذيرات: <?=(int)$r['warnings']?></small></div><?php endforeach;endif?></section>
<section class="card span-6"><div class="card-title"><h2>المشاكل والتصحيحات</h2></div><?php if(!$issues):?><?=AdminUi::empty('لا توجد Issues مسجلة.')?><?php else:foreach($issues as $i):?><div class="issue-row severity-<?=e($i['severity'])?>"><div><b><?=e($i['title'])?></b><small><?=e(AdminUi::label($i['severity']))?> · <?=e(AdminUi::label($i['status']))?> · <?=e(AdminUi::date($i['created_at']))?></small></div><p><?=nl2br(e(pb_substr($i['description'],0,1000)))?></p></div><?php endforeach;endif?></section>

<section class="card span-6"><div class="card-title"><h2>النسخ والنشر</h2><a class="link" href="operations.php">مركز التشغيل</a></div><div class="two-col"><div><b class="small">Backups</b><?php foreach($backups as $b):?><div class="mini-item"><div class="grow"><b><?=e(AdminUi::label($b['kind']))?></b><small><?=e(AdminUi::date($b['created_at']))?></small></div><?=AdminUi::badge($b['status'])?></div><?php endforeach?></div><div><b class="small">Deployments</b><?php foreach($deploys as $d):?><div class="mini-item"><div class="grow"><b><?=e($d['version_ref']?:'Deployment #'.$d['id'])?></b><small><?=e(AdminUi::date($d['created_at']))?></small></div><?=AdminUi::badge($d['state'])?></div><?php endforeach?></div></div></section>
<section class="card span-6"><div class="card-title"><h2>ذاكرة المشروع</h2><a class="link" href="memory.php">إدارة الذاكرة</a></div><?php if(!$memory):?><?=AdminUi::empty('لا توجد ذاكرة مشروع حتى الآن.')?><?php else:foreach($memory as $m):?><div class="mini-item"><div class="grow"><b><?=e(AdminUi::label($m['category']))?></b><small><?=e(pb_substr($m['body_text'],0,240))?></small></div><span class="muted small"><?=e(AdminUi::date($m['updated_at']))?></span></div><?php endforeach;endif?></section>
<section class="card span-12"><div class="card-title"><h2>سجل مراحل المشروع</h2></div><div class="timeline"><?php foreach($stages as $s):?><div class="timeline-row"><span class="timeline-dot"></span><div><b><?=e(AdminUi::label($s['from_stage']?:'new'))?> ← <?=e(AdminUi::label($s['to_stage']))?></b><p><?=e($s['reason']?:'تحديث مرحلة')?></p><small><?=e(AdminUi::date($s['created_at']))?> · <?=e(AdminUi::label($s['actor_type']))?></small></div></div><?php endforeach?></div></section>
</div>
<?php AdminUi::footer();
