<?php
declare(strict_types=1);
final class ProjectService {
    public static function all():array{return db()->query("SELECT p.*,(SELECT COUNT(*) FROM tasks t WHERE t.project_id=p.id AND t.status NOT IN ('completed','cancelled','failed')) open_tasks,(SELECT COUNT(*) FROM project_databases d WHERE d.project_id=p.id AND d.status='active') db_count,(SELECT COUNT(*) FROM project_files f WHERE f.project_id=p.id AND f.status='active') file_count,(SELECT COUNT(*) FROM project_issues i WHERE i.project_id=p.id AND i.status IN ('open','working')) issue_count FROM projects p ORDER BY p.is_system_project DESC,p.status='active' DESC,p.updated_at DESC")->fetchAll();}
    public static function get(int $id):array{$q=db()->prepare('SELECT * FROM projects WHERE id=?');$q->execute([$id]);$p=$q->fetch();if(!$p)throw new RuntimeException('project_not_found');$q=db()->prepare('SELECT * FROM project_domains WHERE project_id=? OR (project_id IS NULL AND domain_name=?) ORDER BY id');$q->execute([$id,$p['primary_domain']]);$p['domains']=$q->fetchAll();$q=db()->prepare('SELECT * FROM project_databases WHERE project_id=? ORDER BY id');$q->execute([$id]);$p['databases']=$q->fetchAll();$q=db()->prepare("SELECT * FROM project_files WHERE project_id=? ORDER BY status='active' DESC,is_important DESC,path LIMIT 2000");$q->execute([$id]);$p['files']=$q->fetchAll();$q=db()->prepare("SELECT * FROM project_issues WHERE project_id=? ORDER BY FIELD(status,'open','working','resolved','ignored'),FIELD(severity,'critical','high','medium','low','info'),id DESC");$q->execute([$id]);$p['issues']=$q->fetchAll();$q=db()->prepare('SELECT c.* FROM customer_projects cp JOIN customers c ON c.id=cp.customer_id WHERE cp.project_id=? ORDER BY cp.created_at DESC');$q->execute([$id]);$p['customers']=$q->fetchAll();return $p;}
    public static function resolve(string $ref,?int $activeId=null):?array{
        $ref=trim(pb_strtolower($ref));if($ref===''){if($activeId){try{return self::get($activeId);}catch(Throwable){}}return null;}
        $host=preg_replace('#^https?://#i','',$ref);$host=preg_replace('#/.*$#','',$host);$q=db()->prepare('SELECT * FROM projects WHERE LOWER(primary_domain)=? OR LOWER(name)=? OR LOWER(uid)=? ORDER BY is_system_project DESC LIMIT 1');$q->execute([$host,$ref,$ref]);$p=$q->fetch();if($p)return $p;
        $q=db()->prepare("SELECT * FROM projects WHERE LOWER(name) LIKE ? OR LOWER(primary_domain) LIKE ? ORDER BY is_system_project DESC,updated_at DESC LIMIT 1");$like='%'.$ref.'%';$q->execute([$like,$like]);return $q->fetch()?:null;
    }
    public static function setStatus(int $id,string $status,string $actor='owner'):void{if(!in_array($status,['active','maintenance','broken','development','archived','unknown'],true))throw new RuntimeException('invalid_project_status');$p=self::get($id);db()->prepare('UPDATE projects SET status=? WHERE id=?')->execute([$status,$id]);Audit::log($actor,$actor==='owner'?'1':$actor,'project.status','project',(string)$id,'verified',$id,null,['from'=>$p['status'],'to'=>$status]);Notifications::add('info','projects','تغيرت حالة المشروع',$p['name'].' → '.AdminUi::label($status),'project',(string)$id);}
    public static function statusSummary(?int $id=null):array{if($id){$p=self::get($id);$q=db()->prepare("SELECT status,COUNT(*) c FROM tasks WHERE project_id=? GROUP BY status");$q->execute([$id]);return ['project'=>$p,'tasks'=>$q->fetchAll()];}$rows=db()->query("SELECT status,COUNT(*) c FROM projects GROUP BY status")->fetchAll();return ['projects'=>$rows,'total'=>array_sum(array_column($rows,'c'))];}
}
