<?php
declare(strict_types=1);
final class ProjectDatabaseClient {
    private static array $pool=[];
    private static function row(int $dbId):array{$q=db()->prepare('SELECT d.*,p.name project_name,p.primary_domain FROM project_databases d JOIN projects p ON p.id=d.project_id WHERE d.id=?');$q->execute([$dbId]);$r=$q->fetch();if(!$r)throw new RuntimeException('project_database_not_found');return $r;}
    private static function password(int $dbId):string{return (string)config('connections.project_db.'.$dbId.'.password','');}
    public static function configured(int $dbId):bool{$r=self::row($dbId);return trim((string)$r['db_user'])!==''&&self::password($dbId)!=='';}
    public static function connection(int $dbId):PDO{
        if(isset(self::$pool[$dbId]))return self::$pool[$dbId];$r=self::row($dbId);$pass=self::password($dbId);if(trim((string)$r['db_user'])===''||$pass==='')throw new RuntimeException('project_database_credentials_required');$host=trim((string)($r['db_host']?:'localhost'));$port=(int)($r['db_port']??3306);if($port<1||$port>65535)$port=3306;
        $pdo=new PDO('mysql:host='.$host.';port='.$port.';dbname='.$r['db_name'].';charset=utf8mb4',(string)$r['db_user'],$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);return self::$pool[$dbId]=$pdo;
    }
    public static function test(int $dbId):array{try{$pdo=self::connection($dbId);$ok=(int)$pdo->query('SELECT 1')->fetchColumn()===1;db()->prepare("UPDATE project_databases SET connection_state=?,last_connection_test_at=NOW() WHERE id=?")->execute([$ok?'verified':'failed',$dbId]);return ['ok'=>$ok,'state'=>$ok?'verified':'failed'];}catch(Throwable $e){db()->prepare("UPDATE project_databases SET connection_state='failed',last_connection_test_at=NOW() WHERE id=?")->execute([$dbId]);return ['ok'=>false,'state'=>'failed','error'=>pb_substr($e->getMessage(),0,180)];}}
    private static function qi(string $s):string{if($s===''||str_contains($s,'`'))throw new RuntimeException('invalid_identifier');return '`'.str_replace('`','``',$s).'`';}
    public static function schemaSummary(int $dbId,int $maxTables=120):array{$pdo=self::connection($dbId);$tables=$pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);$out=[];foreach(array_slice($tables,0,$maxTables) as $t){$t=(string)$t;$cols=$pdo->query('SHOW FULL COLUMNS FROM '.self::qi($t))->fetchAll();$out[]=['table'=>$t,'columns'=>array_map(fn($c)=>['name'=>$c['Field']??'','type'=>$c['Type']??'','null'=>$c['Null']??'','key'=>$c['Key']??'','default'=>$c['Default']??null,'extra'=>$c['Extra']??''],$cols)];}return $out;}
    private static function sqlValue(PDO $pdo,$v):string{if($v===null)return 'NULL';if(is_bool($v))return $v?'1':'0';$s=(string)$v;if($s!==''&&!preg_match('//u',$s))return '0x'.bin2hex($s);return $pdo->quote($s);}
    public static function backup(int $dbId,int $taskId=0,int $maxBytes=104857600):array{
        $r=self::row($dbId);$pdo=self::connection($dbId);$dir=PB_ROOT.'/private/runtime/db-backups/'.date('Ymd');if(!is_dir($dir))mkdir($dir,0700,true);$name='p'.$r['project_id'].'-db'.$dbId.'-t'.$taskId.'-'.date('His').'-'.bin2hex(random_bytes(4)).'.sql';$path=$dir.'/'.$name;$fh=fopen($path,'wb');if(!$fh)throw new RuntimeException('database_backup_open_failed');@chmod($path,0600);$written=0;$write=function(string $x)use($fh,&$written,$maxBytes){$written+=strlen($x);if($written>$maxBytes)throw new RuntimeException('database_backup_size_limit');if(fwrite($fh,$x)===false)throw new RuntimeException('database_backup_write_failed');};
        try{$write("SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n");$objects=$pdo->query('SHOW FULL TABLES')->fetchAll(PDO::FETCH_NUM);$tables=[];$views=[];foreach($objects as $obj){$name=(string)($obj[0]??'');$type=strtoupper((string)($obj[1]??'BASE TABLE'));if($name==='')continue;if($type==='VIEW')$views[]=$name;else $tables[]=$name;}foreach($tables as $table){$cr=$pdo->query('SHOW CREATE TABLE '.self::qi($table))->fetch();$create=(string)($cr['Create Table']??array_values($cr)[1]??'');if($create==='')throw new RuntimeException('database_backup_create_missing');$write("DROP TABLE IF EXISTS ".self::qi($table).";\n".$create.";\n");$st=$pdo->query('SELECT * FROM '.self::qi($table));while($row=$st->fetch(PDO::FETCH_ASSOC)){$cols=array_map(fn($c)=>self::qi((string)$c),array_keys($row));$vals=array_map(fn($v)=>self::sqlValue($pdo,$v),array_values($row));$write('INSERT INTO '.self::qi($table).' ('.implode(',',$cols).') VALUES ('.implode(',',$vals).');' ."\n");}$write("\n");}foreach($views as $view){$cr=$pdo->query('SHOW CREATE VIEW '.self::qi($view))->fetch();$create=(string)($cr['Create View']??array_values($cr)[1]??'');if($create==='')continue;$create=preg_replace('/DEFINER=`[^`]+`@`[^`]+`\s*/i','',$create);$write("DROP VIEW IF EXISTS ".self::qi($view).";\n".$create.";\n\n");}$write("SET FOREIGN_KEY_CHECKS=1;\n");fclose($fh);$sha=hash_file('sha256',$path);db()->prepare("INSERT INTO backups(project_id,task_id,provider,kind,location_ref,checksum,status,verified_at) VALUES (?,?,'pdo','database',?,?,'verified',NOW())")->execute([(int)$r['project_id'],$taskId?:null,'db-backups/'.date('Ymd').'/'.$name,$sha]);$bid=(int)db()->lastInsertId();db()->prepare('UPDATE projects SET last_backup_at=NOW() WHERE id=?')->execute([(int)$r['project_id']]);$actor=Audit::actor();Audit::log((string)$actor['type'],(string)$actor['id'],'database.backup','project_database',(string)$dbId,'verified',(int)$r['project_id'],$taskId?:null,['backup_id'=>$bid,'bytes'=>$written,'sha256'=>$sha]);$cloud=null;try{$cloud=CloudStorageService::mirrorIfEnabled($path,'database/project-'.$r['project_id'].'/'.$name);}catch(Throwable $ce){Notifications::add('warning','backups','تم إنشاء النسخة المحلية وتعذر النسخ السحابي',AdminUi::humanError($ce->getMessage()),'backup',(string)$bid);}return ['backup_id'=>$bid,'bytes'=>$written,'sha256'=>$sha,'location'=>'db-backups/'.date('Ymd').'/'.$name,'cloud'=>$cloud];}catch(Throwable $e){if(is_resource($fh))fclose($fh);@unlink($path);throw $e;}
    }
    private static function normalizeStatement(string $sql):string{$sql=trim($sql);$sql=rtrim($sql,"; \t\r\n");if($sql===''||str_contains($sql,';'))throw new RuntimeException('multiple_sql_statements_not_allowed');if(preg_match('~(?:--|/\*|\*/|\#)~',$sql))throw new RuntimeException('sql_comments_not_allowed');if(preg_match('/\b(DROP|TRUNCATE|RENAME|GRANT|REVOKE|CREATE\s+USER|ALTER\s+USER|LOAD\s+DATA|INTO\s+OUTFILE|DELETE\s+FROM|REPLACE\s+INTO|CALL|DO\s+SLEEP)\b/i',$sql))throw new RuntimeException('destructive_sql_blocked');if(!preg_match('/^(?:CREATE\s+TABLE|CREATE\s+(?:UNIQUE\s+)?INDEX|ALTER\s+TABLE|INSERT\s+INTO|UPDATE\s+)/i',$sql))throw new RuntimeException('sql_operation_not_allowed');if(preg_match('/^ALTER\s+TABLE/i',$sql)&&(!preg_match('/\bADD\b/i',$sql)||preg_match('/\b(?:DROP|CHANGE|MODIFY|RENAME)\b/i',$sql)))throw new RuntimeException('alter_only_add_allowed');if(preg_match('/^UPDATE\s+/i',$sql)&&!preg_match('/\bWHERE\b/i',$sql))throw new RuntimeException('update_requires_where');return $sql;}
    public static function executePlan(int $dbId,int $taskId,int $agentId,array $statements):array{
        if(!$statements)return ['changed'=>false,'backup'=>null,'statements'=>[]];
        $row=self::row($dbId);Permissions::requireProject($agentId,(int)$row['project_id'],'work');$clean=[];
        foreach(array_slice($statements,0,10) as $s){$sql=is_array($s)?(string)($s['sql']??''):(string)$s;$sql=self::normalizeStatement($sql);$schema=(bool)preg_match('/^(?:CREATE|ALTER)/i',$sql);Permissions::requireAgent($agentId,$schema?'database.schema':'database.write');$clean[]=['sql'=>$sql,'reason'=>is_array($s)?(string)($s['reason']??''):''];}
        if(!$clean)return ['changed'=>false,'backup'=>null,'statements'=>[]];
        $backup=self::backup($dbId,$taskId);$pdo=self::connection($dbId);$results=[];$completed=0;
        try{
            foreach($clean as $x){$affected=$pdo->exec($x['sql']);$hash=hash('sha256',$x['sql']);$results[]=['hash'=>$hash,'sql'=>$x['sql'],'operation'=>strtoupper(strtok($x['sql'],' ')),'affected'=>$affected,'reason'=>$x['reason']];$completed++;Audit::log('agent',(string)$agentId,'database.statement','project_database',(string)$dbId,'verified',(int)$row['project_id'],$taskId,['sql_hash'=>$hash,'operation'=>strtoupper(strtok($x['sql'],' ')),'affected'=>$affected,'backup_id'=>$backup['backup_id']??null]);}
        }catch(Throwable $e){
            Audit::log('agent',(string)$agentId,'database.plan','project_database',(string)$dbId,'failed',(int)$row['project_id'],$taskId,['backup_id'=>$backup['backup_id']??null,'completed_statements'=>$completed,'total_statements'=>count($clean),'error'=>pb_substr($e->getMessage(),0,300)]);
            Notifications::add('critical','database','تغيير قاعدة البيانات اتوقف','اتنفذ جزء من الخطة قبل الخطأ. في نسخة احتياطية رقم '.(int)($backup['backup_id']??0).' ولازم مراجعة قاعدة البيانات قبل اعتبار المهمة مكتملة.','task',(string)$taskId);
            throw new RuntimeException('database_plan_partial_failure:backup_id='.(int)($backup['backup_id']??0).':completed='.$completed.':'.$e->getMessage(),0,$e);
        }
        return ['changed'=>true,'db_id'=>$dbId,'backup'=>$backup,'statements'=>$results,'schema_hash'=>hash('sha256',j(self::schemaSummary($dbId)))];
    }
}
