<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$leads=ProspectingService::leads(300);$profile=WalidLearningService::profile();$recentOpps=db()->query("SELECT o.*,f.owner_decision feedback_decision,f.final_status feedback_status,f.actual_revenue,f.actual_cost,f.actual_profit FROM opportunities o LEFT JOIN opportunity_feedback f ON f.opportunity_id=o.id ORDER BY o.id DESC LIMIT 80")->fetchAll();
AdminUi::header('Walid Company Prospecting','prospecting');echo AdminUi::flash();
?>
<section class="card"><div class="card-title"><div><h2>Proactive company prospecting</h2><span class="muted small">This is separate from project/job ads. Walid searches for real companies with a digital need, verifies website evidence, collects contact paths and learns from owner outcomes.</span></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="prospecting_run"><input type="hidden" name="return" value="/api/admin/prospecting.php"><select name="market"><option value="egypt_arab">Egypt then Arab markets</option><option value="egypt">Egypt</option><option value="gulf">Gulf</option><option value="arab">Arab markets</option></select><button class="btn">Queue prospecting run</button></form></div></section>
<div class="grid"><section class="card span-8"><div class="card-title"><h2>Prospect leads</h2><span class="badge s-active"><?=count($leads)?></span></div><div class="creator-grid"><?php foreach($leads as $l):?><article class="card subtle" style="margin:0"><div class="card-title"><div><b><?=e($l['company_name'])?></b><small class="block muted"><?=e($l['country']?:'')?> | score <?=e((string)$l['score'])?></small></div><?=AdminUi::badge($l['status'])?></div><p><?=e($l['opportunity_reason']?:'')?></p><p class="small muted">Website: <?=e($l['website_url']?:'not verified')?> | Source: <?=e($l['source_url']?:'-')?></p><p class="small muted">Contacts: <?=e((string)($l['contact_methods_json']?:'-'))?></p><?php if(!in_array($l['status'],['converted','rejected'],true)):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="prospect_convert"><input type="hidden" name="return" value="/api/admin/prospecting.php"><input type="hidden" name="lead_id" value="<?=$l['id']?>"><button class="btn secondary">Convert to opportunity</button></form><?php endif?></article><?php endforeach?></div><?php if(!$leads)echo AdminUi::empty('No prospect leads yet. Run Walid prospecting first.');?></section><section class="card span-4"><div class="card-title"><h2>Walid learning profile</h2></div><pre class="code-box"><?=e(j($profile))?></pre></section></div>
<section class="card"><div class="card-title"><div><h2>Closed-loop owner feedback</h2><span class="muted small">Record Approved/Rejected and Won/Lost with real revenue/cost. Walid uses these outcomes by source, country, category and service type in future search ranking.</span></div></div><div class="creator-grid"><?php foreach($recentOpps as $o):?><article class="card subtle" style="margin:0"><div class="card-title"><div><b>#<?=$o['id']?> <?=e($o['title_ar']?:$o['title'])?></b><small class="block muted"><?=e($o['source'])?> | <?=e($o['country']?:'-')?> | <?=e($o['category']?:'-')?></small></div><?=AdminUi::badge($o['status'])?></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="opportunity_feedback"><input type="hidden" name="return" value="/api/admin/prospecting.php"><input type="hidden" name="opportunity_id" value="<?=$o['id']?>"><div class="two-col"><div class="field"><label>Owner decision</label><select name="decision"><option value="unknown">unknown</option><option value="approved" <?=($o['feedback_decision']??'')==='approved'?'selected':''?>>approved</option><option value="rejected" <?=($o['feedback_decision']??'')==='rejected'?'selected':''?>>rejected</option></select></div><div class="field"><label>Final status</label><select name="final_status"><option value="unknown">unknown</option><option value="contacted">contacted</option><option value="negotiating">negotiating</option><option value="won" <?=($o['feedback_status']??'')==='won'?'selected':''?>>won</option><option value="lost" <?=($o['feedback_status']??'')==='lost'?'selected':''?>>lost</option></select></div></div><div class="two-col"><div class="field"><label>Actual revenue</label><input type="number" step="0.01" name="revenue" value="<?=e((string)($o['actual_revenue']??''))?>"></div><div class="field"><label>Actual cost</label><input type="number" step="0.01" name="cost" value="<?=e((string)($o['actual_cost']??''))?>"></div></div><div class="field"><label>Notes</label><input name="notes"></div><button class="btn secondary full-width">Save learning outcome</button></form></article><?php endforeach?></div></section>
<?php AdminUi::footer();
