<?php
declare(strict_types=1);

final class ProspectingService {
    private const SOCIAL_HOSTS=['facebook.com','www.facebook.com','instagram.com','www.instagram.com','tiktok.com','www.tiktok.com','linkedin.com','www.linkedin.com','x.com','twitter.com'];
    public static function queue(string $market='egypt_arab',array $queries=[]):array{
        $walid=AgentService::bySlug('walid');Permissions::requireAgent((int)$walid['id'],'prospecting.search');$desc='ابحث عن شركات حقيقية لديها احتياج رقمي واضح حتى لو لم تنشر مشروعًا. اجمع الدليل وطرق التواصل ولا تدّع عدم وجود موقع دون بحث تحقق منفصل.';$tid=TaskService::create('walid','استكشاف شركات تحتاج خدمات',$desc,null,['job_kind'=>'walid_company_prospecting','market'=>$market,'queries'=>$queries],'high',true,null,'owner',(string)(Auth::user()['id']??1));return ['task_id'=>$tid,'summary'=>'تم تشغيل مسار استكشاف الشركات في مهمة #'.$tid];
    }
    public static function runTask(int $taskId):array{
        $task=TaskService::start($taskId);$agent=AgentService::byId((int)$task['assigned_agent_id']);Permissions::requireAgent((int)$agent['id'],'prospecting.search');$ctx=json_decode((string)($task['context_json']??'{}'),true)?:[];$market=pb_substr((string)($ctx['market']??'egypt_arab'),0,80);$queries=array_values(array_filter(array_map('trim',(array)($ctx['queries']??[]))));if(!$queries)$queries=self::defaultQueries($market);
        db()->prepare("INSERT INTO prospecting_runs(agent_id,task_id,market_scope,query_text,state,started_at) VALUES (?,?,?,?,'running',NOW())")->execute([(int)$agent['id'],$taskId,$market,implode("\n",$queries)]);$runId=(int)db()->lastInsertId();$raw=[];$diagnostics=[];$saved=0;
        try{AiBudgetService::assertAllowed((int)$agent['id'],'search');foreach(array_slice($queries,0,8) as $query){TaskService::assertContinuable($taskId);$rows=AiCapabilityRouter::webSearch((int)$agent['id'],$query,8,true);$diagnostics[]=['query'=>$query,'search'=>WebSearchClient::lastDiagnostics(),'count'=>count($rows)];foreach($rows as $r){$r['_query']=$query;$raw[]=$r;}if(count($raw)>=35)break;}
            $raw=self::dedupe($raw);foreach(array_slice($raw,0,30) as $row){TaskService::assertContinuable($taskId);$lead=self::analyze($agent,$row);if(empty($lead['likely_business'])||(int)($lead['score']??0)<45)continue;$verify=self::verifyWebsite((int)$agent['id'],(string)$lead['company_name'],(string)($lead['website_url']??''));$lead=array_merge($lead,$verify);$fp=hash('sha256',pb_strtolower((string)$lead['company_name'].'|'.(string)$row['url']));$contact=self::contacts((string)($row['snippet']??''));$status=(int)$lead['score']>=65&&in_array($lead['website_state'],['none','broken','weak','unknown'],true)?'qualified':'new';$q=db()->prepare("INSERT INTO prospect_leads(run_id,discovered_by_agent_id,company_name,country,industry,source_url,social_url,website_url,website_state,contact_methods_json,opportunity_reason,recommended_service,score,status,fingerprint,audit_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),run_id=VALUES(run_id),website_url=COALESCE(VALUES(website_url),website_url),website_state=VALUES(website_state),contact_methods_json=VALUES(contact_methods_json),opportunity_reason=VALUES(opportunity_reason),recommended_service=VALUES(recommended_service),score=GREATEST(score,VALUES(score)),updated_at=NOW()");$q->execute([$runId,(int)$agent['id'],pb_substr((string)$lead['company_name'],0,300),pb_substr((string)($lead['country']??''),0,120)?:null,pb_substr((string)($lead['industry']??''),0,160)?:null,(string)$row['url'],self::isSocial((string)$row['url'])?(string)$row['url']:null,$lead['website_url']?:null,$lead['website_state'],j($contact),pb_substr((string)$lead['reason'],0,8000),pb_substr((string)$lead['recommended_service'],0,220),max(0,min(100,(int)$lead['score'])),$status,$fp,j(['search_title'=>$row['title']??'','snippet'=>$row['snippet']??'','query'=>$row['_query']??'','verification'=>$verify])]);$leadId=(int)db()->lastInsertId();if($q->rowCount()>0)$saved++;if($leadId>0&&(int)$lead['score']>=55){try{$audit=ProspectWebsiteAuditService::audit($leadId);}catch(Throwable $auditError){$audit=['error'=>pb_substr(Security::redactSecrets($auditError->getMessage()),0,180)];}try{$contacts=ProspectContactDiscoveryService::discover($leadId);}catch(Throwable $contactError){$contacts=['error'=>pb_substr(Security::redactSecrets($contactError->getMessage()),0,180)];}try{db()->prepare('UPDATE prospect_leads SET audit_json=? WHERE id=?')->execute([j(['search_title'=>$row['title']??'','snippet'=>$row['snippet']??'','query'=>$row['_query']??'','verification'=>$verify,'website_audit'=>$audit,'contact_discovery'=>$contacts]),$leadId]);}catch(Throwable){}}}
            $prototype=null;if(setting('prospecting.auto_prototype','1')==='1'){try{$min=max(55,min(95,(int)setting('prospecting.prototype_min_score','75')));$pq=db()->prepare("SELECT id FROM prospect_leads WHERE run_id=? AND score>=? AND website_state IN ('none','broken','weak') AND status IN ('qualified','contact_ready') AND NOT EXISTS (SELECT 1 FROM prospect_prototypes pp WHERE pp.lead_id=prospect_leads.id AND pp.state NOT IN ('rejected','failed')) ORDER BY score DESC,id ASC LIMIT 1");$pq->execute([$runId,$min]);$pid=(int)($pq->fetchColumn()?:0);if($pid)$prototype=ProspectPrototypeService::request($pid,true);}catch(Throwable $pe){$diagnostics[]=['prototype_error'=>pb_substr(Security::redactSecrets($pe->getMessage()),0,180)];}}
            try{AiBudgetService::record((int)$agent['id'],'web_search',WebSearchClient::provider(),'search',0,0,['queries'=>count($queries),'raw'=>count($raw),'saved'=>$saved,'prototype'=>$prototype]);}catch(Throwable){}
            db()->prepare("UPDATE prospecting_runs SET state='completed',raw_count=?,qualified_count=?,diagnostics_json=?,completed_at=NOW() WHERE id=?")->execute([count($raw),$saved,j($diagnostics),$runId]);$result=['run_id'=>$runId,'raw'=>count($raw),'saved'=>$saved,'diagnostics'=>$diagnostics,'learning'=>WalidLearningService::sync()];TaskEvidence::add($taskId,'prospecting','دليل استكشاف الشركات',$result,'verified',(int)$agent['id']);TaskService::complete($taskId,$result,'اكتمل استكشاف الشركات وتسجيل الأدلة بدون ادعاء عدم وجود موقع إلا بعد تحقق البحث.');return $result;
        }catch(Throwable $e){$safe=pb_substr(Security::redactSecrets($e->getMessage()),0,220);db()->prepare("UPDATE prospecting_runs SET state='failed',error_code=?,raw_count=?,qualified_count=?,diagnostics_json=?,completed_at=NOW() WHERE id=?")->execute([$safe,count($raw),$saved,j($diagnostics),$runId]);throw $e;}
    }
    public static function leads(int $limit=200):array{$limit=max(1,min(500,$limit));return db()->query("SELECT l.*,a.display_name agent_name FROM prospect_leads l JOIN agents a ON a.id=l.discovered_by_agent_id ORDER BY FIELD(l.status,'qualified','contact_ready','new','contacted','converted','rejected'),l.score DESC,l.id DESC LIMIT $limit")->fetchAll();}
    public static function convert(int $leadId):int{
        $q=db()->prepare('SELECT * FROM prospect_leads WHERE id=?');$q->execute([$leadId]);$l=$q->fetch();if(!$l)throw new RuntimeException('prospect_not_found');if($l['opportunity_id'])return (int)$l['opportunity_id'];$walid=AgentService::bySlug('walid');$title='تواصل استباقي مع '.(string)$l['company_name'];$details="شركة تم اكتشافها استباقيًا.\nسبب الفرصة: ".(string)$l['opportunity_reason']."\nالخدمة المقترحة: ".(string)$l['recommended_service']."\nحالة الموقع: ".(string)$l['website_state']."\nالمصدر: ".(string)$l['source_url'];$fp=hash('sha256','prospect|'.$leadId.'|'.pb_strtolower((string)$l['company_name']));db()->prepare("INSERT INTO opportunities(source,source_item_id,source_url,title,title_ar,client_name,contact_methods_json,country,language,market_scope,estimated_cost,projected_profit,score,source_quality,intent_confidence,fit_status,difficulty,login_requirement,selection_reason,category,opportunity_type,requirements_text,details_ar,summary_ar,raw_details,fingerprint,discovered_by_agent_id,status) VALUES ('company_prospecting',?,?,?,?,?,?,?,?,?,0,0,?,?,?,'qualified','unknown','public',?,?,?,?,?,?,?,?,?,'new')")->execute([(string)$leadId,(string)$l['source_url'],$title,$title,(string)$l['company_name'],(string)$l['contact_methods_json'],(string)($l['country']??''),'ar',self::market((string)($l['country']??'')),(int)$l['score'],70,max(50,(int)$l['score']),pb_substr((string)$l['opportunity_reason'],0,4000),pb_substr((string)$l['industry'],0,160)?:'تواصل استباقي','company_prospect',pb_substr($details,0,12000),pb_substr($details,0,12000),pb_substr((string)$l['opportunity_reason'],0,2000),pb_substr($details,0,16000),$fp,(int)$walid['id']]);$oid=(int)db()->lastInsertId();db()->prepare("UPDATE prospect_leads SET opportunity_id=?,status='contact_ready' WHERE id=?")->execute([$oid,$leadId]);return $oid;
    }
    private static function analyze(array $agent,array $row):array{
        $schema=['type'=>'object','additionalProperties'=>false,'properties'=>['likely_business'=>['type'=>'boolean'],'company_name'=>['type'=>'string'],'country'=>['type'=>'string'],'industry'=>['type'=>'string'],'website_url'=>['type'=>'string'],'reason'=>['type'=>'string'],'recommended_service'=>['type'=>'string'],'score'=>['type'=>'integer']],'required'=>['likely_business','company_name','country','industry','website_url','reason','recommended_service','score']];$prompt="حلل نتيجة بحث عامة لاستكشاف شركة محتملة. لا تعتبر أنها بلا موقع من هذه النتيجة فقط؛ اترك website_url فارغًا إن لم يوجد دليل مباشر. قيّم وجود احتياج حقيقي لخدمة يمكن لفريقنا تنفيذها.\n".WalidLearningService::promptContext();try{$r=AiGateway::json($agent,$prompt,[['role'=>'user','content'=>j(['title'=>$row['title']??'','url'=>$row['url']??'','snippet'=>$row['snippet']??'','query'=>$row['_query']??''])]],$schema,'prospect_analysis',1200);return (array)$r['data'];}catch(Throwable){$host=(string)(parse_url((string)($row['url']??''),PHP_URL_HOST)?:'');return ['likely_business'=>self::isSocial((string)($row['url']??'')),'company_name'=>pb_substr((string)($row['title']??$host),0,300),'country'=>'','industry'=>'','website_url'=>self::isSocial((string)($row['url']??''))?'':(string)($row['url']??''),'reason'=>'نتيجة بحث تبدو كصفحة نشاط تجاري وتحتاج مراجعة بشرية.','recommended_service'=>'مراجعة الحضور الرقمي والموقع','score'=>50];}}
    private static function verifyWebsite(int $agentId,string $company,string $hint):array{
        $hint=trim($hint);if($hint!==''&&filter_var($hint,FILTER_VALIDATE_URL)&&!self::isSocial($hint)){try{$p=HttpClient::probe($hint,8,160000);$st=(int)($p['status']??0);return ['website_url'=>$hint,'website_state'=>($st>=200&&$st<400)?'present':(($st>=400||$st===0)?'broken':'unknown'),'website_evidence'=>['hint'=>$hint,'status'=>$st]];}catch(Throwable $e){return ['website_url'=>$hint,'website_state'=>'broken','website_evidence'=>['hint'=>$hint,'error'=>pb_substr(Security::redactSecrets($e->getMessage()),0,120)]];}}
        if(trim($company)==='')return ['website_url'=>'','website_state'=>'unknown','website_evidence'=>['reason'=>'company_name_missing']];$rows=AiCapabilityRouter::webSearch($agentId,'"'.pb_substr($company,0,120).'" official website',5,true);foreach($rows as $r){$url=(string)($r['url']??'');if(!self::isSocial($url)&&filter_var($url,FILTER_VALIDATE_URL)){return ['website_url'=>$url,'website_state'=>'present','website_evidence'=>['search_hit'=>$url,'title'=>$r['title']??'']];}}return ['website_url'=>'','website_state'=>'none','website_evidence'=>['verification_query'=>pb_substr($company,0,120),'search_results'=>count($rows),'note'=>'لم يظهر موقع رسمي في بحث التحقق الحالي؛ النتيجة قابلة لإعادة التحقق وليست حقيقة مطلقة.']];
    }
    private static function contacts(string $text):array{$out=[];if(preg_match_all('/[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}/i',$text,$m))$out['emails']=array_values(array_unique($m[0]));if(preg_match_all('/\+?\d[\d\s\-()]{8,}\d/',$text,$m))$out['phones']=array_values(array_unique(array_map('trim',$m[0])));return $out;}
    private static function dedupe(array $rows):array{$seen=[];$out=[];foreach($rows as $r){$u=trim((string)($r['url']??''));if($u===''||isset($seen[$u]))continue;$seen[$u]=1;$out[]=$r;}return $out;}
    private static function isSocial(string $url):bool{$h=pb_strtolower((string)(parse_url($url,PHP_URL_HOST)?:''));foreach(self::SOCIAL_HOSTS as $s)if($h===$s||str_ends_with($h,'.'.$s))return true;return false;}
    private static function defaultQueries(string $market):array{return $market==='egypt'?['site:facebook.com شركة مصر "للتواصل"','site:instagram.com Egypt company business','site:facebook.com Cairo business company']:['site:facebook.com شركة مصر "للتواصل"','site:instagram.com شركة السعودية متجر','site:instagram.com شركة الامارات business','شركة قطر instagram facebook contact','site:facebook.com شركة الكويت خدمات'];}
    private static function market(string $country):string{$c=pb_strtolower($country);if(str_contains($c,'egypt')||str_contains($c,'مصر'))return 'egypt';if($c!=='')return 'arab';return 'unknown';}
}
