<?php
declare(strict_types=1);

/** Public contact discovery for qualified prospects. No login, bypass, scraping behind gates, or private data. */
final class ProspectContactDiscoveryService {
    private const SOCIAL=['facebook.com'=>'facebook','instagram.com'=>'instagram','linkedin.com'=>'linkedin','x.com'=>'x','twitter.com'=>'x','tiktok.com'=>'tiktok','t.me'=>'telegram','telegram.me'=>'telegram'];
    public static function discover(int $leadId):array{
        $lead=self::lead($leadId);$urls=[];foreach(['website_url','source_url','social_url'] as $k){$u=trim((string)($lead[$k]??''));if($u!==''&&filter_var($u,FILTER_VALIDATE_URL))$urls[]=$u;}$urls=array_values(array_unique($urls));$pages=[];$found=[];
        foreach(array_slice($urls,0,3) as $u){try{$u=Security::publicUrl($u);$p=HttpClient::probe($u,8,500000);if((int)($p['status']??0)>=200&&(int)($p['status']??0)<400){$pages[]=['url'=>(string)($p['final_url']??$u),'html'=>(string)($p['body']??''),'kind'=>'seed'];foreach(self::contactLinks((string)($p['body']??''),(string)($p['final_url']??$u)) as $cu){if(count($pages)>=7)break;try{$cp=HttpClient::probe($cu,6,350000);if((int)($cp['status']??0)>=200&&(int)($cp['status']??0)<400)$pages[]=['url'=>(string)($cp['final_url']??$cu),'html'=>(string)($cp['body']??''),'kind'=>'contact_page'];}catch(Throwable){}}}}catch(Throwable){}}
        foreach($pages as $page)foreach(self::extract((string)$page['html'],(string)$page['url']) as $c){$key=$c['type'].'|'.pb_strtolower($c['value']);if(isset($found[$key]))continue;$found[$key]=$c+['source_kind'=>$page['kind']];}
        foreach($found as $c){db()->prepare('INSERT INTO prospect_contact_evidence(lead_id,contact_type,contact_value,source_url,source_kind,confidence,verified) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE source_url=VALUES(source_url),source_kind=VALUES(source_kind),confidence=GREATEST(confidence,VALUES(confidence)),verified=GREATEST(verified,VALUES(verified))')->execute([$leadId,$c['type'],pb_substr($c['value'],0,1200),pb_substr($c['source_url'],0,1200),$c['source_kind'],(int)$c['confidence'],!empty($c['verified'])?1:0]);}
        $methods=[];foreach($found as $c)$methods[$c['type']][]=$c['value'];foreach($methods as &$vals)$vals=array_values(array_unique($vals));unset($vals);$old=json_decode((string)($lead['contact_methods_json']??'{}'),true);if(!is_array($old))$old=[];foreach($methods as $k=>$vals)$old[$k]=array_values(array_unique(array_merge((array)($old[$k]??[]),$vals)));db()->prepare('UPDATE prospect_leads SET contact_methods_json=?,status=IF(status="qualified" AND ? > 0,"contact_ready",status),updated_at=NOW() WHERE id=?')->execute([j($old),count($found),$leadId]);
        $contactId=self::syncDirectory($lead,$methods);return ['lead_id'=>$leadId,'contacts'=>array_values($found),'methods'=>$methods,'directory_contact_id'=>$contactId,'pages_checked'=>count($pages)];
    }
    private static function syncDirectory(array $lead,array $m):?int{
        $email=(string)($m['email'][0]??'');$phone=(string)($m['phone'][0]??'');$wa=(string)($m['whatsapp'][0]??'');if($email===''&&$phone===''&&$wa==='')return null;$q=db()->prepare("SELECT id FROM contact_directory WHERE group_key='prospects' AND (LOWER(display_name)=LOWER(?) OR (?<>'' AND email=?) OR (?<>'' AND phone=?)) ORDER BY id LIMIT 1");$q->execute([(string)$lead['company_name'],$email,$email,$phone,$phone]);$id=(int)($q->fetchColumn()?:0);$data=['display_name'=>(string)$lead['company_name'],'role_title'=>'Prospect / عميل محتمل','phone'=>$phone,'whatsapp_phone'=>$wa?:$phone,'email'=>$email,'telegram_ref'=>(string)($m['telegram'][0]??''),'instagram_ref'=>(string)($m['instagram'][0]??''),'tiktok_ref'=>(string)($m['tiktok'][0]??''),'group_key'=>'prospects','enabled'=>1,'metadata'=>['prospect_lead_id'=>(int)$lead['id'],'facebook'=>$m['facebook'][0]??null,'linkedin'=>$m['linkedin'][0]??null,'x'=>$m['x'][0]??null],'notes'=>'تم جمع بيانات التواصل من صفحات عامة مع Evidence داخل prospect_contact_evidence.'];try{return ContactDirectoryService::save($data,$id?:null);}catch(Throwable){return $id?:null;}
    }
    private static function extract(string $html,string $url):array{
        $out=[];$add=static function(string $type,string $value,int $confidence,bool $verified=false)use(&$out,$url){$value=trim(html_entity_decode($value,ENT_QUOTES|ENT_HTML5));if($value==='')return;$out[]=['type'=>$type,'value'=>$value,'source_url'=>$url,'confidence'=>$confidence,'verified'=>$verified];};
        if(preg_match_all('/mailto:([^"\'\s?<>]+)/i',$html,$m))foreach($m[1] as $v)if(filter_var($v,FILTER_VALIDATE_EMAIL))$add('email',pb_strtolower($v),95,true);
        if(preg_match_all('/[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}/i',strip_tags($html),$m))foreach($m[0] as $v)if(filter_var($v,FILTER_VALIDATE_EMAIL))$add('email',pb_strtolower($v),80,false);
        if(preg_match_all('/tel:([^"\'\s<>]+)/i',$html,$m))foreach($m[1] as $v){$d=preg_replace('/\D+/','',$v)?:'';if(strlen($d)>=7)$add('phone',$d,95,true);}
        if(preg_match_all('#https?://(?:wa\.me|api\.whatsapp\.com)/(?:send\?phone=)?([0-9+]+)#i',$html,$m))foreach($m[1] as $v){$d=preg_replace('/\D+/','',$v)?:'';if(strlen($d)>=7)$add('whatsapp',$d,95,true);}
        if(preg_match_all('/href\s*=\s*["\'](https?:\/\/[^"\']+)["\']/i',$html,$m))foreach($m[1] as $v){$h=pb_strtolower((string)(parse_url(html_entity_decode($v),PHP_URL_HOST)?:''));foreach(self::SOCIAL as $host=>$type)if($h===$host||str_ends_with($h,'.'.$host)){$add($type,html_entity_decode($v),90,true);break;}}
        return $out;
    }
    private static function contactLinks(string $html,string $base):array{
        preg_match_all('/href\s*=\s*["\']([^"\'#]+)["\']/i',$html,$m);$out=[];foreach((array)($m[1]??[]) as $h){if(!preg_match('/contact|about|reach|support|اتصل|تواصل|من-نحن|عن-الشركة/iu',$h))continue;$u=self::absolute($base,html_entity_decode($h));if($u)$out[$u]=1;if(count($out)>=4)break;}return array_keys($out);
    }
    private static function absolute(string $base,string $href):?string{if(filter_var($href,FILTER_VALIDATE_URL))return Security::publicUrl($href);$p=parse_url($base);if(!$p||empty($p['scheme'])||empty($p['host']))return null;$root=$p['scheme'].'://'.$p['host'].(!empty($p['port'])?':'.$p['port']:'');if(str_starts_with($href,'/'))return Security::publicUrl($root.$href);$dir=rtrim(str_replace('\\','/',dirname((string)($p['path']??'/'))),'/.');return Security::publicUrl($root.($dir?'/'.ltrim($dir,'/'):'').'/'.$href);}
    private static function lead(int $id):array{$q=db()->prepare('SELECT * FROM prospect_leads WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('prospect_not_found');return $r;}
}
