<?php
declare(strict_types=1);
final class ProviderCapabilityRouter {
    private const CAPS=['text','coding','vision','embeddings','web_search','search','image','video','stt','tts','realtime_voice','voice','browser','external_api'];
    public static function capabilities():array{return self::CAPS;}
    public static function normalizeCapability(string $c):string{$c=strtolower(trim($c));if($c==='search')$c='web_search';if($c==='voice')$c='realtime_voice';if(!in_array($c,self::CAPS,true))throw new RuntimeException('provider_capability_invalid');return $c;}
    public static function routes(string $capability,bool $includeUnhealthy=true,int $agentId=0):array{
        $capability=self::normalizeCapability($capability);$rows=[];
        if($agentId>0){try{$q=db()->prepare("SELECT r.*,COALESCE(p.label,r.provider_key) provider_label,p.status provider_status,COALESCE(ap.priority_order,99) agent_priority FROM provider_capability_routes r LEFT JOIN providers p ON p.provider_key=r.provider_key LEFT JOIN agent_capability_route_preferences ap ON ap.agent_id=? AND ap.capability=r.capability AND ap.provider_key=r.provider_key AND COALESCE(ap.model_key,'')=COALESCE(r.model_key,'') WHERE r.capability=? AND r.enabled=1 AND COALESCE(ap.enabled,1)=1 ORDER BY CASE WHEN ap.id IS NULL THEN 1 ELSE 0 END,COALESCE(ap.priority_order,99),FIELD(r.health_state,'working','degraded','untested','failed','disabled'),r.route_order");$q->execute([$agentId,$capability]);$rows=$q->fetchAll();}catch(Throwable){$agentId=0;}}
        if($agentId<=0){$q=db()->prepare("SELECT r.*,COALESCE(p.label,r.provider_key) provider_label,p.status provider_status FROM provider_capability_routes r LEFT JOIN providers p ON p.provider_key=r.provider_key WHERE r.capability=? AND r.enabled=1 ORDER BY FIELD(r.health_state,'working','degraded','untested','failed','disabled'),r.route_order");$q->execute([$capability]);$rows=$q->fetchAll();}
        return $includeUnhealthy?$rows:array_values(array_filter($rows,fn($r)=>!in_array((string)$r['health_state'],['failed','disabled'],true)));
    }
    public static function all():array{return db()->query("SELECT r.*,COALESCE(p.label,r.provider_key) provider_label,p.status provider_status FROM provider_capability_routes r LEFT JOIN providers p ON p.provider_key=r.provider_key ORDER BY FIELD(r.health_state,'working','degraded','untested','failed','disabled'),r.capability,r.route_order")->fetchAll();}
    public static function route(string $cap,int $order):array{$cap=self::normalizeCapability($cap);$q=db()->prepare('SELECT * FROM provider_capability_routes WHERE capability=? AND route_order=?');$q->execute([$cap,$order]);$r=$q->fetch();if(!$r)throw new RuntimeException('provider_capability_route_not_found');return $r;}
    public static function preferred(string $cap,int $agentId=0):?array{$r=self::routes($cap,false,$agentId);return $r[0]??null;}
    public static function upsert(string $cap,int $order,string $provider,?string $model=null,bool $enabled=true,array $config=[],?float $cost=null,string $unit='request'):void{$cap=self::normalizeCapability($cap);$order=max(1,min(9,$order));db()->prepare("INSERT INTO provider_capability_routes(capability,route_order,provider_key,model_key,enabled,health_state,config_json,estimated_cost_usd,cost_unit) VALUES (?,?,?,?,?,'untested',?,?,?) ON DUPLICATE KEY UPDATE provider_key=VALUES(provider_key),model_key=VALUES(model_key),enabled=VALUES(enabled),config_json=VALUES(config_json),estimated_cost_usd=VALUES(estimated_cost_usd),cost_unit=VALUES(cost_unit),updated_at=NOW()")->execute([$cap,$order,trim($provider),trim((string)$model)?:null,$enabled?1:0,$config?j($config):'{}',$cost,$unit?:'request']);}
    public static function setAgentPreference(int $agentId,string $cap,string $provider,?string $model,int $priority=1,bool $enabled=true):void{AgentService::byId($agentId);$cap=self::normalizeCapability($cap);db()->prepare("INSERT INTO agent_capability_route_preferences(agent_id,capability,provider_key,model_key,priority_order,enabled) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE priority_order=VALUES(priority_order),enabled=VALUES(enabled),updated_at=NOW()")->execute([$agentId,$cap,trim($provider),trim((string)$model)?:null,max(1,min(99,$priority)),$enabled?1:0]);}
    public static function agentPreferences(int $id):array{$q=db()->prepare('SELECT * FROM agent_capability_route_preferences WHERE agent_id=? ORDER BY capability,priority_order,id');$q->execute([$id]);return $q->fetchAll();}
    public static function markRoute(string $cap,int $order,bool $ok,string $err='',?int $lat=null):void{
        $cap=self::normalizeCapability($cap);$sql='UPDATE provider_capability_routes SET health_state=?,last_checked_at=NOW(),last_error=?,last_latency_ms=?,updated_at=NOW() WHERE capability=? AND route_order=?';$params=[$ok?'working':'failed',$ok?null:substr(Security::redactSecrets($err),0,500),$lat,$cap,$order];
        try{db()->prepare($sql)->execute($params);return;}catch(Throwable $e){if(Database::isDisconnect($e)){try{Database::reconnect();db()->prepare($sql)->execute($params);return;}catch(Throwable $retry){$e=$retry;}}error_log('PerseBayt provider route health telemetry: '.Security::redactSecrets($e->getMessage(),180));}
    }
    public static function text(int $agentId,string $instructions,array $messages,int $max=2500,string $cap='text'):array{$cap=self::normalizeCapability($cap);if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'ai_call');$errors=[];foreach(self::routes($cap,false,$agentId) as $route){$start=microtime(true);try{AiBudgetService::assertAllowed($agentId,$cap,(float)($route['estimated_cost_usd']??0));$p=(string)$route['provider_key'];$a=AgentService::byId($agentId);if(!empty($route['model_key']))$a['model']=$route['model_key'];$r=$p==='openrouter'?self::openRouterText($route,$instructions,$messages,$max):($p==='openai'?OpenAIClient::text($a,$instructions,$messages,$max):throw new RuntimeException('provider_text_driver_unsupported:'.$p));self::markRoute($cap,(int)$route['route_order'],true,'',(int)round((microtime(true)-$start)*1000));AiBudgetService::record($agentId,$p,(string)($r['model']??''),$cap,(int)($r['input_tokens']??0),(int)($r['output_tokens']??0),['route_order'=>(int)$route['route_order']]);if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'ai_call',1,(float)($route['estimated_cost_usd']??0),['capability'=>$cap,'provider'=>$p]);return $r+['provider'=>$p,'capability'=>$cap,'route_order'=>(int)$route['route_order']];}catch(Throwable $e){self::markRoute($cap,(int)$route['route_order'],false,$e->getMessage(),(int)round((microtime(true)-$start)*1000));$errors[]=$e->getMessage();}}throw new RuntimeException('provider_routes_exhausted:'.substr(implode(' | ',$errors),0,600));}
    public static function coding(int $a,string $i,array $m,int $max=5000):array{return self::text($a,$i,$m,$max,'coding');}
    public static function webSearch(int $agentId,string $query,int $limit=8):array{if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'search');$errors=[];foreach(self::routes('web_search',false,$agentId) as $r){$start=microtime(true);try{$p=(string)$r['provider_key'];AiBudgetService::assertAllowed($agentId,'search',(float)($r['estimated_cost_usd']??0));$items=match($p){'openrouter'=>OpenRouterService::webSearchSources($query,$limit),'openai'=>OpenAIClient::webSearchSources($query,$limit),'configured_search','web_search'=>WebSearchClient::searchGeneral($query,$limit),default=>throw new RuntimeException('web_search_driver_unsupported:'.$p)};self::markRoute('web_search',(int)$r['route_order'],true,'',(int)round((microtime(true)-$start)*1000));if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'search',1,(float)($r['estimated_cost_usd']??0),['provider'=>$p]);return ['items'=>$items,'provider'=>$p,'route_order'=>(int)$r['route_order']];}catch(Throwable $e){self::markRoute('web_search',(int)$r['route_order'],false,$e->getMessage(),(int)round((microtime(true)-$start)*1000));$errors[]=$e->getMessage();}}throw new RuntimeException('web_search_routes_exhausted:'.substr(implode(' | ',$errors),0,500));}
    public static function embedding(int $agentId,string $text):array{if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'ai_call');$errors=[];foreach(self::routes('embeddings',false,$agentId) as $r){$start=microtime(true);try{$p=(string)$r['provider_key'];$model=trim((string)($r['model_key']??''));if($p==='openai')$out=OpenAIMediaClient::embedding($text,$model?:null);elseif($p==='openrouter'){$key=trim((string)SecretVault::get('providers.openrouter.api_key',''));if(strlen($key)<10)throw new RuntimeException('openrouter_not_configured');$raw=HttpClient::json('POST',OpenRouterService::BASE_URL.'/embeddings',OpenRouterService::headers()+['Authorization'=>'Bearer '.$key],['model'=>$model?:'openai/text-embedding-3-small','input'=>substr($text,0,12000)],60);$vec=$raw['data'][0]['embedding']??null;if(!is_array($vec))throw new RuntimeException('embedding_vector_missing');$out=['vector'=>array_map('floatval',$vec),'model'=>$raw['model']??$model];}else throw new RuntimeException('embedding_driver_unsupported:'.$p);self::markRoute('embeddings',(int)$r['route_order'],true,'',(int)round((microtime(true)-$start)*1000));if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'ai_call',1,(float)($r['estimated_cost_usd']??0),['capability'=>'embeddings','provider'=>$p]);return $out+['provider'=>$p,'route_order'=>(int)$r['route_order']];}catch(Throwable $e){self::markRoute('embeddings',(int)$r['route_order'],false,$e->getMessage(),(int)round((microtime(true)-$start)*1000));$errors[]=$e->getMessage();}}throw new RuntimeException('embedding_routes_exhausted:'.substr(implode(' | ',$errors),0,500));}
    public static function vision(int $agentId,string $prompt,string $imageUrl,int $max=1500):array{if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'ai_call');$errors=[];foreach(self::routes('vision',false,$agentId) as $r){$start=microtime(true);try{$p=(string)$r['provider_key'];$model=trim((string)($r['model_key']??''));if($p==='openai')$out=OpenAIMediaClient::vision($prompt,$imageUrl,$model?:null,$max);elseif($p==='openrouter'){$payload=['model'=>$model?:OpenRouterService::preferredModel(),'messages'=>[['role'=>'user','content'=>[['type'=>'text','text'=>$prompt],['type'=>'image_url','image_url'=>['url'=>Security::publicUrl($imageUrl)]]]]],'max_completion_tokens'=>$max];$raw=OpenRouterService::chat($payload,90,2);$out=['text'=>OpenRouterService::messageText($raw),'model'=>$raw['model']??$payload['model']];}else throw new RuntimeException('vision_driver_unsupported:'.$p);self::markRoute('vision',(int)$r['route_order'],true,'',(int)round((microtime(true)-$start)*1000));if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'ai_call',1,(float)($r['estimated_cost_usd']??0),['capability'=>'vision','provider'=>$p]);return $out+['provider'=>$p];}catch(Throwable $e){self::markRoute('vision',(int)$r['route_order'],false,$e->getMessage(),null);$errors[]=$e->getMessage();}}throw new RuntimeException('vision_routes_exhausted:'.substr(implode(' | ',$errors),0,500));}
    public static function transcribe(int $agentId,string $path):array{if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'voice');$r=self::audio($agentId,'stt',$path,'');if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'voice',1,0,['capability'=>'stt']);return $r;}
    public static function speak(int $agentId,string $text):array{if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'voice');$r=self::audio($agentId,'tts','',$text);if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'voice',1,0,['capability'=>'tts']);return $r;}
    private static function audio(int $agentId,string $cap,string $path,string $text):array{$errors=[];foreach(self::routes($cap,false,$agentId) as $r){try{$p=(string)$r['provider_key'];if($p!=='openai')throw new RuntimeException($cap.'_driver_unsupported:'.$p);$cfg=json_decode((string)($r['config_json']??'{}'),true)?:[];$out=$cap==='stt'?OpenAIMediaClient::transcribe($path,$r['model_key']?:null):OpenAIMediaClient::tts($text,$r['model_key']?:null,$cfg['voice']??null);self::markRoute($cap,(int)$r['route_order'],true,'',null);return $out+['provider'=>$p,'route_order'=>(int)$r['route_order']];}catch(Throwable $e){self::markRoute($cap,(int)$r['route_order'],false,$e->getMessage(),null);$errors[]=$e->getMessage();}}throw new RuntimeException($cap.'_routes_exhausted:'.substr(implode(' | ',$errors),0,500));}
    public static function realtimeVoice(int $agentId,array $payload=[]):array{if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::authorize($agentId,'voice');$r=self::preferred('realtime_voice',$agentId);if(!$r)throw new RuntimeException('realtime_voice_not_configured');$cfg=json_decode((string)($r['config_json']??'{}'),true)?:[];$url=trim((string)($cfg['bridge_url']??config('calls.bridge_url','')));if($url==='')throw new RuntimeException('realtime_voice_bridge_not_configured');AgentPolicyEngine::authorizeAction($agentId,'voice_center','use',['risk'=>'high','external'=>true,'owner_approved'=>(bool)($payload['owner_approved']??false),'gateway_managed'=>true]);$out=HttpClient::json('POST',$url,[],['agent_id'=>$agentId,'model'=>$r['model_key']??null,'payload'=>$payload],30)+['provider'=>$r['provider_key']];if(class_exists('AgentUsageBudgetService'))AgentUsageBudgetService::record($agentId,'voice',1,(float)($r['estimated_cost_usd']??0),['capability'=>'realtime_voice']);return $out;}
    public static function markRouteHealth(string $cap,int $order,string $state,?string $error=null,?int $latencyMs=null):void{
        $cap=self::normalizeCapability($cap);$state=in_array($state,['working','degraded','untested','failed','disabled'],true)?$state:($state==='verified'?'working':'failed');$sql='UPDATE provider_capability_routes SET health_state=?,last_checked_at=NOW(),last_error=?,last_latency_ms=COALESCE(?,last_latency_ms),updated_at=NOW() WHERE capability=? AND route_order=?';$params=[$state,$state==='working'?null:pb_substr(Security::redactSecrets((string)$error),0,500),$latencyMs,$cap,$order];
        try{db()->prepare($sql)->execute($params);return;}catch(Throwable $e){if(Database::isDisconnect($e)){try{Database::reconnect();db()->prepare($sql)->execute($params);return;}catch(Throwable $retry){$e=$retry;}}error_log('PerseBayt provider health telemetry: '.Security::redactSecrets($e->getMessage(),180));}
    }
    public static function markProviderHealth(string $provider,string $state,?string $error=null):void{
        $mapped=in_array($state,['working','degraded','untested','failed','disabled'],true)?$state:($state==='verified'?'working':'failed');$sql='UPDATE provider_capability_routes SET health_state=?,last_checked_at=NOW(),last_error=?,updated_at=NOW() WHERE provider_key=?';$params=[$mapped,$mapped==='working'?null:pb_substr(Security::redactSecrets((string)$error),0,500),$provider];
        try{db()->prepare($sql)->execute($params);return;}catch(Throwable $e){if(Database::isDisconnect($e)){try{Database::reconnect();db()->prepare($sql)->execute($params);return;}catch(Throwable $retry){$e=$retry;}}error_log('PerseBayt provider status telemetry: '.Security::redactSecrets($e->getMessage(),180));}
    }
    /** Synchronize explicit provider/bridge availability without pretending it was live-tested. */
    public static function syncFromProviders():int{
        $rows=db()->query('SELECT capability,route_order,provider_key,health_state FROM provider_capability_routes WHERE enabled=1')->fetchAll();$changed=0;
        foreach($rows as $r){$p=(string)$r['provider_key'];$old=(string)$r['health_state'];$available=self::configured($p);$next=$old;
            if(!$available)$next='disabled';elseif($old==='disabled')$next='untested';
            if($next!==$old){db()->prepare('UPDATE provider_capability_routes SET health_state=?,last_error=?,updated_at=NOW() WHERE capability=? AND route_order=?')->execute([$next,$next==='disabled'?'provider_not_configured_or_disabled':null,(string)$r['capability'],(int)$r['route_order']]);$changed++;}
        }
        return $changed;
    }
    public static function image(int $agentId,int $projectId,string $label,string $prompt,int $taskId=0):array{
        AgentUsageBudgetService::authorize($agentId,'media');$errors=[];foreach(self::routes('image',false,$agentId) as $r){$start=microtime(true);try{$p=(string)$r['provider_key'];AiBudgetService::assertAllowed($agentId,'image',(float)($r['estimated_cost_usd']??0));if($p==='media_bridge')$out=MediaBridgeClient::request($projectId,$taskId,$agentId,'image',$label,$prompt);elseif($p==='openai'){$raw=OpenAIMediaClient::image($prompt,$r['model_key']?:null);$out=self::recordDirectImage($agentId,$projectId,$taskId,$label,$prompt,$raw,$p,(float)($r['estimated_cost_usd']??0));}else throw new RuntimeException('image_driver_unsupported:'.$p);self::markRoute('image',(int)$r['route_order'],true,'',(int)round((microtime(true)-$start)*1000));if($p!=='media_bridge')AgentUsageBudgetService::record($agentId,'media',1,(float)($r['estimated_cost_usd']??0),['capability'=>'image','provider'=>$p]);return $out+['provider'=>$p,'route_order'=>(int)$r['route_order']];}catch(Throwable $e){self::markRoute('image',(int)$r['route_order'],false,$e->getMessage(),null);$errors[]=$e->getMessage();}}throw new RuntimeException('image_routes_exhausted:'.substr(implode(' | ',$errors),0,500));
    }
    public static function video(int $agentId,int $projectId,string $label,string $prompt,int $taskId=0):array{
        AgentUsageBudgetService::authorize($agentId,'media');$errors=[];foreach(self::routes('video',false,$agentId) as $r){$start=microtime(true);try{$p=(string)$r['provider_key'];if($p!=='media_bridge')throw new RuntimeException('video_driver_unsupported:'.$p);$out=MediaBridgeClient::request($projectId,$taskId,$agentId,'video',$label,$prompt);self::markRoute('video',(int)$r['route_order'],true,'',(int)round((microtime(true)-$start)*1000));if($p!=='media_bridge')AgentUsageBudgetService::record($agentId,'media',1,0,['capability'=>'video','provider'=>$p]);return $out+['provider'=>$p,'route_order'=>(int)$r['route_order']];}catch(Throwable $e){self::markRoute('video',(int)$r['route_order'],false,$e->getMessage(),null);$errors[]=$e->getMessage();}}throw new RuntimeException('video_routes_exhausted:'.substr(implode(' | ',$errors),0,500));
    }
    public static function browser(int $agentId,int $accountId,string $operation,array $params=[]):array{AgentUsageBudgetService::authorize($agentId,'browser');$r=BrowserAutomationService::execute($agentId,$accountId,$operation,$params);return $r;}
    private static function recordDirectImage(int $agentId,int $projectId,int $taskId,string $label,string $prompt,array $raw,string $provider,float $estimatedCost=0):array{
        $path=trim((string)($raw['path']??''));$url=trim((string)($raw['url']??''));if($path===''&&$url==='')throw new RuntimeException('direct_image_reference_missing');
        db()->prepare("INSERT INTO media_requests(project_id,task_id,requested_by_agent_id,media_type,label,prompt_text,provider,state,created_at,completed_at) VALUES (?,?,?,?,?,?,?,'completed',NOW(),NOW())")->execute([$projectId,$taskId?:null,$agentId,'image',$label,$prompt,$provider]);$requestId=(int)db()->lastInsertId();
        db()->prepare("INSERT INTO project_assets(project_id,asset_type,label,source,path_ref,url_ref,status,metadata_json) VALUES (?,?,?,'generated',?,?,'active',?)")->execute([$projectId,'image',$label,$path?:null,$url?:null,j(['media_request_id'=>$requestId,'provider'=>$provider,'model'=>$raw['model']??null,'revised_prompt'=>$raw['revised_prompt']??null])]);$assetId=(int)db()->lastInsertId();
        db()->prepare("UPDATE media_requests SET result_asset_id=? WHERE id=?")->execute([$assetId,$requestId]);
        try{AiBudgetService::record($agentId,$provider,(string)($raw['model']??'image'),'image',0,0,['request_id'=>$requestId,'asset_id'=>$assetId,'estimated_cost_usd'=>$estimatedCost],$taskId?:null,$projectId);}catch(Throwable $e){error_log('PerseBayt direct image budget ledger: '.Security::redactSecrets($e->getMessage(),180));}
        try{Audit::log('system','provider_router','media.generated','project_asset',(string)$assetId,'verified',$projectId,$taskId?:null,['request_id'=>$requestId,'provider'=>$provider,'type'=>'image']);}catch(Throwable){}
        return $raw+['request_id'=>$requestId,'state'=>'completed','asset_id'=>$assetId];
    }
    public static function testRoute(string $cap,int $order):array{$r=self::route($cap,$order);$cap=self::normalizeCapability($cap);$start=microtime(true);try{$p=(string)$r['provider_key'];$ok=match($cap){'browser'=>BrowserAutomationService::configured(),'video','image'=>MediaBridgeClient::configured()||self::configured($p),'web_search'=>self::configured($p),'stt','tts','vision','embeddings','realtime_voice','external_api'=>self::configured($p),default=>self::configured($p)};if(in_array($cap,['text','coding'],true)&&$ok){$agent=(int)AgentService::bySlug('ramy')['id'];$tmp=self::text($agent,'Return OK only.',[['role'=>'user','content'=>'OK']],32,$cap);$ok=trim((string)($tmp['text']??''))!=='';}$lat=(int)round((microtime(true)-$start)*1000);self::markRoute($cap,$order,$ok,$ok?'':'provider_not_configured',$lat);return ['ok'=>$ok,'capability'=>$cap,'provider'=>$p,'latency_ms'=>$lat,'non_billable'=>!in_array($cap,['text','coding'],true)];}catch(Throwable $e){self::markRoute($cap,$order,false,$e->getMessage(),null);throw $e;}}
    private static function openRouterText(array $r,string $inst,array $messages,int $max):array{$payload=['model'=>trim((string)($r['model_key']??''))?:OpenRouterService::preferredModel(),'messages'=>[['role'=>'system','content'=>$inst]],'max_completion_tokens'=>$max,'temperature'=>0.2];foreach($messages as $m)$payload['messages'][]=['role'=>($m['role']??'user')==='assistant'?'assistant':'user','content'=>(string)($m['content']??'')];$raw=OpenRouterService::chat($payload,90,3);return ['text'=>OpenRouterService::messageText($raw),'model'=>$raw['model']??$payload['model'],'input_tokens'=>(int)($raw['usage']['prompt_tokens']??0),'output_tokens'=>(int)($raw['usage']['completion_tokens']??0)];}
    private static function configured(string $p):bool{return match($p){'openrouter'=>OpenRouterService::configured(),'openai'=>OpenAIClient::configured(),'media_bridge'=>MediaBridgeClient::configured(),'browser_automation','browser_bridge'=>BrowserAutomationService::configured(),'generic_call_bridge','call_bridge'=>CallBridgeClient::configured(),'twilio'=>TwilioClient::configured(),'web_search','configured_search'=>WebSearchClient::configured(),default=>self::providerRow($p)};}
    private static function providerRow(string $p):bool{try{$q=db()->prepare('SELECT enabled,status FROM providers WHERE provider_key=?');$q->execute([$p]);$r=$q->fetch();return $r&&(int)$r['enabled']===1&&(string)$r['status']!=='disabled';}catch(Throwable){return false;}}
}
