<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){Auth::verifyCsrf();try{$op=(string)($_POST['op']??'');if($op==='route_save'){ProviderCapabilityRouter::upsert((string)$_POST['capability'],(int)$_POST['route_order'],(string)$_POST['provider_key'],(string)($_POST['model_key']??''),!empty($_POST['enabled']),[],($_POST['estimated_cost_usd']??'')!==''?(float)$_POST['estimated_cost_usd']:null,(string)($_POST['cost_unit']??'request'));$_SESSION['flash']='Capability route saved.';}elseif($op==='route_test'){$r=ProviderCapabilityRouter::testRoute((string)$_POST['capability'],(int)$_POST['route_order']);$_SESSION['flash']='Route test: '.(!empty($r['ok'])?'working':'not verified').' - '.($r['latency_ms']??'').' ms';}else throw new RuntimeException('provider_center_action_invalid');$_SESSION['flash_type']='success';}catch(Throwable $e){$_SESSION['flash']=AdminUi::humanError($e->getMessage());$_SESSION['flash_type']='error';}header('Location: /api/admin/provider-center.php');exit;}
$routes=ProviderCapabilityRouter::all();$providers=db()->query("SELECT provider_key,label,kind,status,enabled,last_checked_at,last_error FROM providers ORDER BY FIELD(status,'verified','working','degraded','untested','failed','disabled'),enabled DESC,label")->fetchAll();$caps=ProviderCapabilityRouter::capabilities();AdminUi::header('Provider Capability Center','provider_center');echo AdminUi::flash();
?>
<section class="card"><div class="card-title"><div><h2>Provider Capability Center</h2><span class="muted small">Routes are capability-aware. Health is evidence from the latest test, not a claim that every external integration is live.</span></div></div><div class="creator-grid"><?php foreach($providers as $p):?><article class="card subtle" style="margin:0"><div class="card-title"><div><b><?=e($p['label'])?></b><small class="muted" style="display:block"><?=e($p['provider_key'])?> - <?=e($p['kind'])?></small></div><?=AdminUi::badge($p['enabled']?$p['status']:'disabled')?></div><p class="small muted">Last test: <?=e(AdminUi::date($p['last_checked_at']))?></p><?php if($p['last_error']):?><p class="small" style="color:#f6a8a8"><?=e(AdminUi::humanError($p['last_error']))?></p><?php endif?><div class="actions"><a class="btn ghost small" href="/api/admin/provider-chat.php?provider=<?=urlencode($p['provider_key'])?>">Chat test</a><a class="btn ghost small" href="/api/admin/integrations.php">Edit</a></div></article><?php endforeach?></div></section>
<section class="card"><div class="card-title"><h2>Capability Routes</h2></div><div class="table-wrap"><table><thead><tr><th>Capability</th><th>Order</th><th>Provider</th><th>Model</th><th>Health</th><th>Cost</th><th>Latency</th><th>Last error</th><th></th></tr></thead><tbody><?php foreach($routes as $r):?><tr><td><?=e($r['capability'])?></td><td><?=(int)$r['route_order']?></td><td><?=e($r['provider_label']?:$r['provider_key'])?></td><td><?=e($r['model_key']?:'default')?></td><td><?=AdminUi::badge($r['enabled']?$r['health_state']:'disabled')?></td><td><?=e($r['estimated_cost_usd']!==null?'$'.$r['estimated_cost_usd'].'/'.$r['cost_unit']:'unknown')?></td><td><?=e($r['last_latency_ms']!==null?$r['last_latency_ms'].' ms':'-')?></td><td><?=e($r['last_error']?AdminUi::humanError($r['last_error']):'-')?></td><td><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="route_test"><input type="hidden" name="capability" value="<?=e($r['capability'])?>"><input type="hidden" name="route_order" value="<?=$r['route_order']?>"><button class="btn small">Test</button></form></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="card-title"><h2>Add or edit route</h2></div><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="route_save"><div class="grid"><div class="field span-3"><label>Capability</label><select name="capability"><?php foreach($caps as $c):?><option value="<?=e($c)?>"><?=e($c)?></option><?php endforeach?></select></div><div class="field span-2"><label>Order</label><input type="number" name="route_order" value="1" min="1" max="9"></div><div class="field span-3"><label>Provider key</label><input name="provider_key" required></div><div class="field span-4"><label>Model</label><input name="model_key"></div><div class="field span-3"><label>Estimated cost USD</label><input type="number" step="0.000001" name="estimated_cost_usd"></div><div class="field span-3"><label>Cost unit</label><input name="cost_unit" value="request"></div><div class="span-3"><label class="check"><input type="checkbox" name="enabled" value="1" checked> Enabled</label></div><div class="span-3"><button class="btn full-width">Save route</button></div></div></form></section>
<?php AdminUi::footer();
