<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){Auth::verifyCsrf();try{$op=(string)($_POST['op']??'');if($op==='approve_resource'){$r=AgentResourceService::approve((int)$_POST['id'],(int)(Auth::user()['id']??1));$_SESSION['flash']='Resource request executed and verified.';}elseif($op==='apply_schema'){$r=PhysicalSchemaService::approveAndApply((int)$_POST['id'],(int)(Auth::user()['id']??1));$_SESSION['flash']='Physical custom table applied and registered.';}else throw new RuntimeException('resource_action_invalid');$_SESSION['flash_type']='success';}catch(Throwable $e){$_SESSION['flash']=AdminUi::humanError($e->getMessage());$_SESSION['flash_type']='error';}header('Location: /api/admin/resources.php');exit;}
$req=AgentResourceService::list(250);$registry=ResourceRegistryService::all(250);$schemas=PhysicalSchemaService::pending();AdminUi::header('Resources & Registry','resources');echo AdminUi::flash();
?>
<section class="card"><div class="card-title"><div><h2>Universal Resource Requests</h2><span class="muted small">Every governed resource follows capability, policy, risk, approval, budget/backup when applicable, execute, verify, registry, evidence and audit.</span></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Agent</th><th>Type</th><th>Project</th><th>Risk</th><th>State</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($req as $r):?><tr><td><?=$r['id']?></td><td><?=e($r['agent_name'])?></td><td><?=e($r['resource_type'])?></td><td><?=e($r['project_name']?:'-')?></td><td><?=e($r['risk_level'])?></td><td><?=AdminUi::badge($r['state'])?></td><td><?=e(AdminUi::date($r['created_at']))?></td><td><?php if($r['state']==='pending_approval'):?><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="approve_resource"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn small">Approve & execute</button></form><?php elseif($r['last_error']):?><span class="small"><?=e(AdminUi::humanError($r['last_error']))?></span><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="card-title"><h2>Physical custom table requests</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Agent</th><th>Table</th><th>Reason</th><th>State</th><th></th></tr></thead><tbody><?php foreach($schemas as $s):?><tr><td><?=$s['id']?></td><td><?=e($s['agent_name'])?></td><td><code><?=e($s['table_name'])?></code></td><td><?=e($s['reason_text']??'')?></td><td><?=AdminUi::badge($s['state'])?></td><td><?php if(in_array($s['state'],['pending','failed'],true)):?><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="apply_schema"><input type="hidden" name="id" value="<?=$s['id']?>"><button class="btn small">Preflight & apply</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="card-title"><h2>Resource Registry</h2></div><div class="table-wrap"><table><thead><tr><th>Type</th><th>Key</th><th>Label</th><th>Agent</th><th>Project</th><th>State</th><th>External ref</th></tr></thead><tbody><?php foreach($registry as $r):?><tr><td><?=e($r['resource_type'])?></td><td><code><?=e($r['resource_key'])?></code></td><td><?=e($r['label'])?></td><td><?=e($r['agent_name']?:'-')?></td><td><?=e($r['project_name']?:'-')?></td><td><?=AdminUi::badge($r['state'])?></td><td><?=e($r['external_ref']?:'-')?></td></tr><?php endforeach?></tbody></table></div></section>
<?php AdminUi::footer();
