<?php
declare(strict_types=1);
final class RuntimeValidationService {
    public static function scenarios():array{return [
        'core_integrations'=>['label'=>'Core integrations, cron and worker continuity','mode'=>'integration'],
        'full_integrations'=>['label'=>'Full integrations and schema readiness','mode'=>'integration'],
        'company_flow'=>['label'=>'Correlated lead to delivery evidence','mode'=>'e2e'],
        'agency_flow'=>['label'=>'Correlated El Fares supervisor loop evidence','mode'=>'e2e'],
        'samir_flow'=>['label'=>'Correlated Samir browser/account evidence','mode'=>'e2e'],
        'mona_flow'=>['label'=>'Correlated Mona scene/render evidence','mode'=>'e2e'],
        'company_synthetic_flow'=>['label'=>'Isolated company workflow readiness','mode'=>'synthetic_e2e'],
        'agency_synthetic_flow'=>['label'=>'Isolated agency workflow readiness','mode'=>'synthetic_e2e'],
        'social_synthetic_flow'=>['label'=>'Isolated social workflow readiness','mode'=>'synthetic_e2e'],
        'v17_core_acceptance'=>['label'=>'Company OS 17 compatibility acceptance','mode'=>'synthetic_e2e'],
        'v20_core_acceptance'=>['label'=>'Company OS 20 unified superset acceptance','mode'=>'synthetic_e2e'],
    ];}
    public static function run(string $scenario,string $requestedBy='owner'):array{
        $defs=self::scenarios();if(!isset($defs[$scenario]))throw new RuntimeException('runtime_validation_scenario_invalid');$d=$defs[$scenario];db()->prepare("INSERT INTO runtime_validation_runs(scenario_key,label_ar,mode_key,state,requested_by,started_at) VALUES (?,?,?,'running',?,NOW())")->execute([$scenario,$d['label'],$d['mode'],$requestedBy]);$id=(int)db()->lastInsertId();$steps=[];try{$steps=match($scenario){'core_integrations'=>self::core($id),'full_integrations'=>self::fullIntegrations($id),'company_flow'=>self::company($id),'agency_flow'=>self::agency($id),'samir_flow'=>self::samir($id),'mona_flow'=>self::mona($id),'company_synthetic_flow'=>self::syntheticCompany($id),'agency_synthetic_flow'=>self::syntheticAgency($id),'social_synthetic_flow'=>self::syntheticSocial($id),'v17_core_acceptance'=>self::v20CoreAcceptance($id),'v20_core_acceptance'=>self::v20CoreAcceptance($id)};$failed=count(array_filter($steps,static fn($x)=>$x['state']==='failed'));$blocked=count(array_filter($steps,static fn($x)=>in_array($x['state'],['blocked','skipped'],true)));$passed=count(array_filter($steps,static fn($x)=>$x['state']==='passed'));$state=$failed?'failed':($blocked?'partial':'passed');$summary=['passed'=>$passed,'failed'=>$failed,'blocked'=>$blocked,'total'=>count($steps)];db()->prepare('UPDATE runtime_validation_runs SET state=?,summary_json=?,completed_at=NOW() WHERE id=?')->execute([$state,j($summary),$id]);return ['run_id'=>$id,'scenario'=>$scenario,'state'=>$state,'summary'=>$summary,'steps'=>$steps];}catch(Throwable $e){db()->prepare("UPDATE runtime_validation_runs SET state='failed',summary_json=?,completed_at=NOW() WHERE id=?")->execute([j(['error'=>pb_substr(Security::redactSecrets($e->getMessage()),0,300)]),$id]);throw $e;}
    }
    private static function add(int $runId,string $key,string $label,string $state,string $details,array $evidence=[]):array{if(!in_array($state,['passed','failed','blocked','skipped'],true))$state='failed';db()->prepare('INSERT INTO runtime_validation_steps(run_id,step_key,label_ar,state,details_text,evidence_json) VALUES (?,?,?,?,?,?)')->execute([$runId,$key,$label,$state,pb_substr($details,0,8000),$evidence?j($evidence):null]);return ['key'=>$key,'label'=>$label,'state'=>$state,'details'=>$details,'evidence'=>$evidence];}
    private static function probeResult(array $r):array{
        $stateRaw=pb_strtolower(trim((string)($r['state']??'')));
        $ok=array_key_exists('ok',$r)?(bool)$r['ok']:null;
        $error=trim((string)($r['error']??$r['result_code']??$r['code']??''));
        $issues=$r['issues']??null;
        if($ok===false||in_array($stateRaw,['failed','error','unhealthy'],true)){
            $hint=pb_strtolower($error.' '.(is_array($issues)?implode(' ',array_map('strval',$issues)):(string)$issues));
            $blocked=str_contains($hint,'not_configured')||str_contains($hint,'missing')||str_contains($hint,'disabled')||str_contains($hint,'unavailable');
            $details=$error!==''?$error:($issues?('issues: '.pb_substr(is_array($issues)?j($issues):(string)$issues,0,700)):'Probe returned a failure state.');
            return [$blocked?'blocked':'failed',$details];
        }
        if(in_array($stateRaw,['blocked','skipped','partial','pending','untested'],true)){
            $details=$error!==''?$error:('Probe returned state '.$stateRaw.'.');
            return [$stateRaw==='skipped'?'skipped':'blocked',$details];
        }
        if($ok===true||$stateRaw===''||in_array($stateRaw,['verified','passed','ok','healthy','success','completed'],true))return ['passed','Live probe succeeded.'];
        return ['blocked','Probe returned an unrecognized state: '.$stateRaw];
    }
    private static function probe(int $runId,string $key,string $label,callable $fn):array{try{$r=$fn();$evidence=is_array($r)?$r:['result'=>$r];[$state,$details]=is_array($r)?self::probeResult($r):['passed','Live probe succeeded.'];return self::add($runId,$key,$label,$state,$details,$evidence);}catch(Throwable $e){$msg=pb_substr(Security::redactSecrets($e->getMessage()),0,500);$low=pb_strtolower($msg);$blocked=str_contains($low,'not_configured')||str_contains($low,'missing')||str_contains($low,'disabled')||str_contains($low,'unavailable');return self::add($runId,$key,$label,$blocked?'blocked':'failed',$msg);}}
    private static function core(int $id):array{
        $out=[];$out[]=self::probe($id,'openrouter','OpenRouter inference',static fn()=>OpenRouterService::inferenceTest());$out[]=self::probe($id,'meta','WhatsApp Meta phone',static fn()=>MetaClient::test());$out[]=self::probe($id,'hostinger','Hostinger inventory',static function(){ $r=HostingerClient::websites();return ['website_count'=>count($r),'sample'=>array_slice(array_map(static fn($x)=>is_array($x)?array_intersect_key($x,array_flip(['domain','username','status'])):$x,$r),0,3)];});$out[]=self::probe($id,'browser','Browser automation bridge',static fn()=>BrowserAutomationService::test());$out[]=self::probe($id,'browser_qa','Browser QA bridge',static fn()=>BrowserQaService::test());$out[]=self::probe($id,'media','Media bridge',static fn()=>MediaBridgeClient::test());
        $last=(string)setting('runtime.worker_heartbeat_at','');$ts=utc_ts($last);$healthy=$ts!==false&&$ts>=time()-300;$out[]=self::add($id,'worker','Worker heartbeat',$healthy?'passed':'failed',$healthy?'Worker heartbeat is recent.':'Worker heartbeat is stale or missing.',['heartbeat_at'=>$last]);
        try{$h=db()->query("SELECT COUNT(*) samples,MIN(heartbeat_minute) first_at,MAX(heartbeat_minute) last_at FROM worker_heartbeat_log WHERE heartbeat_minute>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 6 HOUR)")->fetch()?:[];$samples=(int)($h['samples']??0);$first=(string)($h['first_at']??'');$lastSeen=(string)($h['last_at']??'');$span=0;if($first!==''&&$lastSeen!==''){$a=strtotime($first.' UTC');$b=strtotime($lastSeen.' UTC');if($a!==false&&$b!==false)$span=max(0,$b-$a);}$continuity=$samples>=6&&$span>=5*3600;$out[]=self::add($id,'worker_continuity','Worker six-hour continuity',$continuity?'passed':'blocked',$continuity?'Heartbeat history proves worker activity across at least five hours of the last six.':'There is not yet enough heartbeat history to prove multi-hour continuity. Leave the worker running and repeat this validation later.',['samples'=>$samples,'first_at'=>$first?:null,'last_at'=>$lastSeen?:null,'span_seconds'=>$span]);}catch(Throwable $e){$out[]=self::add($id,'worker_continuity','Worker six-hour continuity','blocked',pb_substr(Security::redactSecrets($e->getMessage()),0,400));}
        try{$site=HostingerClient::siteByDomain((string)(parse_url((string)config('app.base_url'),PHP_URL_HOST)?:'persebayt.com'));$crons=HostingerClient::cronJobs((string)$site['username']);$found=false;foreach($crons as $c){$raw=pb_strtolower(j($c));if(str_contains($raw,'worker')||str_contains($raw,'cron-worker')){$found=true;break;}}$out[]=self::add($id,'cron','Worker cron',$found?'passed':'failed',$found?'Worker cron entry found.':'No worker cron entry was identified.',['cron_count'=>count($crons)]);}catch(Throwable $e){$out[]=self::add($id,'cron','Worker cron','blocked',pb_substr(Security::redactSecrets($e->getMessage()),0,400));}
        return $out;
    }
    private static function company(int $id):array{
        $out=[];$q=db()->query("SELECT p.id,p.name,p.workflow_stage,p.opportunity_id,COALESCE(p.opportunity_id,(SELECT o2.id FROM opportunities o2 WHERE o2.project_id=p.id ORDER BY o2.id DESC LIMIT 1)) linked_opportunity_id FROM projects p WHERE p.is_system_project=0 ORDER BY (COALESCE(p.opportunity_id,(SELECT o3.id FROM opportunities o3 WHERE o3.project_id=p.id ORDER BY o3.id DESC LIMIT 1)) IS NOT NULL) DESC,(p.workflow_stage IN ('delivered','closed')) DESC,p.id DESC LIMIT 1");$p=$q->fetch()?:null;if(!$p)return [self::add($id,'project','Project correlated chain','blocked','No non-system project exists yet.')];$pid=(int)$p['id'];$oid=(int)($p['linked_opportunity_id']??0);$base=['project_id'=>$pid,'project_name'=>$p['name'],'workflow_stage'=>$p['workflow_stage'],'opportunity_id'=>$oid?:null];
        $lead=false;$leadState=null;if($oid>0){$x=db()->prepare('SELECT status FROM opportunities WHERE id=?');$x->execute([$oid]);$leadState=$x->fetchColumn();$lead=in_array((string)$leadState,['approved','contacted','negotiating','won'],true);}$out[]=self::add($id,'lead','Linked qualified opportunity',$lead?'passed':'blocked',$lead?'The same project is linked to an active/approved opportunity.':'The selected project has no linked approved/active opportunity evidence.',$base+['opportunity_status'=>$leadState?:null]);
        $out[]=self::add($id,'project','Project created','passed','A real project row anchors all remaining checks.',$base);
        $x=db()->prepare("SELECT COUNT(*) FROM tasks t JOIN agents a ON a.id=t.assigned_agent_id WHERE t.project_id=? AND a.slug='ayman' AND t.status IN ('approved','completed')");$x->execute([$pid]);$build=(int)$x->fetchColumn();$out[]=self::add($id,'build','Ayman completed work on same project',$build>0?'passed':'blocked',$build>0?'Ayman completion evidence is tied to this project.':'No completed Ayman task is tied to this project.',$base+['ayman_completed_tasks'=>$build]);
        $x=db()->prepare("SELECT COUNT(*) FROM reviews r JOIN agents a ON a.id=r.reviewer_agent_id WHERE r.project_id=? AND a.slug='emad' AND r.status IN ('approved','approved_warning')");$x->execute([$pid]);$qa=(int)$x->fetchColumn();$out[]=self::add($id,'qa','Emad QA approval on same project',$qa>0?'passed':'blocked',$qa>0?'Approved Emad review is tied to this project.':'No approved Emad review is tied to this project.',$base+['approved_reviews'=>$qa]);
        $delivery=in_array((string)$p['workflow_stage'],['delivered','closed'],true);$out[]=self::add($id,'delivery','Delivered/closed same project',$delivery?'passed':'blocked',$delivery?'The correlated project reached delivery/closure.':'The correlated project has not reached delivered/closed.',$base);
        return $out;
    }
    private static function agency(int $id):array{
        $out=[];$q=db()->query("SELECT e.*,t.id linked_thread_id FROM agency_events e LEFT JOIN agency_threads t ON t.id=e.thread_id ORDER BY (e.thread_id IS NOT NULL) DESC,(e.state='completed') DESC,e.id DESC LIMIT 1");$e=$q->fetch()?:null;if(!$e)return [self::add($id,'event','Basant event chain','blocked','No agency event exists yet.')];$eid=(int)$e['id'];$creator=(string)($e['creator_id']??'');$thread=(int)($e['thread_id']??0);$base=['event_id'=>$eid,'creator_id'=>$creator?:null,'thread_id'=>$thread?:null,'event_state'=>$e['state']];
        $imports=0;if($creator!==''){$x=db()->prepare("SELECT COUNT(*) FROM agency_creator_monthly m JOIN agency_imports i ON i.id=m.import_id WHERE m.creator_id=? AND i.state IN ('completed','completed_warning')");$x->execute([$creator]);$imports=(int)$x->fetchColumn();}$out[]=self::add($id,'import','Creator data linked to completed XLSX import',$imports>0?'passed':'blocked',$imports>0?'The same creator has imported TikTok data.':'No completed XLSX import is linked to this event creator.',$base+['matching_import_rows'=>$imports]);
        $out[]=self::add($id,'event','Basant event created','passed','A real agency event anchors this validation.',$base);
        $outbound=0;$inbound=0;if($thread>0){$x=db()->prepare("SELECT SUM(direction='outbound') outbound_count,SUM(direction='inbound') inbound_count FROM agency_thread_messages WHERE thread_id=?");$x->execute([$thread]);$m=$x->fetch()?:[];$outbound=(int)($m['outbound_count']??0);$inbound=(int)($m['inbound_count']??0);}$out[]=self::add($id,'outbound','Supervisor outbound message on same thread',$outbound>0?'passed':'blocked',$outbound>0?'Outbound supervisor message exists on the linked thread.':'No outbound supervisor message exists on the linked event thread.',$base+['outbound_count'=>$outbound]);$out[]=self::add($id,'inbound','Supervisor reply linked to same thread',$inbound>0?'passed':'blocked',$inbound>0?'Inbound supervisor reply is linked to the same thread.':'No inbound supervisor reply is linked to the same thread.',$base+['inbound_count'=>$inbound]);$closed=(string)$e['state']==='completed'&&$inbound>0;$out[]=self::add($id,'closure','Agency event completed after reply',$closed?'passed':'blocked',$closed?'The same event is completed and its thread contains a reply.':'The event is not yet closed with linked reply evidence.',$base);return $out;
    }
    private static function samir(int $id):array{
        $out=[];$q=db()->query("SELECT r.*,p.state playbook_state,p.owner_approved,sa.status account_status FROM social_account_runs r JOIN social_playbooks p ON p.id=r.playbook_id LEFT JOIN service_accounts sa ON sa.id=r.service_account_id ORDER BY (r.state='completed') DESC,r.id DESC LIMIT 1");$r=$q->fetch()?:null;if(!$r)return [self::add($id,'run','Samir correlated browser/account chain','blocked','No social account run exists yet.')];$base=['run_id'=>(int)$r['id'],'playbook_id'=>(int)$r['playbook_id'],'service_account_id'=>!empty($r['service_account_id'])?(int)$r['service_account_id']:null,'platform'=>$r['platform'],'operation'=>$r['operation_key']];$approved=(string)$r['playbook_state']==='approved'&&(int)$r['owner_approved']===1;$out[]=self::add($id,'playbook','Approved platform playbook',$approved?'passed':'blocked',$approved?'The exact run used an owner-approved versioned playbook.':'The selected run is not tied to an approved playbook.',$base);$done=(string)$r['state']==='completed';$out[]=self::add($id,'run','Completed browser playbook run',$done?'passed':'blocked',$done?'The same browser run completed.':'The selected browser run has not completed.',$base+['run_state'=>$r['state']]);$active=$done&&!empty($r['service_account_id'])&&(string)$r['account_status']==='active';$out[]=self::add($id,'account','Active account from same completed run',$active?'passed':'blocked',$active?'The account linked to this completed run is active.':'No active service account is linked to this completed run.',$base+['account_status'=>$r['account_status']??null]);return $out;
    }
    private static function mona(int $id):array{
        $out=[];$q=db()->query("SELECT v.*,EXISTS(SELECT 1 FROM video_render_jobs r WHERE r.production_id=v.id AND r.state='completed' AND r.result_asset_id IS NOT NULL) has_completed_render FROM video_productions v ORDER BY has_completed_render DESC,v.id DESC LIMIT 1");$v=$q->fetch()?:null;if(!$v)return [self::add($id,'production','Mona production chain','blocked','No video production exists yet.')];$pid=(int)$v['id'];$base=['production_id'=>$pid,'title'=>$v['title'],'project_id'=>$v['project_id']?:null,'state'=>$v['state']];$out[]=self::add($id,'production','Video production exists','passed','A real Mona production anchors this validation.',$base);$x=db()->prepare("SELECT COUNT(*) total,SUM(state IN ('ready','approved')) ready FROM video_scenes WHERE production_id=?");$x->execute([$pid]);$s=$x->fetch()?:[];$total=(int)($s['total']??0);$ready=(int)($s['ready']??0);$sceneOk=$total>0&&$ready===$total;$out[]=self::add($id,'scenes','All scenes rendered for same production',$sceneOk?'passed':'blocked',$sceneOk?'Every scene in this production is ready/approved.':'The selected production does not yet have all scene assets ready.',$base+['scene_total'=>$total,'scene_ready'=>$ready]);$x=db()->prepare("SELECT id,result_asset_id,completed_at FROM video_render_jobs WHERE production_id=? AND state='completed' AND result_asset_id IS NOT NULL ORDER BY id DESC LIMIT 1");$x->execute([$pid]);$render=$x->fetch()?:null;$out[]=self::add($id,'render','Completed final composition for same production',$render?'passed':'blocked',$render?'A completed final render is linked to the same production.':'No completed final render is linked to the selected production.',$base+['render_job_id'=>$render?(int)$render['id']:null,'result_asset_id'=>$render?(int)$render['result_asset_id']:null]);return $out;
    }
    private static function fullIntegrations(int $id):array{
        $out=self::core($id);
        $out[]=self::probe($id,'schema_preflight','Schema 20.x preflight',static fn()=>SchemaPreflightService::verify());
        $out[]=self::probe($id,'provider_capabilities','Provider capability health sync',static fn()=>['synced'=>ProviderCapabilityRouter::syncFromProviders(),'routes'=>array_map(static fn($c)=>['capability'=>$c,'preferred'=>ProviderCapabilityRouter::preferred($c)],['text','coding','image','video','tts','stt','voice','browser','search'])]);
        if(OpenAIClient::configured()){$out[]=self::probe($id,'openai_fallback','OpenAI fallback connection',static function(){try{return ConnectionTester::test('openai');}catch(Throwable $e){$ramy=AgentService::bySlug('ramy');$r=OpenAIClient::text($ramy,'Reply with OK only.',[['role'=>'user','content'=>'health check']],64);return ['response'=>pb_substr((string)($r['text']??''),0,100)];}});}else $out[]=self::add($id,'openai_fallback','OpenAI fallback connection','blocked','OpenAI fallback is not configured.');
        if(CallBridgeClient::configured())$out[]=self::probe($id,'call_bridge','Voice/Call bridge health',static fn()=>CallBridgeClient::health());else $out[]=self::add($id,'call_bridge','Voice/Call bridge health','blocked','Call bridge is not configured.');
        $root='';try{$root=StagingService::rootDomain();}catch(Throwable $e){}$out[]=self::add($id,'staging_root','Staging root configured',$root!==''?'passed':'blocked',$root!==''?'Staging root is configured as '.$root.'.':'Staging root is not configured.',['root_domain'=>$root?:null]);
        return $out;
    }
    private static function syntheticCompany(int $id):array{
        $out=[];$schema=SchemaPreflightService::verify();$out[]=self::add($id,'schema','Company workflow schema',$schema['ok']?'passed':'failed',$schema['ok']?'Required 11.0 workflow schema is present.':'Schema preflight reports missing components.',['issues'=>$schema['issues']]);
        foreach(['walid','ayman','emad','ramy'] as $slug){try{$a=AgentService::bySlug($slug);$out[]=self::add($id,'agent_'.$slug,'Required agent '.$slug,(int)($a['is_active']??0)===1?'passed':'blocked',(int)($a['is_active']??0)===1?'Agent is active.':'Agent exists but is not active.',['agent_id'=>(int)$a['id']]);}catch(Throwable $e){$out[]=self::add($id,'agent_'.$slug,'Required agent '.$slug,'failed','Required agent is missing.');}}
        $root='';try{$root=StagingService::rootDomain();}catch(Throwable){}$out[]=self::add($id,'prototype_pipeline','Prospect to prototype pipeline',$root!==''&&class_exists('ProspectPrototypeService')?'passed':'blocked',$root!==''?'Prototype workflow service is loaded and staging root is '.$root.'.':'Prototype workflow cannot run until staging is configured.');
        return $out;
    }
    private static function syntheticAgency(int $id):array{
        $out=[];try{$b=AgentService::bySlug('basant');$out[]=self::add($id,'basant','Basant agent',(int)($b['is_active']??0)===1?'passed':'blocked','Basant agent record is available.',['agent_id'=>(int)$b['id']]);}catch(Throwable $e){$out[]=self::add($id,'basant','Basant agent','failed','Basant agent is missing.');}
        $required=['agency_events','agency_threads','agency_thread_messages','contact_communication_policies'];foreach($required as $t){try{$n=(int)db()->query("SELECT COUNT(*) FROM `$t`")->fetchColumn();$out[]=self::add($id,'table_'.$t,'Agency table '.$t,'passed','Table is queryable.',['rows'=>$n]);}catch(Throwable $e){$out[]=self::add($id,'table_'.$t,'Agency table '.$t,'failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}}
        return $out;
    }
    private static function syntheticSocial(int $id):array{
        $out=[];try{$s=AgentService::bySlug('samir-social');$out[]=self::add($id,'samir','Samir agent',(int)($s['is_active']??0)===1?'passed':'blocked','Samir agent record is available.',['agent_id'=>(int)$s['id']]);}catch(Throwable $e){$out[]=self::add($id,'samir','Samir agent','failed','Samir agent is missing.');}
        $q=db()->query("SELECT platform,operation_key,state,owner_approved FROM social_playbooks WHERE version_no=1 ORDER BY platform,operation_key");$rows=$q->fetchAll();$approved=count(array_filter($rows,static fn($r)=>(string)$r['state']==='approved'&&(int)$r['owner_approved']===1));$out[]=self::add($id,'playbooks','Seeded social playbooks',$rows?'passed':'blocked',$rows?'Versioned playbooks are present.':'No social playbooks are seeded.',['count'=>count($rows),'owner_approved'=>$approved]);
        $out[]=self::add($id,'browser_bridge','Browser automation bridge configuration',BrowserAutomationService::configured()?'passed':'blocked',BrowserAutomationService::configured()?'Browser bridge is configured.':'Browser bridge requires deployment/configuration before real account automation.');
        return $out;
    }
    private static function v20CoreAcceptance(int $id):array{
        $out=[];$schema=SchemaPreflightService::verify();$out[]=self::add($id,'schema20','Company OS 20 canonical schema',!empty($schema['ok'])?'passed':'failed',!empty($schema['ok'])?'All required Company OS 20 superset schema components are present.':'Schema preflight reports missing Company OS 20 components.',['issues'=>array_slice((array)($schema['issues']??[]),0,20)]);
        $services=['AgentPolicyEngine','AgentUsageBudgetService','AgentInitiativeService','CoreAgentInitiativeService','CreatorIntelligenceService','AgentResourceService','PhysicalSchemaService','AgentWorkflowService','VoiceAgentCenterService','ProviderCapabilityRouter','AgentBuilderService','VaultSnapshotService'];foreach($services as $c)$out[]=self::add($id,'svc_'.strtolower($c),$c,class_exists($c)?'passed':'failed',class_exists($c)?'Service is loaded.':'Service class is missing.');
        try{$q=db()->query("SELECT COUNT(*) total,SUM(enabled=1) enabled FROM agent_policy_rules");$r=$q->fetch()?:[];$out[]=self::add($id,'policy_rules','Central policy rules',(int)($r['enabled']??0)>0?'passed':'failed','Policy rules are persisted and enabled.',$r);}catch(Throwable $e){$out[]=self::add($id,'policy_rules','Central policy rules','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$q=db()->query("SELECT COUNT(*) FROM agent_autonomy WHERE brain_enabled=1 AND daily_ai_call_budget>0 AND daily_external_action_budget>0");$n=(int)$q->fetchColumn();$out[]=self::add($id,'count_budgets','Per-agent count/rate budgets',$n>0?'passed':'failed',$n>0?'Autonomous agents have active count/rate budgets.':'No active count/rate budget policy was found.',['agents'=>$n]);}catch(Throwable $e){$out[]=self::add($id,'count_budgets','Per-agent count/rate budgets','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$q=db()->query("SELECT COUNT(*) FROM agent_initiatives WHERE uid IS NOT NULL");$n=(int)$q->fetchColumn();$out[]=self::add($id,'rich_initiatives','Rich initiative schema/runtime','passed','Rich initiative schema is queryable; historical rows may be zero.',['rows_with_uid'=>$n]);}catch(Throwable $e){$out[]=self::add($id,'rich_initiatives','Rich initiative schema/runtime','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$n=(int)db()->query("SELECT COUNT(*) FROM agent_workflow_templates WHERE enabled=1 AND state='active'")->fetchColumn();$steps=(int)db()->query("SELECT COUNT(*) FROM agent_workflow_steps WHERE enabled=1")->fetchColumn();$out[]=self::add($id,'workflow_runtime','Normalized workflow runtime',$n>=4&&$steps>=4?'passed':'failed','Reusable workflows and normalized enabled steps are queryable.',['templates'=>$n,'steps'=>$steps]);}catch(Throwable $e){$out[]=self::add($id,'workflow_runtime','Normalized workflow runtime','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$n=(int)db()->query("SELECT COUNT(*) FROM provider_capability_routes WHERE enabled=1 AND capability IN ('text','coding','vision','embeddings','web_search','image','video','stt','tts','realtime_voice','browser','external_api')")->fetchColumn();$out[]=self::add($id,'provider_router','Unified provider capability routes',$n>=12?'passed':'failed','Required capability routes are registered.',['route_rows'=>$n]);}catch(Throwable $e){$out[]=self::add($id,'provider_router','Unified provider capability routes','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$bad=(int)db()->query("SELECT COUNT(*) FROM agents WHERE is_active=1 AND slug IN ('ramy','walid','ayman','emad','samir-social','video-director','basant','community-manager') AND (system_prompt LIKE '%socialpanelova.com%' OR system_prompt LIKE '%[CompanyOS 4.%' OR system_prompt LIKE '%[CompanyOS 5.%' OR system_prompt LIKE '%[CompanyOS 8.%')")->fetchColumn();$out[]=self::add($id,'canonical_prompts','Canonical active prompts',$bad===0?'passed':'failed',$bad===0?'Active built-in agent prompts are canonical and do not include obsolete prompt blocks.':'One or more active prompts still contain legacy instructions.',['legacy_prompt_count'=>$bad]);}catch(Throwable $e){$out[]=self::add($id,'canonical_prompts','Canonical active prompts','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$n=(int)db()->query("SELECT COUNT(*) FROM secure_vault_snapshots WHERE state='verified' AND CHAR_LENGTH(envelope_sha256)=64")->fetchColumn();$out[]=self::add($id,'encrypted_vault_snapshot','Encrypted current vault snapshot',$n>0?'passed':'failed',$n>0?'Encrypted vault envelope is preserved in the database without plaintext secrets.':'No verified encrypted vault snapshot is available.',['snapshots'=>$n]);}catch(Throwable $e){$out[]=self::add($id,'encrypted_vault_snapshot','Encrypted current vault snapshot','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$n=(int)db()->query("SELECT COUNT(*) FROM secure_config_snapshots WHERE state='verified' AND CHAR_LENGTH(config_sha256)=64")->fetchColumn();$out[]=self::add($id,'encrypted_config_snapshot','Encrypted current config snapshot',$n>0?'passed':'failed',$n>0?'Encrypted config envelope and config hash are preserved.':'No verified encrypted config snapshot is available.',['snapshots'=>$n]);}catch(Throwable $e){$out[]=self::add($id,'encrypted_config_snapshot','Encrypted current config snapshot','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$n=(int)db()->query("SELECT COUNT(DISTINCT capability) FROM provider_capability_routes WHERE enabled=1 AND capability IN ('image','video','browser','embeddings')")->fetchColumn();$out[]=self::add($id,'provider_media_browser_routes','Image/video/browser/embedding routes',$n===4?'passed':'failed',$n===4?'All Company OS 20 extended provider routes are registered.':'One or more extended provider routes are missing.',['capabilities'=>$n]);}catch(Throwable $e){$out[]=self::add($id,'provider_media_browser_routes','Image/video/browser/embedding routes','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$sync=ProviderCapabilityRouter::syncFromProviders();$out[]=self::add($id,'provider_health_sync','Provider capability synchronization','passed','Provider routes synchronized without a missing-method/runtime error.',is_array($sync)?$sync:['result'=>$sync]);}catch(Throwable $e){$out[]=self::add($id,'provider_health_sync','Provider capability synchronization','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        try{$q=db()->prepare("SELECT COUNT(*) FROM schema_migrations WHERE migration_id='companyos_20_0_final_unified' AND state IN ('applied','verified')");$q->execute();$n=(int)$q->fetchColumn();$out[]=self::add($id,'migration20','Company OS 20 migration ledger',$n>0?'passed':'failed',$n>0?'Company OS 20 migration is recorded.':'Company OS 20 migration record is missing.');}catch(Throwable $e){$out[]=self::add($id,'migration20','Company OS 20 migration ledger','failed',pb_substr(Security::redactSecrets($e->getMessage()),0,300));}
        $out[]=self::add($id,'canonicalizer_service','Prompt canonicalizer service',class_exists('PromptCanonicalizerService')?'passed':'failed',class_exists('PromptCanonicalizerService')?'Prompt canonicalizer is available.':'Prompt canonicalizer service is missing.');
        $releaseOk=class_exists('ReleaseInfo')&&(ReleaseInfo::VERSION==='20.0.0-final-unified'||str_starts_with(ReleaseInfo::VERSION,'20.1.'));$out[]=self::add($id,'release20','Release 20/20.1 package marker',$releaseOk?'passed':'failed','Release marker is '.(class_exists('ReleaseInfo')?ReleaseInfo::VERSION:'missing').'.');
        $out[]=self::add($id,'db_reconnect_guard','MySQL stale-connection recovery',method_exists(Database::class,'isDisconnect')&&method_exists(Database::class,'reconnect')?'passed':'failed','Long provider calls can recover stale PDO connections before post-call writes.');
        return $out;
    }
    public static function scheduled():array{
        if(setting('runtime.validation.scheduler_enabled','1')==='0')return ['enabled'=>false,'runs'=>[]];$utc=new DateTimeImmutable('now',new DateTimeZone('UTC'));$hour=(int)$utc->format('G');$dow=(int)$utc->format('w');$dailyHour=max(0,min(23,(int)setting('runtime.validation.daily_hour_utc','2')));$weeklyDay=max(0,min(6,(int)setting('runtime.validation.weekly_day_utc','0')));$weeklyHour=max(0,min(23,(int)setting('runtime.validation.weekly_hour_utc','3')));$rows=[];try{$rows=db()->query("SELECT * FROM runtime_validation_scenarios WHERE enabled=1 ORDER BY scenario_key")->fetchAll();}catch(Throwable){$rows=[];}$map=['critical_integrations'=>'core_integrations','full_integrations'=>'full_integrations','company_synthetic_flow'=>'company_synthetic_flow','agency_synthetic_flow'=>'agency_synthetic_flow','social_synthetic_flow'=>'social_synthetic_flow','v17_core_acceptance'=>'v17_core_acceptance','v20_core_acceptance'=>'v20_core_acceptance'];$runs=[];
        foreach($rows as $r){$key=(string)$r['scenario_key'];$scenario=$map[$key]??$key;if(!isset(self::scenarios()[$scenario]))continue;$schedule=(string)$r['schedule_key'];if(!in_array($schedule,['daily','weekly'],true))continue;$due=false;if($schedule==='daily'&&$hour>=$dailyHour){$q=db()->prepare('SELECT MAX(started_at) FROM runtime_validation_runs WHERE scenario_key=?');$q->execute([$scenario]);$last=(string)($q->fetchColumn()?:'');$due=$last===''||substr($last,0,10)!==$utc->format('Y-m-d');}elseif($schedule==='weekly'&&$dow===$weeklyDay&&$hour>=$weeklyHour){$q=db()->prepare('SELECT MAX(started_at) FROM runtime_validation_runs WHERE scenario_key=?');$q->execute([$scenario]);$last=(string)($q->fetchColumn()?:'');$ts=$last!==''?utc_ts($last):false;$due=$ts===false||$ts<time()-6*86400;}if(!$due)continue;try{$runs[$key]=self::run($scenario,'scheduler');}catch(Throwable $e){$runs[$key]=['state'=>'failed','error'=>pb_substr(Security::redactSecrets($e->getMessage()),0,240)];}}
        return ['enabled'=>true,'runs'=>$runs,'checked_at'=>now_utc()];
    }

    public static function latest(int $limit=40):array{$limit=max(1,min(200,$limit));return db()->query('SELECT * FROM runtime_validation_runs ORDER BY id DESC LIMIT '.$limit)->fetchAll();}
    public static function details(int $id):array{$q=db()->prepare('SELECT * FROM runtime_validation_runs WHERE id=?');$q->execute([$id]);$run=$q->fetch();if(!$run)throw new RuntimeException('runtime_validation_not_found');$s=db()->prepare('SELECT * FROM runtime_validation_steps WHERE run_id=? ORDER BY id');$s->execute([$id]);return ['run'=>$run,'steps'=>$s->fetchAll()];}
}
