<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$scenarios=RuntimeValidationService::scenarios();$runs=RuntimeValidationService::latest(60);$selected=(int)($_GET['run']??0);$detail=$selected?RuntimeValidationService::details($selected):null;
AdminUi::header('Runtime Validation','runtime_validation');echo AdminUi::flash();
?>
<section class="card"><div class="card-title"><div><h2>Evidence-based live validation</h2><span class="muted small">A feature is not marked proven because code exists. These scenarios inspect real integration responses and real Company OS evidence after deployment.</span></div></div><div class="creator-grid"><?php foreach($scenarios as $key=>$label):?><article class="card subtle" style="margin:0"><b><?=e($label)?></b><form method="post" action="action.php" style="margin-top:10px"><?=AdminUi::csrf()?><input type="hidden" name="action" value="runtime_validate"><input type="hidden" name="return" value="/api/admin/runtime-validation.php"><input type="hidden" name="scenario" value="<?=e($key)?>"><button class="btn full-width">Run now</button></form></article><?php endforeach?></div></section>
<?php if($detail):?><section class="card"><div class="card-title"><h2>Validation run #<?=$detail['run']['id']?></h2><?=AdminUi::badge($detail['run']['state'])?></div><div class="table-wrap"><table><thead><tr><th>Step</th><th>State</th><th>Message</th><th>Evidence</th></tr></thead><tbody><?php foreach($detail['steps'] as $s):?><tr><td><?=e($s['step_key'])?></td><td><?=AdminUi::badge($s['state'])?></td><td><?=e($s['details_text']??'')?></td><td><pre class="code-box"><?=e($s['evidence_json']??'')?></pre></td></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<section class="card"><div class="card-title"><h2>Validation history</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Scenario</th><th>State</th><th>Passed</th><th>Blocked</th><th>Failed</th><th>Time</th><th></th></tr></thead><tbody><?php foreach($runs as $r):?><tr><td>#<?=$r['id']?></td><td><?=e($r['scenario_key'])?></td><td><?=AdminUi::badge($r['state'])?></td><td><?=(int)$r['passed_steps']?></td><td><?=(int)$r['blocked_steps']?></td><td><?=(int)$r['failed_steps']?></td><td><?=e(AdminUi::date($r['created_at']))?></td><td><a class="link" href="?run=<?=$r['id']?>">Details</a></td></tr><?php endforeach?></tbody></table></div></section>
<?php AdminUi::footer();
