<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$quotes=db()->query("SELECT q.*,c.display_name customer_name,c.phone,p.name project_name,(SELECT COALESCE(SUM(amount),0) FROM payments x WHERE x.quote_id=q.id AND x.status='confirmed') paid FROM quotes q JOIN customers c ON c.id=q.customer_id LEFT JOIN projects p ON p.id=q.project_id ORDER BY q.id DESC LIMIT 300")->fetchAll();
$changes=db()->query("SELECT cr.*,c.display_name customer_name,p.name project_name FROM change_requests cr LEFT JOIN customers c ON c.id=cr.customer_id JOIN projects p ON p.id=cr.project_id ORDER BY cr.id DESC LIMIT 200")->fetchAll();
$customers=db()->query("SELECT id,display_name,phone,status FROM customers WHERE status IN ('lead','negotiating','active') ORDER BY updated_at DESC LIMIT 400")->fetchAll();
$projects=db()->query("SELECT id,name,primary_domain,status FROM projects WHERE status<>'archived' ORDER BY updated_at DESC LIMIT 400")->fetchAll();
AdminUi::header('العروض والتعديلات','sales');echo AdminUi::flash();
?>
<div class="grid">
<section class="card span-8" id="quotes"><div class="card-title"><div><h2>عروض الأسعار والصفقات</h2><span class="muted small">العرض يرسل للعميل، ولا يبدأ التنفيذ إلا بعد قبول العميل وتحقيق نسبة العربون المؤكد.</span></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>العميل</th><th>العرض</th><th>المشروع</th><th>الإجمالي</th><th>المقدم</th><th>المدفوع</th><th>الحالة</th><th>بدأ</th><th>جاهز</th><th>سُلّم</th><th>إجراء</th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td>#<?=$q['id']?></td><td><a href="customers.php?id=<?=$q['customer_id']?>"><?=e($q['customer_name']?:$q['phone'])?></a></td><td><?=e($q['title'])?></td><td><?=e($q['project_name']?:'—')?></td><td><?=e(number_format((float)$q['amount'],2).' '.AdminUi::currency((string)$q['currency']))?></td><td><?=e(number_format((float)($q['deposit_percent']??setting('business.deposit_start_percent','40')),0).'%')?><?=$q['owner_exception_required']?' '.AdminUi::badge('warning'):''?></td><td><?=e(number_format((float)$q['paid'],2))?></td><td><?=AdminUi::badge($q['status'])?></td><td><?=e(AdminUi::date($q['project_started_at']))?></td><td><?=e(AdminUi::date($q['delivery_ready_at']))?></td><td><?=e(AdminUi::date($q['delivered_at']))?></td><td><?php if($q['status']==='sent'):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="quote_accept_manual"><input type="hidden" name="quote_id" value="<?=$q['id']?>"><button class="btn secondary small-btn" data-confirm="تسجيل أن العميل قبل هذا العرض؟">قبول مؤكد</button></form><?php else:?>—<?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card span-4"><div class="card-title"><div><h2>إنشاء عرض جديد</h2><span class="muted small">رامي يرسل العرض عبر قناة العميل الحالية بعد إنشائه.</span></div></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="quote_create"><input type="hidden" name="return" value="/api/admin/sales.php"><div class="field"><label>العميل</label><select name="customer_id" required><option value="">اختر العميل</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=e($c['display_name']?:$c['phone']?:'عميل #'.$c['id'])?> — <?=e($c['status'])?></option><?php endforeach?></select></div><div class="field"><label>المشروع — اختياري</label><select name="project_id"><option value="0">بدون مشروع حالي</option><?php foreach($projects as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?><?= $p['primary_domain']?' — '.e($p['primary_domain']):''?></option><?php endforeach?></select></div><div class="field"><label>عنوان العرض</label><input name="title" required placeholder="مثال: موقع شركة تعريفي"></div><div class="field"><label>نطاق العمل</label><textarea name="scope_text" required placeholder="ما الذي سيتم تنفيذه وما الذي يشمله السعر"></textarea></div><div class="form-row"><div class="field"><label>السعر</label><input type="number" step="0.01" min="0.01" name="amount" required></div><div class="field"><label>العملة</label><input name="currency" value="<?=e((string)setting('business.currency','EGP'))?>" maxlength="3"></div></div><div class="form-row"><div class="field"><label>المقدم %</label><input type="number" step="1" min="1" max="100" name="deposit_percent" value="<?=e(setting('business.deposit_start_percent','40'))?>"></div><div class="field"><label>ملاحظات التفاوض</label><input name="negotiation_notes" placeholder="اختياري"></div></div><button class="btn full-width">إنشاء وإرسال العرض</button></form></section>
<section class="card span-12"><div class="card-title"><div><h2>قرارات التفاوض خارج السياسة</h2></div></div><?php $exceptions=array_values(array_filter($quotes,static fn($x)=>(int)($x['owner_exception_required']??0)===1));?><?php if(!$exceptions):?><?=AdminUi::empty('لا توجد استثناءات تفاوض معلقة.')?><?php else:?><div class="table-wrap"><table><thead><tr><th>العرض</th><th>العميل</th><th>الحالي</th><th>سبب/ملاحظة</th><th>قرار المالك</th></tr></thead><tbody><?php foreach($exceptions as $x):?><tr><td>#<?=$x['id']?> <?=e($x['title'])?></td><td><?=e($x['customer_name']?:'—')?></td><td><?=e(number_format((float)$x['amount'],2).' '.$x['currency'])?> · مقدم <?=e(number_format((float)($x['deposit_percent']??0),0).'%')?></td><td><?=e(pb_substr((string)($x['negotiation_notes']??''),0,500))?></td><td><form method="post" action="action.php" class="inline-edit"><?=AdminUi::csrf()?><input type="hidden" name="action" value="quote_owner_override"><input type="hidden" name="quote_id" value="<?=$x['id']?>"><input type="hidden" name="return" value="/api/admin/sales.php"><input type="number" step="0.01" min="0.01" name="amount" value="<?=e((string)$x['amount'])?>" required><input type="number" min="1" max="100" name="deposit_percent" value="<?=e((string)($x['deposit_percent']??setting('business.deposit_start_percent','40')))?>" required><input name="owner_note" placeholder="ملاحظة القرار"><button class="btn small-btn" data-confirm="اعتماد الاستثناء وإرسال تحديث العرض للعميل؟">اعتماد وإرسال</button></form></td></tr><?php endforeach?></tbody></table></div><?php endif?></section>
<section class="card span-12" id="changes" style="margin-top:2px"><div class="card-title"><div><h2>طلبات التعديل</h2><span class="muted small">التعديل الكبير يرجع لك قبل التنفيذ؛ الصغير داخل النطاق يستطيع رامي تمريره لدورة أيمن وعماد.</span></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>العميل</th><th>المشروع</th><th>الحجم</th><th>الطلب</th><th>الحالة</th><th>المهمة</th><th>قرار</th></tr></thead><tbody><?php foreach($changes as $cr):?><tr><td>#<?=$cr['id']?></td><td><?=e($cr['customer_name']?:'—')?></td><td><a href="projects.php?id=<?=$cr['project_id']?>"><?=e($cr['project_name'])?></a></td><td><?=AdminUi::badge($cr['size'])?></td><td><?=e(pb_substr($cr['request_text'],0,500))?></td><td><?=AdminUi::badge($cr['status'])?></td><td><?=$cr['task_id']?'<a class="link" href="tasks.php?id='.(int)$cr['task_id'].'">#'.(int)$cr['task_id'].'</a>':'—'?></td><td><?php if(in_array($cr['status'],['new','owner_review'],true)):?><div class="actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="change_request_decide"><input type="hidden" name="id" value="<?=$cr['id']?>"><input type="hidden" name="decision" value="approved"><button class="btn small-btn">اعتماد وتشغيل</button></form><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="change_request_decide"><input type="hidden" name="id" value="<?=$cr['id']?>"><input type="hidden" name="decision" value="rejected"><button class="btn danger small-btn">رفض</button></form></div><?php else:?>—<?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
</div><?php AdminUi::footer();
