<?php
declare(strict_types=1);
/** Verifies the canonical Company OS 20 superset schema after migration. */
final class SchemaPreflightService {
    private const REQUIRED_TABLES=[
        'schema_migrations','schema_migration_steps','migration_preflight_runs','release_setting_snapshots','agent_permission_sources','agent_tool_sources','agent_role_templates','agent_policy_rules','agent_policy_decisions',
        'agent_usage_daily','agent_usage_events','agent_initiatives','agent_goal_contributions','creator_intelligence_snapshots','company_goals','agent_budget_reservations',
        'resource_registry','resource_registry_events','resource_requests','physical_schema_requests','agent_schema_requests','schema_table_catalog',
        'agent_workflow_templates','agent_workflow_steps','agent_workflow_assignments','agent_workflow_runs','agent_workflow_run_steps',
        'voice_conversations','voice_turns','provider_capability_routes','agent_capability_route_preferences','agent_builder_profiles','data_source_registry','secure_vault_snapshots','secure_config_snapshots',
        'prospect_website_audits','prospect_contact_evidence','prospect_prototypes','goal_metric_definitions','video_continuity_assets','video_audio_assets','social_playbook_step_runs','data_retention_policies','runtime_validation_scenarios','runtime_validation_runs','runtime_validation_steps','system_archives','agent_memory_bank','agent_prompt_versions'
    ];
    private const REQUIRED_COLUMNS=[
        'agent_capability_catalog'=>['default_access_level','risk_level','requires_owner_approval','requires_backup','external_action','production_sensitive'],
        'agent_capability_assignments'=>['access_level','requires_owner_approval','requires_backup'],
        'agent_policy_decisions'=>['capability_key','permission_key','action_key','project_id','task_id','decision','decision_state','reason_code','owner_approval_required','owner_approved','reason_json','context_json','rule_id'],
        'agent_autonomy'=>['brain_enabled','max_initiatives_per_day','initiative_min_value','auto_execute_max_risk','followup_enabled','learning_enabled','self_improvement_enabled','daily_ai_call_budget','daily_external_action_budget','daily_search_budget','daily_media_budget','daily_voice_budget','daily_browser_budget','last_think_at','last_initiative_at','last_brain_state','last_brain_note'],
        'agent_initiatives'=>['uid','goal_id','summary','proposed_action','value_score','risk_level','requires_owner_approval','dedupe_key','reasoning_summary','payload_json','result_json','approved_by_user_id','approved_at','executed_at','expected_delta','actual_delta'],
        'agent_workflow_steps'=>['workflow_id','step_no','action_key','blocking','on_failure','risk_level','requires_owner_approval','enabled'],
        'agent_workflow_runs'=>['project_id','source_task_id','current_step','waiting_task_id','context_json','result_json','policy_decision_id','error_text','error_code','completed_at','finished_at'],
        'voice_conversations'=>['uid','agent_id','contact_id','channel_key','provider_key','external_call_id','state','transcript_text','last_turn_at','started_at','ended_at'],
        'voice_turns'=>['turn_no','direction','speaker','input_text','output_text','input_audio_path','output_audio_path','provider_key','state','evidence_json'],
        'provider_capability_routes'=>['capability','route_order','provider_key','model_key','enabled','config_json','estimated_cost_usd','cost_unit','health_state','last_checked_at','last_error','last_latency_ms','updated_at'],
        'agent_change_proposals'=>['before_snapshot_json','after_snapshot_json','rollback_state','rolled_back_at'],
        'agent_followups'=>['resolution_state','resolution_note','resolved_task_id','last_executed_at'],
        'agency_events'=>['remind_at','next_action_at','resolution_code','reply_confidence','dedupe_key'],
        'company_goals'=>['progress_percent','forecast_value','health_state','last_metric_sync_at','completed_at'],
        'media_requests'=>['provider_job_id','idempotency_key','next_poll_at','last_checked_at','provider_state','metadata_json'],
        'video_scenes'=>['approval_required','approved_at'],
        'social_account_runs'=>['context_json'],
        'secure_vault_snapshots'=>['envelope_b64','envelope_sha256','source_ref','state'],
        'secure_config_snapshots'=>['envelope_b64','envelope_sha256','config_sha256','source_ref','state']
    ];
    private const REQUIRED_INDEX_GROUPS=[
        'schema_migration_steps'=>[['uq_schema_migration_step']],
        'resource_registry'=>[['uq_resource_registry17','uq_resource_registry19','uq_resource_registry20']],
        'agent_workflow_templates'=>[['uq_agent_workflow_key17','uq_agent_workflow_key19','uq_agent_workflow_key20']],
        'agent_workflow_steps'=>[['uq_workflow_step17','uq_workflow_step19','uq_workflow_step20']],
        'voice_conversations'=>[['uq_voice_conversation_uid17','uq_voice_conversation_uid19','uq_voice_conversation_uid20']],
        'creator_intelligence_snapshots'=>[['uq_creator_intelligence17','uq_creator_intelligence19','uq_creator_intelligence20']]
    ];
    public static function verify():array{
        $pdo=db();$db=(string)$pdo->query('SELECT DATABASE()')->fetchColumn();if($db==='')throw new RuntimeException('database_name_missing');
        $issues=[];$details=['database'=>$db,'php'=>PHP_VERSION,'tables'=>[],'columns'=>[],'indexes'=>[],'prompts'=>[],'sources'=>[],'vault'=>[],'config'=>[],'routes'=>[],'runtime'=>[]];
        if(PHP_VERSION_ID<80100)$issues[]='php_8_1_required';foreach(['pdo_mysql','curl','mbstring','openssl','json'] as $ext)if(!extension_loaded($ext))$issues[]='php_extension_missing:'.$ext;
        $q=$pdo->prepare('SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=?');$q->execute([$db]);$tables=array_fill_keys($q->fetchAll(PDO::FETCH_COLUMN),true);
        foreach(self::REQUIRED_TABLES as $t){$ok=isset($tables[$t]);$details['tables'][$t]=$ok;if(!$ok)$issues[]='missing_table:'.$t;}
        foreach(self::REQUIRED_COLUMNS as $table=>$cols){if(!isset($tables[$table]))continue;$q=$pdo->prepare('SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME=?');$q->execute([$db,$table]);$have=array_fill_keys($q->fetchAll(PDO::FETCH_COLUMN),true);foreach($cols as $c){$ok=isset($have[$c]);$details['columns'][$table.'.'.$c]=$ok;if(!$ok)$issues[]='missing_column:'.$table.'.'.$c;}}
        foreach(self::REQUIRED_INDEX_GROUPS as $table=>$groups){if(!isset($tables[$table]))continue;$q=$pdo->prepare('SELECT DISTINCT INDEX_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=? AND TABLE_NAME=?');$q->execute([$db,$table]);$have=array_fill_keys($q->fetchAll(PDO::FETCH_COLUMN),true);foreach($groups as $alternatives){$ok=false;foreach($alternatives as $idx)if(isset($have[$idx])){$ok=true;break;}$key=$table.'.'.implode('|',$alternatives);$details['indexes'][$key]=$ok;if(!$ok)$issues[]='missing_index_group:'.$key;}}
        try{$slugs=['ramy','walid','ayman','emad','samir-social','video-director','basant','community-manager'];$in="'".implode("','",$slugs)."'";$bad=(int)$pdo->query("SELECT COUNT(*) FROM agents WHERE is_active=1 AND slug IN ($in) AND (system_prompt LIKE '%socialpanelova.com%' OR system_prompt LIKE '%[CompanyOS 4.%' OR system_prompt LIKE '%[CompanyOS 5.%' OR system_prompt LIKE '%[CompanyOS 8.%')")->fetchColumn();$versioned=(int)$pdo->query("SELECT COUNT(DISTINCT agent_id) FROM agent_prompt_versions WHERE change_summary='CompanyOS 20 canonical active prompt'")->fetchColumn();$active=(int)$pdo->query("SELECT COUNT(*) FROM agents WHERE is_active=1 AND slug IN ($in)")->fetchColumn();$details['prompts']=['canonical_clean'=>$bad===0,'versioned'=>$versioned,'active'=>$active];if($bad>0)$issues[]='canonical_prompt_cleanup_required';if($active>0&&$versioned<$active)$issues[]='canonical_prompt_version_missing';}catch(Throwable){$issues[]='canonical_prompt_check_failed';}
        try{$q=$pdo->prepare('SELECT status FROM data_source_registry WHERE source_key=?');foreach([['agent_memory_bank','canonical'],['agent_memory','legacy_read_only'],['agent_initiatives','canonical'],['resource_registry','canonical'],['agent_workflow_steps','canonical'],['provider_capability_routes','canonical'],['creator_intelligence_snapshots','canonical'],['secure_vault_snapshots','archive'],['secure_config_snapshots','archive']] as [$k,$want]){$q->execute([$k]);$got=(string)($q->fetchColumn()?:'');$details['sources'][$k]=$got;if($got!==$want)$issues[]='data_source_status_invalid:'.$k;}}catch(Throwable){$issues[]='data_source_registry_check_failed';}
        $root=defined('PB_ROOT')?PB_ROOT:'';$vaultFile=$root!==''?$root.'/private/runtime/secrets.enc':'';$configFile=$root!==''?$root.'/private/config.php':'';
        if($vaultFile!==''&&is_file($vaultFile)){try{$hash=hash_file('sha256',$vaultFile);$q=$pdo->prepare("SELECT envelope_sha256,state FROM secure_vault_snapshots WHERE envelope_sha256=? AND state='verified' ORDER BY id DESC LIMIT 1");$q->execute([$hash]);$v=$q->fetch()?:[];$details['vault']=['file_sha256'=>$hash,'snapshot'=>$v,'match'=>!empty($v)];if(empty($v))$issues[]='encrypted_vault_snapshot_hash_mismatch';}catch(Throwable){$issues[]='encrypted_vault_snapshot_check_failed';}}else{$details['vault']=['required'=>false,'reason'=>'no_runtime_vault_file'];}
        if($configFile!==''&&is_file($configFile)){try{$hash=hash_file('sha256',$configFile);$q=$pdo->prepare("SELECT config_sha256,state FROM secure_config_snapshots WHERE config_sha256=? AND state='verified' ORDER BY id DESC LIMIT 1");$q->execute([$hash]);$v=$q->fetch()?:[];$details['config']=['file_sha256'=>$hash,'snapshot'=>$v,'match'=>!empty($v)];if(empty($v))$issues[]='encrypted_config_snapshot_hash_mismatch';}catch(Throwable){$issues[]='encrypted_config_snapshot_check_failed';}}else{$details['config']=['required'=>false,'reason'=>'no_runtime_config_file'];}
        foreach(['resource_manager','workflow_runtime','voice_center','creator_intelligence'] as $cap){try{$q=$pdo->prepare('SELECT COUNT(*) FROM agent_capability_catalog WHERE capability_key=? AND enabled=1');$q->execute([$cap]);$ok=(int)$q->fetchColumn()>0;$details['runtime']['capability.'.$cap]=$ok;if(!$ok)$issues[]='missing_capability:'.$cap;}catch(Throwable){$issues[]='capability_check_failed:'.$cap;}}
        try{$need=['text','coding','vision','embeddings','web_search','image','video','stt','tts','realtime_voice','browser','external_api'];$q=$pdo->prepare('SELECT COUNT(*) FROM provider_capability_routes WHERE capability=? AND enabled=1');foreach($need as $cap){$q->execute([$cap]);$ok=(int)$q->fetchColumn()>0;$details['routes'][$cap]=$ok;if(!$ok)$issues[]='missing_provider_route:'.$cap;}}catch(Throwable){$issues[]='provider_route_check_failed';}
        try{$n=(int)$pdo->query('SELECT COUNT(*) FROM agent_policy_rules WHERE enabled=1')->fetchColumn();$details['runtime']['policy_rules']=$n;if($n<6)$issues[]='policy_rules_incomplete';}catch(Throwable){$issues[]='policy_rules_check_failed';}
        try{$templates=(int)$pdo->query("SELECT COUNT(*) FROM agent_workflow_templates WHERE enabled=1 AND COALESCE(state,'active')='active'")->fetchColumn();$steps=(int)$pdo->query('SELECT COUNT(*) FROM agent_workflow_steps WHERE enabled=1')->fetchColumn();$details['runtime']['workflow_templates']=$templates;$details['runtime']['workflow_steps']=$steps;if($templates<1||$steps<1)$issues[]='normalized_workflow_runtime_incomplete';}catch(Throwable){$issues[]='workflow_runtime_check_failed';}
        $migration=null;try{$q=$pdo->prepare('SELECT * FROM schema_migrations WHERE migration_id=? LIMIT 1');$q->execute(['companyos_20_0_final_unified']);$migration=$q->fetch()?:null;if(!$migration)$issues[]='migration_20_not_recorded';}catch(Throwable){$issues[]='migration_20_check_failed';}
        try{$details['runtime']['system.schema']=(string)setting('system.schema','');if($details['runtime']['system.schema']!=='20.0')$issues[]='system_schema_not_20';$details['runtime']['system.version']=(string)setting('system.version','');if(!preg_match('/^20(?:\.|$)/',$details['runtime']['system.version']))$issues[]='system_version_not_20_family';}catch(Throwable){$issues[]='system_version_check_failed';}
        try{$q=$pdo->prepare('SELECT COUNT(*) FROM runtime_validation_scenarios WHERE scenario_key=? AND enabled=1');$q->execute(['v20_core_acceptance']);$ok=(int)$q->fetchColumn()>0;$details['runtime']['v20_core_acceptance']=$ok;if(!$ok)$issues[]='runtime_validation_v20_missing';}catch(Throwable){$issues[]='runtime_validation_check_failed';}
        return ['ok'=>$issues===[],'issues'=>$issues,'migration'=>$migration,'details'=>$details];
    }
    public static function markVerified():array{$r=self::verify();if(!$r['ok'])throw new RuntimeException('schema_preflight_failed:'.implode(',',array_slice($r['issues'],0,14)));db()->prepare("UPDATE schema_migrations SET state='verified',verified_at=NOW(),details_json=? WHERE migration_id='companyos_20_0_final_unified'")->execute([j(['verified_by'=>'SchemaPreflightService','verified_at'=>now_utc()])]);return $r+['marked_verified'=>true];}
}
