<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();$q=trim((string)($_GET['q']??''));$like='%'.$q.'%';$opps=[];$projects=[];$customers=[];$tasks=[];$agents=[];if($q!==''){$s=db()->prepare("SELECT id,title,source,status,score FROM opportunities WHERE title LIKE ? OR client_name LIKE ? OR requirements_text LIKE ? ORDER BY score DESC,id DESC LIMIT 30");$s->execute([$like,$like,$like]);$opps=$s->fetchAll();$s=db()->prepare("SELECT id,name,primary_domain,workflow_stage,status FROM projects WHERE name LIKE ? OR primary_domain LIKE ? ORDER BY updated_at DESC LIMIT 30");$s->execute([$like,$like]);$projects=$s->fetchAll();$s=db()->prepare("SELECT id,display_name,phone,email,status FROM customers WHERE display_name LIKE ? OR phone LIKE ? OR email LIKE ? ORDER BY updated_at DESC LIMIT 30");$s->execute([$like,$like,$like]);$customers=$s->fetchAll();$s=db()->prepare("SELECT t.id,t.title,t.status,p.name project_name,a.display_name agent_name FROM tasks t LEFT JOIN projects p ON p.id=t.project_id LEFT JOIN agents a ON a.id=t.assigned_agent_id WHERE t.title LIKE ? OR t.description LIKE ? ORDER BY t.id DESC LIMIT 30");$s->execute([$like,$like]);$tasks=$s->fetchAll();$s=db()->prepare("SELECT id,slug,display_name,role_title,status FROM agents WHERE display_name LIKE ? OR role_title LIKE ? OR specialty LIKE ? ORDER BY id LIMIT 30");$s->execute([$like,$like,$like]);$agents=$s->fetchAll();}
AdminUi::header('البحث الشامل','dashboard');echo AdminUi::flash();?>
<div class="hero-strip"><div><span class="eyebrow">GLOBAL SEARCH</span><h2>ابحث في الفرص والمشاريع والعملاء والمهام والوكلاء</h2></div><form class="search-hero" method="get"><input type="search" name="q" value="<?=e($q)?>" placeholder="اكتب اسم مشروع أو عميل أو مهمة" autofocus><button class="btn">بحث</button></form></div>
<?php if($q===''):?><?=AdminUi::empty('اكتب كلمة بحث من الشريط بالأعلى.')?><?php else:?><div class="grid"><section class="card span-6"><div class="card-title"><h2>الفرص (<?=count($opps)?>)</h2></div><?php foreach($opps as $x):?><a class="search-result" href="orders.php?id=<?=$x['id']?>"><div><b><?=e($x['title'])?></b><small><?=e($x['source'])?> · <?=e(AdminUi::label($x['status']))?></small></div><span><?=$x['score']?>/100</span></a><?php endforeach?><?php if(!$opps)echo AdminUi::empty('لا نتائج.')?></section>
<section class="card span-6"><div class="card-title"><h2>المشاريع (<?=count($projects)?>)</h2></div><?php foreach($projects as $x):?><a class="search-result" href="project.php?id=<?=$x['id']?>"><div><b><?=e($x['name'])?></b><small><?=e($x['primary_domain']?:'بدون دومين')?> · <?=e(AdminUi::label($x['workflow_stage']))?></small></div><?=AdminUi::badge($x['status'])?></a><?php endforeach?><?php if(!$projects)echo AdminUi::empty('لا نتائج.')?></section>
<section class="card span-6"><div class="card-title"><h2>العملاء (<?=count($customers)?>)</h2></div><?php foreach($customers as $x):?><a class="search-result" href="customers.php?id=<?=$x['id']?>"><div><b><?=e($x['display_name']?:'عميل #'.$x['id'])?></b><small><?=e($x['phone']?:$x['email']?:'—')?></small></div><?=AdminUi::badge($x['status'])?></a><?php endforeach?><?php if(!$customers)echo AdminUi::empty('لا نتائج.')?></section>
<section class="card span-6"><div class="card-title"><h2>المهام (<?=count($tasks)?>)</h2></div><?php foreach($tasks as $x):?><a class="search-result" href="tasks.php?id=<?=$x['id']?>"><div><b>#<?=$x['id']?> <?=e($x['title'])?></b><small><?=e($x['project_name']?:'بدون مشروع')?> · <?=e($x['agent_name']?:'—')?></small></div><?=AdminUi::badge($x['status'])?></a><?php endforeach?><?php if(!$tasks)echo AdminUi::empty('لا نتائج.')?></section>
<section class="card span-12"><div class="card-title"><h2>الوكلاء (<?=count($agents)?>)</h2></div><div class="source-grid"><?php foreach($agents as $x):?><a class="source-card" href="agent-profile.php?slug=<?=e($x['slug'])?>"><div class="card-title"><b><?=e($x['display_name'])?></b><?=AdminUi::badge($x['status'])?></div><small><?=e($x['role_title'])?></small></a><?php endforeach?></div></section></div><?php endif?>
<?php AdminUi::footer();
