<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$state=SearchDiagnosticsService::snapshot();$last=(array)($state['last']??[]);$sources=(array)($state['sources']??[]);
AdminUi::header('تشخيص بحث وليد','opportunity_hunt');echo AdminUi::flash();
?>
<div class="hero-strip"><div><span class="eyebrow">LIVE SEARCH DIAGNOSTICS</span><h2>تشخيص مصدر المشاريع قبل تشغيل وليد</h2><p>الصفحة تفرّق بين وصول المصدر، استخراج روابط مشاريع فردية، ومحرك البحث. صفحة قائمة عامة لا تُحفظ كفرصة؛ لازم تتحول لرابط مشروع فردي أولًا.</p></div><div class="hero-actions"><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="search_diagnostics_run"><input type="hidden" name="return" value="/api/admin/search-diagnostics.php"><button class="btn btn-xl">اختبر الاكتشاف الآن</button></form><a class="btn secondary" href="opportunity-hunt.php">رجوع لوليد</a></div></div>
<div class="metric-grid metric-grid-4">
<?=AdminUi::stat('Search Provider',AdminUi::provider((string)$state['provider']),'auto يختار أفضل مسار متاح')?>
<?=AdminUi::stat('Search API',($state['serper']||$state['brave']||$state['tavily'])?'مربوط':'بدون مفتاح','Serper / Brave / Tavily')?>
<?=AdminUi::stat('مصادر مباشرة',$state['marketplace_seeds']?'مفعلة':'متوقفة','نفذلي · مستقل · Freelancer')?>
<?=AdminUi::stat('OpenRouter Web',$state['openrouter_paid_web']?'مفعّل':'مقفول','منفصل عن OpenRouter AI المجاني')?>
</div>
<div class="quick-status" style="margin:0 0 16px"><span class="pill">Serper: <?=e($state['serper']?'Key':'—')?></span><span class="pill">Brave: <?=e($state['brave']?'Key':'—')?></span><span class="pill">Tavily: <?=e($state['tavily']?'Key':'—')?></span><span class="pill">Bing HTML: <?=e($state['bing_html']?'On':'Off')?></span><span class="pill">Public fallback: <?=e($state['public_fallback']?'On':'Off')?></span><span class="pill">OpenRouter AI: <?=e($state['openrouter_ai']?'Ready':'—')?></span></div>
<div class="grid">
<section class="card span-7"><div class="card-title"><div><h2>المصادر المباشرة</h2><span class="muted small">هذه صفحات قوائم عامة، ووليد يستخرج منها روابط Project Detail فقط.</span></div></div><div class="table-wrap"><table><thead><tr><th>المصدر</th><th>الحالة</th><th>الرابط</th><th>آخر فحص</th><th>الخطأ</th></tr></thead><tbody><?php foreach($sources as $s):?><tr><td><b><?=e($s['name'])?></b><small><?=e($s['source_key'])?></small></td><td><?=AdminUi::badge($s['enabled']?'active':'disabled')?> <?=!empty($s['last_state'])?AdminUi::badge((string)$s['last_state']):''?></td><td class="small"><?=e($s['base_url']?:'—')?></td><td><?=e(AdminUi::date($s['last_run_at']??null))?></td><td class="small"><?=e(!empty($s['last_error'])?AdminUi::humanError((string)$s['last_error']):'—')?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card span-5"><div class="card-title"><h2>OpenRouter Web Search</h2><?=AdminUi::badge($state['openrouter_paid_web']?'active':'disabled')?></div><p class="muted">OpenRouter هو Primary للذكاء الاصطناعي، لكن البحث على الويب خدمة منفصلة. لذلك لا يتم استهلاكها تلقائيًا في 7.0.11 إلا لو فعّلتها أنت.</p><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="search_web_paid_toggle"><input type="hidden" name="return" value="/api/admin/search-diagnostics.php"><input type="hidden" name="enabled" value="<?=$state['openrouter_paid_web']?'0':'1'?>"><button class="btn <?=$state['openrouter_paid_web']?'secondary':''?>"><?=$state['openrouter_paid_web']?'إيقاف البحث المدفوع':'تفعيل كـFallback'?></button></form></section>
<?php if(!$last):?><section class="card span-12"><?=AdminUi::empty('لم يتم تشغيل اختبار اكتشاف 7.0.11 بعد. اضغط «اختبر الاكتشاف الآن».')?></section><?php else:?>
<section class="card span-12"><div class="card-title"><div><h2>آخر اختبار فعلي</h2><span class="muted small"><?=e(AdminUi::date($last['tested_at']??null))?> · <?=e((string)($last['elapsed_ms']??0))?> ms</span></div><?=AdminUi::badge(($last['state']??'failed')==='verified'?'verified':'failed')?></div>
<div class="metric-grid metric-grid-4"><?=AdminUi::stat('روابط مباشرة',(int)($last['direct_project_links']??0),'من صفحات الأسواق')?><?=AdminUi::stat('نتائج Search',(int)($last['web_search_count']??0),'بعد فلترة المصدر')?><?=AdminUi::stat('الحالة',AdminUi::humanError((string)($last['code']??'')),'الاكتشاف وليس تحليل AI')?><?=AdminUi::stat('الوقت',round(((int)($last['elapsed_ms']??0))/1000,1).' ث','اختبار تشخيصي')?></div>
<div class="source-grid top-gap"><?php foreach((array)($last['direct_sources']??[]) as $c):?><article class="source-card"><div class="card-title"><b><?=e($c['source']??'مصدر')?></b><?=AdminUi::badge((string)($c['state']??'failed'))?></div><p class="small">HTTP: <?=e((string)($c['http_status']??0))?> · روابط مشاريع: <?=e((string)($c['detail_links']??0))?> · <?=e((string)($c['elapsed_ms']??0))?> ms</p><?php if(!empty($c['error'])):?><p class="small error-text"><?=e(AdminUi::humanError((string)$c['error']))?> <code><?=e((string)$c['error'])?></code></p><?php endif?><?php if(!empty($c['samples'])):?><details><summary>نماذج روابط</summary><pre class="json-box"><?=e(j($c['samples']))?></pre></details><?php endif?></article><?php endforeach?></div>
<?php if(!empty($last['web_search_diagnostics'])):?><details class="subtle top-gap"><summary>تشخيص محركات البحث</summary><pre class="json-box"><?=e(j($last['web_search_diagnostics']))?></pre></details><?php endif?><?php if(!empty($last['web_search_samples'])):?><details class="subtle top-gap"><summary>نماذج نتائج البحث</summary><pre class="json-box"><?=e(j($last['web_search_samples']))?></pre></details><?php endif?>
</section><?php endif?>
</div>
<?php AdminUi::footer();
