<?php
declare(strict_types=1);

final class SecurityLabService {
    public static function createTarget(array $d,string $ownerId='1'):int{
        $label=trim((string)($d['label']??''));$url=rtrim(trim((string)($d['base_url']??'')),'/').'/';if($label===''||$url==='/')throw new RuntimeException('security_target_fields_required');Security::publicUrl($url);
        $env=(string)($d['environment']??'testing');if(!in_array($env,['testing','staging','production','external_authorized'],true))throw new RuntimeException('security_target_environment_invalid');$projectId=(int)($d['project_id']??0)?:null;if($projectId)ProjectService::get($projectId);
        $rawPaths=$d['paths']??['/'];if(is_string($rawPaths))$rawPaths=preg_split('/[\r\n,]+/',$rawPaths)?:['/'];$paths=array_values(array_filter(array_map(static fn($v)=>trim((string)$v),(array)$rawPaths),static fn($v)=>$v!==''));$scope=['paths'=>$paths?:['/'],'notes'=>trim((string)($d['scope_notes']??''))];
        db()->prepare("INSERT INTO security_targets(project_id,label,base_url,environment,active,scope_json,notes,created_by_type,created_by_id) VALUES (?,?,?,?,1,?,?, 'owner',?)")->execute([$projectId,pb_substr($label,0,220),$url,$env,j($scope),pb_substr(trim((string)($d['notes']??'')),0,8000)?:null,pb_substr($ownerId,0,100)]);$id=(int)db()->lastInsertId();
        $scopeText=trim((string)($d['authorization_scope']??'اختبار QA وأمان غير مدمر داخل النطاق المحدد فقط.'));self::authorize($id,$scopeText,!empty($d['allow_authenticated_tests']),!empty($d['allow_intrusive_tests']),!empty($d['allow_production_changes']),!array_key_exists('allow_data_proof',$d)||!empty($d['allow_data_proof']),trim((string)($d['valid_until']??''))?:null,$ownerId);
        Audit::log('owner',$ownerId,'security.target_create','security_target',(string)$id,'verified',$projectId,null,['environment'=>$env,'base_url'=>$url]);return $id;
    }

    public static function target(int $id):array{$q=db()->prepare('SELECT t.*,p.name project_name FROM security_targets t LEFT JOIN projects p ON p.id=t.project_id WHERE t.id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('security_target_not_found');return $r;}

    public static function authorize(int $targetId,string $scopeText,bool $authenticated=true,bool $intrusive=false,bool $productionChanges=false,bool $dataProof=true,?string $validUntil=null,string $ownerId='1'):int{
        self::target($targetId);$scopeText=trim($scopeText);if($scopeText==='')throw new RuntimeException('security_authorization_scope_required');$until=null;if($validUntil!==null&&$validUntil!==''){$ts=utc_ts($validUntil);if($ts===false||$ts<=time())throw new RuntimeException('security_authorization_expiry_invalid');$until=gmdate('Y-m-d H:i:s',$ts);}
        db()->prepare("UPDATE security_authorizations SET state='revoked' WHERE target_id=? AND state='active'")->execute([$targetId]);db()->prepare("INSERT INTO security_authorizations(target_id,authorized_by_type,authorized_by_id,scope_text,allow_authenticated_tests,allow_intrusive_tests,allow_production_changes,allow_data_proof,valid_until,state) VALUES (?,'owner',?,?,?,?,?,?,?,'active')")->execute([$targetId,pb_substr($ownerId,0,100),$scopeText,$authenticated?1:0,$intrusive?1:0,$productionChanges?1:0,$dataProof?1:0,$until]);$id=(int)db()->lastInsertId();Audit::log('owner',$ownerId,'security.authorize','security_target',(string)$targetId,'verified',self::target($targetId)['project_id']?(int)self::target($targetId)['project_id']:null,null,['authorization_id'=>$id,'intrusive'=>$intrusive,'production_changes'=>$productionChanges]);return $id;
    }

    public static function authorization(int $targetId):array{
        $q=db()->prepare("SELECT * FROM security_authorizations WHERE target_id=? AND state='active' AND valid_from<=NOW() AND (valid_until IS NULL OR valid_until>NOW()) ORDER BY id DESC LIMIT 1");$q->execute([$targetId]);$r=$q->fetch();if(!$r)throw new RuntimeException('security_authorization_required');return $r;
    }

    public static function startRun(int $targetId,string $runType='full_safe_review',string $requestedBy='owner',string $requestedId='1'):array{
        $target=self::target($targetId);if(!(int)$target['active'])throw new RuntimeException('security_target_disabled');$auth=self::authorization($targetId);$emad=AgentService::assertRunnable(AgentService::bySlug('emad'));Permissions::requireAgent((int)$emad['id'],'security.run');AgentService::requireTool((int)$emad['id'],'security_lab');
        $testCount=(int)db()->query("SELECT COUNT(*) FROM security_test_cases WHERE enabled=1")->fetchColumn();db()->prepare("INSERT INTO security_test_runs(target_id,authorization_id,agent_id,run_type,state,tests_total) VALUES (?,?,?,?,'queued',?)")->execute([$targetId,(int)$auth['id'],(int)$emad['id'],pb_substr($runType,0,80),$testCount]);$runId=(int)db()->lastInsertId();
        $desc='نفذ مراجعة QA + Security آمنة للهدف المصرح فقط: '.(string)$target['label'].' — '.(string)$target['base_url']."\nAuthorization #".(int)$auth['id'].'. التزم بالنطاق وMinimal Proof. لا تتجاوز CAPTCHA/2FA/WAF ولا تنفذ اختبارات intrusive إلا إذا كانت مصرح بها ومطبقة مسبقًا داخل Playbook.';
        $task=TaskService::create('emad','اختبار أمني وتشغيلي: '.pb_substr((string)$target['label'],0,150),$desc,$target['project_id']?(int)$target['project_id']:null,['job_kind'=>'emad_security_review','security_run_id'=>$runId,'security_target_id'=>$targetId,'authorization_id'=>(int)$auth['id']],'high',true,null,$requestedBy,$requestedId);db()->prepare('UPDATE security_test_runs SET task_id=? WHERE id=?')->execute([$task,$runId]);
        return ['run_id'=>$runId,'task_id'=>$task,'target_id'=>$targetId,'authorization_id'=>(int)$auth['id']];
    }

    public static function getRun(int $runId):array{$q=db()->prepare('SELECT r.*,t.label target_label,t.base_url,t.environment,t.project_id,a.scope_text authorization_scope,a.allow_intrusive_tests,a.allow_authenticated_tests,a.allow_data_proof FROM security_test_runs r JOIN security_targets t ON t.id=r.target_id JOIN security_authorizations a ON a.id=r.authorization_id WHERE r.id=?');$q->execute([$runId]);$r=$q->fetch();if(!$r)throw new RuntimeException('security_run_not_found');return $r;}

    public static function targets():array{
        $sql="SELECT t.*,p.name project_name,(SELECT r.id FROM security_test_runs r WHERE r.target_id=t.id ORDER BY r.id DESC LIMIT 1) last_run_id,(SELECT MAX(r.created_at) FROM security_test_runs r WHERE r.target_id=t.id) last_run_at,(SELECT r.state FROM security_test_runs r WHERE r.target_id=t.id ORDER BY r.id DESC LIMIT 1) last_run_state,(SELECT r.tests_total FROM security_test_runs r WHERE r.target_id=t.id ORDER BY r.id DESC LIMIT 1) last_tests_total,(SELECT r.tests_passed FROM security_test_runs r WHERE r.target_id=t.id ORDER BY r.id DESC LIMIT 1) last_tests_passed,(SELECT r.tests_failed FROM security_test_runs r WHERE r.target_id=t.id ORDER BY r.id DESC LIMIT 1) last_tests_failed,(SELECT r.tests_blocked FROM security_test_runs r WHERE r.target_id=t.id ORDER BY r.id DESC LIMIT 1) last_tests_blocked,(SELECT COUNT(*) FROM security_test_runs r WHERE r.target_id=t.id) runs_count,(SELECT COUNT(*) FROM security_findings f WHERE f.target_id=t.id AND f.status NOT IN ('fixed','accepted_risk','false_positive')) open_findings,(SELECT COUNT(*) FROM security_findings f WHERE f.target_id=t.id AND f.status NOT IN ('fixed','accepted_risk','false_positive') AND f.severity='critical') critical_open,(SELECT COUNT(*) FROM security_findings f WHERE f.target_id=t.id AND f.status NOT IN ('fixed','accepted_risk','false_positive') AND f.severity='high') high_open FROM security_targets t LEFT JOIN projects p ON p.id=t.project_id ORDER BY t.active DESC,critical_open DESC,high_open DESC,t.id DESC";return db()->query($sql)->fetchAll();
    }

    public static function runDetails(int $runId):array{$run=self::getRun($runId);$q=db()->prepare('SELECT e.*,c.label_ar,c.category,c.test_mode,c.severity_if_failed FROM security_test_events e LEFT JOIN security_test_cases c ON c.id=e.test_case_id WHERE e.run_id=? ORDER BY e.id');$q->execute([$runId]);$events=$q->fetchAll();$q=db()->prepare('SELECT f.*,a.display_name assigned_agent_name FROM security_findings f LEFT JOIN agents a ON a.id=f.assigned_agent_id WHERE f.run_id=? ORDER BY FIELD(f.severity,\'critical\',\'high\',\'medium\',\'low\',\'info\'),f.id');$q->execute([$runId]);return ['run'=>$run,'events'=>$events,'findings'=>$q->fetchAll()];}

    public static function finding(int $id):array{$q=db()->prepare('SELECT f.*,t.base_url,t.label target_label,p.name project_name FROM security_findings f JOIN security_targets t ON t.id=f.target_id LEFT JOIN projects p ON p.id=f.project_id WHERE f.id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('security_finding_not_found');return $r;}

    public static function assignFix(int $findingId):int{
        $f=self::finding($findingId);if(in_array((string)$f['status'],['fixed','false_positive','accepted_risk'],true))throw new RuntimeException('security_finding_closed');$a=AgentService::bySlug('ayman');$desc="Security Finding #{$findingId}\nTarget: ".(string)$f['target_label']."\nSeverity: ".(string)$f['severity']."\nالمشكلة: ".(string)$f['description_text']."\nالتأثير: ".(string)($f['impact_text']??'')."\nMinimal proof: ".(string)($f['proof_text']??'')."\nالإصلاح المقترح: ".(string)($f['remediation_text']??'')."\nنفذ الإصلاح على بيئة الاختبار المناسبة مع Backup/Evidence. لا تغير Production مباشرة.";$tid=TaskService::create('ayman','إصلاح Finding #'.$findingId.': '.pb_substr((string)$f['title_ar'],0,130),$desc,$f['project_id']?(int)$f['project_id']:null,['job_kind'=>'ayman_execute','security_finding_id'=>$findingId],'high',true,null,'owner',(string)(Auth::user()['id']??1));db()->prepare("UPDATE security_findings SET assigned_agent_id=?,fix_task_id=?,status='assigned' WHERE id=?")->execute([(int)$a['id'],$tid,$findingId]);return $tid;
    }

    public static function startRetest(int $findingId):array{
        $f=self::finding($findingId);$emad=AgentService::bySlug('emad');db()->prepare("INSERT INTO security_retests(finding_id,agent_id,state) VALUES (?,?,'queued')")->execute([$findingId,(int)$emad['id']]);$rid=(int)db()->lastInsertId();$run=self::startRun((int)$f['target_id'],'retest_finding_'.$findingId,'owner',(string)(Auth::user()['id']??1));db()->prepare('UPDATE security_retests SET run_id=?,task_id=? WHERE id=?')->execute([$run['run_id'],$run['task_id'],$rid]);db()->prepare("UPDATE security_findings SET status='retesting' WHERE id=?")->execute([$findingId]);return ['retest_id'=>$rid]+$run;
    }
}
