<?php
declare(strict_types=1);

final class SecurityReviewRunner {
    public static function run(int $taskId):array{
        $task=TaskService::start($taskId);$ctx=json_decode((string)($task['context_json']??'{}'),true)?:[];$runId=(int)($ctx['security_run_id']??0);if($runId<1)throw new RuntimeException('security_run_missing');$run=SecurityLabService::getRun($runId);$auth=SecurityLabService::authorization((int)$run['target_id']);if((int)$auth['id']!==(int)$run['authorization_id'])throw new RuntimeException('security_authorization_changed');
        $base=Security::publicUrl((string)$run['base_url']);$agentId=(int)$run['agent_id'];Permissions::requireAgent($agentId,'security.review');AgentService::requireTool($agentId,'security_lab');db()->prepare("UPDATE security_test_runs SET state='running',started_at=COALESCE(started_at,NOW()),current_test_key=NULL WHERE id=?")->execute([$runId]);
        $cases=db()->query("SELECT * FROM security_test_cases WHERE enabled=1 ORDER BY id")->fetchAll();
        $retestFinding=null;
        if(preg_match('/^retest_finding_(\d+)$/',(string)$run['run_type'],$rm)){
            $retestFinding=SecurityLabService::finding((int)$rm[1]);
            $retestKey=explode(':',(string)$retestFinding['finding_key'],2)[0];
            $cases=array_values(array_filter($cases,static fn($c)=>(string)($c['test_key']??'')===$retestKey));
            db()->prepare('UPDATE security_test_runs SET tests_total=? WHERE id=?')->execute([count($cases),$runId]);
            if(!$cases)throw new RuntimeException('security_retest_case_not_found');
        }
        $passed=0;$failed=0;$blocked=0;$findings=0;$evidence=[];$probe=null;
        try{
            foreach($cases as $case){TaskService::assertContinuable($taskId);$key=(string)$case['test_key'];db()->prepare('UPDATE security_test_runs SET current_test_key=? WHERE id=?')->execute([$key,$runId]);
                if((string)$case['test_mode']==='manual'){$thisEvent=self::event($runId,$case,'manual_required','هذا الاختبار يحتاج حسابات/خطوات بشرية مصرح بها.','لم ينفذ تلقائيًا لتجنب ادعاء نتيجة غير مثبتة.','unknown',['manual'=>true]);$blocked++;continue;}
                if((string)$case['test_mode']==='intrusive_guarded'){$reason=(int)$auth['allow_intrusive_tests']===1?'مصرح من حيث النطاق، لكن لا توجد حمولة استغلال عامة تلقائية في النظام؛ أضف Test Case محددًا واعتمده أولًا.':'Authorization لا تسمح بالاختبارات intrusive.';self::event($runId,$case,'blocked','اختبار intrusive محدد ومعتمد فقط.',$reason,'unknown',['allow_intrusive'=>(bool)$auth['allow_intrusive_tests']]);$blocked++;continue;}
                if($key==='http_availability'){$probe=HttpClient::probe($base,20,180000);$ok=!empty($probe['ok'])&&(int)$probe['status']>=200&&(int)$probe['status']<500;$actual='HTTP '.(int)$probe['status'].' على '.(string)($probe['final_url']??$base);$ev=['status'=>$probe['status'],'final_url'=>$probe['final_url']??$base,'content_type'=>$probe['content_type']??'','sha256'=>$probe['sha256']??''];$event=self::event($runId,$case,$ok?'passed':'finding','استجابة HTTP بدون 5xx.',$actual,$ok?'unknown':'very_easy',$ev);if($ok)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'تعطل أو فشل استجابة الموقع',$actual,'قد يمنع الوصول للموقع أو يشير إلى خطأ تطبيق/استضافة.','تم إثبات الحالة من استجابة HTTP فقط؛ لم يتم تنفيذ أي تعديل.','راجع سجلات التطبيق والاستضافة وأصلح سبب الاستجابة ثم أعد الاختبار.','very_easy',$ev);}}
                elseif($key==='tls_certificate'){$host=(string)parse_url($base,PHP_URL_HOST);$r=TlsInspector::inspect($host);$ok=!empty($r['ok'])&&((int)($r['days_left']??0)>7);$event=self::event($runId,$case,$ok?'passed':'finding','شهادة TLS صالحة وليست قريبة جدًا من الانتهاء.',$ok?'صالحة؛ متبقي '.(int)$r['days_left'].' يوم.':'TLS يحتاج مراجعة: '.(string)($r['error']??('days_left='.($r['days_left']??'?'))),'easy',$r);if($ok)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'مشكلة في شهادة HTTPS',(string)($r['error']??'شهادة غير صالحة أو قريبة من الانتهاء'),'قد تظهر تحذيرات للزوار أو يتوقف الاتصال الآمن.','فحص شهادة TLS على الدومين فقط.','جدد الشهادة واضبط سلسلة الثقة وفعّل التجديد التلقائي.','easy',$r);}}
                elseif($key==='security_headers'){$probe=$probe?:HttpClient::probe($base,20,180000);$h=(array)($probe['headers']??[]);$need=['content-security-policy','strict-transport-security','x-content-type-options','referrer-policy'];$missing=array_values(array_filter($need,static fn($x)=>empty($h[$x])));$ok=!$missing;$ev=['missing'=>$missing,'present'=>array_values(array_intersect($need,array_keys($h)))];$event=self::event($runId,$case,$ok?'passed':'finding','وجود رؤوس أمان المتصفح الأساسية.',$ok?'الرؤوس الأساسية موجودة.':'ناقص: '.implode(', ',$missing),'very_easy',$ev);if($ok)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'رؤوس أمان متصفح ناقصة','Missing security headers','قد يزيد أثر بعض ثغرات المتصفح أو كشف المحتوى حسب التطبيق.','تمت قراءة Response Headers فقط؛ لا توجد محاولة استغلال.','أضف الرؤوس المناسبة تدريجيًا واختبر عدم كسر الوظائف.','very_easy',$ev);}}
                elseif($key==='cookie_flags'){$probe=$probe?:HttpClient::probe($base,20,180000);$cookie=(string)(($probe['headers']['set-cookie']??''));if($cookie===''){self::event($runId,$case,'passed','أي Cookie حساس ظاهر يجب أن يحمل خصائص حماية مناسبة.','لم يظهر Set-Cookie في الصفحة الأساسية؛ لا يمكن إثبات نقص من هذا الطلب.','unknown',['set_cookie_seen'=>false]);$passed++;}else{$low=pb_strtolower($cookie);$missing=[];foreach(['secure','httponly','samesite'] as $flag)if(!str_contains($low,$flag))$missing[]=$flag;$ok=!$missing;$ev=['set_cookie_seen'=>true,'missing_flags'=>$missing,'cookie_name'=>preg_replace('/=.*/','',explode(';',$cookie)[0]??'')];$event=self::event($runId,$case,$ok?'passed':'finding','Cookie ظاهر يحمل Secure/HttpOnly/SameSite عند ملاءمتها.',$ok?'خصائص الحماية ظاهرة.':'خصائص محتملة ناقصة: '.implode(', ',$missing),'easy',$ev);if($ok)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'خصائص حماية Cookie ناقصة','Cookie security flags','قد يزيد خطر سرقة/إساءة استخدام الجلسة حسب نوع الـCookie.','تم فحص خصائص Cookie الظاهرة في الاستجابة فقط بدون محاولة سرقة جلسة.','فعّل Secure وHttpOnly واضبط SameSite بما يناسب تدفق التطبيق.','easy',$ev);}}}
                elseif($key==='cors_policy'){$probe=$probe?:HttpClient::probe($base,20,180000);$h=(array)($probe['headers']??[]);$origin=trim((string)($h['access-control-allow-origin']??''));$cred=pb_strtolower((string)($h['access-control-allow-credentials']??''));$bad=$origin==='*'&&$cred==='true';$ev=['allow_origin'=>$origin,'allow_credentials'=>$cred];$event=self::event($runId,$case,$bad?'finding':'passed','عدم الجمع بين Origin واسع وCredentials.',$bad?'Access-Control-Allow-Origin=* مع Credentials=true':'لا توجد تركيبة CORS الخطرة في الاستجابة الأساسية.',$bad?'easy':'unknown',$ev);if(!$bad)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'سياسة CORS واسعة مع Credentials','CORS misconfiguration','قد تسمح لمواقع أخرى بطلب بيانات معتمدة حسب المتصفح والتدفق.','تم إثبات الترويسات فقط؛ لم يتم إرسال طلبات هجومية من Origin خارجي.','قيد origins الموثوقة ولا تجمع wildcard مع credentials.','easy',$ev);}}
                elseif($key==='error_disclosure'){$probe=$probe?:HttpClient::probe($base,20,180000);$body=(string)($probe['body']??'');$patterns=['/Fatal error:/i','/Stack trace:/i','/SQLSTATE\[/i','/PDOException/i','/mysqli?_(?:query|connect)/i','/Warning:\s+.*\.php on line/i'];$hit='';foreach($patterns as $p)if(preg_match($p,$body,$m)){$hit=$m[0];break;}$bad=$hit!=='';$ev=['matched'=>$bad?$hit:null,'body_sha256'=>$probe['sha256']??null];$event=self::event($runId,$case,$bad?'finding':'passed','عدم كشف stack trace أو أخطاء داخلية في الصفحة العامة.',$bad?'ظهر مؤشر خطأ داخلي: '.$hit:'لم يظهر مؤشر معروف في الصفحة الأساسية.',$bad?'very_easy':'unknown',$ev);if(!$bad)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'كشف أخطاء داخلية للمستخدم','Error / stack trace disclosure','قد يكشف مسارات أو أسماء جداول أو تفاصيل تساعد على استهداف التطبيق.','Minimal proof: نوع رسالة الخطأ فقط، بدون حفظ محتوى حساس كامل.','عطل display_errors في Production وسجل الخطأ داخليًا مع مرجع آمن.','very_easy',$ev);}}
                elseif($key==='directory_listing'){$probe=$probe?:HttpClient::probe($base,20,180000);$body=pb_strtolower((string)($probe['body']??''));$bad=str_contains($body,'<title>index of /')||str_contains($body,'directory listing for /');$ev=['base_page_only'=>true,'body_sha256'=>$probe['sha256']??null];$event=self::event($runId,$case,$bad?'finding':'passed','عدم ظهور فهرس ملفات في الصفحة التي تم الوصول إليها طبيعيًا.',$bad?'ظهر مؤشر Directory Listing في الصفحة الأساسية.':'لا يظهر فهرس ملفات في الصفحة الأساسية.',$bad?'very_easy':'unknown',$ev);if(!$bad)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'عرض فهرس الملفات','Directory listing','قد يكشف أسماء ملفات أو نسخ احتياطية إذا وُجدت في نفس المسار.','تم فحص الصفحة الأساسية فقط؛ لم يتم تخمين مسارات.','عطّل autoindex/directory listing وحدد Document Root بدقة.','very_easy',$ev);}}
                elseif($key==='http_methods_policy'){$r=HttpClient::probeMethod('OPTIONS',$base,15,32000);$allow=pb_strtolower((string)($r['headers']['allow']??$r['headers']['access-control-allow-methods']??''));$bad=preg_match('/(^|[, ]+)(trace|connect)([, ]+|$)/i',$allow)===1;$ev=['status'=>$r['status'],'allow'=>$allow];$event=self::event($runId,$case,$bad?'finding':'passed','Root OPTIONS must not expose TRACE/CONNECT as application methods.',$bad?'Sensitive HTTP method advertised: '.$allow:'No TRACE/CONNECT method advertised on the tested root.',$bad?'easy':'unknown',$ev);if(!$bad)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'Sensitive HTTP method exposed','HTTP method policy','TRACE/CONNECT can increase attack surface depending on the server path.','Only OPTIONS on the authorized root was used; no state-changing method was sent.','Disable unnecessary methods at web server/application routing layers.','easy',$ev);}}
                elseif($key==='cache_sensitive_headers'){$probe=$probe?:HttpClient::probe($base,20,180000);$h=(array)($probe['headers']??[]);$cc=pb_strtolower((string)($h['cache-control']??''));$cookie=(string)($h['set-cookie']??'');$bad=$cookie!==''&&(str_contains($cc,'public')||preg_match('/max-age=([1-9][0-9]*)/',$cc));$ev=['cache_control'=>$cc,'set_cookie_seen'=>$cookie!==''];$event=self::event($runId,$case,$bad?'finding':'passed','Responses setting a session cookie should not explicitly enable shared/public caching.',$bad?'A response with Set-Cookie also advertises cacheability: '.$cc:'No explicit public cache policy was found with the observed cookie state.',$bad?'easy':'unknown',$ev);if(!$bad)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'Potentially unsafe cache policy with session cookie','Cache-Control review','Shared caching of personalized responses can expose content between users in some architectures.','Header-only evidence from the authorized root.','Use private/no-store for authenticated or personalized responses and verify CDN rules.','easy',$ev);}}
                elseif($key==='robots_exposure'){$u=rtrim($base,'/').'/robots.txt';$r=HttpClient::probe($u,12,64000);$body=(string)($r['body']??'');$sensitive=[];foreach(preg_split('/\R/',$body)?:[] as $line){if(!preg_match('/^\s*Disallow\s*:\s*(\S+)/i',$line,$m))continue;$path=pb_strtolower($m[1]);if(preg_match('#(admin|backup|config|secret|private|database|db|phpmyadmin)#',$path))$sensitive[]=$m[1];}$bad=(int)($r['status']??0)===200&&!empty($sensitive);$ev=['status'=>$r['status']??0,'sensitive_hints'=>array_slice($sensitive,0,20),'body_sha256'=>$r['sha256']??null];$event=self::event($runId,$case,$bad?'finding':'passed','robots.txt must not be treated as access control and should avoid advertising sensitive locations.',$bad?'Sensitive-looking path hints found in public robots.txt.':'No sensitive path hint was identified in the public robots file.','very_easy',$ev);if(!$bad)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'Sensitive path hints in robots.txt','robots.txt exposure','Public path hints can assist enumeration, although robots.txt itself is not a protection mechanism.','Only public robots.txt was read; no hinted path was requested.','Remove unnecessary sensitive path hints and enforce server-side authorization on every path.','very_easy',$ev);}}
                elseif($key==='well_known_security'){$parts=parse_url($base);$origin=(string)($parts['scheme']??'https').'://'.(string)($parts['host']??'');if(isset($parts['port']))$origin.=':'.(int)$parts['port'];$u=$origin.'/.well-known/security.txt';$r=HttpClient::probe($u,12,64000);$ok=(int)($r['status']??0)===200&&str_contains(pb_strtolower((string)($r['body']??'')),'contact:');$ev=['status'=>$r['status']??0,'body_sha256'=>$r['sha256']??null];$event=self::event($runId,$case,$ok?'passed':'finding','Optional security.txt provides a valid Contact field when the project uses this governance control.',$ok?'security.txt with Contact field is present.':'security.txt is missing or has no Contact field.','very_easy',$ev);if($ok)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'security.txt not published','security.txt governance','This is a governance/info finding, not proof of an application vulnerability.','Only the standard public well-known path was requested.','Publish a minimal security.txt when appropriate for the project and support process.','very_easy',$ev);}}
                elseif($key==='browser_responsive'){
                    if(!BrowserQaService::configured()){self::event($runId,$case,'blocked','اختبار UI حقيقي عبر Browser QA Bridge.','Browser QA Bridge غير مربوط بعد.','unknown',['configured'=>false]);$blocked++;}
                    else{$scope=json_decode((string)(SecurityLabService::target((int)$run['target_id'])['scope_json']??'{}'),true)?:[];$paths=array_values(array_filter((array)($scope['paths']??['/'])));$r=BrowserQaService::run($base,$paths?:['/']);$warn=(array)($r['warnings']??[]);$challenge='';foreach($warn as $w){$low=pb_strtolower(is_scalar($w)?(string)$w:j($w));if(str_contains($low,'captcha')||str_contains($low,'2fa')||str_contains($low,'waf')||str_contains($low,'cloudflare')){$challenge=is_scalar($w)?(string)$w:'browser_challenge';break;}}if($challenge!==''){self::event($runId,$case,'blocked','Browser QA بدون تجاوز حماية.','تم إيقاف الاختبار بسبب حماية/تحقق بشري: '.$challenge,'unknown',['run_id'=>$r['run_id']??null]);$blocked++;self::notifyChallenge($run,$challenge);db()->prepare("UPDATE security_test_runs SET state='blocked_owner',summary=? WHERE id=?")->execute(['توقف Browser QA بسبب حماية تحتاج تدخل المالك.',$runId]);break;}
                        $bad=0;foreach((array)$r['tests'] as $t)if(is_array($t)&&in_array((string)($t['state']??$t['status']??''),['failed','error'],true))$bad++;$ev=['browser_run_id'=>$r['run_id']??null,'tests_count'=>count((array)$r['tests']),'failed'=>$bad,'screenshots'=>array_slice((array)$r['screenshots'],0,12),'warnings'=>array_slice($warn,0,12)];$event=self::event($runId,$case,$bad?'finding':'passed','واجهة تعمل على Desktop/Tablet/Mobile بدون أخطاء Browser QA واضحة.',$bad?$bad.' اختبار Browser QA فشل.':'Browser QA اكتمل بدون فشل معلن.',$bad?'easy':'unknown',$ev);if(!$bad)$passed++;else{$failed++;$findings+=self::finding($run,$case,$event,'مشكلات واجهة/متصفح في Browser QA','Browser QA failures','قد تؤثر على الاستخدام أو التسليم حسب الاختبارات الفاشلة.','Evidence يحتوي معرف تشغيل المتصفح والملخص والصور المرجعية فقط.','افتح تفاصيل Browser QA وأصلح الاختبارات الفاشلة ثم أعد التشغيل.','easy',$ev);}}}
                else{self::event($runId,$case,'skipped','اختبار معروف ومطبق.','لا يوجد Runner تلقائي لهذا المفتاح في هذا الإصدار.','unknown',[]);$blocked++;}
                db()->prepare('UPDATE security_test_runs SET tests_passed=?,tests_failed=?,tests_blocked=?,findings_count=? WHERE id=?')->execute([$passed,$failed,$blocked,$findings,$runId]);
            }
            $current=SecurityLabService::getRun($runId);if((string)$current['state']==='blocked_owner'){$summary='توقف التشغيل بسبب حماية تحتاج تدخل المالك. تم حفظ '.($passed+$failed+$blocked).' نتيجة حتى نقطة التوقف.';$final='blocked_owner';}
            else{$summary='اكتمل '.($passed+$failed+$blocked).' اختبار/حالة: '.$passed.' Passed، '.$failed.' Findings، '.$blocked.' Blocked/Manual. Findings المسجلة: '.$findings.'.';$final=$findings>0||$blocked>0?'completed_warning':'completed';db()->prepare('UPDATE security_test_runs SET state=?,summary=?,current_test_key=NULL,tests_passed=?,tests_failed=?,tests_blocked=?,findings_count=?,finished_at=NOW() WHERE id=?')->execute([$final,$summary,$passed,$failed,$blocked,$findings,$runId]);}
            $evidence=['security_run_id'=>$runId,'target_id'=>(int)$run['target_id'],'authorization_id'=>(int)$run['authorization_id'],'summary'=>$summary,'tests_passed'=>$passed,'tests_failed'=>$failed,'tests_blocked'=>$blocked,'findings'=>$findings];TaskEvidence::add($taskId,'security_review','نتيجة مراجعة عماد الأمنية والتشغيلية',$evidence,$final==='completed'?'verified':'warning',$agentId);TaskService::complete($taskId,$evidence,$summary);self::finishRetestIfAny($runId,$findings,$final);return $evidence+['state'=>$final];
        }catch(Throwable $e){$safe=pb_substr(Security::redactSecrets($e->getMessage(),500),0,500);db()->prepare("UPDATE security_test_runs SET state='failed',summary=?,finished_at=NOW(),current_test_key=NULL WHERE id=?")->execute([$safe,$runId]);throw $e;}
    }

    private static function event(int $runId,array $case,string $state,string $expected,string $actual,string $difficulty,array $ev):int{db()->prepare('INSERT INTO security_test_events(run_id,test_case_id,test_key,state,expected_text,actual_text,difficulty,evidence_json,started_at,finished_at) VALUES (?,?,?,?,?,?,?,?,NOW(),NOW())')->execute([$runId,(int)$case['id'],(string)$case['test_key'],$state,$expected,$actual,$difficulty,$ev?j($ev):null]);return (int)db()->lastInsertId();}
    private static function finding(array $run,array $case,int $eventId,string $title,string $description,string $impact,string $proof,string $remediation,string $difficulty,array $ev):int{
        $key=(string)$case['test_key'].':'.hash('sha256',(string)$run['target_id'].'|'.$title);
        if(preg_match('/^retest_finding_(\d+)$/',(string)($run['run_type']??''),$rm)){
            try{
                $original=SecurityLabService::finding((int)$rm[1]);
                if((string)$original['finding_key']===$key){
                    db()->prepare("UPDATE security_findings SET status='reopened',test_event_id=?,description_text=?,impact_text=?,proof_text=?,remediation_text=?,evidence_json=?,last_verified_at=NOW() WHERE id=?")->execute([$eventId,$description,$impact,$proof,$remediation,$ev?j($ev):null,(int)$original['id']]);
                    if(in_array((string)$case['severity_if_failed'],['critical','high'],true))self::notifyFinding($run,(int)$original['id'],$title,(string)$case['severity_if_failed']);
                    return 1;
                }
            }catch(Throwable){}
        }
        db()->prepare("INSERT INTO security_findings(run_id,target_id,test_event_id,project_id,finding_key,title_ar,technical_name,severity,difficulty,status,description_text,impact_text,proof_text,remediation_text,evidence_json,last_verified_at) VALUES (?,?,?,?,?,?,?,?,?,'open',?,?,?,?,?,NOW())")->execute([(int)$run['id'],(int)$run['target_id'],$eventId,$run['project_id']?(int)$run['project_id']:null,pb_substr($key,0,190),pb_substr($title,0,255),(string)$case['label_ar'],(string)$case['severity_if_failed'],$difficulty,$description,$impact,$proof,$remediation,$ev?j($ev):null]);
        $id=(int)db()->lastInsertId();if(in_array((string)$case['severity_if_failed'],['critical','high'],true))self::notifyFinding($run,$id,$title,(string)$case['severity_if_failed']);return 1;
    }
    private static function notifyFinding(array $run,int $findingId,string $title,string $severity):void{$msg='عماد: اكتشفت Finding '.strtoupper($severity).' #'.$findingId.' في '.(string)$run['target_label'].': '.$title.'. راجع صفحة الاختبارات قبل التسليم.';try{Notifications::add('critical','security','Finding أمني مهم',$msg,'security_finding',(string)$findingId);}catch(Throwable){}if(setting('security.notify_owner_whatsapp','1')==='1')try{CommunicationGateway::agentToOwner('emad',$msg,'whatsapp',false,true);}catch(Throwable $e){error_log('ELMETR security owner notify: '.Security::redactSecrets($e->getMessage(),180));}}
    private static function notifyChallenge(array $run,string $challenge):void{$msg='عماد: توقفت في اختبار '.(string)$run['target_label'].' بسبب حماية/تحقق بشري ('.pb_substr($challenge,0,160).'). مطلوب تدخل المالك؛ لم أحاول تجاوزها تلقائيًا.';try{Notifications::add('warning','security','الاختبار يحتاج تدخل المالك',$msg,'security_run',(string)$run['id']);}catch(Throwable){}if(setting('security.notify_owner_whatsapp','1')==='1')try{CommunicationGateway::agentToOwner('emad',$msg,'whatsapp',false,true);}catch(Throwable $e){error_log('ELMETR security challenge notify: '.Security::redactSecrets($e->getMessage(),180));}}
    private static function finishRetestIfAny(int $runId,int $findings,string $final):void{
        $q=db()->prepare("SELECT * FROM security_retests WHERE run_id=? AND state IN ('queued','running') ORDER BY id DESC LIMIT 1");$q->execute([$runId]);$r=$q->fetch();if(!$r)return;
        $f=SecurityLabService::finding((int)$r['finding_id']);$testKey=explode(':',(string)$f['finding_key'],2)[0];
        $e=db()->prepare("SELECT state FROM security_test_events WHERE run_id=? AND test_key=? ORDER BY id DESC LIMIT 1");$e->execute([$runId,$testKey]);$eventState=(string)($e->fetchColumn()?:'');
        if($final==='blocked_owner'||in_array($eventState,['blocked','error','manual_required','skipped',''],true))$state='blocked';
        elseif($eventState==='finding')$state='failed';
        elseif($eventState==='passed')$state='passed';
        else $state=$findings>0?'failed':'blocked';
        $txt=$state==='passed'?'إعادة الاختبار المحددة لم تعثر على نفس Finding؛ تم التحقق من الإصلاح.':($state==='failed'?'المشكلة مازالت قابلة للرصد في إعادة الاختبار المحددة.':'إعادة الاختبار لم تكتمل بنتيجة حاسمة أو توقفت بسبب حماية/تدخل مطلوب.');
        db()->prepare('UPDATE security_retests SET state=?,result_text=?,completed_at=NOW() WHERE id=?')->execute([$state,$txt,(int)$r['id']]);
        if($state==='passed')db()->prepare("UPDATE security_findings SET status='fixed',fixed_at=NOW(),last_verified_at=NOW() WHERE id=?")->execute([(int)$f['id']]);
        elseif($state==='failed')db()->prepare("UPDATE security_findings SET status='reopened',fixed_at=NULL,last_verified_at=NOW() WHERE id=?")->execute([(int)$f['id']]);
    }
}
