<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$tab=(string)($_GET['tab']??'general');
if($tab==='connections'){header('Location: /api/admin/integrations.php');exit;}
AdminUi::header('الإعدادات والأمان','settings');echo AdminUi::flash();
echo AdminUi::tabs([
 'general'=>['عام','settings.php?tab=general'],
 'workflow'=>['طريقة الشغل','settings.php?tab=workflow'],
 'security'=>['الأمان','settings.php?tab=security'],
],$tab);
if($tab==='general'){
    $methods=db()->query('SELECT * FROM payment_methods ORDER BY id')->fetchAll();
?>
<div class="grid">
<section class="card span-6"><div class="card-title"><h2>بيانات الشركة والمالك</h2></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_general_settings"><input type="hidden" name="return" value="/api/admin/settings.php?tab=general">
<div class="field"><label>اسم الشركة</label><input name="business_name" value="<?=e(setting('business.name','المتر للاتصالات وتكنولوجيا المعلومات'))?>" required></div>
<div class="field"><label>اسم المالك</label><input name="owner_name" value="<?=e(setting('owner.name','أبانوب شكري'))?>" required></div>
<div class="field"><label>رقم المالك لاستقبال واتساب والمكالمات</label><input name="owner_phone" inputmode="tel" value="<?=e(setting('owner.phone',''))?>" placeholder="مثال: 201xxxxxxxxx" required></div>
<div class="field"><label>قناة التواصل الأساسية مع المالك</label><select name="default_owner_channel"><?php $cur=setting('communications.default_owner_channel','whatsapp');foreach(['whatsapp'=>'واتساب','dashboard'=>'لوحة التحكم','sms'=>'رسالة نصية','generic_message'=>'ربط رسائل خارجي'] as $v=>$l):?><option value="<?=$v?>" <?=$cur===$v?'selected':''?>><?=$l?></option><?php endforeach?></select></div>
<button class="btn">حفظ البيانات</button></form>
</section>
<section class="card span-6"><div class="card-title"><div><h2>طرق الدفع</h2><span class="muted small">عدّل بيانات كل طريقة أو وقف ظهورها في عروض السعر.</span></div><a class="link" href="payments.php">فتح الدفعات</a></div>
<?php foreach($methods as $m):?><details class="subtle payment-method" style="margin-bottom:10px"><summary style="cursor:pointer;display:flex;gap:10px;align-items:center;justify-content:space-between"><span><b><?=e($m['label'])?></b><small class="muted" style="display:block"><?=e($m['holder_name']?:'من غير اسم صاحب')?><?=($m['account_reference']??'')!==''?' · '.e($m['account_reference']):''?></small></span><?=AdminUi::badge($m['enabled']?'active':'disabled')?></summary><form method="post" action="action.php" style="margin-top:12px"><?=AdminUi::csrf()?><input type="hidden" name="action" value="payment_method_save"><input type="hidden" name="id" value="<?=$m['id']?>"><input type="hidden" name="return" value="/api/admin/settings.php?tab=general"><div class="form-row"><div class="field"><label>اسم طريقة الدفع</label><input name="label" value="<?=e($m['label'])?>" required></div><div class="field"><label>اسم صاحب الحساب</label><input name="holder_name" value="<?=e($m['holder_name']?:'')?>"></div></div><div class="field"><label>رقم الحساب أو المحفظة</label><input name="account_reference" value="<?=e($m['account_reference']?:'')?>"></div><div class="field"><label>تعليمات بسيطة للعميل</label><textarea name="instructions"><?=e($m['instructions']?:'')?></textarea></div><div class="check-grid"><label class="check-row"><input type="checkbox" name="enabled" value="1" <?=$m['enabled']?'checked':''?>> مفعّلة</label><label class="check-row"><input type="checkbox" name="show_on_quotes" value="1" <?=$m['show_on_quotes']?'checked':''?>> تظهر في عروض السعر</label></div><button class="btn secondary" style="margin-top:10px">حفظ الطريقة</button></form></details><?php endforeach?><?php if(!$methods):?><?=AdminUi::empty('مفيش طريقة دفع متسجلة لسه.')?><?php endif?>
<details class="subtle"><summary style="cursor:pointer"><b>إضافة طريقة دفع جديدة</b></summary><form method="post" action="action.php" style="margin-top:12px"><?=AdminUi::csrf()?><input type="hidden" name="action" value="payment_method_add"><input type="hidden" name="return" value="/api/admin/settings.php?tab=general"><div class="field"><label>اسم طريقة الدفع</label><input name="label" required placeholder="مثال: فودافون كاش"></div><div class="form-row"><div class="field"><label>اسم صاحب الحساب</label><input name="holder_name"></div><div class="field"><label>رقم الحساب أو المحفظة</label><input name="account_reference"></div></div><div class="field"><label>تعليمات للعميل</label><textarea name="instructions"></textarea></div><div class="check-grid"><label class="check-row"><input type="checkbox" name="enabled" value="1" checked> مفعّلة</label><label class="check-row"><input type="checkbox" name="show_on_quotes" value="1" checked> تظهر في عروض السعر</label></div><button class="btn" style="margin-top:10px">إضافة الطريقة</button></form></details></section>
<section class="card span-12"><div class="card-title"><div><h2>المفاتيح والربط</h2><span class="muted small">كل خدمة ليها كارت مستقل عشان الإعدادات تبقى واضحة.</span></div><a class="btn secondary" href="integrations.php">فتح صفحة المفاتيح والربط</a></div></section>
</div>
<?php
}elseif($tab==='workflow'){
?>
<div class="grid">
<section class="card span-7"><div class="card-title"><div><h2>تشغيل وليد وصيد الفرص</h2><span class="muted small">هذه الإعدادات تخص البحث التجاري، وليست فحص Hostinger.</span></div></div>
<form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="save_operating_settings"><input type="hidden" name="return" value="/api/admin/settings.php?tab=workflow">
<div class="form-row"><div class="field"><label>نطاق البحث — آخر كام يوم</label><input type="number" min="1" max="60" name="opportunities__lookback_days" value="<?=e(setting('opportunities.lookback_days','15'))?>"></div><div class="field"><label>النتائج الخام المستهدفة</label><input type="number" min="5" max="100" name="opportunities__default_raw_target" value="<?=e(setting('opportunities.default_raw_target','30'))?>"></div></div>
<div class="form-row"><div class="field"><label>عدد القائمة المختصرة المستهدف</label><input type="number" min="1" max="100" name="opportunities__default_shortlist_target" value="<?=e(setting('opportunities.default_shortlist_target','10'))?>"></div><div class="field"><label>تشغيل البحث التلقائي كل كام ساعة</label><input type="number" min="1" max="720" name="opportunities__hunt_interval_hours" value="<?=e(setting('opportunities.hunt_interval_hours','24'))?>"></div></div>
<label class="check-row"><input type="checkbox" name="opportunities__auto_hunt" value="1" <?=setting('opportunities.auto_hunt','0')==='1'?'checked':''?>> تشغيل بحث وليد تلقائيًا من Cron</label>
<div class="field top-gap"><label>مزود البحث العام</label><select name="opportunities__search_provider"><?php $sp=setting('opportunities.search_provider','auto');foreach(['auto'=>'Auto — أفضل مزود متاح','openai_web'=>'OpenAI Web Search — يستخدم مفتاح OpenAI الحالي','openrouter_web'=>'OpenRouter Web Search — اختياري وقد يستهلك رصيد','duckduckgo'=>'DuckDuckGo — بدون مفتاح API','bing_rss'=>'Bing RSS — بدون مفتاح API','serper'=>'Serper / Google','brave'=>'Brave Search','tavily'=>'Tavily',''=>'المصادر المضافة فقط'] as $v=>$l):?><option value="<?=e($v)?>" <?=$sp===$v?'selected':''?>><?=e($l)?></option><?php endforeach?></select><small class="muted">Auto هو الافتراضي: Serper/Brave/Tavily عند وجود مفتاح ثم OpenAI Web Search. الـfeeds العامة غير الموثوقة لا تُعتبر Search Healthy تلقائيًا. OpenRouter Web Search متاح يدويًا وقد يستهلك رصيد بحث. كل نتيجة تمر على Buyer Intent Gate.</small></div>
<hr style="border:0;border-top:1px solid var(--line);margin:20px 0">
<div class="card-title"><div><h2>فهرسة Hostinger التقنية</h2><span class="muted small">تحت إدارة رامي؛ تربط المواقع والدومينات وقواعد البيانات.</span></div></div>
<div class="field"><label>الفهرسة التلقائية كل كام ساعة</label><input type="number" min="12" max="720" name="hosting__inventory_interval_hours" value="<?=e(setting('hosting.inventory_interval_hours','48'))?>"></div>
<label class="check-row"><input type="checkbox" name="hosting__auto_inventory" value="1" <?=setting('hosting.auto_inventory','0')==='1'?'checked':''?>> تشغيل فهرسة Hostinger تلقائيًا</label>
<hr style="border:0;border-top:1px solid var(--line);margin:20px 0">
<div class="card-title"><h2>الجودة والدليل</h2></div>
<div class="field"><label>أقصى دورات أيمن ↔ عماد</label><input type="number" min="1" max="10" name="workflow__max_fix_cycles" value="<?=e(setting('workflow.max_fix_cycles','4'))?>"></div>
<label class="check-row"><input type="checkbox" name="workflow__require_task_evidence" value="1" <?=setting('workflow.require_task_evidence','1')==='1'?'checked':''?>> لا تغلق مهام وليد/أيمن/عماد بدون Evidence</label>
<label class="check-row"><input type="checkbox" name="workflow__require_master_brief_before_execution" value="1" <?=setting('workflow.require_master_brief_before_execution','1')==='1'?'checked':''?>> Master Brief إلزامي قبل تنفيذ مشروع عميل</label>
<label class="check-row"><input type="checkbox" name="learning__owner_review_required" value="1" <?=setting('learning.owner_review_required','1')==='1'?'checked':''?>> تعلم الوكلاء ينتظر مراجعة المالك قبل دخوله للذاكرة الدائمة</label>
<hr style="border:0;border-top:1px solid var(--line);margin:20px 0">
<div class="card-title"><h2>سياسة السعر والمقدم</h2></div>
<div class="form-row"><div class="field"><label>أقل نسبة من ميزانية العميل %</label><input type="number" min="1" max="100" name="business__price_budget_min_percent" value="<?=e(setting('business.price_budget_min_percent','85'))?>"></div><div class="field"><label>أعلى نسبة %</label><input type="number" min="1" max="100" name="business__price_budget_max_percent" value="<?=e(setting('business.price_budget_max_percent','95'))?>"></div></div>
<div class="form-row"><div class="field"><label>المقدم الابتدائي %</label><input type="number" min="0" max="100" name="business__deposit_start_percent" value="<?=e(setting('business.deposit_start_percent','40'))?>"></div><div class="field"><label>أقل مقدم طبيعي %</label><input type="number" min="0" max="100" name="business__deposit_min_percent" value="<?=e(setting('business.deposit_min_percent','20'))?>"></div></div>
<div class="form-row"><div class="field"><label>تكلفة يوم العمل الداخلية — <?=e(setting('business.currency','EGP'))?></label><input type="number" min="1" step="0.01" name="business__internal_day_cost" value="<?=e(setting('business.internal_day_cost','1500'))?>"><small class="muted">وليد يستخدمها لحساب التكلفة علينا عندما لا توجد تكلفة تاريخية كافية.</small></div><div class="field"><label>هامش الربح المستهدف %</label><input type="number" min="5" max="90" step="0.1" name="business__target_profit_margin_percent" value="<?=e(setting('business.target_profit_margin_percent','45'))?>"><small class="muted">يستخدمه النظام لاقتراح عرض سعر إذا العميل لم يعلن ميزانية.</small></div></div>
<div class="form-row"><div class="field"><label>أقل هامش ربح مقبول للفرصة %</label><input type="number" min="0" max="90" step="0.1" name="opportunities__minimum_verified_margin_percent" value="<?=e(setting('opportunities.minimum_verified_margin_percent','30'))?>"><small class="muted">الفرص الأقل من الهامش ده تتراجع في الترتيب أو تحتاج مراجعة.</small></div><div class="field"><label>أقل Score يظهر في أفضل الفرص</label><input type="number" min="0" max="100" name="opportunities__shortlist_min_score" value="<?=e(setting('opportunities.shortlist_min_score','70'))?>"><small class="muted">يمنع الفرص الضعيفة والمتشابهة من ملء قائمة أفضل الفرص.</small></div></div>
<div class="form-row"><div class="field"><label>تكلفة يوم التنفيذ بالدولار USD</label><input type="number" min="1" step="0.01" name="business__internal_day_cost_usd" value="<?=e(setting('business.internal_day_cost_usd','35'))?>"></div><div class="field"><label>تكلفة يوم التنفيذ بالريال SAR</label><input type="number" min="1" step="0.01" name="business__internal_day_cost_sar" value="<?=e(setting('business.internal_day_cost_sar','130'))?>"></div></div>
<div class="field"><label>تكلفة يوم التنفيذ بالدرهم AED</label><input type="number" min="1" step="0.01" name="business__internal_day_cost_aed" value="<?=e(setting('business.internal_day_cost_aed','130'))?>"><small class="muted">القيم دي تستخدم فقط لما ميزانية العميل بنفس العملة؛ تكلفة EGP لا تتحول تلقائيًا إلى دولار أو ريال.</small></div>
<button class="btn">حفظ سياسة التشغيل كاملة</button></form></section>
<section class="card span-5"><div class="card-title"><h2>قواعد التشغيل المعتمدة</h2></div>
<div class="mini-item"><div class="grow"><b>أمر المالك = تصريح</b><small>الأمر الواضح يبدأ التنفيذ بلا موافقة ثانية. العمليات المدمرة تشترط Backup/Restore Point متحققًا منه.</small></div></div>
<div class="mini-item"><div class="grow"><b>رامي يفهم السياق</b><small>آخر <?=e(setting('context.history_limit','20'))?> رسالة + المشروع + المهمة + Master Brief + الذاكرة.</small></div></div>
<div class="mini-item"><div class="grow"><b>وليد يجلب العمل</b><small>آخر 15 يومًا افتراضيًا، ويب عام + مصادر مفضلة، بدون تجاوز Login أو حماية.</small></div></div>
<div class="mini-item"><div class="grow"><b>أيمن ينفذ بعد Brief</b><small>قراءة، Backup، تعديل، اختبار أولي، Evidence، ثم تسليم لعماد.</small></div></div>
<div class="mini-item"><div class="grow"><b>عماد مستقل</b><small>Expected/Actual/Repro/Severity ودورة تصحيح حتى النجاح أو مانع حقيقي.</small></div></div>
<div class="mini-item"><div class="grow"><b>الكلام ليس تنفيذًا</b><small>لا تعتمد كلمة «تم» بدون Job/Result/Timestamp/Evidence واختبار يناسب المهمة.</small></div></div>
</section></div>
<?php
}else{
    $owner=Auth::user();
?>
<div class="grid"><section class="card span-6"><div class="card-title"><h2>قواعد الحماية</h2></div>
<div class="mini-item"><div class="grow"><b>خزنة أسرار مشفرة</b><small>المفاتيح وكلمات المرور مش بتدخل ذاكرة الوكلاء ومش بتظهر كنص في الموقع.</small></div><?=AdminUi::badge('verified')?></div>
<div class="mini-item"><div class="grow"><b>أقل صلاحيات ممكنة</b><small>أي وكيل جديد يبدأ بصلاحيات بسيطة، وبتزوده بس باللي محتاجه.</small></div><?=AdminUi::badge('verified')?></div>
<div class="mini-item"><div class="grow"><b>كل عملية حساسة مسجلة</b><small>مين نفذ، عمل إيه، فين، إمتى، وعلى أي مشروع ومهمة، والنتيجة كانت إيه.</small></div><?=AdminUi::badge('verified')?></div>
<div class="mini-item"><div class="grow"><b>مفيش نجاح وهمي</b><small>النظام بيفرق بين محاولة التنفيذ، التنفيذ الفعلي، والتحقق النهائي.</small></div><?=AdminUi::badge('verified')?></div>
</section>
<section class="card span-6"><div class="card-title"><h2>بيئة التشغيل</h2><a class="link" href="health.php">تفاصيل حالة النظام</a></div><dl class="kvs"><dt>إصدار تشغيل الموقع</dt><dd><?=e(PHP_VERSION)?></dd><dt>اتصال الموقع بالخدمات الخارجية</dt><dd><?=AdminUi::badge(extension_loaded('curl')?'verified':'failed')?></dd><dt>التشفير</dt><dd><?=AdminUi::badge(extension_loaded('openssl')?'verified':'failed')?></dd><dt>اتصال قاعدة البيانات</dt><dd><?=AdminUi::badge(extension_loaded('pdo_mysql')?'verified':'failed')?></dd><dt>دعم البيانات المنظمة</dt><dd><?=AdminUi::badge(extension_loaded('json')?'verified':'failed')?></dd><dt>دعم العربي</dt><dd><?=AdminUi::badge(extension_loaded('mbstring')?'verified':'failed')?></dd><dt>إصدار التشغيل حديث ومناسب</dt><dd><?=AdminUi::badge(version_compare(PHP_VERSION,'8.1.0','>=')?'verified':'failed')?></dd></dl></section>
<section class="card span-6"><div class="card-title"><h2>تغيير كلمة مرور المالك</h2></div><form method="post" action="action.php" autocomplete="off"><?=AdminUi::csrf()?><input type="hidden" name="action" value="owner_password_change"><input type="hidden" name="return" value="/api/admin/settings.php?tab=security"><div class="field"><label>كلمة المرور الحالية</label><input type="password" name="current_password" required autocomplete="current-password"></div><div class="field"><label>كلمة المرور الجديدة</label><input type="password" name="new_password" minlength="12" required autocomplete="new-password"></div><div class="field"><label>تأكيد كلمة المرور الجديدة</label><input type="password" name="confirm_password" minlength="12" required autocomplete="new-password"></div><button class="btn">تغيير كلمة المرور</button></form></section>
<section class="card span-6"><div class="card-title"><h2>الجلسة الحالية</h2></div><dl class="kvs"><dt>الحساب</dt><dd><?=e($owner['full_name']??'أبانوب')?></dd><dt>الصلاحية</dt><dd>المالك الرئيسي</dd><dt>حماية جلسة الدخول</dt><dd><?=AdminUi::badge('verified')?></dd><dt>حماية النماذج</dt><dd><?=AdminUi::badge('verified')?></dd><dt>منع محاولات الدخول الكتير</dt><dd><?=AdminUi::badge('verified')?></dd><dt>حماية المتصفح</dt><dd><?=AdminUi::badge('verified')?></dd></dl></section></div>
<?php } AdminUi::footer();
