<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$ready=false;$summary=[];$accounts=[];$contacts=[];$interactions=[];$content=[];$videos=[];$publications=[];$projects=[];$assets=[];
try{
    $ready=(bool)db()->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='social_content'")->fetchColumn();
    if($ready){
        $summary=SocialMediaService::summary();$accounts=SocialMediaService::accounts();$contacts=SocialMediaService::contacts(80);$interactions=SocialMediaService::interactions(80);
        $content=db()->query("SELECT c.*,a.display_name agent_name,p.name project_name FROM social_content c JOIN agents a ON a.id=c.created_by_agent_id LEFT JOIN projects p ON p.id=c.project_id ORDER BY c.id DESC LIMIT 100")->fetchAll();
        $videos=db()->query("SELECT v.*,a.display_name agent_name,p.name project_name FROM video_productions v JOIN agents a ON a.id=v.created_by_agent_id LEFT JOIN projects p ON p.id=v.project_id ORDER BY v.id DESC LIMIT 80")->fetchAll();
        $publications=SocialMediaService::publications(120);
        $assets=db()->query("SELECT id,project_id,asset_type,label,url_ref,path_ref,status FROM project_assets WHERE status='active' ORDER BY id DESC LIMIT 250")->fetchAll();
    }
    $projects=db()->query("SELECT id,name,primary_domain FROM projects ORDER BY updated_at DESC,id DESC LIMIT 100")->fetchAll();
}catch(Throwable $e){$ready=false;}
AdminUi::header('مركز السوشيال والفيديو','social_center');echo AdminUi::flash();
?>
<?php if(!$ready):?>
<section class="card"><div class="card-title"><h2>ترقية قاعدة البيانات مطلوبة</h2></div><p>استورد ملف <b>upgrade_companyos_8_1_final.sql</b> أولًا. الترقية Non-destructive ولا تحذف الجداول أو بيانات التشغيل الحالية.</p></section>
<?php else:?>
<div class="stats-grid">
<?=AdminUi::card('الحسابات','<div class="metric">'.(int)($summary['social_accounts']??0).'</div>')?>
<?=AdminUi::card('جهات الاتصال','<div class="metric">'.(int)($summary['social_contacts']??0).'</div>')?>
<?=AdminUi::card('التفاعلات','<div class="metric">'.(int)($summary['social_interactions']??0).'</div>')?>
<?=AdminUi::card('المحتوى','<div class="metric">'.(int)($summary['social_content']??0).'</div>')?>
<?=AdminUi::card('عمليات النشر','<div class="metric">'.(int)($summary['social_publications']??0).'</div>')?>
<?=AdminUi::card('الفيديوهات','<div class="metric">'.(int)($summary['video_productions']??0).'</div>')?>
</div>

<div class="two-col" style="margin-top:16px">
<section class="card"><div class="card-title"><div><h2>مزامنة الحسابات الرسمية</h2><span class="muted small">Facebook Pages وInstagram Professional عبر Meta Graph API بدون تخزين Page Tokens في قاعدة البيانات.</span></div><a class="link" href="integrations.php">إعداد المفاتيح</a></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_sync_accounts"><input type="hidden" name="return" value="/api/admin/social.php"><button class="btn">مزامنة Facebook / Instagram الآن</button></form></section>
<section class="card"><div class="card-title"><div><h2>تشغيل وكيل Social / Media</h2><span class="muted small">رامي هو المتحكم. كل اختيار نشر أدناه موافقة صريحة لهذه المهمة فقط.</span></div></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_agent_task"><input type="hidden" name="return" value="/api/admin/social.php"><div class="form-grid"><div class="field"><label>الوكيل</label><select name="slug"><option value="samir-social">سمير سوشيال</option><option value="video-director">منى — مخرجة الفيديو</option><option value="community-manager">مدير المجتمع</option></select></div><div class="field"><label>المشروع اختياري</label><select name="project_id"><option value="">بدون مشروع</option><?php foreach($projects as $p):?><option value="<?=$p['id']?>"><?=e($p['name'].' · '.$p['primary_domain'])?></option><?php endforeach?></select></div></div><div class="field"><label>المطلوب</label><textarea name="request" rows="4" required></textarea></div><div class="check-grid"><label class="check"><input type="checkbox" name="approved_actions[]" value="facebook.publish"> Facebook publish</label><label class="check"><input type="checkbox" name="approved_actions[]" value="instagram.publish"> Instagram publish</label><label class="check"><input type="checkbox" name="approved_actions[]" value="youtube.upload"> YouTube upload</label><label class="check"><input type="checkbox" name="approved_actions[]" value="tiktok.publish"> TikTok publish</label><label class="check"><input type="checkbox" name="approved_actions[]" value="telegram.send"> Telegram send</label><label class="check"><input type="checkbox" name="approved_actions[]" value="whatsapp.send"> WhatsApp send</label><label class="check"><input type="checkbox" name="approved_actions[]" value="account.create"> إنشاء بيانات حساب جديد</label><label class="check"><input type="checkbox" name="approved_actions[]" value="browser.external"> تنفيذ تسجيل/إرسال عبر المتصفح</label></div><button class="btn">إنشاء المهمة تحت إشراف رامي</button></form></section>
</div>

<section class="card" style="margin-top:16px"><div class="card-title"><div><h2>إنشاء مسودة وجدولتها</h2><span class="muted small">الإنشاء لا ينشر. يلزم اعتماد المسودة ثم اختيار حساب هدف. الجدولة ينفذها Worker.</span></div></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_content_create"><input type="hidden" name="return" value="/api/admin/social.php"><div class="form-grid"><div class="field"><label>النوع</label><select name="content_type"><?php foreach(['text'=>'نص','image'=>'صورة','video'=>'فيديو','short'=>'Short','reel'=>'Reel','story'=>'Story'] as $v=>$l):?><option value="<?=$v?>"><?=$l?></option><?php endforeach?></select></div><div class="field"><label>المشروع</label><select name="project_id"><option value="">بدون مشروع</option><?php foreach($projects as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach?></select></div><div class="field"><label>Asset اختياري</label><select name="asset_id"><option value="">بدون Asset</option><?php foreach($assets as $x):?><option value="<?=$x['id']?>">#<?=$x['id']?> · <?=e($x['asset_type'].' · '.$x['label'])?></option><?php endforeach?></select></div><div class="field"><label>موعد النشر اختياري</label><input type="datetime-local" name="scheduled_at"></div></div><div class="field"><label>العنوان</label><input name="title" maxlength="220"></div><div class="field"><label>Caption / النص</label><textarea name="caption" rows="4"></textarea></div><div class="field"><label>Prompt / تعليمات داخلية</label><textarea name="prompt" rows="3"></textarea></div><button class="btn">حفظ كمسودة</button></form></section>

<section class="card" style="margin-top:16px"><div class="card-title"><h2>المسودات والمحتوى</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>المحتوى</th><th>المشروع</th><th>الحالة</th><th>الموعد</th><th>اعتماد</th><th>نشر/جدولة</th></tr></thead><tbody><?php foreach($content as $c):?><tr><td>#<?=$c['id']?></td><td><b><?=e($c['title']?:AdminUi::label($c['content_type']))?></b><small class="muted block"><?=e(pb_substr((string)($c['caption']??''),0,180))?></small><?php if($c['asset_id']):?><small class="muted block">Asset #<?=(int)$c['asset_id']?></small><?php endif?></td><td><?=e($c['project_name']??'—')?></td><td><?=AdminUi::badge($c['status'])?></td><td><?=e(AdminUi::date($c['scheduled_at']))?></td><td><?php if(!(int)$c['owner_approved']):?><form method="post" action="action.php" class="inline-form"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_content_approve"><input type="hidden" name="content_id" value="<?=$c['id']?>"><input type="hidden" name="return" value="/api/admin/social.php"><button class="btn secondary small-btn">اعتماد</button></form><?php else:?><span class="badge s-active">معتمد</span><?php endif?></td><td><?php if((int)$c['owner_approved']&&$accounts):?><form method="post" action="action.php" class="inline-form"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_publication_queue"><input type="hidden" name="content_id" value="<?=$c['id']?>"><input type="hidden" name="return" value="/api/admin/social.php"><select name="account_id" required style="min-width:150px"><option value="">اختر الحساب</option><?php foreach($accounts as $a):?><?php if($a['status']==='active'):?><option value="<?=$a['id']?>"><?=e(AdminUi::provider($a['platform']).' · '.$a['display_name'])?></option><?php endif?><?php endforeach?></select><label class="check"><input type="checkbox" name="publish_now" value="1" <?=empty($c['scheduled_at'])?'checked':''?>> الآن</label><button class="btn secondary small-btn">إرسال للطابور</button></form><?php else:?><span class="muted small">اعتمد المسودة واربط حسابًا أولًا</span><?php endif?></td></tr><?php endforeach?><?php if(!$content):?><tr><td colspan="7" class="muted">لا توجد مسودات.</td></tr><?php endif?></tbody></table></div></section>

<section class="card" style="margin-top:16px"><div class="card-title"><div><h2>سجل النشر الحقيقي</h2><span class="muted small">published لا تُسجل إلا بعد معرف خارجي/نتيجة API موثقة. TikTok وInstagram يظلان publishing حتى اكتمال المعالجة الخارجية.</span></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>المنصة/الحساب</th><th>المحتوى</th><th>الحالة</th><th>المعرف الخارجي</th><th>الخطأ</th><th>تحكم</th></tr></thead><tbody><?php foreach($publications as $p):?><tr><td>#<?=$p['id']?></td><td><?=e(AdminUi::provider($p['platform']))?><small class="muted block"><?=e($p['account_name']??'—')?></small></td><td><?=e($p['title']?:AdminUi::label($p['content_type']))?></td><td><?=AdminUi::badge($p['state'])?></td><td><?php $extUrl=trim((string)($p['external_url']??''));if($extUrl!==''&&preg_match('#^https?://#i',$extUrl)):?><a class="link" target="_blank" rel="noopener noreferrer" href="<?=e($extUrl)?>"><?=e($p['external_post_id']?:'فتح المنشور')?></a><?php else:?><?=e($p['external_post_id']??'—')?><?php endif?></td><td><?=e($p['error_code']??'—')?></td><td><?php if($p['state']==='failed'):?><form method="post" action="action.php" class="inline-form"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_publication_retry"><input type="hidden" name="publication_id" value="<?=$p['id']?>"><input type="hidden" name="return" value="/api/admin/social.php"><button class="btn secondary small-btn">إعادة المحاولة</button></form><?php elseif($p['state']==='queued'):?><form method="post" action="action.php" class="inline-form"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_publication_publish_now"><input type="hidden" name="publication_id" value="<?=$p['id']?>"><input type="hidden" name="return" value="/api/admin/social.php"><button class="btn secondary small-btn">نشر الآن</button></form><?php else:?>—<?php endif?></td></tr><?php endforeach?><?php if(!$publications):?><tr><td colspan="7" class="muted">لا توجد عمليات نشر بعد.</td></tr><?php endif?></tbody></table></div></section>

<section class="card" style="margin-top:16px"><div class="card-title"><h2>إنتاج الفيديو السينمائي</h2><a class="link" href="integrations.php">Media Bridge / YouTube</a></div><div class="table-wrap"><table><thead><tr><th>#</th><th>العنوان</th><th>الوكيل</th><th>المشروع</th><th>الحالة</th><th>Asset</th><th>اعتماد/رفع</th></tr></thead><tbody><?php foreach($videos as $v):?><tr><td>#<?=$v['id']?></td><td><?=e($v['title'])?><small class="muted block"><?=e($v['duration_seconds'].'s · '.$v['aspect_ratio'].' · '.$v['target_platform'])?></small></td><td><?=e($v['agent_name'])?></td><td><?=e($v['project_name']??'—')?></td><td><?=AdminUi::badge($v['state'])?></td><td><?=$v['asset_id']?'#'.(int)$v['asset_id']:'—'?></td><td><?php if(!(int)$v['owner_approved']):?><form method="post" action="action.php" class="inline-form"><?=AdminUi::csrf()?><input type="hidden" name="action" value="video_production_approve"><input type="hidden" name="production_id" value="<?=$v['id']?>"><input type="hidden" name="return" value="/api/admin/social.php"><button class="btn secondary small-btn">اعتماد الفيديو</button></form><?php elseif($v['asset_id']&&$v['state']!=='published'):?><form method="post" action="action.php" class="inline-form"><?=AdminUi::csrf()?><input type="hidden" name="action" value="video_youtube_upload"><input type="hidden" name="production_id" value="<?=$v['id']?>"><input type="hidden" name="privacy" value="private"><input type="hidden" name="return" value="/api/admin/social.php"><button class="btn secondary small-btn">رفع YouTube خاص</button></form><?php else:?>معتمد<?php endif?></td></tr><?php endforeach?><?php if(!$videos):?><tr><td colspan="7" class="muted">لا توجد إنتاجات بعد.</td></tr><?php endif?></tbody></table></div></section>

<div class="two-col" style="margin-top:16px"><section class="card"><div class="card-title"><h2>الحسابات المرتبطة</h2></div><div class="table-wrap"><table><thead><tr><th>المنصة</th><th>الحساب</th><th>الوكيل</th><th>الحالة</th></tr></thead><tbody><?php foreach($accounts as $a):?><tr><td><?=e(AdminUi::provider($a['platform']))?></td><td><?=e($a['display_name'])?><small class="muted block"><?=e($a['external_ref'])?></small></td><td><?=e($a['owner_agent_name']??'—')?></td><td><?=AdminUi::badge($a['status'])?></td></tr><?php endforeach?><?php if(!$accounts):?><tr><td colspan="4" class="muted">تظهر الحسابات بعد نجاح الربط والمزامنة.</td></tr><?php endif?></tbody></table></div></section><section class="card"><div class="card-title"><h2>أحدث جهات الاتصال والأعضاء</h2></div><div class="table-wrap"><table><thead><tr><th>المنصة</th><th>الاسم</th><th>المعرف</th><th>آخر تفاعل</th></tr></thead><tbody><?php foreach(array_slice($contacts,0,30) as $c):?><tr><td><?=e($c['source_platform'])?></td><td><?=e($c['display_name']?:$c['username']?:'—')?></td><td><?=e($c['phone']?:$c['external_ref']?:'—')?></td><td><?=e(AdminUi::date($c['last_interaction_at']))?></td></tr><?php endforeach?><?php if(!$contacts):?><tr><td colspan="4" class="muted">لا توجد جهات اتصال بعد.</td></tr><?php endif?></tbody></table></div></section></div>
<section class="card" style="margin-top:16px"><div class="card-title"><h2>سجل التفاعلات الموحد</h2></div><div class="table-wrap"><table><thead><tr><th>الوقت</th><th>المنصة</th><th>الاتجاه</th><th>العضو/جهة الاتصال</th><th>المحتوى</th></tr></thead><tbody><?php foreach(array_slice($interactions,0,50) as $i):?><tr><td><?=e(AdminUi::date($i['happened_at']))?></td><td><?=e($i['platform'])?></td><td><?=e($i['direction'])?></td><td><?=e($i['contact_name']?:$i['contact_username']?:'—')?></td><td><?=e(pb_substr((string)($i['body_text']??''),0,180))?></td></tr><?php endforeach?><?php if(!$interactions):?><tr><td colspan="5" class="muted">لا توجد تفاعلات مسجلة بعد.</td></tr><?php endif?></tbody></table></div></section>
<?php endif; AdminUi::footer();
