<?php
declare(strict_types=1);

final class SocialPublisher {
    private static function ready():bool{try{$q=db()->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='social_publications'");return (int)$q->fetchColumn()>0;}catch(Throwable){return false;}}
    private static function row(int $id):array{
        $q=db()->prepare("SELECT p.*,c.created_by_agent_id,c.project_id,c.content_type,c.title,c.caption,c.asset_id,c.owner_approved content_owner_approved,c.scheduled_at,a.external_ref account_external_ref,a.display_name account_name,a.status account_status,a.owner_agent_id account_owner_agent_id,a.metadata_json account_metadata_json FROM social_publications p JOIN social_content c ON c.id=p.content_id LEFT JOIN social_accounts a ON a.id=p.account_id WHERE p.id=? LIMIT 1");$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('social_publication_not_found');return $r;
    }
    private static function asset(?int $assetId):?array{if(!$assetId)return null;$q=db()->prepare('SELECT * FROM project_assets WHERE id=?');$q->execute([$assetId]);$a=$q->fetch();if(!$a)throw new RuntimeException('project_asset_not_found');return $a;}
    private static function assetUrl(?int $assetId):string{$a=self::asset($assetId);if(!$a)return '';$url=trim((string)($a['url_ref']??''));return $url!==''?Security::publicUrl($url):'';}
    private static function enqueue(int $publicationId,int $priority=70):int{
        $p=self::row($publicationId);if(!in_array((string)$p['state'],['queued','failed'],true))return (int)($p['job_id']??0);if((int)($p['owner_approved']??0)!==1||(int)$p['content_owner_approved']!==1)throw new RuntimeException('owner_approval_required:social.publish');
        if(!empty($p['job_id'])){$q=db()->prepare("SELECT id,state FROM jobs WHERE id=?");$q->execute([(int)$p['job_id']]);$j=$q->fetch();if($j&&in_array((string)$j['state'],['queued','running','waiting'],true))return (int)$j['id'];}
        $agent=(int)($p['requested_by_agent_id']??0)?:((int)$p['created_by_agent_id']?:null);$project=(int)($p['project_id']??0)?:null;
        db()->prepare("INSERT INTO jobs(kind,agent_id,task_id,project_id,state,priority,payload_json,max_attempts) VALUES ('social_publish',?,NULL,?,'queued',?,?,3)")->execute([$agent,$project,max(1,min(100,$priority)),j(['publication_id'=>$publicationId])]);$jobId=(int)db()->lastInsertId();db()->prepare("UPDATE social_publications SET job_id=?,state='queued',error_code=NULL,updated_at=NOW() WHERE id=?")->execute([$jobId,$publicationId]);try{WorkerWakeup::schedule();}catch(Throwable){}return $jobId;
    }
    public static function queue(int $contentId,int $accountId,int $requestedByAgentId=0,bool $ownerApproved=true,bool $publishNow=false):array{
        if(!self::ready())throw new RuntimeException('social_schema_missing');$c=SocialMediaService::content($contentId);$a=SocialMediaService::account($accountId);if((int)$c['owner_approved']!==1)throw new RuntimeException('social_content_not_approved');if((string)$a['status']!=='active')throw new RuntimeException('social_account_not_active');$platform=(string)$a['platform'];if($requestedByAgentId>0){AgentService::byId($requestedByAgentId);Permissions::requireAgent($requestedByAgentId,'social.publish');}
        $q=db()->prepare("SELECT id FROM social_publications WHERE content_id=? AND account_id=? AND platform=? AND state IN ('queued','publishing','published') ORDER BY id DESC LIMIT 1");$q->execute([$contentId,$accountId,$platform]);$existing=(int)($q->fetchColumn()?:0);if($existing)return ['publication_id'=>$existing,'job_id'=>(int)(self::row($existing)['job_id']??0),'existing'=>true];
        db()->prepare("INSERT INTO social_publications(content_id,account_id,platform,state,requested_by_agent_id,owner_approved,approved_at,attempts,metadata_json,updated_at) VALUES (?,?,?,'queued',?,?,?,?,?,NOW())")->execute([$contentId,$accountId,$platform,$requestedByAgentId?:null,$ownerApproved?1:0,$ownerApproved?now_utc():null,0,j(['queued_by'=>'owner_ui'])]);$id=(int)db()->lastInsertId();$jobId=0;$due=$publishNow||empty($c['scheduled_at'])||strtotime((string)$c['scheduled_at'])<=time();if($ownerApproved&&$due)$jobId=self::enqueue($id,85);Audit::log('owner','1','social.publication_queue','social_publication',(string)$id,'verified',(int)($c['project_id']??0)?:null,null,['platform'=>$platform,'job_id'=>$jobId]);return ['publication_id'=>$id,'job_id'=>$jobId,'existing'=>false];
    }
    public static function queueDue(int $limit=30):array{
        if(!self::ready()||setting('social.auto_scheduler','1')==='0')return ['queued'=>0];$limit=max(1,min(100,$limit));$rows=db()->query("SELECT p.id FROM social_publications p JOIN social_content c ON c.id=p.content_id WHERE p.state='queued' AND p.owner_approved=1 AND c.owner_approved=1 AND (p.job_id IS NULL OR p.job_id=0) AND (c.scheduled_at IS NULL OR c.scheduled_at<=NOW()) ORDER BY COALESCE(c.scheduled_at,c.created_at),p.id LIMIT ".$limit)->fetchAll();$n=0;foreach($rows as $r){try{self::enqueue((int)$r['id']);$n++;}catch(Throwable $e){error_log('ELMETR social queue: '.Security::redactSecrets($e->getMessage(),180));}}return ['queued'=>$n];
    }
    public static function retry(int $publicationId):array{$p=self::row($publicationId);if((string)$p['state']!=='failed')throw new RuntimeException('social_publication_not_failed');db()->prepare("UPDATE social_publications SET state='queued',job_id=NULL,error_code=NULL,provider_response_json=NULL,updated_at=NOW() WHERE id=?")->execute([$publicationId]);return ['publication_id'=>$publicationId,'job_id'=>self::enqueue($publicationId,90)];}
    public static function publishNow(int $publicationId):array{$p=self::row($publicationId);if((string)$p['state']==='failed')db()->prepare("UPDATE social_publications SET state='queued',job_id=NULL,error_code=NULL,updated_at=NOW() WHERE id=?")->execute([$publicationId]);elseif((string)$p['state']!=='queued')throw new RuntimeException('social_publication_not_queueable');return ['publication_id'=>$publicationId,'job_id'=>self::enqueue($publicationId,95)];}

    private static function finalize(int $id,string $state,string $externalId='',string $url='',array $response=[],string $error=''):void{
        $published=$state==='published';db()->prepare("UPDATE social_publications SET state=?,external_post_id=?,external_url=?,provider_response_json=?,error_code=?,published_at=IF(?,NOW(),published_at),last_checked_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$state,$externalId?:null,$url?:null,$response?j($response):null,$error?:null,$published?1:0,$id]);$p=self::row($id);if($published)db()->prepare("UPDATE social_content SET status='published',updated_at=NOW() WHERE id=?")->execute([(int)$p['content_id']]);elseif($state==='failed')db()->prepare("UPDATE social_content SET status=IF(status='published','published','failed'),updated_at=NOW() WHERE id=?")->execute([(int)$p['content_id']]);else db()->prepare("UPDATE social_content SET status='publishing',updated_at=NOW() WHERE id=? AND status<>'published'")->execute([(int)$p['content_id']]);
    }
    public static function runJob(array $job):array{
        $payload=json_decode((string)($job['payload_json']??''),true);if(!is_array($payload))$payload=[];$id=(int)($payload['publication_id']??0);if(!$id)throw new RuntimeException('social_publication_id_required');$p=self::row($id);if((int)$p['owner_approved']!==1||(int)$p['content_owner_approved']!==1)throw new RuntimeException('owner_approval_required:social.publish');if((string)$p['state']==='published')return ['publication_id'=>$id,'state'=>'published','already_done'=>true];
        db()->prepare("UPDATE social_publications SET state='publishing',attempts=attempts+1,last_checked_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$id]);$p=self::row($id);$platform=(string)$p['platform'];$caption=trim((string)($p['caption']??''));$title=trim((string)($p['title']??''));$assetId=(int)($p['asset_id']??0);$externalRef=trim((string)($p['account_external_ref']??''));
        try{
            if($platform==='facebook'){
                if($assetId&&((string)($p['content_type']??''))==='image'){$imageUrl=self::assetUrl($assetId);if($imageUrl==='')throw new RuntimeException('facebook_public_image_url_required');$r=MetaSocialClient::publishFacebookImage($externalRef,$imageUrl,$caption?:$title);}else{$r=MetaSocialClient::publishFacebookText($externalRef,$caption?:$title);}$postId=(string)($r['post_id']??$r['id']??'');self::finalize($id,'published',$postId,'',$r);return ['publication_id'=>$id,'state'=>'published','external_id'=>$postId];
            }
            if($platform==='instagram'){
                if(!$assetId)throw new RuntimeException('instagram_asset_required');$asset=self::asset($assetId);$url=self::assetUrl($assetId);if($url==='')throw new RuntimeException('instagram_public_asset_url_required');$reel=in_array((string)($p['content_type']??''),['video','reel','short'],true)||(string)($asset['asset_type']??'')==='video';$r=MetaSocialClient::createInstagramContainer($externalRef,$url,$caption?:$title,$reel);$creation=(string)($r['id']??'');if($creation==='')throw new RuntimeException('instagram_container_missing_id');self::finalize($id,'publishing',$creation,'',['phase'=>'container','creation_id'=>$creation,'init'=>$r]);return ['publication_id'=>$id,'state'=>'publishing','creation_id'=>$creation];
            }
            if($platform==='tiktok'){
                if(!$assetId)throw new RuntimeException('tiktok_video_asset_required');$r=TikTokClient::initDirectPostFromAsset($assetId,$caption?:$title,(string)setting('social.tiktok_privacy','SELF_ONLY'));$publishId=(string)($r['data']['publish_id']??'');if($publishId==='')throw new RuntimeException('tiktok_publish_id_missing');self::finalize($id,'publishing',$publishId,'',['phase'=>'processing','publish_id'=>$publishId,'init'=>$r]);return ['publication_id'=>$id,'state'=>'publishing','publish_id'=>$publishId];
            }
            if($platform==='youtube'){
                if(!$assetId)throw new RuntimeException('youtube_video_asset_required');$privacy=(string)setting('social.default_youtube_privacy','private');$r=YouTubeClient::uploadAsset($assetId,$title!==''?$title:'PerseBayt Video',$caption,$privacy);$vid=(string)($r['id']??'');$url=$vid!==''?'https://www.youtube.com/watch?v='.rawurlencode($vid):'';self::finalize($id,'published',$vid,$url,$r);return ['publication_id'=>$id,'state'=>'published','video_id'=>$vid,'url'=>$url];
            }
            if($platform==='telegram'){
                $chat=$externalRef?:TelegramClient::defaultChatId();$asset=self::asset($assetId?:null);$url=$assetId?self::assetUrl($assetId):'';if($asset&&$url!==''&&(string)$asset['asset_type']==='video')$r=TelegramClient::sendVideoUrl($chat,$url,$caption?:$title);else$r=TelegramClient::sendMessage($chat,$caption?:$title);$mid=(string)($r['result']['message_id']??'');self::finalize($id,'published',$mid,'',$r);return ['publication_id'=>$id,'state'=>'published','message_id'=>$mid];
            }
            if($platform==='x'){
                $meta=json_decode((string)($p['account_metadata_json']??'{}'),true)?:[];$serviceId=(int)($meta['service_account_id']??0);if(!$serviceId){$q=db()->prepare("SELECT id FROM service_accounts WHERE platform IN ('x','twitter') AND status='active' AND (? IS NULL OR owner_agent_id=? OR owner_agent_id IS NULL) ORDER BY (owner_agent_id=? ) DESC,id DESC LIMIT 1");$owner=!empty($p['account_owner_agent_id'])?(int)$p['account_owner_agent_id']:null;$q->execute([$owner,$owner,$owner]);$serviceId=(int)($q->fetchColumn()?:0);}if(!$serviceId)throw new RuntimeException('x_service_account_required');$play=SocialPlaybookService::findApproved('x','publish');if(!$play)throw new RuntimeException('x_publish_playbook_missing');$agent=(int)($p['requested_by_agent_id']??0)?:((int)($p['created_by_agent_id']??0)?:((int)($p['account_owner_agent_id']??0)));if(!$agent)throw new RuntimeException('x_publish_agent_missing');$r=SocialPlaybookService::start($agent,$serviceId,(int)$play['id'],0,['caption'=>$caption?:$title,'title'=>$title,'asset_url'=>$assetId?self::assetUrl($assetId):'','publication_id'=>$id]);$runId=(int)$r['run_id'];self::finalize($id,'publishing','playbook_run:'.$runId,'',['phase'=>'browser_playbook','run_id'=>$runId]);return ['publication_id'=>$id,'state'=>'publishing','playbook_run_id'=>$runId];
            }
            throw new RuntimeException('social_platform_publish_not_supported:'.$platform);
        }catch(Throwable $e){$safe=pb_substr(Security::redactSecrets($e->getMessage()),0,190);self::finalize($id,'failed','','',[],$safe);throw $e;}
    }

    public static function reconcilePending(int $limit=30):array{
        if(!self::ready())return ['checked'=>0,'published'=>0,'failed'=>0];$limit=max(1,min(100,$limit));$rows=db()->query("SELECT id FROM social_publications WHERE state='publishing' AND platform IN ('tiktok','instagram','x') ORDER BY COALESCE(last_checked_at,created_at),id LIMIT ".$limit)->fetchAll();$checked=0;$published=0;$failed=0;
        foreach($rows as $r){$id=(int)$r['id'];try{$p=self::row($id);$checked++;if($p['platform']==='tiktok'){$s=TikTokClient::status((string)$p['external_post_id']);$status=strtoupper((string)($s['data']['status']??$s['data']['publish_status']??''));if(in_array($status,['PUBLISH_COMPLETE','PUBLISHED','SUCCESS'],true)){$ids=(array)($s['data']['publicaly_available_post_id']??$s['data']['publicly_available_post_id']??[]);$postId=(string)($ids[0]??$p['external_post_id']);self::finalize($id,'published',$postId,'',$s);$published++;}elseif(in_array($status,['FAILED','PUBLISH_FAILED','ERROR'],true)){$err=(string)($s['data']['fail_reason']??$s['error']['message']??'tiktok_publish_failed');self::finalize($id,'failed',(string)$p['external_post_id'],'',$s,pb_substr($err,0,190));$failed++;}else{db()->prepare('UPDATE social_publications SET provider_response_json=?,last_checked_at=NOW(),updated_at=NOW() WHERE id=?')->execute([j($s),$id]);}}
                elseif($p['platform']==='x'){$runId=(int)str_replace('playbook_run:','',(string)$p['external_post_id']);$q=db()->prepare('SELECT state,evidence_json,challenge_text FROM social_account_runs WHERE id=?');$q->execute([$runId]);$run=$q->fetch();if(!$run){self::finalize($id,'failed',(string)$p['external_post_id'],'',[],'x_playbook_run_missing');$failed++;}elseif((string)$run['state']==='completed'){$ev=json_decode((string)($run['evidence_json']??'[]'),true)?:[];$url='';foreach(array_reverse($ev) as $x){if(is_array($x)&&!empty($x['url'])){$url=(string)$x['url'];break;}}self::finalize($id,'published','x_playbook:'.$runId,$url,['run_id'=>$runId,'evidence'=>$ev]);$published++;}elseif((string)$run['state']==='failed'){self::finalize($id,'failed',(string)$p['external_post_id'],'',['run_id'=>$runId],pb_substr((string)($run['challenge_text']??'x_playbook_failed'),0,190));$failed++;}else{db()->prepare('UPDATE social_publications SET provider_response_json=?,last_checked_at=NOW(),updated_at=NOW() WHERE id=?')->execute([j(['run_id'=>$runId,'state'=>$run['state'],'challenge'=>$run['challenge_text']??null]),$id]);}}
                else{$s=MetaSocialClient::instagramContainerStatus((string)$p['account_external_ref'],(string)$p['external_post_id']);$status=strtoupper((string)($s['status_code']??''));if($status==='FINISHED'){$pub=MetaSocialClient::publishInstagramContainer((string)$p['account_external_ref'],(string)$p['external_post_id']);$media=(array)($pub['media']??[]);$mid=(string)($pub['id']??'');self::finalize($id,'published',$mid,(string)($media['permalink']??''),['container'=>$s,'publish'=>$pub]);$published++;}elseif(in_array($status,['ERROR','EXPIRED'],true)){self::finalize($id,'failed',(string)$p['external_post_id'],'',$s,'instagram_container_'.$status);$failed++;}else{db()->prepare('UPDATE social_publications SET provider_response_json=?,last_checked_at=NOW(),updated_at=NOW() WHERE id=?')->execute([j($s),$id]);}}
            }catch(Throwable $e){error_log('ELMETR social reconcile: '.Security::redactSecrets($e->getMessage(),180));}
        }
        return ['checked'=>$checked,'published'=>$published,'failed'=>$failed];
    }
}
