<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$books=SocialPlaybookService::list();$accounts=ServiceAccountService::all(300);$runs=db()->query("SELECT r.*,p.label_ar,p.platform,a.display_name agent_name,sa.display_name account_name FROM social_account_runs r JOIN social_playbooks p ON p.id=r.playbook_id JOIN agents a ON a.id=r.agent_id LEFT JOIN service_accounts sa ON sa.id=r.service_account_id ORDER BY r.id DESC LIMIT 100")->fetchAll();
AdminUi::header('Samir Social Playbooks','social_playbooks');echo AdminUi::flash();
?>
<div class="grid"><section class="card span-5"><div class="card-title"><h2>Create versioned playbook</h2></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_playbook_create"><input type="hidden" name="return" value="/api/admin/social-playbooks.php"><div class="field"><label>Platform</label><input name="platform" placeholder="facebook / instagram / x / tiktok" required></div><div class="field"><label>Operation</label><input name="operation_key" placeholder="signup / login / publish" required></div><div class="field"><label>Label</label><input name="label" required></div><div class="field"><label>Steps JSON</label><textarea name="steps_json" rows="12" required>[{"action_type":"navigate","value":"https://example.com"},{"action_type":"snapshot"}]</textarea></div><button class="btn full-width">Create draft</button></form></section><section class="card span-7"><div class="card-title"><h2>Rules</h2></div><p>Each platform flow is explicit, versioned and owner-approved. Generic browser actions are never treated as a permanent Facebook/Instagram/X/TikTok workflow.</p><p class="muted small">CAPTCHA, 2FA, security challenge and WAF stop the run and require owner intervention. Password values are obtained from the vault only for execution and are not logged.</p></section></div>
<section class="card"><div class="card-title"><h2>Playbooks</h2></div><div class="creator-grid"><?php foreach($books as $p):?><article class="card subtle" style="margin:0"><div class="card-title"><div><b><?=e($p['platform'])?> / <?=e($p['label_ar'])?></b><small class="block muted">operation <?=e($p['operation_key'])?> | v<?=e((string)$p['version_no'])?></small></div><?=AdminUi::badge($p['state'])?></div><?php if(empty($p['owner_approved'])):?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_playbook_approve"><input type="hidden" name="return" value="/api/admin/social-playbooks.php"><input type="hidden" name="playbook_id" value="<?=$p['id']?>"><button class="btn secondary">Owner approve</button></form><?php else:?><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="social_playbook_run"><input type="hidden" name="return" value="/api/admin/social-playbooks.php"><input type="hidden" name="playbook_id" value="<?=$p['id']?>"><div class="field"><label>Account</label><select name="account_id" required><?php foreach($accounts as $a):?><option value="<?=$a['id']?>"><?=e($a['platform_key'].' / '.$a['display_name'])?></option><?php endforeach?></select></div><button class="btn">Queue real browser run</button></form><?php endif?></article><?php endforeach?></div></section>
<section class="card"><div class="card-title"><h2>Execution runs</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Playbook</th><th>Account</th><th>State</th><th>Challenge</th><th>Started</th><th>Finished</th></tr></thead><tbody><?php foreach($runs as $r):?><tr><td>#<?=$r['id']?></td><td><?=e($r['platform'].' / '.$r['label_ar'])?></td><td><?=e($r['account_name']?:'-')?></td><td><?=AdminUi::badge($r['state'])?></td><td><?=e($r['challenge_text']?:'-')?></td><td><?=e(AdminUi::date($r['started_at']))?></td><td><?=e(AdminUi::date($r['completed_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<?php AdminUi::footer();
