<?php
declare(strict_types=1);

final class SocialPlaybookService {
    private const ALLOWED_ACTIONS=['navigate','login','snapshot','click','fill','submit','send_message','create_account','check_notifications','logout'];
    private const CHALLENGE_POLICIES=['stop_and_notify','stop','owner_intervention','fail'];
    private const EVIDENCE_POLICIES=['none','url_only','summary','screenshot_and_url'];

    public static function list(string $platform=''):array{$sql='SELECT p.*,(SELECT COUNT(*) FROM social_playbook_steps s WHERE s.playbook_id=p.id) step_count FROM social_playbooks p';$args=[];if($platform!==''){$sql.=' WHERE p.platform=?';$args[]=$platform;}$sql.=' ORDER BY FIELD(p.state,\'approved\',\'draft\',\'disabled\'),p.platform,p.operation_key,p.version_no DESC';$q=db()->prepare($sql);$q->execute($args);return $q->fetchAll();}
    public static function get(int $id):array{$q=db()->prepare('SELECT * FROM social_playbooks WHERE id=?');$q->execute([$id]);$p=$q->fetch();if(!$p)throw new RuntimeException('social_playbook_not_found');$s=db()->prepare('SELECT * FROM social_playbook_steps WHERE playbook_id=? ORDER BY step_no');$s->execute([$id]);$p['steps']=$s->fetchAll();return $p;}

    public static function createDraft(string $platform,string $operation,string $label,array $steps,array $config=[]):int{
        $platform=pb_strtolower(trim($platform));$operation=pb_strtolower(trim($operation));if(!preg_match('/^[a-z0-9_.-]{2,80}$/',$platform)||!preg_match('/^[a-z0-9_.-]{2,80}$/',$operation))throw new RuntimeException('social_playbook_key_invalid');if(!$steps)throw new RuntimeException('social_playbook_steps_required');$q=db()->prepare('SELECT COALESCE(MAX(version_no),0)+1 FROM social_playbooks WHERE platform=? AND operation_key=?');$q->execute([$platform,$operation]);$version=(int)$q->fetchColumn();db()->prepare("INSERT INTO social_playbooks(platform,operation_key,version_no,label_ar,state,owner_approved,config_json) VALUES (?,?,?,?,'draft',0,?)")->execute([$platform,$operation,$version,pb_substr(trim($label)?:($platform.' '.$operation),0,220),$config?j($config):null]);$id=(int)db()->lastInsertId();$n=0;
        foreach(array_slice($steps,0,60) as $step){if(!is_array($step))continue;$action=(string)($step['action_type']??'');if(!in_array($action,self::ALLOWED_ACTIONS,true))throw new RuntimeException('social_playbook_action_invalid:'.$action);$challenge=(string)($step['challenge_policy']??'stop_and_notify');if(!in_array($challenge,self::CHALLENGE_POLICIES,true))$challenge='stop_and_notify';$evidence=(string)($step['evidence_policy']??'screenshot_and_url');if(!in_array($evidence,self::EVIDENCE_POLICIES,true))$evidence='screenshot_and_url';$n++;db()->prepare('INSERT INTO social_playbook_steps(playbook_id,step_no,action_type,selector_text,value_template,expected_text,challenge_policy,evidence_policy) VALUES (?,?,?,?,?,?,?,?)')->execute([$id,$n,$action,pb_substr((string)($step['selector']??$step['selector_text']??''),0,1200),pb_substr((string)($step['value']??$step['value_template']??''),0,8000),pb_substr((string)($step['expected']??$step['expected_text']??''),0,4000),$challenge,$evidence]);}
        if($n<1)throw new RuntimeException('social_playbook_steps_required');Audit::log('owner','1','social.playbook_create','social_playbook',(string)$id,'executed',null,null,['platform'=>$platform,'operation'=>$operation,'version'=>$version,'steps'=>$n]);return $id;
    }
    public static function approve(int $id):void{self::get($id);db()->prepare("UPDATE social_playbooks SET state='approved',owner_approved=1,updated_at=NOW() WHERE id=?")->execute([$id]);Audit::log('owner','1','social.playbook_approve','social_playbook',(string)$id,'verified');}
    public static function findApproved(string $platform,string $operation):?array{$q=db()->prepare("SELECT id FROM social_playbooks WHERE platform=? AND operation_key=? AND state='approved' AND owner_approved=1 ORDER BY version_no DESC,id DESC LIMIT 1");$q->execute([pb_strtolower($platform),pb_strtolower($operation)]);$id=(int)($q->fetchColumn()?:0);return $id?self::get($id):null;}

    public static function start(int $agentId,int $accountId,int $playbookId,int $taskId=0,array $context=[]):array{
        Permissions::requireAgent($agentId,'browser.execute');$p=self::get($playbookId);if((string)$p['state']!=='approved'||!(int)$p['owner_approved'])throw new RuntimeException('social_playbook_owner_approval_required');if($accountId>0){$a=ServiceAccountService::get($accountId);if(pb_strtolower((string)$a['platform'])!==pb_strtolower((string)$p['platform']))throw new RuntimeException('social_playbook_platform_mismatch');}
        db()->prepare("INSERT INTO social_account_runs(agent_id,service_account_id,playbook_id,task_id,platform,operation_key,context_json,state) VALUES (?,?,?,?,?,?,?,'queued')")->execute([$agentId,$accountId?:null,$playbookId,$taskId?:null,(string)$p['platform'],(string)$p['operation_key'],$context?j($context):null]);$run=(int)db()->lastInsertId();db()->prepare("INSERT INTO jobs(kind,agent_id,task_id,state,priority,payload_json) VALUES ('social_playbook',?,?, 'queued',70,?)")->execute([$agentId,$taskId?:null,j(['social_account_run_id'=>$run])]);WorkerWakeup::schedule();return ['run_id'=>$run,'state'=>'queued'];
    }

    public static function runJob(array $job):array{
        $payload=json_decode((string)($job['payload_json']??'{}'),true)?:[];$runId=(int)($payload['social_account_run_id']??0);$q=db()->prepare('SELECT r.*,p.state playbook_state,p.owner_approved,p.config_json FROM social_account_runs r JOIN social_playbooks p ON p.id=r.playbook_id WHERE r.id=?');$q->execute([$runId]);$run=$q->fetch();if(!$run)throw new RuntimeException('social_account_run_not_found');if((string)$run['playbook_state']!=='approved'||!(int)$run['owner_approved'])throw new RuntimeException('social_playbook_owner_approval_required');$steps=db()->prepare('SELECT * FROM social_playbook_steps WHERE playbook_id=? ORDER BY step_no');$steps->execute([(int)$run['playbook_id']]);$rows=$steps->fetchAll();$credential=!empty($run['service_account_id'])?((string)$run['operation_key']==='create_account'?ServiceAccountService::credentialForProvisioning((int)$run['agent_id'],(int)$run['service_account_id']):ServiceAccountService::credentialForExecution((int)$run['agent_id'],(int)$run['service_account_id'])):['id'=>0,'platform'=>$run['platform'],'username'=>'','email'=>'','password'=>'','login_url'=>''];$profile=self::profileContext($run);$input=json_decode((string)($run['context_json']??'{}'),true)?:[];$ctx=['account'=>$credential,'secret'=>['password'=>(string)($credential['password']??'')],'profile'=>$profile,'input'=>$input,'run'=>['id'=>$runId,'platform'=>$run['platform'],'operation'=>$run['operation_key']]];$evidence=[];db()->prepare("UPDATE social_account_runs SET state='running',started_at=COALESCE(started_at,NOW()),challenge_text=NULL WHERE id=?")->execute([$runId]);
        try{
            foreach($rows as $step){$no=(int)$step['step_no'];db()->prepare('UPDATE social_account_runs SET current_step=? WHERE id=?')->execute([$no,$runId]);self::stepStart($runId,$step);$params=self::paramsForStep($step,$ctx);$result=BrowserAutomationService::execute((int)$run['agent_id'],(int)($run['service_account_id']??0),(string)$step['action_type'],$params,(string)$run['operation_key']==='create_account');$ok=!array_key_exists('ok',$result)||(bool)$result['ok'];$challenge=trim((string)($result['challenge']??''));$human=!empty($result['requires_human'])||$challenge!=='';
                if(!$ok&&!$human){$ev=self::evidenceForStep($step,$result);self::stepFinish($runId,$no,'failed',$step,$result,'browser_step_result_not_ok',$ev);$evidence[]=$ev+['step'=>$no,'state'=>'failed'];throw new RuntimeException('social_playbook_step_failed:'.$no);}
                if($human){$policy=(string)($step['challenge_policy']??'stop_and_notify');$ev=self::evidenceForStep($step,$result);self::stepFinish($runId,$no,$policy==='fail'?'failed':'challenge',$step,$result,'human_verification_required',$ev);$evidence[]=$ev+['step'=>$no,'state'=>'challenge'];if($policy==='fail')throw new RuntimeException('social_playbook_challenge_failed:'.$no);db()->prepare("UPDATE social_account_runs SET state='challenge',challenge_text=?,evidence_json=? WHERE id=?")->execute([pb_substr($challenge?:'human_verification',0,1000),j($evidence),$runId]);return ['run_id'=>$runId,'state'=>'challenge','step'=>$no,'challenge_policy'=>$policy,'evidence'=>$evidence];}
                $expected=trim((string)($step['expected_text']??''));if($expected!==''&&!self::matchesExpected($expected,$result)){$ev=self::evidenceForStep($step,$result);self::stepFinish($runId,$no,'failed',$step,$result,'expected_text_not_found',$ev);$evidence[]=$ev+['step'=>$no,'state'=>'failed'];throw new RuntimeException('social_playbook_expected_text_missing:'.$no);}
                $ev=self::evidenceForStep($step,$result);self::stepFinish($runId,$no,'passed',$step,$result,'',$ev);$evidence[]=$ev+['step'=>$no,'state'=>'passed'];
            }
            db()->prepare("UPDATE social_account_runs SET state='completed',evidence_json=?,completed_at=NOW() WHERE id=?")->execute([j($evidence),$runId]);if(!empty($run['service_account_id']))ServiceAccountService::setStatus((int)$run['service_account_id'],'active',['last_playbook_run'=>$runId,'operation'=>$run['operation_key'],'completed_at'=>now_utc()]);$ev=['social_account_run_id'=>$runId,'platform'=>$run['platform'],'operation'=>$run['operation_key'],'steps'=>count($evidence),'state'=>'completed'];if(!empty($run['task_id'])){try{TaskEvidence::add((int)$run['task_id'],'browser_automation','Versioned social playbook completed',$ev,'verified',(int)$run['agent_id']);$t=TaskService::get((int)$run['task_id']);if(!in_array($t['status'],['completed','cancelled','failed'],true))TaskService::complete((int)$run['task_id'],$ev,'Social/browser playbook completed.');}catch(Throwable $e){error_log('ELMETR social playbook task completion: '.Security::redactSecrets($e->getMessage(),180));}}return $ev+['evidence'=>$evidence];
        }catch(Throwable $e){db()->prepare("UPDATE social_account_runs SET state='failed',challenge_text=?,evidence_json=?,completed_at=NOW() WHERE id=?")->execute([pb_substr(Security::redactSecrets($e->getMessage()),0,1000),j($evidence),$runId]);throw $e;}
        finally{if(isset($credential['password']))$credential['password']='***';if(isset($ctx['secret']['password']))$ctx['secret']['password']='***';}
    }

    private static function profileContext(array $run):array{$cfg=json_decode((string)($run['config_json']??'{}'),true)?:[];return ['display_name'=>(string)($cfg['display_name']??''),'bio'=>(string)($cfg['bio']??''),'website'=>(string)($cfg['website']??'')];}
    private static function interpolate(string $value,array $ctx):string{return (string)preg_replace_callback('/\{\{\s*([a-zA-Z0-9_.-]+)\s*\}\}/',static function($m)use($ctx){$parts=explode('.',$m[1]);$v=$ctx;foreach($parts as $p){if(!is_array($v)||!array_key_exists($p,$v))return ''; $v=$v[$p];}return is_scalar($v)?(string)$v:'';},$value);}
    private static function interpolateAny(mixed $v,array $ctx):mixed{if(is_string($v))return self::interpolate($v,$ctx);if(is_array($v)){foreach($v as $k=>$x)$v[$k]=self::interpolateAny($x,$ctx);return $v;}return $v;}
    private static function paramsForStep(array $step,array $ctx):array{
        $action=(string)$step['action_type'];$selector=self::interpolate((string)($step['selector_text']??''),$ctx);$raw=trim((string)($step['value_template']??''));$params=[];
        if($raw!==''&&in_array($raw[0]??'',['{','['],true)){$decoded=json_decode($raw,true);if(is_array($decoded))$decoded=self::interpolateAny($decoded,$ctx);else $decoded=null;}else $decoded=null;
        if($action==='navigate')$params=['url'=>self::interpolate($raw,$ctx)];elseif($action==='login')$params=$decoded??[];elseif($action==='snapshot'||$action==='logout'||$action==='check_notifications'){$params=$decoded??[];if($selector!=='')$params['selector']=$selector;}elseif($action==='create_account'){$params=$decoded??[];if($selector!==''&&!isset($params['submit_selector']))$params['submit_selector']=$selector;}elseif($action==='send_message'){$params=$decoded??[];if($selector!=='')$params['message_selector']=$selector;}else{$params=['selector'=>$selector];if($raw!=='')$params['value']=$decoded??self::interpolate($raw,$ctx);}return $params;
    }
    private static function matchesExpected(string $expected,array $result):bool{$hay=[];foreach(['title','text','body','body_text','status_text','message','url'] as $k)if(isset($result[$k])&&is_scalar($result[$k]))$hay[]=(string)$result[$k];if(isset($result['snapshot'])&&is_array($result['snapshot']))$hay[]=j($result['snapshot']);$blob=pb_strtolower(implode("\n",$hay));foreach(array_filter(array_map('trim',preg_split('/\|\|/',$expected)?:[])) as $needle){if(str_contains($blob,pb_strtolower($needle)))return true;}return false;}
    private static function evidenceForStep(array $step,array $result):array{$policy=(string)($step['evidence_policy']??'screenshot_and_url');$base=['ok'=>!array_key_exists('ok',$result)||(bool)$result['ok'],'challenge'=>$result['challenge']??null];if($policy==='none')return ['policy'=>'none'];if(in_array($policy,['url_only','summary','screenshot_and_url'],true)){$base['url']=$result['url']??null;$base['title']=$policy!=='url_only'?($result['title']??null):null;}if($policy==='screenshot_and_url')$base['screenshot']=$result['screenshot']??$result['screenshot_url']??$result['screenshot_path']??null;if($policy==='summary')$base['summary']=$result['message']??$result['status_text']??null;$safe=json_decode(Security::redactSecrets(j($base),6000),true);return is_array($safe)?$safe:['redacted'=>true];}
    private static function actualText(array $result):string{$parts=[];foreach(['title','text','body_text','message','status_text','url'] as $k)if(isset($result[$k])&&is_scalar($result[$k]))$parts[]=(string)$result[$k];return pb_substr(Security::redactSecrets(implode("\n",$parts)),0,8000);}
    private static function stepStart(int $runId,array $step):void{db()->prepare("INSERT INTO social_playbook_step_runs(run_id,step_no,action_type,state,expected_text,started_at) VALUES (?,?,?,'running',?,NOW()) ON DUPLICATE KEY UPDATE action_type=VALUES(action_type),state='running',expected_text=VALUES(expected_text),actual_text=NULL,evidence_json=NULL,error_code=NULL,started_at=NOW(),completed_at=NULL")->execute([$runId,(int)$step['step_no'],(string)$step['action_type'],pb_substr((string)($step['expected_text']??''),0,4000)?:null]);}
    private static function stepFinish(int $runId,int $stepNo,string $state,array $step,array $result,string $error,array $evidence):void{db()->prepare('UPDATE social_playbook_step_runs SET state=?,actual_text=?,evidence_json=?,error_code=?,completed_at=NOW() WHERE run_id=? AND step_no=?')->execute([$state,self::actualText($result),$evidence?j($evidence):null,$error!==''?pb_substr($error,0,220):null,$runId,$stepNo]);}
}
