<?php
declare(strict_types=1);
final class TaskService {
    public static function create(string $agentSlug,string $title,string $description,?int $projectId=null,array $context=[],string $priority='normal',bool $ownerAuthorized=true,?int $parent=null,string $requestedBy='owner',string $requestedId='1',bool $autoQueue=true):int{
        $a=AgentService::assertRunnable(AgentService::bySlug($agentSlug));$uid=uid('TK');$q=db()->prepare("INSERT INTO tasks(uid,parent_task_id,project_id,requested_by_type,requested_by_id,created_by_agent_id,assigned_agent_id,title,description,context_json,priority,status,review_status,owner_authorized,destructive) VALUES (?,?,?,?,?,?,?,?,?,?,?,'queued',?,?,?)");
        $review=!empty($context['recovery_execution'])?'not_required':($agentSlug==='emad'?'pending':($agentSlug==='ayman'?'pending':'not_required'));$destructive=(int)($context['destructive']??0);
        $q->execute([$uid,$parent,$projectId,$requestedBy,$requestedId,$requestedBy==='agent'?(int)$requestedId:null,(int)$a['id'],$title,$description,$context?j($context):null,in_array($priority,['low','normal','high','critical'],true)?$priority:'normal',$review,$ownerAuthorized?1:0,$destructive]);$id=(int)db()->lastInsertId();if($projectId){$scope=match($agentSlug){'ramy'=>'manage','ayman'=>'work','emad'=>!empty($context['recovery_execution'])?'work':'read','walid'=>'read',default=>'read'};db()->prepare("INSERT INTO agent_project_access(agent_id,project_id,access_scope) VALUES (?,?,?) ON DUPLICATE KEY UPDATE access_scope=IF(FIELD(VALUES(access_scope),'read','work','manage')>FIELD(access_scope,'read','work','manage'),VALUES(access_scope),access_scope)")->execute([(int)$a['id'],$projectId,$scope]);}
        self::event($id,$requestedBy,$requestedId,'created',null,'queued',['assigned_agent'=>$agentSlug]);if($autoQueue)self::queueIfReady($id);Notifications::add('info','tasks','مهمة جديدة: '.$title,'تم تكليف '.$a['display_name'].' بالمهمة.','task',(string)$id);try{TeamChatService::taskAssigned(self::get($id),$requestedBy,$requestedId);}catch(Throwable){}return $id;
    }
    public static function event(int $taskId,string $actorType,string $actorId,string $event,?string $from,?string $to,array $details=[],array $evidence=[]):void{$q=db()->prepare('INSERT INTO task_events(task_id,actor_type,actor_id,event_type,from_status,to_status,details_json,evidence_json) VALUES (?,?,?,?,?,?,?,?)');$q->execute([$taskId,$actorType,$actorId,$event,$from,$to,$details?j($details):null,$evidence?j($evidence):null]);}
    public static function addDependency(int $taskId,int $depends):void{db()->prepare('INSERT IGNORE INTO task_dependencies(task_id,depends_on_task_id) VALUES (?,?)')->execute([$taskId,$depends]);}
    public static function cancelTree(int $taskId,string $actorType='owner',string $actorId='1'):int{
        $root=self::get($taskId);$ids=[$taskId];for($i=0;$i<count($ids);$i++){$q=db()->prepare('SELECT id FROM tasks WHERE parent_task_id=?');$q->execute([$ids[$i]]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $child){$cid=(int)$child;if(!in_array($cid,$ids,true))$ids[]=$cid;}}
        $count=0;foreach(array_reverse($ids) as $id){$t=self::get($id);db()->prepare("UPDATE jobs SET state='cancelled',locked_at=NULL,lease_token=NULL,lease_expires_at=NULL,finished_at=NOW(),error_code='task_cancelled' WHERE task_id=? AND state IN ('queued','running','waiting')")->execute([$id]);if(!in_array($t['status'],['completed','cancelled','failed'],true)){db()->prepare("UPDATE tasks SET status='cancelled',completed_at=NOW() WHERE id=?")->execute([$id]);self::event($id,$actorType,$actorId,'cancelled',$t['status'],'cancelled',['root_task'=>$taskId]);try{AgentFollowupService::resolveFromTask($id,'cancelled','تم إلغاء المهمة التابعة للمتابعة.');}catch(Throwable){}$count++;}if(!empty($t['assigned_agent_id']))self::runtimeIdle((int)$t['assigned_agent_id']);}
        return $count;
    }
    private static function runtimeIdle(int $agentId):void{try{AgentService::runtimeStatus($agentId,'idle');}catch(Throwable){}}
    public static function get(int $id):array{$q=db()->prepare('SELECT t.*,a.slug agent_slug,a.display_name agent_name,p.name project_name,p.primary_domain FROM tasks t LEFT JOIN agents a ON a.id=t.assigned_agent_id LEFT JOIN projects p ON p.id=t.project_id WHERE t.id=?');$q->execute([$id]);$t=$q->fetch();if(!$t)throw new RuntimeException('task_not_found');return $t;}
    public static function assertContinuable(int $id):array{Worker::heartbeatTask($id);$t=self::get($id);if($t['status']==='cancelled')throw new RuntimeException('task_cancelled');if(in_array($t['status'],['completed','failed'],true))throw new RuntimeException('task_not_active');if(!empty($t['assigned_agent_id'])&&!AgentService::runnable((int)$t['assigned_agent_id']))throw new RuntimeException('agent_disabled');return $t;}
    public static function list(array $filters=[]):array{$where=[];$args=[];if(!empty($filters['status'])){$where[]='t.status=?';$args[]=$filters['status'];}if(!empty($filters['project_id'])){$where[]='t.project_id=?';$args[]=(int)$filters['project_id'];}$sql="SELECT t.*,a.display_name agent_name,a.slug agent_slug,p.name project_name FROM tasks t LEFT JOIN agents a ON a.id=t.assigned_agent_id LEFT JOIN projects p ON p.id=t.project_id".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY t.id DESC LIMIT 200';$q=db()->prepare($sql);$q->execute($args);return $q->fetchAll();}
    private static function jobKind(array $t):string{
        $ctx=json_decode((string)($t['context_json']??'{}'),true)?:[];
        $explicit=(string)($ctx['job_kind']??'');
        $allowed=['walid_opportunity_search','walid_company_prospecting','hosting_inventory','ayman_execute','emad_recovery_execute','emad_review','emad_security_review','ramy_followup','agent_task','video_scene_generate','video_audio_generate','video_render','social_playbook'];
        if(in_array($explicit,$allowed,true))return $explicit;
        return match((string)$t['agent_slug']){'walid'=>'walid_opportunity_search','ayman'=>'ayman_execute','emad'=>'emad_review','ramy'=>'ramy_followup',default=>'agent_task'};
    }
    public static function queueIfReady(int $taskId):bool{
        $t=self::get($taskId);if(in_array($t['status'],['completed','cancelled','failed','working'],true))return false;
        $agent=AgentService::byId((int)$t['assigned_agent_id']);
        if(!AgentService::runnable($agent)){db()->prepare("UPDATE tasks SET status='waiting' WHERE id=? AND status NOT IN ('completed','cancelled','failed','working')")->execute([$taskId]);return false;}
        $q=db()->prepare("SELECT COUNT(*) FROM task_dependencies d JOIN tasks x ON x.id=d.depends_on_task_id WHERE d.task_id=? AND x.status<>'completed'");$q->execute([$taskId]);
        if((int)$q->fetchColumn()>0){db()->prepare("UPDATE tasks SET status='waiting' WHERE id=?")->execute([$taskId]);return false;}
        $exists=db()->prepare("SELECT COUNT(*) FROM jobs WHERE task_id=? AND state IN ('queued','running','waiting')");$exists->execute([$taskId]);
        if((int)$exists->fetchColumn()>0){WorkerWakeup::schedule();return true;}
        $kind=self::jobKind($t);
        db()->prepare("INSERT INTO jobs(kind,agent_id,task_id,project_id,state,priority,payload_json) VALUES (?,?,?,?,'queued',?,?)")->execute([$kind,$t['assigned_agent_id'],$taskId,$t['project_id'],self::priorityNumber($t['priority']),j(['task_id'=>$taskId])]);
        db()->prepare("UPDATE tasks SET status='assigned' WHERE id=? AND status IN ('new','queued','waiting')")->execute([$taskId]);
        Scheduler::ensureWorkerCronIfStale();
        WorkerWakeup::schedule();
        return true;
    }

    public static function reconcileOrphanedJobs(int $limit=40):int{
        $limit=max(1,min(100,$limit));$q=db()->query("SELECT t.id,t.status,t.assigned_agent_id FROM tasks t JOIN agents a ON a.id=t.assigned_agent_id WHERE t.status IN ('queued','assigned','working','waiting') AND a.is_active=1 AND a.status<>'disabled' AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.task_id=t.id AND j.state IN ('queued','running','waiting')) ORDER BY t.updated_at ASC,t.id ASC LIMIT ".$limit);$fixed=0;
        foreach($q->fetchAll() as $row){$id=(int)$row['id'];$dep=db()->prepare("SELECT COUNT(*) FROM task_dependencies d JOIN tasks x ON x.id=d.depends_on_task_id WHERE d.task_id=? AND x.status<>'completed'");$dep->execute([$id]);if((int)$dep->fetchColumn()>0)continue;$before=(string)$row['status'];if($before==='working'){db()->prepare("UPDATE tasks SET status='waiting' WHERE id=? AND status='working'")->execute([$id]);self::event($id,'system','runtime_reconciler','orphaned_job_recovered','working','waiting',['reason'=>'active_task_without_active_job']);}try{if(self::queueIfReady($id))$fixed++;}catch(Throwable $e){error_log('ELMETR orphan task reconcile: '.Security::redactSecrets($e->getMessage(),180));}}
        return $fixed;
    }

    private static function priorityNumber(string $p):int{return ['low'=>30,'normal'=>50,'high'=>75,'critical'=>100][$p]??50;}
    public static function start(int $id):array{$t=self::assertContinuable($id);AgentService::assertRunnable((int)$t['assigned_agent_id']);$from=$t['status'];db()->prepare("UPDATE tasks SET status='working',started_at=COALESCE(started_at,NOW()),current_attempt=current_attempt+1 WHERE id=?")->execute([$id]);self::event($id,'agent',(string)$t['assigned_agent_id'],'started',$from,'working');AgentService::runtimeStatus((int)$t['assigned_agent_id'],'working',$id);return self::get($id);}
    public static function complete(int $id,array $evidence=[],string $summary=''):void{$t=self::assertContinuable($id);TaskEvidence::assertCompletionEvidence($id,$evidence);$to=$t['agent_slug']==='ayman'?'needs_review':'completed';$review=$t['agent_slug']==='ayman'?'pending':$t['review_status'];db()->prepare('UPDATE tasks SET status=?,review_status=?,completed_at=IF(?=\'completed\',NOW(),completed_at) WHERE id=?')->execute([$to,$review,$to,$id]);self::event($id,'agent',(string)$t['assigned_agent_id'],'completed',$t['status'],$to,$summary?['summary'=>$summary]:[],$evidence);try{AgentFollowupService::resolveFromTask($id,$to,$summary,$evidence);}catch(Throwable $followupError){error_log('ELMETR followup resolution: '.Security::redactSecrets($followupError->getMessage(),160));}try{ProspectPrototypeService::afterTask($id,$to,$evidence,$summary);}catch(Throwable $prototypeError){error_log('ELMETR prototype workflow: '.Security::redactSecrets($prototypeError->getMessage(),160));}try{TeamChatService::taskResult($t,$to,$summary);}catch(Throwable){}try{$ctx=json_decode((string)($t['context_json']??'{}'),true)?:[];$gid=(int)($ctx['company_goal_id']??0);if($gid>0)CompanyGoalService::progress($gid,(int)$t['assigned_agent_id'],null,'Task completed: '.(string)$t['title'],null,$id,$evidence);}catch(Throwable $goalError){error_log('ELMETR goal progress: '.Security::redactSecrets($goalError->getMessage(),160));}AgentService::runtimeStatus((int)$t['assigned_agent_id'],'idle');Workflow::afterTask($id);}
    public static function fail(int $id,string $code,string $summary=''):void{$t=self::get($id);if($t['status']==='cancelled')return;db()->prepare("UPDATE tasks SET status='failed',completed_at=NOW() WHERE id=?")->execute([$id]);self::event($id,'agent',(string)$t['assigned_agent_id'],'failed',$t['status'],'failed',['error_code'=>$code,'summary'=>$summary]);try{AgentFollowupService::resolveFromTask($id,'failed',$summary?:$code);}catch(Throwable){}try{ProspectPrototypeService::afterTask($id,'failed',['error_code'=>$code],$summary);}catch(Throwable){}try{TeamChatService::taskResult($t,'failed',$summary?:AdminUi::humanError($code));}catch(Throwable){}AgentService::runtimeStatus((int)$t['assigned_agent_id'],'error',null,$code);$deps=db()->prepare("SELECT t.id,t.status FROM task_dependencies d JOIN tasks t ON t.id=d.task_id WHERE d.depends_on_task_id=? AND t.status NOT IN ('completed','cancelled','failed')");$deps->execute([$id]);foreach($deps->fetchAll() as $dep){$did=(int)$dep['id'];db()->prepare("UPDATE tasks SET status='blocked' WHERE id=?")->execute([$did]);self::event($did,'system','dependency','dependency_failed',(string)$dep['status'],'blocked',['depends_on'=>$id,'error_code'=>$code]);}Notifications::add('critical','tasks','فشلت مهمة: '.$t['title'],$summary?:AdminUi::humanError($code),'task',(string)$id);try{Workflow::afterFailure($id,$code,$summary);}catch(Throwable $e){error_log('ELMETR fallback workflow: '.$e->getMessage());}}
}
