<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireOwner();
$rows=AgentService::all();$ramy=AgentService::bySlug('ramy');
$openRouterReady=OpenRouterService::configured();
$aiProviders=db()->query("SELECT provider_key,label FROM providers WHERE kind='ai' AND enabled=1 ORDER BY FIELD(provider_key,'openrouter','openai','gemini','groq','anthropic','ollama'),label")->fetchAll();
AdminUi::header('فريق الوكلاء','agents');echo AdminUi::flash();
?>
<div class="company-tree">
  <div class="tree-owner"><b>أبانوب — المالك</b><small>صاحب القرار الأعلى</small></div><div class="tree-connector"></div>
  <a class="tree-manager" href="agent-profile.php?slug=ramy" style="text-decoration:none;color:inherit"><b>رامي — المدير التنفيذي ونائب المالك</b><small>الإدارة · التفاوض · التشغيل · توزيع العمل · بوابة القرارات الحساسة</small></a><div class="tree-connector"></div>
  <div class="tree-team"><?php foreach($rows as $a):if($a['slug']==='ramy')continue;?><a class="tree-agent" href="agent-profile.php?slug=<?=e($a['slug'])?>" style="text-decoration:none;color:inherit"><b><?=e($a['display_name'])?></b><small><?=e($a['specialty'])?></small></a><?php endforeach?></div>
</div>
<div class="grid"><section class="card span-8"><div class="card-title"><div><h2>فريق شركة المتر</h2><span class="muted small">كل وكيل له ملف وهوية وذاكرة وصلاحيات وأدوات وعقل مبادرة ومسارات AI وعلاقات تواصل. إنشاء وكيل جديد لا يحتاج تعديل كود.</span></div><a class="btn" href="#create-agent">إنشاء وكيل جديد</a></div><div class="two-col"><?php foreach($rows as $a):?><a class="card subtle" style="text-decoration:none;color:inherit;margin:0" href="agent-profile.php?slug=<?=e($a['slug'])?>"><div class="card-title"><div style="display:flex;gap:10px;align-items:center"><div class="avatar"><?=e(pb_substr($a['display_name'],0,1))?></div><div><b><?=e($a['display_name'])?></b><small style="display:block" class="muted"><?=e($a['role_title'])?></small></div></div><?=AdminUi::badge($a['status'])?></div><p class="small"><?=e($a['profile_identity']?:$a['specialty'])?></p><dl class="kvs"><dt>المدير</dt><dd><?=e($a['manager_name']?:'أبانوب مباشرة')?></dd><dt>AI Primary</dt><dd><?=e($a['provider_key'])?></dd><dt>المهام المكتملة</dt><dd><?=(int)$a['completed_tasks']?></dd><dt>الملف</dt><dd>فتح وتعديل →</dd></dl></a><?php endforeach?></div></section>
<section class="card span-4" id="create-agent"><div class="card-title"><div><h2>إنشاء وكيل جديد</h2><span class="muted small">يُنشأ معه تلقائيًا Memory + Data Studio + Team Chat + مبادرة + علاقات الفريق.</span></div></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="agent_create"><input type="hidden" name="return" value="/api/admin/team.php">
<div class="field"><label>الاسم</label><input name="display_name" required></div><div class="field"><label>الاسم المختصر للنظام</label><input name="slug" pattern="[a-zA-Z0-9_-]+" required placeholder="مثال: designer"></div><div class="field"><label>المسمى</label><input name="role_title" required></div><div class="field"><label>التخصص</label><input name="specialty" required></div><div class="field"><label>المدير المباشر</label><select name="manager_id"><option value="<?=$ramy['id']?>">رامي — الافتراضي</option><option value="-1">أبانوب مباشرة</option><?php foreach($rows as $m):if($m['slug']==='ramy')continue;?><option value="<?=$m['id']?>"><?=e($m['display_name'])?></option><?php endforeach?></select></div>
<div class="field"><label>AI Primary</label><select name="provider_key"><?php foreach($aiProviders as $pr):?><option value="<?=e($pr['provider_key'])?>" <?=($openRouterReady?$pr['provider_key']==='openrouter':$pr['provider_key']==='openai')?'selected':''?>><?=e($pr['label'])?></option><?php endforeach?></select><small class="muted"><?=$openRouterReady?'OpenRouter مربوط وسيتم جعله Primary تلقائيًا، وأي مزود AI تضيفه من مركز الربط متاح كـFallback.':'لو OpenRouter غير مربوط سيستخدم النظام أول مزود AI متاح.'?></small></div>
<div class="field"><label>هوية الوكيل</label><input name="profile_identity" placeholder="شخصيته ومسؤوليته داخل الشركة"></div><div class="field"><label>تفاصيل عمله</label><textarea name="profile_work_details" required placeholder="ما الذي يفعله يوميًا وما الذي يعتبر نجاحًا؟"></textarea></div><div class="field"><label>تعليماته الأساسية</label><textarea name="system_prompt" required placeholder="حدود الدور، طريقة التفكير، الأدلة المطلوبة، متى يصعد القرار لرامي/المالك"></textarea></div>
<div class="field"><label>التواصل مع المالك</label><select name="owner_communication"><option value="through_ramy">عبر رامي</option><option value="dashboard_only" selected>Dashboard مباشرة</option><option value="dashboard_whatsapp">Dashboard + WhatsApp</option><option value="whatsapp">WhatsApp</option><option value="emergency_only">WhatsApp للطوارئ فقط</option><option value="disabled">مغلق</option></select></div><label class="check"><input type="checkbox" name="whatsapp_enabled" value="1"> اسمح بقناة WhatsApp حسب السياسة</label>
<fieldset class="capability-box"><legend>عقل المبادرة</legend><label class="check"><input type="checkbox" name="initiative_enabled" value="1" checked> يبدأ عمله المفيد تلقائيًا</label><div class="two-col"><div class="field"><label>كل كام دقيقة</label><input type="number" name="cadence_minutes" min="15" max="10080" value="240"></div><div class="field"><label>أقصى مهام نشطة</label><input type="number" name="max_active_tasks" min="1" max="8" value="1"></div></div><div class="field"><label>نطاق المبادرة</label><select name="initiative_scope"><option value="internal">داخلي فقط</option><option value="owner_team" selected>الفريق + المالك</option><option value="external_guarded">خارجي عبر بوابات الموافقة</option></select></div><div class="field"><label>المهمة الدائمة</label><textarea name="mission_text" placeholder="لو تركتها فارغة يستخدم تفاصيل العمل كتوجيه للمبادرة"></textarea></div></fieldset>
<details><summary>صلاحيات وأدوات إضافية جاهزة</summary><div class="details-pad"><p class="small muted">الصلاحيات الأساسية والذاكرة والشات تضاف تلقائيًا. افتح فقط ما يحتاجه الدور.</p><div class="two-col"><label class="check"><input type="checkbox" name="permission_keys[]" value="accounts.create"> إنشاء حسابات</label><label class="check"><input type="checkbox" name="tool_keys[]" value="browser_automation"> متصفح تنفيذي</label><label class="check"><input type="checkbox" name="permission_keys[]" value="security.review"> مراجعة أمنية</label><label class="check"><input type="checkbox" name="tool_keys[]" value="security_lab"> Security Lab</label><label class="check"><input type="checkbox" name="permission_keys[]" value="agent_data.schema"> إنشاء Data Schema</label><label class="check"><input type="checkbox" name="permission_keys[]" value="agent_data.write"> كتابة Data Studio</label><label class="check"><input type="checkbox" name="tool_keys[]" value="agency_ops"> بيانات وكالة الفارس</label><label class="check"><input type="checkbox" name="tool_keys[]" value="video"> إنتاج Media</label></div></div></details>
<div class="field"><label>ملاحظات التواصل/الهوية</label><textarea name="profile_contact_details"></textarea></div><button class="btn full-width">إنشاء الوكيل + الذاكرة + المبادرة</button></form></section></div>
<?php AdminUi::footer();
