<?php
declare(strict_types=1);
final class TikTokClient {
    private static function token():string{return trim((string)config('connections.tiktok.access_token',''));}
    public static function configured():bool{return self::token()!=='';}
    private static function headers():array{if(!self::configured())throw new RuntimeException('tiktok_not_configured');return ['Authorization'=>'Bearer '.self::token()];}
    public static function creatorInfo():array{return HttpClient::json('POST','https://open.tiktokapis.com/v2/post/publish/creator_info/query/',self::headers(),[],35);}
    public static function test():array{$r=self::creatorInfo();return ['creator_username'=>$r['data']['creator_username']??null,'privacy_level_options'=>$r['data']['privacy_level_options']??[],'comment_disabled'=>$r['data']['comment_disabled']??null];}
    private static function postInfo(string $title,string $privacy,bool $disableComment,bool $disableDuet,bool $disableStitch,bool $brandContent,bool $brandOrganic,bool $isAiGenerated):array{
        $info=self::creatorInfo();$allowed=(array)($info['data']['privacy_level_options']??[]);if($allowed&&!in_array($privacy,$allowed,true))$privacy='SELF_ONLY';
        return ['title'=>pb_substr(trim($title),0,2200),'privacy_level'=>$privacy,'disable_duet'=>$disableDuet,'disable_comment'=>$disableComment,'disable_stitch'=>$disableStitch,'video_cover_timestamp_ms'=>1000,'brand_content_toggle'=>$brandContent,'brand_organic_toggle'=>$brandOrganic,'is_aigc'=>$isAiGenerated];
    }
    public static function initDirectPostFromUrl(string $videoUrl,string $title,string $privacy='SELF_ONLY',bool $disableComment=false,bool $disableDuet=false,bool $disableStitch=false,bool $brandContent=false,bool $brandOrganic=true,bool $isAiGenerated=true):array{
        $videoUrl=Security::publicUrl($videoUrl);$body=['post_info'=>self::postInfo($title,$privacy,$disableComment,$disableDuet,$disableStitch,$brandContent,$brandOrganic,$isAiGenerated),'source_info'=>['source'=>'PULL_FROM_URL','video_url'=>$videoUrl]];
        $r=HttpClient::json('POST','https://open.tiktokapis.com/v2/post/publish/video/init/',self::headers(),$body,45);if((string)($r['error']['code']??'ok')!=='ok')throw new RuntimeException('tiktok_publish_init_failed:'.pb_substr((string)($r['error']['code']??'unknown'),0,80));return $r;
    }
    private static function assetPath(int $assetId):array{
        $q=db()->prepare('SELECT * FROM project_assets WHERE id=?');$q->execute([$assetId]);$a=$q->fetch();if(!$a)throw new RuntimeException('project_asset_not_found');if((string)$a['asset_type']!=='video')throw new RuntimeException('tiktok_asset_must_be_video');$path=trim((string)($a['path_ref']??''));if($path!==''&&!str_starts_with($path,'/'))$path=PB_ROOT.'/'.ltrim($path,'/');if($path!==''&&is_file($path))return ['path'=>$path,'cleanup'=>false];$url=trim((string)($a['url_ref']??''));if($url==='')throw new RuntimeException('tiktok_video_file_missing');return ['path'=>self::downloadVideo($url),'cleanup'=>true];
    }
    private static function downloadVideo(string $url):string{
        $url=Security::publicUrl($url);$max=(int)setting('tiktok.max_download_bytes','2147483648');$tmp=tempnam(sys_get_temp_dir(),'pb_tt_');if($tmp===false)throw new RuntimeException('tiktok_tempfile_failed');$fh=fopen($tmp,'wb');if(!$fh){@unlink($tmp);throw new RuntimeException('tiktok_tempfile_open_failed');}$bytes=0;$ch=curl_init($url);if(!$ch){fclose($fh);@unlink($tmp);throw new RuntimeException('curl_extension_missing');}curl_setopt_array($ch,[CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>600,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_WRITEFUNCTION=>static function($ch,$chunk)use($fh,&$bytes,$max){$bytes+=strlen($chunk);if($bytes>$max)return 0;return fwrite($fh,$chunk);},CURLOPT_USERAGENT=>'PerseBayt/8.1']);$ok=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);fclose($fh);if($ok===false||$status<200||$status>=300||$bytes<=0){@unlink($tmp);throw new RuntimeException($bytes>$max?'tiktok_video_too_large':'tiktok_video_download_failed:'.$status.':'.$err);}return $tmp;
    }
    private static function uploadChunks(string $uploadUrl,string $path,int $size,int $chunkSize):void{
        $uploadUrl=Security::publicUrl($uploadUrl);$fh=fopen($path,'rb');if(!$fh)throw new RuntimeException('tiktok_video_open_failed');$offset=0;try{while($offset<$size){$len=min($chunkSize,$size-$offset);$data=fread($fh,$len);if($data===false||strlen($data)!==$len)throw new RuntimeException('tiktok_video_read_failed');$end=$offset+$len-1;$attempt=0;$ok=false;$last='';while($attempt<3&&!$ok){$attempt++;$ch=curl_init($uploadUrl);if(!$ch)throw new RuntimeException('curl_extension_missing');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>'PUT',CURLOPT_POSTFIELDS=>$data,CURLOPT_HTTPHEADER=>['Content-Type: video/mp4','Content-Length: '.$len,'Content-Range: bytes '.$offset.'-'.$end.'/'.$size],CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>300,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);$last=$status.':'.$err;if($raw!==false&&in_array($status,[200,201,202,204,206,308],true))$ok=true;elseif($attempt<3)usleep(350000*$attempt);}if(!$ok)throw new RuntimeException('tiktok_upload_chunk_failed:'.$last);$offset=$end+1;}}
        finally{fclose($fh);}
    }
    public static function initDirectPostFromAsset(int $assetId,string $title,string $privacy='SELF_ONLY',bool $disableComment=false,bool $disableDuet=false,bool $disableStitch=false,bool $brandContent=false,bool $brandOrganic=true,bool $isAiGenerated=true):array{
        $local=self::assetPath($assetId);$path=$local['path'];try{$size=filesize($path);if($size===false||$size<1)throw new RuntimeException('tiktok_video_empty');$chunk=10*1024*1024;if($size<$chunk)$chunk=$size;$total=(int)ceil($size/$chunk);if($total>1000){$chunk=(int)ceil($size/1000);$total=(int)ceil($size/$chunk);}if($chunk>64*1024*1024)throw new RuntimeException('tiktok_video_too_large_for_file_upload');$body=['post_info'=>self::postInfo($title,$privacy,$disableComment,$disableDuet,$disableStitch,$brandContent,$brandOrganic,$isAiGenerated),'source_info'=>['source'=>'FILE_UPLOAD','video_size'=>$size,'chunk_size'=>$chunk,'total_chunk_count'=>$total]];$r=HttpClient::json('POST','https://open.tiktokapis.com/v2/post/publish/video/init/',self::headers(),$body,45);if((string)($r['error']['code']??'ok')!=='ok')throw new RuntimeException('tiktok_publish_init_failed:'.pb_substr((string)($r['error']['code']??'unknown'),0,80));$uploadUrl=trim((string)($r['data']['upload_url']??''));if($uploadUrl==='')throw new RuntimeException('tiktok_upload_url_missing');self::uploadChunks($uploadUrl,$path,(int)$size,$chunk);$r['upload']=['completed'=>true,'bytes'=>(int)$size,'chunks'=>$total];return $r;}finally{if($local['cleanup'])@unlink($path);}
    }
    public static function status(string $publishId):array{$publishId=trim($publishId);if($publishId==='')throw new RuntimeException('tiktok_publish_id_required');return HttpClient::json('POST','https://open.tiktokapis.com/v2/post/publish/status/fetch/',self::headers(),['publish_id'=>$publishId],35);}
}
