<?php
declare(strict_types=1);

final class VideoStudioService {
    public static function create(int $agentId,?int $projectId,int $taskId,string $title,string $concept,int $durationSeconds=30,string $aspectRatio='16:9',string $targetPlatform='youtube'):array{
        $agent=AgentService::byId($agentId);Permissions::requireAgent($agentId,'media.video.generate');AgentService::requireTool($agentId,'media_generation');
        if(!$projectId)$projectId=(int)setting('social.default_project_id','0');if(!$projectId)throw new RuntimeException('video_project_required');ProjectService::get($projectId);
        $title=trim($title)?:'Cinematic video';$concept=trim($concept);if($concept==='')throw new RuntimeException('video_concept_required');MemoryService::assertSafeMemory($concept);
        $durationSeconds=max(5,min(600,$durationSeconds));if(!in_array($aspectRatio,['16:9','9:16','1:1','4:5'],true))$aspectRatio='16:9';
        $sceneSeconds=max(3,min(12,(int)setting('video.scene_seconds','6')));$sceneCount=max(1,min(24,(int)ceil($durationSeconds/$sceneSeconds)));
        $schema=['type'=>'object','properties'=>['master_prompt'=>['type'=>'string'],'continuity'=>['type'=>'object'],'scenes'=>['type'=>'array','items'=>['type'=>'object','properties'=>['title'=>['type'=>'string'],'duration_seconds'=>['type'=>'integer'],'visual_prompt'=>['type'=>'string'],'voice_text'=>['type'=>'string'],'camera'=>['type'=>'string'],'continuity'=>['type'=>'object']],'required'=>['title','duration_seconds','visual_prompt','voice_text','camera','continuity']]]],'required'=>['master_prompt','continuity','scenes']];
        $instructions='You are a cinematic director. Build a real multi-scene production plan with motion, camera direction, lighting, continuity, voice when useful, and no slideshow behavior. Keep recurring characters/locations visually consistent. Return exactly the requested number of scenes. Do not claim rendering happened.';
        try{$ai=AiGateway::json($agent,$instructions,[['role'=>'user','content'=>j(['title'=>$title,'concept'=>$concept,'duration_seconds'=>$durationSeconds,'aspect_ratio'=>$aspectRatio,'platform'=>$targetPlatform,'scene_count'=>$sceneCount])]],$schema,'video_storyboard',9000);$plan=(array)($ai['json']??[]);}catch(Throwable){$plan=['master_prompt'=>$concept,'continuity'=>['style'=>'cinematic','aspect_ratio'=>$aspectRatio],'scenes'=>[]];for($i=1;$i<=$sceneCount;$i++)$plan['scenes'][]=['title'=>'Scene '.$i,'duration_seconds'=>(int)ceil($durationSeconds/$sceneCount),'visual_prompt'=>$concept.' Scene '.$i.' of '.$sceneCount.'. Preserve continuity and cinematic motion.','voice_text'=>'','camera'=>'cinematic camera movement','continuity'=>$plan['continuity']];}
        $master=trim((string)($plan['master_prompt']??$concept));db()->prepare("INSERT INTO video_productions(created_by_agent_id,project_id,task_id,title,concept,cinematic_prompt,duration_seconds,aspect_ratio,target_platform,state,owner_approved) VALUES (?,?,?,?,?,?,?,?,?,'draft',0)")->execute([$agentId,$projectId,$taskId?:null,pb_substr($title,0,220),pb_substr($concept,0,12000),pb_substr($master,0,16000),$durationSeconds,$aspectRatio,pb_substr($targetPlatform,0,40)]);$productionId=(int)db()->lastInsertId();
        self::seedContinuity($productionId,(array)($plan['continuity']??[]));
        $scenes=array_slice((array)($plan['scenes']??[]),0,$sceneCount);if(!$scenes)throw new RuntimeException('video_storyboard_empty');$n=0;$sceneIds=[];$audioIds=[];$approval=setting('video.scene_approval_required','0')==='1';$audioEnabled=setting('video.audio_pipeline_enabled','1')==='1';
        foreach($scenes as $scene){if(!is_array($scene))continue;$n++;$dur=max(2,min(20,(int)($scene['duration_seconds']??$sceneSeconds)));$prompt=trim((string)($scene['visual_prompt']??''));if($prompt==='')$prompt=$concept.' Scene '.$n;$voice=pb_substr((string)($scene['voice_text']??''),0,4000);db()->prepare("INSERT INTO video_scenes(production_id,scene_no,title,duration_seconds,prompt_text,voice_text,camera_text,continuity_json,state,approval_required) VALUES (?,?,?,?,?,?,?,?,'queued',?)")->execute([$productionId,$n,pb_substr((string)($scene['title']??('Scene '.$n)),0,220),$dur,pb_substr($prompt,0,16000),$voice,pb_substr((string)($scene['camera']??''),0,4000),j((array)($scene['continuity']??$plan['continuity']??[])),$approval?1:0]);$sid=(int)db()->lastInsertId();$sceneIds[]=$sid;self::queueJob('video_scene_generate',$agentId,$taskId,$projectId,70,['scene_id'=>$sid,'production_id'=>$productionId]);
            if($audioEnabled&&trim($voice)!==''){db()->prepare("INSERT INTO video_audio_assets(production_id,scene_id,audio_type,voice_key,text_content,state,metadata_json) VALUES (?,?,'voiceover',?,?,'queued',?)")->execute([$productionId,$sid,pb_substr((string)setting('video.default_voice_key','default'),0,120),$voice,j(['duration_hint_seconds'=>$dur])]);$aid=(int)db()->lastInsertId();$audioIds[]=$aid;self::queueJob('video_audio_generate',$agentId,$taskId,$projectId,68,['audio_id'=>$aid,'production_id'=>$productionId]);}
        }
        db()->prepare("UPDATE video_productions SET state='generating',updated_at=NOW() WHERE id=?")->execute([$productionId]);WorkerWakeup::schedule();return ['production_id'=>$productionId,'state'=>'generating','scenes'=>count($sceneIds),'scene_ids'=>$sceneIds,'audio_jobs'=>count($audioIds),'scene_approval_required'=>$approval];
    }

    private static function seedContinuity(int $productionId,array $continuity):void{
        foreach($continuity as $k=>$v){if(is_array($v)||is_object($v))$value=j($v);else $value=trim((string)$v);if($value==='')continue;$type=match(pb_strtolower((string)$k)){'character','characters'=>'character','face','face_reference'=>'face_reference','location','locations'=>'location','costume','wardrobe'=>'costume','color','palette'=>'color','style','visual_style'=>'style',default=>'other'};db()->prepare('INSERT INTO video_continuity_assets(production_id,asset_type,label,metadata_json) VALUES (?,?,?,?)')->execute([$productionId,$type,pb_substr((string)$k,0,220),j(['value'=>$value])]);}
    }
    private static function queueJob(string $kind,int $agentId,int $taskId,int $projectId,int $priority,array $payload):int{db()->prepare("INSERT INTO jobs(kind,agent_id,task_id,project_id,state,priority,payload_json) VALUES (?,?,?,?,'queued',?,?)")->execute([$kind,$agentId,$taskId?:null,$projectId,$priority,j($payload)]);return (int)db()->lastInsertId();}
    private static function continuityForProduction(int $productionId):array{$q=db()->prepare('SELECT asset_type,label,project_asset_id,reference_url,seed_value,metadata_json FROM video_continuity_assets WHERE production_id=? ORDER BY id');$q->execute([$productionId]);$out=[];foreach($q->fetchAll() as $r){$out[]=['type'=>$r['asset_type'],'label'=>$r['label'],'asset_id'=>$r['project_asset_id']?(int)$r['project_asset_id']:null,'url'=>$r['reference_url']?:null,'seed'=>$r['seed_value']?:null,'metadata'=>json_decode((string)($r['metadata_json']??'{}'),true)?:[]];}return $out;}

    public static function runSceneJob(array $job):array{
        $p=json_decode((string)($job['payload_json']??'{}'),true)?:[];$sceneId=(int)($p['scene_id']??0);if($sceneId<1)throw new RuntimeException('video_scene_missing');$q=db()->prepare("SELECT s.*,v.project_id,v.task_id,v.created_by_agent_id,v.title production_title,v.aspect_ratio FROM video_scenes s JOIN video_productions v ON v.id=s.production_id WHERE s.id=?");$q->execute([$sceneId]);$s=$q->fetch();if(!$s)throw new RuntimeException('video_scene_not_found');
        if(in_array((string)$s['state'],['ready','approved'],true)&&!empty($s['asset_id'])){self::queueRenderIfReady((int)$s['production_id']);return ['scene_id'=>$sceneId,'production_id'=>(int)$s['production_id'],'asset_id'=>(int)$s['asset_id'],'state'=>(string)$s['state'],'reused'=>true];}
        $prompt=(string)$s['prompt_text']."\nCamera: ".(string)$s['camera_text']."\nDuration: ".(int)$s['duration_seconds']." seconds. Aspect ratio: ".(string)$s['aspect_ratio'].". Continuity: ".(string)$s['continuity_json']."\nGlobal references: ".j(self::continuityForProduction((int)$s['production_id']));
        db()->prepare("UPDATE video_scenes SET state='generating',error_code=NULL WHERE id=?")->execute([$sceneId]);
        $r=MediaBridgeClient::request((int)$s['project_id'],(int)($s['task_id']??0),(int)$s['created_by_agent_id'],'video',(string)$s['production_title'].' - scene '.(int)$s['scene_no'],$prompt,['source_ref'=>'video_scene:'.$sceneId,'idempotency_key'=>'video_scene:'.$sceneId,'retry_failed'=>!empty($p['retry_failed']),'provider_options'=>['duration_seconds'=>(int)$s['duration_seconds'],'aspect_ratio'=>(string)$s['aspect_ratio'],'continuity'=>self::continuityForProduction((int)$s['production_id'])]]);
        db()->prepare("UPDATE video_scenes SET media_request_id=COALESCE(media_request_id,?),error_code=? WHERE id=?")->execute([$r['request_id']??null,isset($r['error'])?pb_substr((string)$r['error'],0,220):null,$sceneId]);
        if(($r['state']??'')==='failed'){db()->prepare("UPDATE video_scenes SET state='failed' WHERE id=?")->execute([$sceneId]);throw new RuntimeException((string)($r['error']??'video_scene_failed'));}
        if(($r['state']??'')==='completed'&&!empty($r['asset_id']))self::markSceneReady($sceneId,(int)$r['asset_id']);
        return ['scene_id'=>$sceneId,'production_id'=>(int)$s['production_id'],'request_id'=>(int)($r['request_id']??0),'asset_id'=>(int)($r['asset_id']??0)?:null,'state'=>(string)($r['state']??'processing'),'pending'=>in_array((string)($r['state']??''),['requested','submitted','processing','generating'],true)];
    }

    public static function runAudioJob(array $job):array{
        $p=json_decode((string)($job['payload_json']??'{}'),true)?:[];$audioId=(int)($p['audio_id']??0);if($audioId<1)throw new RuntimeException('video_audio_missing');$q=db()->prepare("SELECT a.*,v.project_id,v.task_id,v.created_by_agent_id,v.title production_title FROM video_audio_assets a JOIN video_productions v ON v.id=a.production_id WHERE a.id=?");$q->execute([$audioId]);$a=$q->fetch();if(!$a)throw new RuntimeException('video_audio_not_found');if((string)$a['state']==='ready'&&!empty($a['project_asset_id'])){self::queueRenderIfReady((int)$a['production_id']);return ['audio_id'=>$audioId,'state'=>'ready','asset_id'=>(int)$a['project_asset_id'],'reused'=>true];}
        $text=trim((string)($a['text_content']??''));if($text===''){db()->prepare("UPDATE video_audio_assets SET state='ready',updated_at=NOW() WHERE id=?")->execute([$audioId]);self::queueRenderIfReady((int)$a['production_id']);return ['audio_id'=>$audioId,'state'=>'ready','empty'=>true];}
        $prompt='Generate clean spoken voiceover audio only. Voice key: '.(string)($a['voice_key']??'default').". Text:\n".$text;
        db()->prepare("UPDATE video_audio_assets SET state='processing',updated_at=NOW() WHERE id=?")->execute([$audioId]);$r=MediaBridgeClient::request((int)$a['project_id'],(int)($a['task_id']??0),(int)$a['created_by_agent_id'],'audio',(string)$a['production_title'].' - voiceover',$prompt,['source_ref'=>'video_audio:'.$audioId,'idempotency_key'=>'video_audio:'.$audioId,'retry_failed'=>!empty($p['retry_failed']),'provider_options'=>['audio_type'=>(string)$a['audio_type'],'voice_key'=>(string)($a['voice_key']??'default')]]);
        $meta=json_decode((string)($a['metadata_json']??'{}'),true)?:[];$meta['media_request_id']=(int)($r['request_id']??0);db()->prepare("UPDATE video_audio_assets SET metadata_json=?,state=? WHERE id=?")->execute([j($meta),($r['state']??'')==='failed'?'failed':'processing',$audioId]);if(($r['state']??'')==='failed')throw new RuntimeException((string)($r['error']??'video_audio_failed'));if(($r['state']??'')==='completed'&&!empty($r['asset_id']))self::markAudioReady($audioId,(int)$r['asset_id']);return ['audio_id'=>$audioId,'request_id'=>(int)($r['request_id']??0),'asset_id'=>(int)($r['asset_id']??0)?:null,'state'=>(string)($r['state']??'processing')];
    }

    private static function markSceneReady(int $sceneId,int $assetId):void{$q=db()->prepare('SELECT production_id,approval_required FROM video_scenes WHERE id=?');$q->execute([$sceneId]);$s=$q->fetch();if(!$s)return;$state=(int)$s['approval_required']===1?'ready':'approved';db()->prepare("UPDATE video_scenes SET state=?,asset_id=?,error_code=NULL,approved_at=IF(?='approved',COALESCE(approved_at,NOW()),approved_at) WHERE id=?")->execute([$state,$assetId,$state,$sceneId]);self::queueRenderIfReady((int)$s['production_id']);}
    private static function markAudioReady(int $audioId,int $assetId):void{$q=db()->prepare('SELECT production_id FROM video_audio_assets WHERE id=?');$q->execute([$audioId]);$pid=(int)($q->fetchColumn()?:0);db()->prepare("UPDATE video_audio_assets SET state='ready',project_asset_id=?,updated_at=NOW() WHERE id=?")->execute([$assetId,$audioId]);if($pid)self::queueRenderIfReady($pid);}
    public static function approveScene(int $sceneId):void{$q=db()->prepare('SELECT production_id,state FROM video_scenes WHERE id=?');$q->execute([$sceneId]);$s=$q->fetch();if(!$s)throw new RuntimeException('video_scene_not_found');if(!in_array((string)$s['state'],['ready','approved'],true))throw new RuntimeException('video_scene_not_ready_for_approval');db()->prepare("UPDATE video_scenes SET state='approved',approved_at=NOW() WHERE id=?")->execute([$sceneId]);self::queueRenderIfReady((int)$s['production_id']);}

    public static function mediaCompleted(int $requestId,int $assetId,array $payload=[]):void{
        $r=MediaBridgeClient::get($requestId);$meta=json_decode((string)($r['metadata_json']??'{}'),true)?:[];$source=(string)($meta['source_ref']??'');
        if(str_starts_with($source,'video_scene:')){self::markSceneReady((int)substr($source,12),$assetId);return;}
        if(str_starts_with($source,'video_audio:')){self::markAudioReady((int)substr($source,12),$assetId);return;}
        if(str_starts_with($source,'render:')){$q=db()->prepare('SELECT id,production_id,task_id FROM video_render_jobs WHERE media_request_id=? LIMIT 1');$q->execute([$requestId]);$rr=$q->fetch();if($rr)self::completeRender((int)$rr['id'],(int)$rr['production_id'],$assetId);}
    }
    public static function mediaFailed(int $requestId,string $error,array $payload=[]):void{
        try{$r=MediaBridgeClient::get($requestId);$meta=json_decode((string)($r['metadata_json']??'{}'),true)?:[];$source=(string)($meta['source_ref']??'');if(str_starts_with($source,'video_scene:'))db()->prepare("UPDATE video_scenes SET state='failed',error_code=? WHERE id=?")->execute([pb_substr($error,0,220),(int)substr($source,12)]);elseif(str_starts_with($source,'video_audio:'))db()->prepare("UPDATE video_audio_assets SET state='failed',metadata_json=? WHERE id=?")->execute([j(['error'=>pb_substr($error,0,220),'media_request_id'=>$requestId]),(int)substr($source,12)]);elseif(str_starts_with($source,'render:')){$q=db()->prepare('SELECT id,production_id FROM video_render_jobs WHERE media_request_id=? LIMIT 1');$q->execute([$requestId]);if($x=$q->fetch()){db()->prepare("UPDATE video_render_jobs SET state='failed',error_code=?,completed_at=NOW() WHERE id=?")->execute([pb_substr($error,0,220),(int)$x['id']]);db()->prepare("UPDATE video_productions SET state='failed',error_code=?,updated_at=NOW() WHERE id=?")->execute([pb_substr($error,0,190),(int)$x['production_id']]);}}}catch(Throwable){}
    }

    private static function queueRenderIfReady(int $productionId):void{
        $q=db()->prepare("SELECT COUNT(*) total,SUM(state IN ('ready','approved')) generated,SUM(state='approved' OR (state='ready' AND approval_required=0)) acceptable,SUM(state='failed') failed FROM video_scenes WHERE production_id=?");$q->execute([$productionId]);$r=$q->fetch();if((int)$r['failed']>0)return;if((int)$r['total']<1||(int)$r['acceptable']!==(int)$r['total'])return;
        if(setting('video.audio_pipeline_enabled','1')==='1'){$a=db()->prepare("SELECT COUNT(*) total,SUM(state='ready') ready,SUM(state='failed') failed FROM video_audio_assets WHERE production_id=?");$a->execute([$productionId]);$ar=$a->fetch();if((int)($ar['failed']??0)>0)return;if((int)($ar['total']??0)>0&&(int)$ar['ready']!==(int)$ar['total'])return;}
        $exists=db()->prepare("SELECT COUNT(*) FROM video_render_jobs WHERE production_id=? AND state IN ('queued','rendering','completed')");$exists->execute([$productionId]);if((int)$exists->fetchColumn()>0)return;$p=db()->prepare('SELECT * FROM video_productions WHERE id=?');$p->execute([$productionId]);$v=$p->fetch();if(!$v)return;db()->prepare("INSERT INTO video_render_jobs(production_id,task_id,state) VALUES (?,?,'queued')")->execute([$productionId,$v['task_id']?:null]);$rid=(int)db()->lastInsertId();self::queueJob('video_render',(int)$v['created_by_agent_id'],(int)($v['task_id']??0),(int)$v['project_id'],75,['render_job_id'=>$rid,'production_id'=>$productionId]);WorkerWakeup::schedule();
    }

    private static function manifest(int $productionId):array{
        $s=db()->prepare("SELECT s.*,a.url_ref,a.path_ref FROM video_scenes s LEFT JOIN project_assets a ON a.id=s.asset_id WHERE s.production_id=? ORDER BY s.scene_no");$s->execute([$productionId]);$audioQ=db()->prepare("SELECT va.*,pa.url_ref,pa.path_ref FROM video_audio_assets va LEFT JOIN project_assets pa ON pa.id=va.project_asset_id WHERE va.production_id=? ORDER BY va.scene_id,va.id");$audioQ->execute([$productionId]);$audioByScene=[];foreach($audioQ->fetchAll() as $a){if((string)$a['state']!=='ready')throw new RuntimeException('video_audio_not_ready');$audioByScene[(int)($a['scene_id']??0)][]=['type'=>$a['audio_type'],'asset_id'=>$a['project_asset_id']?(int)$a['project_asset_id']:null,'url'=>$a['url_ref']?:null,'path'=>$a['path_ref']?:null,'voice_key'=>$a['voice_key']?:null];}
        $manifest=[];foreach($s->fetchAll() as $row){$acceptable=(string)$row['state']==='approved'||((string)$row['state']==='ready'&&(int)$row['approval_required']===0);if(!$acceptable||(!$row['url_ref']&&!$row['path_ref']))throw new RuntimeException('video_scene_not_ready');$manifest[]=['scene_no'=>(int)$row['scene_no'],'duration_seconds'=>(int)$row['duration_seconds'],'asset_id'=>(int)$row['asset_id'],'url'=>$row['url_ref']?:null,'path'=>$row['path_ref']?:null,'voice_text'=>(string)($row['voice_text']??''),'audio_assets'=>$audioByScene[(int)$row['id']]??[],'camera'=>(string)($row['camera_text']??''),'continuity'=>json_decode((string)($row['continuity_json']??'{}'),true)?:[]];}return $manifest;
    }
    public static function runRenderJob(array $job):array{
        $payload=json_decode((string)($job['payload_json']??'{}'),true)?:[];$renderId=(int)($payload['render_job_id']??0);$q=db()->prepare("SELECT r.*,v.project_id,v.task_id,v.created_by_agent_id,v.title,v.aspect_ratio,v.target_platform FROM video_render_jobs r JOIN video_productions v ON v.id=r.production_id WHERE r.id=?");$q->execute([$renderId]);$r=$q->fetch();if(!$r)throw new RuntimeException('video_render_job_not_found');if((string)$r['state']==='completed'&&!empty($r['result_asset_id']))return ['render_job_id'=>$renderId,'production_id'=>(int)$r['production_id'],'asset_id'=>(int)$r['result_asset_id'],'state'=>'ready','reused'=>true];$manifest=self::manifest((int)$r['production_id']);db()->prepare("UPDATE video_render_jobs SET state='rendering',started_at=COALESCE(started_at,NOW()),manifest_json=?,error_code=NULL WHERE id=?")->execute([j($manifest),$renderId]);
        $out=MediaBridgeClient::compose((int)$r['project_id'],(int)($r['task_id']??0),(int)$r['created_by_agent_id'],(string)$r['title'],$manifest,$renderId);db()->prepare('UPDATE video_render_jobs SET media_request_id=COALESCE(media_request_id,?) WHERE id=?')->execute([$out['request_id']??null,$renderId]);
        if(($out['state']??'')==='failed'){db()->prepare("UPDATE video_render_jobs SET state='failed',error_code=?,completed_at=NOW() WHERE id=?")->execute([pb_substr((string)($out['error']??'video_render_failed'),0,220),$renderId]);throw new RuntimeException((string)($out['error']??'video_render_failed'));}
        if(($out['state']??'')==='completed'&&!empty($out['asset_id']))self::completeRender($renderId,(int)$r['production_id'],(int)$out['asset_id']);
        return ['render_job_id'=>$renderId,'production_id'=>(int)$r['production_id'],'request_id'=>(int)($out['request_id']??0),'asset_id'=>(int)($out['asset_id']??0)?:null,'state'=>($out['state']??'processing')==='completed'?'ready':'rendering','pending'=>($out['state']??'')!=='completed'];
    }
    private static function completeRender(int $renderId,int $productionId,int $asset):void{
        $q=db()->prepare('SELECT r.*,v.created_by_agent_id,v.task_id FROM video_render_jobs r JOIN video_productions v ON v.id=r.production_id WHERE r.id=?');$q->execute([$renderId]);$r=$q->fetch();if(!$r)return;if((string)$r['state']==='completed')return;db()->prepare("UPDATE video_render_jobs SET state='completed',result_asset_id=?,completed_at=NOW(),error_code=NULL WHERE id=?")->execute([$asset,$renderId]);db()->prepare("UPDATE video_productions SET state='ready',asset_id=?,error_code=NULL,updated_at=NOW() WHERE id=?")->execute([$asset,$productionId]);$manifest=json_decode((string)($r['manifest_json']??'[]'),true)?:[];$ev=['video_production_id'=>$productionId,'render_job_id'=>$renderId,'scene_count'=>count($manifest),'asset_id'=>$asset];if(!empty($r['task_id'])){try{$t=TaskService::get((int)$r['task_id']);if(!in_array($t['status'],['completed','failed','cancelled'],true)){TaskEvidence::add((int)$r['task_id'],'video_render','Multi-scene video render',$ev,'verified',(int)$r['created_by_agent_id']);TaskService::complete((int)$r['task_id'],$ev,'Multi-scene video rendered and ready for owner review.');}}catch(Throwable $e){error_log('ELMETR video task completion: '.Security::redactSecrets($e->getMessage(),180));}}
    }
    public static function retryProduction(int $productionId):array{
        $p=VideoProductionService::get($productionId);$rows=db()->prepare('SELECT id,state FROM video_scenes WHERE production_id=? ORDER BY scene_no');$rows->execute([$productionId]);$queued=0;foreach($rows->fetchAll() as $s){if(in_array((string)$s['state'],['ready','approved'],true))continue;db()->prepare("UPDATE video_scenes SET state='queued',error_code=NULL WHERE id=?")->execute([(int)$s['id']]);self::queueJob('video_scene_generate',(int)$p['created_by_agent_id'],(int)($p['task_id']??0),(int)$p['project_id'],70,['scene_id'=>(int)$s['id'],'production_id'=>$productionId,'retry_failed'=>1]);$queued++;}
        $aq=db()->prepare("SELECT id,state FROM video_audio_assets WHERE production_id=? AND state='failed'");$aq->execute([$productionId]);$audio=0;foreach($aq->fetchAll() as $a){db()->prepare("UPDATE video_audio_assets SET state='queued' WHERE id=?")->execute([(int)$a['id']]);self::queueJob('video_audio_generate',(int)$p['created_by_agent_id'],(int)($p['task_id']??0),(int)$p['project_id'],68,['audio_id'=>(int)$a['id'],'production_id'=>$productionId,'retry_failed'=>1]);$audio++;}
        db()->prepare("UPDATE video_render_jobs SET state='failed',error_code='superseded_by_retry',completed_at=NOW() WHERE production_id=? AND state IN ('queued','rendering')")->execute([$productionId]);db()->prepare("UPDATE video_productions SET state='generating',error_code=NULL WHERE id=?")->execute([$productionId]);WorkerWakeup::schedule();return ['production_id'=>$productionId,'queued_scenes'=>$queued,'queued_audio'=>$audio];
    }
}
