<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
$productions=db()->query("SELECT v.*,a.display_name agent_name,p.name project_name,(SELECT COUNT(*) FROM video_scenes s WHERE s.production_id=v.id) scene_count,(SELECT COUNT(*) FROM video_scenes s WHERE s.production_id=v.id AND s.state='ready') ready_scenes FROM video_productions v LEFT JOIN agents a ON a.id=v.created_by_agent_id LEFT JOIN projects p ON p.id=v.project_id ORDER BY v.id DESC LIMIT 100")->fetchAll();
$projects=db()->query("SELECT id,name,primary_domain FROM projects ORDER BY id DESC LIMIT 300")->fetchAll();
AdminUi::header('Mona Video Studio','video_studio');echo AdminUi::flash();
?>
<div class="grid"><section class="card span-5"><div class="card-title"><h2>New multi-scene production</h2></div><form method="post" action="action.php"><?=AdminUi::csrf()?><input type="hidden" name="action" value="video_create"><input type="hidden" name="return" value="/api/admin/video-studio.php"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Concept / brief</label><textarea name="concept" required rows="7"></textarea></div><div class="field"><label>Project</label><select name="project_id"><option value="0">No project</option><?php foreach($projects as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach?></select></div><div class="two-col"><div class="field"><label>Duration seconds</label><input type="number" min="6" max="600" name="duration_seconds" value="30"></div><div class="field"><label>Aspect ratio</label><select name="aspect_ratio"><option>16:9</option><option>9:16</option><option>1:1</option></select></div></div><div class="field"><label>Target platform</label><select name="target_platform"><option>youtube</option><option>tiktok</option><option>instagram</option><option>facebook</option><option>whatsapp</option></select></div><button class="btn full-width">Plan storyboard and queue scenes</button></form></section>
<section class="card span-7"><div class="card-title"><h2>Pipeline contract</h2></div><p>Storyboard -> ordered scenes -> per-scene visual prompt, camera movement and continuity -> media generation -> final compose/render -> asset -> owner approval.</p><p class="muted small">A single prompt is never treated as a finished cinematic video. A final state requires scene jobs and a compose result from the configured media provider.</p></section></div>
<section class="card"><div class="card-title"><h2>Productions</h2></div><div class="creator-grid"><?php foreach($productions as $v):$sc=db()->prepare('SELECT * FROM video_scenes WHERE production_id=? ORDER BY scene_no');$sc->execute([(int)$v['id']]);$scenes=$sc->fetchAll();?><article class="card subtle" style="margin:0"><div class="card-title"><div><b>#<?=$v['id']?> <?=e($v['title'])?></b><small class="block muted"><?=e($v['project_name']?:'No project')?> | <?=e($v['target_platform'])?></small></div><?=AdminUi::badge($v['state'])?></div><p class="small muted">Scenes: <?=(int)$v['ready_scenes']?> / <?=(int)$v['scene_count']?> | duration <?=e((string)$v['duration_seconds'])?>s | <?=e($v['aspect_ratio'])?></p><details><summary>Scene details</summary><div class="details-pad"><?php foreach($scenes as $s):?><div class="agent-row"><div class="grow"><b>Scene <?=$s['scene_no']?>: <?=e($s['title']?:'')?></b><small><?=e($s['prompt_text']?:'')?> | camera: <?=e($s['camera_text']?:'-')?></small></div><?=AdminUi::badge($s['state'])?></div><?php endforeach?></div></details><?php if(!in_array($v['state'],['completed','approved'],true)):?><form method="post" action="action.php" style="margin-top:8px"><?=AdminUi::csrf()?><input type="hidden" name="action" value="video_retry"><input type="hidden" name="return" value="/api/admin/video-studio.php"><input type="hidden" name="production_id" value="<?=$v['id']?>"><button class="btn secondary">Retry missing scenes/render</button></form><?php endif?></article><?php endforeach?></div><?php if(!$productions)echo AdminUi::empty('No video productions yet.');?></section>
<?php AdminUi::footer();
