<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';Auth::requireOwner();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    Auth::verifyCsrf();$op=(string)($_POST['op']??'');try{
        $agentId=(int)($_POST['agent_id']??0);if($agentId<1)throw new RuntimeException('agent_required');
        if($op==='audio'){$path=VoiceAgentCenterService::storeUpload($_FILES['audio']??[]);$r=VoiceAgentCenterService::processAudio($agentId,$path);$_SESSION['flash']='Voice message processed for '.$r['agent']['display_name'];$_SESSION['flash_type']='success';header('Location: /api/admin/voice.php?conversation='.$r['conversation_id']);exit;}
        if($op==='text'){$r=VoiceAgentCenterService::processText($agentId,(string)($_POST['text']??''));$_SESSION['flash']='Agent reply generated.';$_SESSION['flash_type']='success';header('Location: /api/admin/voice.php?conversation='.$r['conversation_id']);exit;}
        if($op==='call'){$r=VoiceAgentCenterService::startOwnerCall($agentId,(string)($_POST['provider']??'twilio'));$_SESSION['flash']='Call request started.';$_SESSION['flash_type']='success';header('Location: /api/admin/voice.php?conversation='.$r['conversation_id']);exit;}
        throw new RuntimeException('voice_action_invalid');
    }catch(Throwable $e){$_SESSION['flash']=AdminUi::humanError($e->getMessage());$_SESSION['flash_type']='error';header('Location: /api/admin/voice.php');exit;}
}
$agents=array_values(array_filter(AgentService::all(),fn($a)=>(int)$a['is_active']===1&&(string)$a['status']!=='disabled'));$rows=VoiceAgentCenterService::recent(80);$selected=(int)($_GET['conversation']??0);$detail=$selected?VoiceAgentCenterService::get($selected):null;$turns=$selected?VoiceAgentCenterService::turns($selected):[];
AdminUi::header('Voice & Calls','voice_center');echo AdminUi::flash();
?>
<div class="grid"><section class="card span-6"><div class="card-title"><div><h2>Talk to an Agent</h2><span class="muted small">Record or upload audio, transcribe it, send it to the selected agent with its context and memory, then generate a spoken reply.</span></div></div>
<form method="post" enctype="multipart/form-data"><?=AdminUi::csrf()?><input type="hidden" name="op" value="audio"><div class="field"><label>Agent</label><select name="agent_id" required><?php foreach($agents as $a):?><option value="<?=$a['id']?>"><?=e($a['display_name'])?> - <?=e($a['role_title'])?></option><?php endforeach?></select></div><div class="field"><label>Audio file</label><input type="file" name="audio" accept="audio/*,video/webm" required></div><button class="btn full-width">Transcribe and reply</button></form>
<hr><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="text"><div class="field"><label>Agent</label><select name="agent_id" required><?php foreach($agents as $a):?><option value="<?=$a['id']?>"><?=e($a['display_name'])?></option><?php endforeach?></select></div><div class="field"><label>Text fallback</label><textarea name="text" required></textarea></div><button class="btn ghost full-width">Send text and generate spoken reply</button></form></section>
<section class="card span-6"><div class="card-title"><div><h2>Start a Call</h2><span class="muted small">Provider support is checked at runtime. Configured does not mean verified.</span></div></div><form method="post"><?=AdminUi::csrf()?><input type="hidden" name="op" value="call"><div class="field"><label>Agent</label><select name="agent_id" required><?php foreach($agents as $a):?><option value="<?=$a['id']?>"><?=e($a['display_name'])?></option><?php endforeach?></select></div><div class="field"><label>Provider</label><select name="provider"><option value="twilio">Twilio</option><option value="generic">Generic Call Bridge</option><option value="whatsapp">WhatsApp Calling Bridge</option></select></div><button class="btn full-width">Start call</button></form></section></div>
<?php if($detail):?><section class="card"><div class="card-title"><div><h2>Conversation <?=e($detail['uid'])?></h2><span class="muted small"><?=e($detail['agent_name'])?> - <?=e($detail['provider_key'])?></span></div><?=AdminUi::badge($detail['state'])?></div><?php foreach($turns as $t):?><article class="card subtle" style="margin:8px 0"><small class="muted">Turn <?=$t['turn_no']?> - <?=e(AdminUi::date($t['created_at']))?></small><p><b>Owner:</b> <?=nl2br(e($t['input_text']??''))?></p><p><b>Agent:</b> <?=nl2br(e($t['output_text']??''))?></p><div class="actions"><?php if($t['input_audio_path']):?><audio controls preload="none" src="/api/admin/voice-audio.php?id=<?=$t['id']?>&kind=input"></audio><?php endif?><?php if($t['output_audio_path']):?><audio controls preload="none" src="/api/admin/voice-audio.php?id=<?=$t['id']?>&kind=output"></audio><?php endif?></div></article><?php endforeach?></section><?php endif?>
<section class="card"><div class="card-title"><h2>Conversation History</h2></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Agent</th><th>Channel</th><th>Provider</th><th>State</th><th>Turns</th><th>Started</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['uid'])?></td><td><?=e($r['agent_name'])?></td><td><?=e($r['channel_key'])?></td><td><?=e($r['provider_key'])?></td><td><?=AdminUi::badge($r['state'])?></td><td><?=(int)$r['turn_count']?></td><td><?=e(AdminUi::date($r['started_at']))?></td><td><a class="link" href="?conversation=<?=$r['id']?>">Open</a></td></tr><?php endforeach?></tbody></table></div></section>
<?php AdminUi::footer();
