<?php
declare(strict_types=1);
final class YouTubeClient {
    private static function clientId():string{return trim((string)config('connections.youtube.client_id',''));}
    private static function clientSecret():string{return trim((string)config('connections.youtube.client_secret',''));}
    private static function refreshToken():string{return trim((string)config('connections.youtube.refresh_token',''));}
    private static function accessToken():string{return trim((string)config('connections.youtube.access_token',''));}
    public static function configured():bool{return self::accessToken()!==''||(self::clientId()!==''&&self::clientSecret()!==''&&self::refreshToken()!=='');}
    private static function token():string{
        if(self::clientId()!==''&&self::clientSecret()!==''&&self::refreshToken()!==''){
            $r=HttpClient::form('POST','https://oauth2.googleapis.com/token',[],['client_id'=>self::clientId(),'client_secret'=>self::clientSecret(),'refresh_token'=>self::refreshToken(),'grant_type'=>'refresh_token'],30);$t=trim((string)($r['access_token']??''));if($t!=='')return $t;
        }
        $t=self::accessToken();if($t==='')throw new RuntimeException('youtube_not_configured');return $t;
    }
    public static function test():array{$r=HttpClient::json('GET','https://www.googleapis.com/youtube/v3/channels?part=id,snippet&mine=true',['Authorization'=>'Bearer '.self::token()],null,35);$item=(array)($r['items'][0]??[]);if(!$item)throw new RuntimeException('youtube_channel_not_found_or_scope_missing');return ['channel_id'=>$item['id']??null,'title'=>$item['snippet']['title']??null];}
    private static function localAsset(int $assetId):array{
        $q=db()->prepare('SELECT * FROM project_assets WHERE id=?');$q->execute([$assetId]);$a=$q->fetch();if(!$a)throw new RuntimeException('project_asset_not_found');if((string)$a['asset_type']!=='video')throw new RuntimeException('youtube_asset_must_be_video');$cleanup=false;$path=trim((string)($a['path_ref']??''));if($path!==''&&!str_starts_with($path,'/'))$path=PB_ROOT.'/'.ltrim($path,'/');
        if($path===''||!is_file($path)){$url=trim((string)($a['url_ref']??''));if($url==='')throw new RuntimeException('youtube_video_file_missing');$path=self::downloadVideo($url);$cleanup=true;}
        return ['asset'=>$a,'path'=>$path,'cleanup'=>$cleanup];
    }
    private static function downloadVideo(string $url):string{
        $url=Security::publicUrl($url);$max=(int)setting('youtube.max_download_bytes','2147483648');$tmp=tempnam(sys_get_temp_dir(),'pb_yt_');if($tmp===false)throw new RuntimeException('youtube_tempfile_failed');$fh=fopen($tmp,'wb');if(!$fh){@unlink($tmp);throw new RuntimeException('youtube_tempfile_open_failed');}$bytes=0;$ch=curl_init($url);if(!$ch){fclose($fh);@unlink($tmp);throw new RuntimeException('curl_extension_missing');}curl_setopt_array($ch,[CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>600,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_WRITEFUNCTION=>static function($ch,$chunk)use($fh,&$bytes,$max){$bytes+=strlen($chunk);if($bytes>$max)return 0;return fwrite($fh,$chunk);},CURLOPT_USERAGENT=>'PerseBayt/8.0']);$ok=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);fclose($fh);if($ok===false||$status<200||$status>=300||$bytes<=0){@unlink($tmp);throw new RuntimeException($bytes>$max?'youtube_video_too_large':'youtube_video_download_failed:'.$status.':'.$err);}return $tmp;
    }
    private static function uploadChunk(string $location,string $token,string $mime,string $data,int $start,int $end,int $size):array{
        $attempt=0;$lastStatus=0;$lastErr='';$lastRaw='';
        while($attempt<4){$attempt++;$ch=curl_init($location);if(!$ch)throw new RuntimeException('curl_extension_missing');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>'PUT',CURLOPT_POSTFIELDS=>$data,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token,'Content-Type: '.$mime,'Content-Length: '.strlen($data),'Content-Range: bytes '.$start.'-'.$end.'/'.$size],CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>600,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);$lastStatus=$status;$lastErr=$err;$lastRaw=is_string($raw)?$raw:'';if($raw!==false&&($status===308||($status>=200&&$status<300)))return ['status'=>$status,'raw'=>$lastRaw];if(!in_array($status,[0,408,429,500,502,503,504],true))break;if($attempt<4)usleep(400000*$attempt);}
        throw new RuntimeException('youtube_upload_chunk_failed:'.$lastStatus.':'.$lastErr.':'.pb_substr($lastRaw,0,160));
    }
    public static function uploadAsset(int $assetId,string $title,string $description='',string $privacy='private'):array{
        if(!self::configured())throw new RuntimeException('youtube_not_configured');if(!in_array($privacy,['private','unlisted','public'],true))$privacy='private';$local=self::localAsset($assetId);$path=$local['path'];$size=filesize($path);if($size===false||$size<1)throw new RuntimeException('youtube_video_empty');$mime=function_exists('mime_content_type')?(string)mime_content_type($path):'video/mp4';if(!str_starts_with($mime,'video/'))$mime='video/mp4';$token=self::token();$metadata=['snippet'=>['title'=>pb_substr(trim($title),0,100),'description'=>pb_substr(trim($description),0,5000)],'status'=>['privacyStatus'=>$privacy,'selfDeclaredMadeForKids'=>false]];
        $location='';$ch=curl_init('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status');if(!$ch)throw new RuntimeException('curl_extension_missing');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token,'Content-Type: application/json; charset=UTF-8','X-Upload-Content-Length: '.$size,'X-Upload-Content-Type: '.$mime],CURLOPT_POSTFIELDS=>j($metadata),CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>60,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_HEADERFUNCTION=>static function($ch,$line)use(&$location){$len=strlen($line);$p=strpos($line,':');if($p!==false&&strtolower(trim(substr($line,0,$p)))==='location')$location=trim(substr($line,$p+1));return $len;}]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false||$status<200||$status>=300||$location==='')throw new RuntimeException('youtube_resumable_init_failed:'.$status.':'.$err);$location=Security::publicUrl($location);
        $fh=fopen($path,'rb');if(!$fh)throw new RuntimeException('youtube_video_open_failed');$chunkSize=max(1024*1024,min(32*1024*1024,(int)setting('youtube.upload_chunk_bytes','8388608')));$quantum=256*1024;$chunkSize=max($quantum,(int)(floor($chunkSize/$quantum)*$quantum));$offset=0;$result=null;try{while($offset<$size){$len=min($chunkSize,$size-$offset);$data=fread($fh,$len);if($data===false||strlen($data)!==$len)throw new RuntimeException('youtube_video_read_failed');$end=$offset+$len-1;$r=self::uploadChunk($location,$token,$mime,$data,$offset,$end,(int)$size);if($r['status']>=200&&$r['status']<300){$decoded=json_decode((string)$r['raw'],true);if(is_array($decoded)&&!empty($decoded['id'])){$result=$decoded;break;}}$offset=$end+1;}}
        finally{fclose($fh);if($local['cleanup'])@unlink($path);}if(!is_array($result)||empty($result['id']))throw new RuntimeException('youtube_upload_completed_without_video_id');return $result;
    }
    public static function videoStats(string $videoId):array{
        $videoId=trim($videoId);if($videoId==='')throw new RuntimeException('youtube_video_id_required');$r=HttpClient::json('GET','https://www.googleapis.com/youtube/v3/videos?part=id,statistics,status&id='.rawurlencode($videoId),['Authorization'=>'Bearer '.self::token()],null,35);$item=(array)($r['items'][0]??[]);if(!$item)throw new RuntimeException('youtube_video_not_found');return ['id'=>$item['id']??$videoId,'statistics'=>$item['statistics']??[],'status'=>$item['status']??[]];
    }
}
